### ISSUE TITLE
Expanded ranges don't stay open in index navigation

### ISSUE THREAD

**Issue by wragge** [UniversalViewer/universalviewer#1041]
**UV version:**

```
 universalviewer@v4.0.25
```

**I'm submitting a:**

- [x ] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When viewing a manifest with nested ranges, the index navigation doesn't work as expected. If you expand a range, then click on one of the items within it, the range immediately closes so you lose your place within the navigation.

**Expected behavior:**

I would expect expanded ranges to stay expanded unless deliberately closed. You can [view the expected behaviour in v3](https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fraw.githubusercontent.com%2Fwragge%2Fiiif-tests%2Fmain%2Fnla.obj-224441684-manifest.json&xywh=-698%2C-199%2C3806%2C3436) of UV.

**Steps to reproduce:**

- open [this manifest](https://raw.githubusercontent.com/wragge/iiif-tests/main/nla.obj-224441684-v3-manifest.json) in the [UV dev demo](https://www.universalviewer.dev/#?xywh=-1197%2C41%2C4833%2C3436&iiifManifestId=https%3A%2F%2Fraw.githubusercontent.com%2Fwragge%2Fiiif-tests%2Fmain%2Fnla.obj-224441684-v3-manifest.json)
- Click on the 'Index' tab
- click on + to expand a range
- click on an item with the range
- all expanded ranges are closed
- this also seems to be triggered if you use the arrows to move between canvases

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by demiankatz** [comment]
Fixed by #1092.
