### ISSUE TITLE
UV4 on netlify not supporting non-IIIF images

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#1042]
When attempting to add a non IIIF manifest in V4 on Netlify the image does not load and instead displays spinning loading icon. 

Possibly related to https://github.com/UniversalViewer/universalviewer/issues/983

**Comment by LanieOkorodudu** [comment]
@LlGC-szw The issue related to #983 has been closed and fixed. However, when loading the image on the new version (4.0.25) at https://uclalibrary.github.io/uv4025_demo/, it takes a while before the image appears.

**Comment by LanieOkorodudu** [comment]
A PDF file that loads successfully in Universal Viewer version 3 [UV3](https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest) fails to load in version 4 [UV4](https://uv-v4.netlify.app/#?c=&m=&cv=&xywh=-1836%2C-1%2C6240%2C3543&iiifManifestId=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest). Could this be related to the issue #1042?

**Comment by demiankatz** [comment]
> A PDF file that loads successfully in Universal Viewer version 3 [UV3](https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest) fails to load in version 4 [UV4](https://uv-v4.netlify.app/#?c=&m=&cv=&xywh=-1836%2C-1%2C6240%2C3543&iiifManifestId=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest). Could this be related to the issue #1042?

The problem you are seeing is related to #940 -- UV v4.0.0 (and some later versions) were loading the PDF.js library from a CDN URL that stopped working. The URL is corrected by #940 and these should work in the latest 4.0.x release.

**Comment by LanieOkorodudu** [comment]
@demiankatz Thank you for the clarification! That makes sense. Does this mean that updating to the latest 4.0.x release should address the issue? Currently, none of the PDF files are loading in version 4

**Comment by demiankatz** [comment]
> @demiankatz Thank you for the clarification! That makes sense. Does this mean that updating to the latest 4.0.x release should address the issue? Currently, none of the PDF files are loading in version 4

Yes, that is correct, an upgrade should fix the issue for all PDFs.

**Comment by demiankatz** [comment]
@LlGC-szw, meanwhile, can you confirm whether or not the original issue described here has been resolved at this point?

**Comment by LlGC-szw** [comment]
@demiankatz I think I was the documenter here and not the original reporter I'm afraid.

**Comment by demiankatz** [comment]
Thanks for the clarification, @LlGC-szw.

Using @LanieOkorodudu's link above (https://uclalibrary.github.io/uv4025_demo/) the image seems to load right away for me. Is it possible we can safely close this now?

Are there any other stakeholders we should check in with?

**Comment by LlGC-szw** [comment]
> Using @LanieOkorodudu's link above (https://uclalibrary.github.io/uv4025_demo/) the image seems to load right away for me. Is it possible we can safely close this now?
> 
> Are there any other stakeholders we should check in with?

Looks safe to close. Apologies for not noting the orginal reporter!

**Comment by demiankatz** [comment]
Thanks, everyone -- closing now!
