### ISSUE TITLE
Accessibility issue: when spacing is increased, Go button is pushed out of view and image string cut off

### ISSUE THREAD

**Issue by scoutb-cogapp** [UniversalViewer/universalviewer#1066]
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
header panel navigation bar

### Issue description
When the user adjusts the spacing on the site, this can break the header panel: 
- the term "image" before the number field gets cut off at the end and disappears behind the number field (see screenshot). This is worse for languages where this word has more letters 
- the Go button is pushed into a new line. This makes it mostly disappear, only the top is visible (see screenshot). 

### Steps to reproduce
1. install this bookmarklet which will increase the text spacing on the test page according to the WCAG requirements: https://dylanb.github.io/bookmarklets.html
2. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
3. switch to Welsh
4. click the bookmarklet and obsere the header panel: the term for "image" and the "Go" button

### Expected behaviour:
All components remain fully visible and legible when increased spacing is applied to the page.

### WCAG criterion
1.4.12 Text Spacing (Level AA 2.1 only)

### Related code:
"Image" string:

```html
<div class="mode"><label for="image">Delwedd</label><input type="radio" id="image" name="mode" tabindex="0" checked="checked" style="display: none;"><label for="page" class="disabled" style="display: none;">Tudalen</label><input type="radio" id="page" name="mode" tabindex="0" disabled="disabled" style="display: none;"></div>
```
"Go" button:
```html
<a class="go btn btn-primary" tabindex="0">GWELD</a>
```

### Rating:
high

### Other information:
**Note:** I have seen both those issues happening in Firefox even without spacing out the elements on the page when switched to French

To reproduce: Open the page in Firefox and switch to French. In this case both issues happen without even increasing the spacing on the page.

### Screenshot:
![UV-cutoff-controls](https://github.com/user-attachments/assets/7932cd43-8601-468f-8b0b-7fe8fed486ed)

**Comment by hannahb-cogapp** [comment]
Note: You don't even need to install the text spacing bookmark to see this happening, it happens when the language is changed to French.

**Comment by LlGC-jop** [comment]
I'll take a look at this
