### ISSUE TITLE
 Accessibility issue: untranslated button label

### ISSUE THREAD

**Issue by scoutb-cogapp** [UniversalViewer/universalviewer#1083]
**UV version:** _universalviewer@4.0.25_

**I'm submitting a:** *bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below*

### Page area
close button on the attribution notice

### Issue description
When switching to a different language, most buttons are translated. However, the close button on the attribution notice box has been left in English   

### Steps to reproduce
1. open [this manifest](https://www.universalviewer.dev/#?xywh=583%2C1062%2C2492%2C1379&iiifManifestId=https%3A%2F%2Feap.bl.uk%2Farchive-file%2FEAP500-1-1%2Fmanifest&cv=)
2. switch language away from English
3. investigate the close button for the attribution box with devtools and observe that the aria-label is still in English 

### Expected behaviour
Interface is fully localised to any chosen language

### Possible fix
Translate the aria-label and ensure it is included in the language switch functionality
 
### WCAG criterion
[3.1.2 Language of Parts (Level AA)](https://www.w3.org/WAI/WCAG22/Understanding/language-of-parts.html)

### Related code example

```html
<button type="button" class="close" aria-label="Close"><span aria-hidden="true">×</span></button>
```

**Comment by Geoffsc** [comment]
Commenting to follow and participate :)

**Comment by LlGC-jop** [comment]
Ditto

**Comment by LlGC-mag** [comment]
^ Me too

**Comment by demiankatz** [comment]
See pull request: https://github.com/UniversalViewer/universalviewer/pull/1126
