### ISSUE TITLE
Language switching done at view point

### ISSUE THREAD

**Issue by fractos** [UniversalViewer/universalviewer#11]
Language switching done at view point (the same view point reached when language switched, rather than returning to a start point) – i.e., zoom level, open panels, position in panels etc is preserved when switching language.

**Comment by tomcrane** [comment]
Preserve state

**Comment by edsilv** [comment]
This needs to be a separate issue around preserving state. This should include the case where an item is shared and we want to preserve open panels, language as well as the canvas index, zoom level, etc.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
