### ISSUE TITLE
Eliminate all remaining divs with `.label` and replace with `label` (search for class="label")

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#1103]

**Comment by msimpsonBL** [comment]
I'm happy to pick this one up. Just to confirm it is replacing all div elements with the class label with the label element itself?

**Comment by demiankatz** [comment]
> I'm happy to pick this one up. Just to confirm it is replacing all div elements with the class label with the label element itself?

Yes, that is my understanding of the task -- and, of course, making sure that this change doesn't visually break anything.
