### ISSUE TITLE
Clickthrough auth service

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#113]

**Comment by tomcrane** [comment]
Examples:

Clickthrough in player:
http://wellcomelibrary.org/player/b1818893x

Equivalent manifest:
http://wellcomelibrary.org/iiif/b1818893x/manifest
(unchanged)

Can test on:
http://wellcomelibrary.org/item/b1818893x

info.json:
http://wellcomelibrary.org/iiif-img/b1818893x-0/e100fbe3-5f1c-49b7-a6ce-7bf82be23c1e/info.json

In addition to the IIIF 2.1 login, logout and token services there is a fourth service identified by the profile "http://wellcomelibrary.org/ld/iiif-ext/0/accept-terms-click-through" (which can change later).

This should give enough info to reconstruct the clickthrough user experience:

@id is the URI that the containing page will be sent to; the redirectUrl must be supplied

label, description - give you the markup to build the box; metadata values (so can have multiple lang although none supplied from Wellcome)

exp:fullTerms - a link to a web page containing the full terms (not used in current impl but worth including)
exp:fullTermsSimple - a link to a web page containing the full terms without any page furniture etc - suitable for reproducing current behaviour of loading in extended terms into the popup - just a raw chunk of HTML
exp:actionLabel - metadata value (with same multilang behaviour) for the "call to action" button

Once authed via the clickthrough the UV should continue using the token service as before to detect the state of the user's permissions. If the current Player behaviour is reproduced, the UV will have reloaded from scratch because the parent page has been navigated through a redirect. Which may or may not affect its token storage depending on implementation. One significant advantage of the clickthrough method is avoiding popup blockers from cross-domain popups by navigating the entire browser through the clickthrough and back again, e.g., you couldn't get away with an immediate self closing popup on the @id because it would be blocked.

**Comment by tomcrane** [comment]
Update:

To help with testing, 8-digit b numbers that have an odd number at their 7th digit will include the accept terms click through in their image services, those with an even number won't.

Examples:

http://wellcomelibrary.org/iiif/b19863585/manifest =>
http://local.wellcomelibrary.org/iiif-img/b19863585-0/d34bb2af-c01a-4271-922b-0c232064f3e1/info.json

No clickthroughs for this manifest because "8" at second from last position in b number

Whereas the Crick letter mentioned above http://wellcomelibrary.org/item/b1818893x has a "3" so includes the clickthrough.

**Comment by tomcrane** [comment]
The above special behaviour is now even more complex (https://github.com/wellcomelibrary/dds-ecosystem/commit/d9955260fb12165d391b4c94b85c95f9f7679250#diff-8d50899917f7accf80fc5fe67723d3ca) 

For an image that would normally be "requires registration", I'm going to provide three
different strategies to aid with testing.

strategy determined by the character at position 7 of the b number (ie before the check digit)
0,1,2,3 : Full extension clickthrough service
4,5,6: Regular IIIF, login popup is clickthrough popup
7,8,9: Full CAS login (use library acct or Twitter etc)

Examples:

http://wellcomelibrary.org/iiif/b21893639/manifest
All images have the clickthrough service

http://wellcomelibrary.org/iiif/b18175545/manifest
All images have login service linking to clickthroug ony

http://wellcomelibrary.org/iiif/b19334278/manifest
Full login service

**Comment by edsilv** [comment]
The description property of the service currently has the <h1> title and <a> link to view the terms. I'm creating these in the dialogue myself and will have to strip them out for the time being.

**Comment by edsilv** [comment]
The full terms uri lacks a CORS header: http://wellcomelibrary.org/itembody/about-this-site/terms-and-conditions/

**Comment by tomcrane** [comment]
I've removed the title etc form the description, and added the CORS header.

**Comment by tomcrane** [comment]
The clickthrough service now supports two modes of operation - but we should settle on one and disregard the other as long as we are sure it works across all devices.

Example: http://wellcomelibrary.org/iiif-img/b21893639-0/dbdd8658-7815-4e9e-82f7-8845d54f9de8/info.json

clickthrough: @id: "http://wellcomelibrary.org/service/login/clickthrough"

If this is invoked with ?redirectUrl=xxx, then the intended behaviour is that the UV navigates the whole browser through the page, which will set the cookie then redirect back. The problem with this is preserving state - the UV then needs to retry etc, but as far as it's concerned its a new instantiation.

If this is invoked as is, with no parameter, the intended behaviour is that it is opened as a separate tab or window and polled in exactly the same way the normal auth popup/tab is. The difference is that it will always immediately close itself.

You can see these two options here (clear cookies first):

http://tomcrane.github.io/iiifauth/dds-static/osd/tom.html

select "Crick (AC clickthrough)" - the UV would then display the clickthrough dialogue. I'm simulating both options together in the panel on the left for testing.

The second method is definitely preferable, we need to be sure it works everywhere.

**Comment by tomcrane** [comment]
One tiny change, which is breaking so I won't deploy to live yet. I've removed the "exp:" prefixes from the click through service's extra properties ("exp:fullTerms" becomes "fullTerms") and ensured they are defined in the context, which is included in the service block:

    {
      "@context": "http://wellcomelibrary.org/ld/ixif/0/context.json",
      "@id": "http://local.wellcomelibrary.org/service/login/clickthrough",
      "profile": "http://wellcomelibrary.org/ld/iiif-ext/0/accept-terms-click-through",
      "label": "Archival material less than 100 years old",
      "description": "<p>...</p>",
      "service": [
        {
          "@id": "http://local.wellcomelibrary.org/iiif/tokenterms",
          "profile": "http://iiif.io/api/auth/0/token"
        },
        {
          "@id": "http://local.wellcomelibrary.org/iiif/logout",
          "profile": "http://iiif.io/api/auth/0/logout",
          "label": "Log out of Wellcome Library",
          "description": "Log out of Wellcome Library"
        }
      ],
      "fullTerms": "http://local.wellcomelibrary.org/about-this-site/terms-and-conditions/",
      "fullTermsSimple": "http://local.wellcomelibrary.org/itembody/about-this-site/terms-and-conditions/",
      "actionLabel": "Accept Terms and Open"
    }

It's the last three you'll need to change - fullTerms, fullTermsSimple and actionLabel. Now looks nicer, and is completely valid because they have their own little @context.
