### ISSUE TITLE
Email address

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#1136]
Create or confirm access to a shared email address in order to authenticate access to other services? Use UV domain for this?

- [x] Decide on email address
- [x] Setup forwarding to other addresses as required or to slack channel?
- [x] Setup MFA 
- [x] Document credentials
- [x] Communicate the new address to the responsible members of the Steering Group

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by LlGC-szw** [comment]
Who needs to be forwarded to?

**Comment by erinburnand** [comment]
Have added Demian and Sara's email addresses

**Comment by demiankatz** [comment]
Thanks, @erinburnand, I have received and confirmed the forwarding request, so I think we're all set for me!

**Comment by LlGC-szw** [comment]
Also confirmed the email.
