### ISSUE TITLE
Communication and content creation

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#1137]
Communication via Social Media, promote UV activities and events on Slack and website content

- [x] Nominate comms officers who will share activities and grow the community on Slack and Social Media, and update website/wiki page content when necessary
- [x] Create brief SM policy

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by LlGC-szw** [comment]
Create Slack comms channel with James and Sara as primary responsible members.

**Comment by LlGC-szw** [comment]
Proposed SM public statement/policy:

`The Universal Viewer (UV) social media accounts are managed by the Steering Group and exist to promote the work of the UV and associated communities, to share examples of best practice and to promote those who contribute to, and make best use of, the UV.
Any social media post will be made in good faith, and the Steering Group will consider all requests to remove posts that are reported as causing reputational damage to the community.`

**Comment by LlGC-szw** [comment]
Where should this statement sit?

**Comment by LlGC-szw** [comment]
Social media statement page created and added to the wiki home page TOC.

**Comment by demiankatz** [comment]
Looks good to me! I think it may be time to close this issue.
