### ISSUE TITLE
Payments/Open Collective admin

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#1141]
Open Collective is the account that holds the Steering Group membership fees and budget.	

- [x] #1216
- [x] #1217
- [x] #1218
- [x] #1219

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by LlGC-szw** [comment]
I now have access to the account.
