### ISSUE TITLE
Index tab does not open when user uses tab>Index and keyboard enter button.

### ISSUE THREAD

**Issue by damodeburca** [UniversalViewer/universalviewer#1157]
**UV version:**

```
 universalviewer@4.025
```

**I'm submitting a:**

- [X ] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Using the keyboard the user can tab through the various buttons, on getting to the Index tab in the centre panel with the button active clicking the keyboard enter button the index tab is NOT opened

**Expected behavior:**
Using the the keyboard, tab to the index tab, ensure the index tab is active and when the keyboard enter button is hit the Index tab should open

**Steps to reproduce:**
1. Tab to the Index tab using the keyboard
2. The index tab is active - surrounding white border is visible
3. Hit the enter button on the keyboard
4. The index tab is not opened
**Note the same is true for the Thumbnail tab**

**Other information:**
Keyboard Accessibility Issue
![image](https://github.com/user-attachments/assets/f0691731-ad8c-4096-99a6-9d5b7aef7dca)

**Comment by LlGC-jop** [comment]
I'll have a look at this.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
