### ISSUE TITLE
Inform user of possible pop up blocking

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#116]
When the viewer is hosted on a different domain from the embedding page, its auth popups will be blocked. It's not obvious to the end user that this has happened (depending on your browser - Chrome has little icon in address bar) so webapps usually provide a more obvious alert to users that they need to unblock the popup.

Maybe use the yellow bar UI that we already have to do this.

Note - clickthrough auth (#113) prevents this problem a lot of the time, but the UV still needs to handle it:

 - for Wellcome material that is more restricted than clickthroughs
 - for everyone else's material

**Comment by edsilv** [comment]
fixed with user-initiated popups.
