### ISSUE TITLE
Fading of OSD controls is not handled by Reduced Animation setting

### ISSUE THREAD

**Issue by LlGC-jop** [UniversalViewer/universalviewer#1167]
**UV version:** universalviewer@4.0.25

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When the reduce animations settings is checked the controls inside the OpenSeaDragon viewer still fade out when mouse is removed from the centre panel or focus is lost on one of the controls.

**Expected behavior:**

Controls should instantly be hidden rather than fading.

**Steps to reproduce:**

1. Go to the [dev site](https://www.universalviewer.dev/)
2. Open the settings dialogue
3. Check the reduced animations option and close the dialogue
4. Hover mouse over the centre panel and then remove it. The controls will pop in and then fade out.

**Comment by LlGC-jop** [comment]
Fixing this should hopefully just be a case of overriding the `controlsFadeLength` setting in OSD's config, although whether this can be changed at runtime without having to reload OSD or the viewer I'm not sure.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
