### ISSUE TITLE
Account for differences in language context and grammatical structure

### ISSUE THREAD

**Issue by fractos** [UniversalViewer/universalviewer#12]
eg – ensure strings with different context are repeated if necessary

Follow guidelines  provided by the Welsh Language Commissioner on Welsh language localisation

http://www.comisiynyddygymraeg.org/english/publications/pages/publicationdetails.aspx?publicationid=97cca305-2f7f-4364-9cfc-273b37b526c3&category=dogfennau%20cyngor%20ac%20argymhellion

**Comment by LlGC-szw** [comment]
The 4 arrow navigation button hover text need to be added as a single phrases instead of amalgamated words:

First Page
Previous Page
Next Page
Last Page
