### ISSUE TITLE
Ensure more than one SG member has access to enable payments out of the account to be made

### ISSUE THREAD

**Issue by erinburnand** [UniversalViewer/universalviewer#1217]
Document credentials and process for payments from OC.

**Comment by LlGC-szw** [comment]
Is there a way of doing this without sharing credentials?

**Comment by LlGC-szw** [comment]
NLW to keep copy of access credentials.

**Comment by LlGC-szw** [comment]
Suggestion to use keypass to store.

**Comment by LlGC-szw** [comment]
@edsilv Could you send the OC admin credentials to me in a PM please?
