### ISSUE TITLE
Look ahead to Annotation support

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#122]
Just putting this issue in here as a marker, it will need to be split into several further issues. But we need to start thinking about it.

"Support annotations" is a very open ended requirement, there are more and more sophisticated layers of functionality allowed for by IIIF. 

Initially, convey the presence of anno lists referenced by the manifest and display "painting" annos by overlaying them on the OSD canvas. Example - any OCRed Wellcome book has an "otherContent" property per canvas that links to a list like this: http://wellcomelibrary.org/iiif/b18252461/contentAsText/20. These anno bodies are just text/plain so the UV can dsplay them in overlays quite easily. text/html would also be OK. Other types need more thought. Maybe just links by default.

Later we need the ability to make annos - on rectangles within canvases, and on other resources. The UV becomes a selection tool (cf Mirador). To do this the UV needs to talk to an annotation server to save the annos, or it can save them locally for the users own use (save to disk...). This ties in with auth and lots of other things.

A minor point, noted here just to have a record of it - when the UV becomes a selection tool it would be handy to expose the selection to the containing page (fire a "selection" event passing canvas-id?whxy=... and maybe a "within" to note the manifest open at the time, see https://groups.google.com/forum/#!topic/iiif-discuss/shc08t1rCGY

And also use the many discussions on the Mirador issue list, when we get to the equivalent functionality, as many of the "what do we do here?" questions will have been discussed and solved for us. At random: https://github.com/IIIF/mirador/issues/589 but there are dozens or hundreds.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
There is a discussion ongoing to create a IIIF Commons reference implementation, which is a requirement to progress this.
