### ISSUE TITLE
iOS issues for auth

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#123]
Testing on iPad in Chrome and Safari.

The pop up is completely blocked, and you don't get any warning. If you go into settings you can turn off popup blocking, but the UV's popups still won't show.

However, Rob's example does work (in a new tab): http://www.conqueringcorsairs.com/index.html

I think the issue might be that the window.open is not triggered by a user click, as in this discussion:

http://stackoverflow.com/questions/9880316/javascript-window-open-in-safari

We could do this in a non-OS-sniffy way - using the "popup blocked" code in that thread, detect whether the window we just think we opened is there. If not, show a button to open it. If not after that, show "unblock your popups" message.

In Rob's example the "popup" still works even after I turn the blocker back on. So maybe it is just the user-initiated nature of the popup. Or the fact that's it's a new tab (default window.open behaviour) rather than a sized popup, with an additional parameter to window.open - probably that.

So we will need to degrade the experience a bit on mobile - require the user to trigger the process rather than automatic attempt (you can't fake this by scripting a click).

**Comment by edsilv** [comment]
related to #116

**Comment by edsilv** [comment]
User-initiated popup tested in Chrome and Safari on iPad. Closing.
