### ISSUE TITLE
Update search and autocomplete implementation to IIIF Search 0.9

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#132]
...Not published just yet, at http://search.iiif.io/api/search/0.9/

Depends on examples provided by Wellcome from DLCS-116

Will need to invent vocabulary for https://github.com/IIIF/iiif.io/issues/511 in the short term.

**Comment by tomcrane** [comment]
This implementation is ready for deployment server side

**Comment by tomcrane** [comment]
Test endpoints and other useful links:

Draft search spec
http://search.iiif.io/api/search/0.9/

In a manifest (e.g., http://wellcomelibrary.org/iiif/b18035978/manifest) note nested search services, different profiles, no more “within”, no more “&q=” in @id, nicer URI pattern

Search results are now a combination of a simple annotation list (like this - http://wellcomelibrary.org/iiif/b18035978/contentAsText/96) and a "hits" resource that porvides the additional information to render them as results. This allows any viewer that can paint anno rectangles to render the results, and viewer with specialist search result UI to add in the extra info.

Search:
http://wellcomelibrary.org/annoservices/search/b18035978?q=bottle

shows anno list (for painting) and separate hit information (for enhancing UI)

Ignored params:
http://wellcomelibrary.org/annoservices/search/b18035978?q=bottle&user=ed
"user" is a param in the spec, but we don't do anything with it so we report as ignored. 

Hit spanning 2 annotations:
http://wellcomelibrary.org/annoservices/search/b18035978?q=parties%20treat
Here there are two annotations (two rectangles to be painted) but only one "hit".
Note use of “match” to provide the full hit text

Autocomplete:
http://wellcomelibrary.org/annoservices/autocomplete/b18035978?q=bott

I have omitted the “total” as I do not have this information. I think it’s icing on the cake, no-one complained about its absence.

**Comment by tomcrane** [comment]
See https://groups.google.com/forum/#!topic/iiif-discuss/-62qJDxx-ic

Jeffrey Witt has some search results that are plain annotation lists (this is the UV-33 only part of the full search implementation, i.e., no "hits" in the results, just annos).

I've asked for some sample manifests that reference the services so we can test in the UV.

(i.e., the UV shouldn't assume the presence of "hits" in a search result and should be able to convert vanilla annotations to search results too - maybe by wrapping each in an artificial hit to generate the same model to render in the results bar)

**Comment by tomcrane** [comment]
Update - UV assumes autocomplete service but not necessarily available.

Test manifest: http://scta.info/iiif/pp-sorb/manifest

* Search service only, no autocomplete
* Search service returns vanilla anno list, no "hits"

UV should support this scenario

**Comment by edsilv** [comment]
"Assumed autocomplete" is fixed. We need to add visual feedback probably in the form of a spinner while a search is ongoing.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive (discussed on 28/09/2023 Community Call)
