### ISSUE TITLE
Elide labels in thumb view

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#133]
http://digital.library.villanova.edu/Item/vudl:347767/Viewer#?si=0&ci=0

cc @demiankatz

**Comment by demiankatz** [comment]
Thanks for the heads-up. I have noticed a handful of alignment issues that are probably all related to the same root cause. Let me know if you're planning on investigating this; otherwise, Chris and I will take a look when time permits.

**Comment by edsilv** [comment]
I'm working my way through the Wellcome backlog of issues at the moment. Probably a quick fix. Will let you know if I look at it.
