### ISSUE TITLE
Hierachical index with structure/range not working?

### ISSUE THREAD

**Issue by ra-magnus-welander** [UniversalViewer/universalviewer#144]
There may be some things I don't understand, but I'm not getting hierarchical indexes to work with UV. Actually, there are two issues:

1. UV doesn't seem to support the IIIF Presentation API regarding Ranges, http://iiif.io/api/presentation/2.0/#ranges. UV seems to require nesting the child range objects within the parent range. But accordning to the docs, this is not allowed. It says specifically:
> Ranges may include other ranges. This is done in a ranges property within the range. The values within the ranges list *must be strings* giving the URIs of ranges in the list in the manifest. 

2. When I do try to supply the child range objects nested, the child ranges are never selectable/clickable.

**Comment by ra-magnus-welander** [comment]
Example for point 2:
  "structures": [
    {
      "@id": "http://wellcomelibrary.org/iiif/b18035723/range/r-10",
      "@type": "sc:Range",
      "label": "Toppen-noden",
        "canvases": [
          "http://wellcomelibrary.org/iiif/b18035723/canvas/c0"
        ],
      "ranges": [
        {
          "@id": "http://wellcomelibrary.org/iiif/b18035723/range/r-0",
          "@type": "sc:Range",
          "label": "Front Cover",
          "canvases": [
            "http://wellcomelibrary.org/iiif/b18035723/canvas/c0"
          ]
        },
        {
          "@id": "http://wellcomelibrary.org/iiif/b18035723/range/r-1",
          "@type": "sc:Range",
          "label": "Back Cover",
          "canvases": [
            "http://wellcomelibrary.org/iiif/b18035723/canvas/c1"
          ]
        },
        {
          "@id": "http://wellcomelibrary.org/iiif/b18035723/range/r-2",
          "@type": "sc:Range",
          "label": "Title Page",
          "canvases": [
            "http://wellcomelibrary.org/iiif/b18035723/canvas/c3"
          ]
        },
        {
          "@id": "http://wellcomelibrary.org/iiif/b18035723/range/r-5",
          "@type": "sc:Range",
          "label": "Mitt i skiten",
          "canvases": [
            "http://wellcomelibrary.org/iiif/b18035723/canvas/c5"
          ]
        }
      ]
    }
  ]

**Comment by edsilv** [comment]
Hi,

There was a bug in manifesto. I've added a new test for nested ranges:

https://github.com/UniversalViewer/manifesto/commit/958dda1f0d439add65a5a8efc5cd181d17fbbb49

(Manifesto is the library the UV uses for all IIIF-related functionality).

To try this in the UV, you'll need to update this line of the `bower.json`:

https://github.com/UniversalViewer/universalviewer/blob/master/bower.json#L27

To `"manifesto": "universalviewer/manifesto#tree",` in order to reference manifesto's `tree` branch.

Then run `bower update`.

This *should* work... You should definitely only use id strings to reference nested ranges as per the spec. 

I don't currently have a good example of a real manifest with a nested hierarchy. Is your manifest available at a public url?

Ed

**Comment by ra-magnus-welander** [comment]
I'll definitely try this out later today or tomorrow. The manifest is not publicly available (it's just a test anyway), but if you want to I can make it public.

Sorry for the late reply. I wasn't at work thursday or friday.

**Comment by edsilv** [comment]
I've merged the changes with the manifesto 'dev' branch - so if you just pull the latest UV from master then run `bower update` you should get these.

I've been working on IIIF collections support in the tree, here's the Chemist and Druggist example:

http://universalviewer.azurewebsites.net/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb19974760

This is loading a collection of collections, each child collection represents a volume and each child manifest represents an issue. Clicking on issues will reload the UV and open the corresponding manifest. The manifest's structure is also present in the tree.

There seems to be a sporadic problem with the back end at the moment causing time outs when loading.

This suffices as a test of hierarchical data for now. So no worries about using yours.

**Comment by ra-magnus-welander** [comment]
I've tested this now, and it's working for us. Thanks!
