### ISSUE TITLE
Thumbnail requests always seem to expect Image API 2.0 or above.

### ISSUE THREAD

**Issue by mattmcgrattan** [UniversalViewer/universalviewer#145]
I have a manifest which has content from multiple institutions, so a mix of version 2.0 and version 1.1 image servers. The canvas/image annotation has the API version provided in the context/profile for the image service, as expected.

The UV honours that for the main image window, with the panning and zooming control, and makes requests for 'native.jpg' images when the service is 1.1 and for 'default.jpg' when it is 2.0, but the thumbnail requests are all for 'default.jpg' which 400s on a 1.1 Image Server.

See:   http://iiif.bodleian.ox.ac.uk/examples/mushaf.html

With the manifest at: http://iiif.bodleian.ox.ac.uk/examples/mushaf4.json

**Comment by edsilv** [comment]
This is a problem with manifesto assuming a v2.0 image server:

https://github.com/UniversalViewer/manifesto/blob/master/src/Canvas.ts#L68

I have some work to do on thumbnails:

https://github.com/UniversalViewer/universalviewer/issues/102

I'll include this as part of it. 

BTW, the UV community call is this Thursday at 3pm UTC. I think manifesto supporting other versions is a good topic for discussion.
