### ISSUE TITLE
Logos in rightPanel

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#147]
On some of our items we have to include partnership logos. We've tried to add these in the manifest so that they show up in the rightPanel but this only shows a broken image. Is there a way of putting an image into this panel? Could it be done by adding html to the manifest?

![broken-image](https://cloud.githubusercontent.com/assets/1083554/9936006/d62d3bda-5d51-11e5-9ac3-589f9b65d731.png)

![logo-manifest](https://cloud.githubusercontent.com/assets/1083554/9936909/1d727c86-5d56-11e5-9b65-155201627e5b.png)

We've tried to put a iiif image in as can be seen above.

Thanks,
Dylan

**Comment by edsilv** [comment]
I've included an 'attributions' test manifest at the bottom of the 'Manifests' drop down here:

http://universalviewer.azurewebsites.net/

(You may need to clear your cache to get the latest manifests.json file).

If you select that, and check "force jsonp" in the options, then "Set" it will load one of the BL's test manifests. The IIP and thumbnail images are not currently available, but if you open the more info panel you can see that it includes attribution and a logo metadata, the attribution has an Creative Commons license image within it. Here's the manifest:

https://github.com/UniversalViewer/examples/blob/master/manifest/attribution.js

**Comment by glenrobson** [comment]
Hi Ed,

I think I've caused this issue Dylan is seeing by adding a IIIF thumbnail into the Manifest. I did this because there was a problem with storing institution logos in Mirador, see the following:

https://github.com/IIIF/mirador/issues/563#issuecomment-116748580

Now I've included the IIIF logo in the manifest it works for Mirador but I think the UV viewer may be expecting the thumbnail field to contain a URL to an image rather than a JSON Object. (Note the same happens when you look at the metadata panel in Mirador).

Let me know if this is a problem with the Manifest rather than the Viewer.

Thanks 

Glen

**Comment by edsilv** [comment]
Hi Glen,

Sorry about the delayed response. Yep, this is definitely a problem with the UV. I've added a new test for it and will try to fit this in asap.

Ed

**Comment by glenrobson** [comment]
Hi Ed,

Sorry to hassle, have you had a chance to look at fixing the logo thumbnail?

Thanks

Glen

**Comment by edsilv** [comment]
Hi Glen,

Haven't looked at this yet. I'll dedicate some time to info-panel-related stuff asap.

**Comment by LlGC-dwj** [comment]
Hi Ed,

I've downloaded the latest version of the uv but the logo doesn't show up.

In the console output I get an error [object%20Object]:1 GET [object%20Object] 404 (Not Found)

which is line 7475 of app.js where it picks out the image src. Its trying to pick out the node instead of the image address.

Any ideas?

Thanks,
Dylan

**Comment by edsilv** [comment]
Could you describe the steps you took?

I'll assume you mean clicking on the "Download ZIP" button on the repository homepage.

If I do this and copy the unzipped 'uv-1.5.32' folder into my demo site:

https://github.com/UniversalViewer/demo-site

Change the manifest to:

    data-uri="http://dams.llgc.org.uk/iiif/2.0/1123257/manifest.json"

And view it on localhost, the logo shows without an error.

This is not the recommended way of doing things however. You should fork the UV to your own profile and sync the latest changes:

https://help.github.com/articles/syncing-a-fork/

**Comment by LlGC-dwj** [comment]
Hi Ed,

I used the instructions for syncing a fork as I always do, and had merged my fork with commit 336e41a. I've done the same thing this morning and with your latest commit and the logo appears.

Thanks,
Dylan
