### ISSUE TITLE
uv.js

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#156]
Create a new uv.js script that enables developers to create instances of the UV without needing embed.js. This would allow interactions via easyXDM.postMessage like this:

```
var myUV = new UV('#myDiv');
myUV.setCanvasIndex(23);
```

Events could be listened for:

```
myUv.on('canvasIndexChanged', function(newIndex) {
    console.log(newIndex);
});
```

**Comment by edsilv** [comment]
load and navigate (takes an id) or expose provider?

**Comment by edsilv** [comment]
should there be a useIframe option?

**Comment by nicolasfranck** [comment]
This object oriented idea is great! Should be handy to add the manifest as a javascript-object using one of its methods. Now there are two request: one to load UV, and one to load the manifest.

```
uv.load_from_object(manifest);
uv.load_from_url(manifest_url);
```

**Comment by tomcrane** [comment]
Example of use - similar to http://www.wellcomeimageawards.org/2016/ebola-virus, where the initial UX is just an image and the viewer only appears on click.

Warning - that page isn't actually the UV, it's the Player, and it is still loading the whole js codebase before it will accept the click.

A uv.js bootsrapper would contain the minimal script to set up the event handling but only load the viewing environment when the user takes an action.

**Comment by edsilv** [comment]
There is now a new component model (#319). The UV can potentially inherit base-component in order to form a 'fractal architecture'.
