### ISSUE TITLE
Nested collection references don't load correctly

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#164]
If you load a collection which contains subcollections that are included as URI references (as opposed to fully specified objects), they do not expand when you click on them. For example, load:

http://digital.library.villanova.edu/Collection/vudl:3/IIIF

The Americana subcollection auto-loads correctly, but none of the subsequent subcollections work as of this writing.

**Comment by edsilv** [comment]
Solved by #308 but needs more work to allow comma-separated hash params for collectionIndex and manifestIndex
