### ISSUE TITLE
Support paging of search results when returned as paged anno lists

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#166]
As per spec - http://search.iiif.io/api/search/0.9/#paging-results-and-ignored-parameters

Low priority because no known instances of paged results in the wild yet - we'll have to create some for testing purposes.

**Comment by glenrobson** [comment]
Here is an example of a IIIF Search endpoint that supports paging:

http://dev.llgc.org.uk/iiif/search/4546256.json

and see results for cae (Welsh for Field):

http://dev.llgc.org.uk/iiif/search/4546256/search?q=cae

Its currently limited to 10 results per page and there are 26 results for cae.

**Comment by LlGC-dwj** [comment]
Some more search terms to look for:

Park returns 332 results but only shows 10
http://nlw.azurewebsites.net/?manifest=http://dev.llgc.org.uk/iiif/search/4546256.json#?cv=11&h=park

I'll look for more after lunch

**Comment by edsilv** [comment]
@LlGC-dwj that should be fixed now and show all results.

**Comment by LlGC-dwj** [comment]
Thanks Ed.

**Comment by LlGC-dwj** [comment]
@edsilv Just to clarify when searching for gene in http://nlw.azurewebsites.net/#?cv=23&h=gene the bottom result shows how many pages have results not the total amount of results found?

Would the string then be better as something like **26 items/pages found containing 'house'**?

**Comment by edsilv** [comment]
Hmm, yeah that should give the total number of results across all pages I think.
