### ISSUE TITLE
Allow locale-specific local configurations

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#170]
Right now, the configuration specified by data-config is global. In order to enable local customizations of l10n strings, we need to allow locale-specific overrides.

This was discussed in the comments on #168 and several options were proposed. One preferred solution would be to either allow the configuration file to be optionally divided into "global" and locale-specific sections, or else to allow inclusion of a map of locales to secondary locale-specific configurations that could be dynamically loaded as needed.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as fixed (discussed on 28/09/2023 Community Call)
