### ISSUE TITLE
"license" property should be rendered as link

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#173]
The license property is expected to be a URI, not a metadata value object, so should be rendered as a link:

http://iiif.io/api/presentation/2.0/index.html#rights-and-licensing-properties

Example manifest:

http://universalviewer.azurewebsites.net/?manifest=http://library-uat.wellcomelibrary.org/iiif/b18035978/manifest

Maybe the link text should be "License" - but will need a different layout (it's not a name/value pair to the user).

**Comment by demiankatz** [comment]
This is addressed by #168, though that's currently held up by issues related to #172.
