### ISSUE TITLE
Level of support for IE8/9

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#177]
Background:

https://gist.github.com/tomcrane/a4c2a8c63988093e3923

Until recently the UV was using JSONP in IE8/9 to load an info.json cross domain.

* IE8/9 needs to use XDomainRequest rather than XmlHttpRequest to load info.json from a different domain. This is shimmed into jQuery with [this](https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest), but that may cause a problem with requireJS.

Investigate/fix requireJS problem by including shim code directly (it's not very big).
This gives us proper cross domain info.json in IE8/9 without requiring JSONP on the other end, so this is an improvement on what we had.

* Problem in IE8/9 - if the info.json is subject to auth, we can't implement the client side auth flow because XDomainRequest doesn't let us interact with the response body or HTTP status codes unless it's a 200. However, we might be able to support authed info.jsons *on the same domain* if we can ensure that IE8/9 uses XmlHttpRequest for the same domain, which does expose status codes and the body.

The shim would allow the UV in IE8/9 to request info.json cross domain. However, if the info.json is authed and on a different domain, IE8/9 can't deal with it and we show a message to the user (in reponse to the [500 error we get from the shim](https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest/blob/master/jQuery.XDomainRequest.js#L97)).

"You are attempting to view access-controlled content on a different domain. This feature is not supported in your browser. Try a better one..."

We need to ensure that the shim does this:

|    ***info.json***             | Open           | Authed         |
| --------------- |:--------------:| --------------:|
| **Same domain**   | XmlHttpRequest | XmlHttpRequest |
| **Other domain**  | XDomainRequest |      N/A       |

I think it already does this:

https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest/blob/master/jQuery.XDomainRequest.js#L33

if(!options.crossDomain...) suggests it won't shim XDomainRequest in unless it is really cross domain, so I *think* we will get the behaviour in that table. Needs testing.

Note that JSONP doesn't help here, we can't interact with the Auth flow from JSONP. So we are no worse off without it, and we have gained cross-domain support for open content in IE8/9 without requiring JSONP on the other end.

If an institution has a large IE8/9 user base, they can support them for their OWN **authed** content on their OWN site by hosting the UV and the content on the same domain - in theory this will work because jquery.ajaxTransport will use XmlHttpRequest in IE8/9. There might be other limitations of IE8/9 XmlHttpRequest that prevent an interaction with the auth flow, but fingers crossed...

**Comment by edsilv** [comment]
This should be resolved by https://github.com/UniversalViewer/universalviewer/commit/a89e192f8d1e174459a6d2eb9e70f5dd1716c993
