### ISSUE TITLE
Alt + Fullscreen = Windowed mode

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#184]
https://groups.google.com/forum/#!topic/universalviewer/qDA_CGxSg08

Holding alt (option on mac) and clicking the full screen button will force windowed mode.

This will be documented on the UV wiki, which can be reached by clicking on "more info" in the settings dialogue.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closing as inactive -- discussed on 9/28/23 community call.
