### ISSUE TITLE
Configurable order of more info panel data

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#185]
https://groups.google.com/forum/#!topic/universalviewer/TqQ9EjAH5mA

Include a new `rootLevelDataFirst` or similar config option.

**Comment by tomcrane** [comment]
Could just use the iiif names:

```
"moreInfoDisplay" : ["license", "attribution", "metadata", "logo"]
```

Actually this is pretty nice - if the BL always show the attribution as an overlay regardless of home domain etc, then they would leave it out of the more info panel completely:

BL's config:

```
"moreInfoDisplay" : ["metadata", "license"]
```

(for example)

Call it something better than moreInfoDisplay.

**Comment by edsilv** [comment]
Yep, that could work. Maybe name it `infoDisplayOrder`.

I don't think an array will work though with the json config editor. It would need to be a csv string:

"license, attribution, metadata, logo"

**Comment by glenrobson** [comment]
Thanks for looking at this Ed and the explanation you sent to the list, I've been spending weeks off and on trying to get the attribution and license at the bottom. Has the order changed in recent versions of the UV? The following has it at the bottom:

http://nlw.azurewebsites.net/?jsonp=null&testids=false&defaultToFullScreen=false&manifest=http%3A%2F%2Fdams.llgc.org.uk%2Fiiif%2F2.0%2F1124200%2Fmanifest.json&locale=en-GB#?si=0&ci=0&z=-0.3731%2C0%2C1.7462%2C1.6038

but the version we are using has it at the top. Having it configurable and also possibly hiding things like logo would be really useful. In the theme we've got of the UV we've already got two of our logos showing so we may want to hide the one in the metadata section. 

Thanks

Glen

**Comment by edsilv** [comment]
Hi, yes the order changed fairly recently. I'm not sure why this came about - but should be solved by the proposed new configuration option. Regarding hiding specific metadata items, that would have to be a case of excluding them from the manifest I think...

**Comment by tomcrane** [comment]
I have already put this into Wellcome Library config in anticipation of the feature:

    "moreInfoRightPanel": {
      "options": {
        ...
        "infoDisplayOrder": "metadata, license, attribution"
      },

(note NO LOGO - Wellcome doesn't want to display its own logo when the viewer is embedded with this config on its own site)

**Comment by edsilv** [comment]
I just pushed v1.6.7. This adds`displayOrder` and `exclude` to the moreInfoRightPanel config.

Using `displayOrder` you can set the order of `attribution`, `license`, `logo`, `description`, and `metadata` using a csv string.

e.g. 

    attribution, license, description, metadata, logo

`exclude` can be used to exclude any of these using a csv string.

e.g.

    description, logo

Both of these config options are empty by default. The idea is that deployers use the `data-config` attribute to override them.

To target items contained in `metadata`, you need to exclude them from the manifest itself. @glenrobson let me know if this works for you.

**Comment by tomcrane** [comment]
I can confirm this works on wellcomelibrary.org manifests.

**Comment by LlGC-szw** [comment]
We're setting up the new version for Glen to test this over the next couple of days. Hopefully Glen will get back to you once this is done. Thanks for implementing these changes, they'll make a big difference.
