### ISSUE TITLE
Showing image specific information in the right panel

### ISSUE THREAD

**Issue by bazer** [UniversalViewer/universalviewer#188]
Hi!

We are working on a feature to show image specific information in the "more information" panel.
I know you guys have been talking about doing something similar so I wanted to check with you first if you have any thoughts.

We are thinking about using the MetaData element on canvas to store the information. We need to have it in both swedish and english and metadata handles that very well. Since the right panel also already understands metadata it seems consistent.

We are planning to show the image specific information below the information that is already there, perhaps with a slight border in between. On paging we then swap that portion out with new data from the manifest.

Is this something along the lines of what you were thinking about? Would you be interested in having this feature in UV?

**Comment by tomcrane** [comment]
Hi,

Currently the UV takes the manifest-level metadata, and once #185 is done, will display those pairs at the position given in the config, using the language/locale setting to pick out the correct language strings.

Up till now we have not addressed the display of metadata for other resources that might be "in scope". For example, if the user is looking at a particular image, there might be metadata, rights and licensing properties for the image, for the canvas, for the current sequence, for the range, for the manifest and for the collection. All of these could contribute something to the "more info" panel.

What should the UV do? Clearly there needs to be some kind of aggregation of metadata, as in your proposal (show the image-specific metadata below the manifest-level metadata, with some visual clue to indicate their separate origin). Should we do anything special if a metadata value is the same as one already declared at a higher level? Probably not, we should discuss what the UV does here. 

The UV's history means that it never had anything other than manifest level data - once rendered, the more info panel had no need to change as the user explores the item further. But the IIIF model is richer and more flexible than this, and manifests from other publishers will have more complex hierarchies of metadata. As well the UX for metadata we need to consider the UX for notifying the user of available annotation lists, which also changes from canvas to canvas, and logically fits under "more information".

So yes, we do want this feature in the UV for those manifests that provide different metadata at different levels - sounds like a topic for the community call.

Tom

**Comment by tomcrane** [comment]
See also #119, #122

**Comment by demiankatz** [comment]
Definitely worth discussing on the community call. In the past we have talked about the possibility of introducing tabs into the "more info" panel so you can switch between item-level and image-level metadata.

**Comment by edsilv** [comment]
Maybe there could be two tabs, one for read-only metadata, another for read-write, like annotations. Then within these tabs we use collapsible accordion menus to logically group things.

**Comment by bazer** [comment]
We are thinking about something like this:

![rightpanel](https://cloud.githubusercontent.com/assets/760713/11216062/a241f0d6-8d49-11e5-8a4e-4a30ca90d519.PNG)

It should scale reasonably well with adding sequence metadata and other info too. We are not sure about the actual header texts, it's hard to find something really fitting because we have lots of different types of material. But we have added the texts to the config. We also made it so that if you don't set any text, no header will show and it will look just like before.

Being able to collapse the headers like Ed suggested sounds like a great idea. I don't think we will have enough information to really make it necessary for us though. But it could be added pretty easily when needed.

Maybe the annotations could be in another tab, or added at the bottom (or top). We don't really have any annotations so I'm not to familiar with those.

I'd be glad to join you at the next community call for some discussion.

**Comment by tomcrane** [comment]
Also relevant - this discussion on iiif-discuss:

https://groups.google.com/forum/#!topic/iiif-discuss/x3dofAuiUnQ

Although sometimes annotations will be read/write, most people will consume them (especially transcription annotations, commentary etc) as read only. In a library discovery scenario, annotation lists the manifest knows about are more likely to be read-only in the UV, annotation lists the user brings are unlikely to be known to the manifest. This is a guess from imagined use cases and could be completely wrong.

Regardless, I agree that the annotation UI should be completely separate from the metadata and rights and licensing; it's a different kind of interaction altogether.

**Comment by azaroth42** [comment]
:+1: on this issue! Canvas level metadata display is something that has been on many wish lists for a long time.

**Comment by tpendragon** [comment]
:+1: The mockup looks great.

**Comment by tpendragon** [comment]
May be a different issue, but now that https://github.com/IIIF/iiif.io/issues/703 is clear to me, could we add range metadata here as well? I'm not sure what the header would be, but even "Additional Metadata" would be sufficient.

**Comment by bazer** [comment]
We have got this working in production already, for example:
https://sok.riksarkivet.se/bildvisning/C0000263_00050?beta=true

The code is over in our fork:
https://github.com/Riksarkivet/universalviewer

I'm currently working on a different project for a different employer, but I'll be back on this in two weeks.
I can try and get a pull request together for you then if you want? 
Otherwise you can always poke around and see what comes up :)

**Comment by LlGC-szw** [comment]
This looks great. Hopefully we can get some data into a manifest to get this working with us.

**Comment by bazer** [comment]
I finally got around to putting together a pull request, it's over here: #243.

**Comment by tomcrane** [comment]
Princeton's use case is Range-level metadata, as @tpendragon mentions above https://github.com/UniversalViewer/universalviewer/issues/188#issuecomment-176294919 and on https://github.com/IIIF/iiif.io/issues/703.

This (and canvas-level metadata) are specific cases of the more general "display all metadata in scope".

Given the visual appearance of this is solved by @bazer in his PR, can we generalise this to aggregate all the relevant metadata for what's in the viewport and list it "top-down" in the more info panel?

Possible issues:

* A canvas could be in more than one range, but the user navigation journey has a particular range as context. Which means the metadata might depend on what range is selected in the tree nav. This is important for solving #239 
* A canvas could be in more than one sequence - but the UV only shows one sequence at a time, so that is probably not an issue.

In the Sammelband use case given in https://github.com/IIIF/iiif.io/issues/703 the manifest-level metadata could be quite light, but the top level range for each bound work could have much more metadata. That's OK - maybe the order is..

1. Manifest level metadata
2. Sequence level metadata
3. Metadata from the current Range, walking up the Ranges to the top, displayed in top down order
4. Canvas level metadata
5. Image level metadata (if image choice https://github.com/UniversalViewer/universalviewer/issues/119)
