### ISSUE TITLE
Resizing stops working after fullscreen

### ISSUE THREAD

**Issue by ra-magnus-welander** [UniversalViewer/universalviewer#189]
Steps to reproduce:
1. Go to https://demosok.riksarkivet.se/bildvisning/F0002433?beta=true#?s=0&cv=7&c=0&m=0&z=-0.1721%2C0.0044%2C1.3443%2C0.7285
2. Resize the window - content resizes
3. Press the fullscreen icon
4. Leave fullscreen
5. Resize the window - content doesn't resize

**Comment by edsilv** [comment]
is your embed.js up to date? see this line:

https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/embed.js#L341

this resets the containing div's width and height to the size it was before being full screened.

**Comment by edsilv** [comment]
That should be fixed now.

**Comment by ra-magnus-welander** [comment]
Yes, this works now, cheers!
