### ISSUE TITLE
Should we have a config setting for default "you are being asked to authenticate" message?

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#195]
Consider this auth service:

```
  "service": {
    "@id": "http://local.wellcomelibrary.org/iiif/accepttermslogin",
    "profile": "http://iiif.io/api/auth/0/login",
    "label": "Archival material less than 100 years old",
    "service": [
      {
        "@id": "http://local.wellcomelibrary.org/iiif/tokenterms",
        "profile": "http://iiif.io/api/auth/0/token"
      },
      {
        "@id": "http://local.wellcomelibrary.org/iiif/logout",
        "profile": "http://iiif.io/api/auth/0/logout",
        "label": "Log out of Wellcome Library",
        "description": "Log out of Wellcome Library"
      }
    ]
  }
```

The UV does exactly the right thing by showing this dialogue:

![login](http://tomcrane.github.io/presentations/general/login-no-message.png)

...but should the UV in this case pull something from its config, e.g.,

"The server at http://wellcomelibrary.org is asking you to authenticate to view this image"

to fill the dialogue box?

If the service provides a description:

```
  "service": {
    "@id": "http://local.wellcomelibrary.org/iiif/accepttermslogin",
    "profile": "http://iiif.io/api/auth/0/login",
    "label": "Archival material less than 100 years old",
    "description": "Description goes here",
```

...then the UV shows it:

![login-desc](http://tomcrane.github.io/presentations/general/login-with-description.png)

I'm wondering if it's simply incumbent on the publisher of the service to provide a description, or whether the UV should provide a default description - and label too, for that matter.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by tomcrane** [comment]
Suggest close this issue has it has been superseded by IIIF Authorization Flow 2 (which is a separate issue!)

Support for Auth v1 should be considered legacy.
