### ISSUE TITLE
Text editing in search box

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#199]
(reported by @pollecuttn, @jennpb at https://digirati.atlassian.net/browse/UV-43)
 —

http://wellcomelibrary.org/item/b21211887 

I want to search within ‘method it employs’ but realise this is wrong. I can select ‘it’ and type over it to change it to ‘he’ but I can’t hit ‘delete’ to get rid of anything in the search box.

It feels weird that I can’t select and delete something in a text box with the delete button.

THEN, in trying to replicate this, I spotted another problem.
 If I enter a search string that has no matches, I click OK in the dialog box and then it totally greys out the whole viewer. You have to refresh the page to attempt another search.

I captured it here: http://screencast.com/t/buuSjLuV 

Thanks,

Natalie

**Comment by edsilv** [comment]
There's a problem with the autocomplete box not opening on mac #218
