### ISSUE TITLE
support facing-pages viewingHint

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#204]
http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb19956447%2Fmanifest&locale=en-GB#?c=0&m=0&s=0&cv=10&z=0%2C-0.2931%2C2%2C1.4794

(although the hint is not present on the resource at time of writing - the two page spread should be shown on its own).

**Comment by tomcrane** [comment]
> Canvases with this hint, in a sequence or manifest with the “paged” viewing hint, must be displayed by themselves, as they depict both parts of the opening. If all of the canvases are like this, then page turning is not possible, so simply use “individuals” instead.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by tomcrane** [comment]
This is another "filling in the unsupported bits of the spec" issue - i.e., nice to do for completeness but maybe not to be prioritized at the expense of bugs.

I don't know how common `facing-pages` is; maybe canvas the views of UV users?
