### ISSUE TITLE
Collections with single page items don't render the nav tree

### ISSUE THREAD

**Issue by mattmcgrattan** [UniversalViewer/universalviewer#206]
If we load a collection into the UV, where the first item in the collection is a single page item, such as a map or poster, the navigation tree doesn't appear, so it's not possible to navigate to other items in the collection.

**Comment by Daniel-KM** [comment]
Hi,

I confirm the bug. It appears between 1.5.30 and 1.5.42 and the last release 1.6.6 has this bug too.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by edsilv** [comment]
This should be fixed on the dev branch now.
