### ISSUE TITLE
Support continuous and all other viewing hints

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#209]
http://iiif.io/api/presentation/2.1/#technical-properties

(can split these as per #602 if easier)

**individuals** Already supported implicitly. Explicit support should DENY the two-up view. 

**paged**  Already supported.

**continuous**  NOT YET IMPLEMENTED _Valid on manifest, sequence and range. Each canvas is a partial view and an appropriate rendering might display either the canvases individually, or_ **_all of the canvases virtually stitched together in the display**_ (OSD Collection). _Examples when this would be appropriate include long scrolls, rolls, or objects designed to be displayed adjacent to each other. If this viewingHint is present, then the resource must also have a viewingDirection which will determine the arrangement of the canvases._

**multi-part**: Implicitly supported - UV treats all collections like this currently. _Valid only for collections. Collections with this hint consist of multiple manifests that each form part of a logical whole. Clients might render the collection as a table of contents, rather than with thumbnails. Examples include multi-volume books or a set of journal issues or other serials._

**non-paged**: NOT YET IMPLEMENTED. _Canvases with this hint must not be presented in a page turning interface, and must be skipped over when determining the page sequence. This viewing hint must be ignored if the current sequence or manifest does not have the ‘paged’ viewing hint._

**top**: NOT YET IMPLEMENTED. _Only valid on a range. A range which has this viewingHint is the top-most node in a hierarchy of ranges that represents a structure to be rendered by the client to assist in navigation. For example, a table of contents within a paged object, major sections of a 3d object, the textual areas within a single scroll, and so forth. Other ranges that are descendants of the “top” range are the entries to be rendered in the navigation structure. There may be multiple ranges marked with this hint. If so, the client should display a choice of multiple structures to navigate through._ We don't have any examples of this so need to make/obtain some.

**facing-pages**: NOT YET IMPLEMENTED. See #204 for this as a separate issue. Canvases with this hint, in a sequence or manifest with the “paged” viewing hint, must be displayed by themselves, as they depict both parts of the opening. If all of the canvases are like this, then page turning is not possible, so simply use “individuals” instead.

**Comment by tomcrane** [comment]
Note on **continuous**:

The OSD canvas seems straightforward, using collection mode and the viewingHints.

But what is the implication for the thumbnail view? This is the UI problem to solve. For top-to-bottom continuous items the thumbnail view if OK, but what about a left-to-right?

Extreme case - The Bayeux Tapestry. 200 separate canvases with a continuous viewingHint and ltr viewingDirection. What does this look like in the thumbnail panel?

**Comment by tomcrane** [comment]
Note on **top**:

This viewingHint would allow the viewer to present different navigation tree structures for the same work, if the manifest offers multiple ranges marked as "top" - e.g., to choose between two different interpretations of the structure of a work - toggle between two different navigation trees.

**Comment by tomcrane** [comment]
I'm going to separate these out as they can't be labelled as separate requirements when they are all in this issue.

**Comment by tomcrane** [comment]
Superseded by:

https://github.com/UniversalViewer/universalviewer/issues/101 - non-paged
https://github.com/UniversalViewer/universalviewer/issues/295 - continuous
https://github.com/UniversalViewer/universalviewer/issues/204 - facing-pages
https://github.com/UniversalViewer/universalviewer/issues/296 - top

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by tomcrane** [comment]
CLOSE this issue - as the comment says, it has been split into individual issues.
https://github.com/UniversalViewer/universalviewer/issues/209#issuecomment-213743586
