### ISSUE TITLE
Multi-up comparison view

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#211]
Investigate using https://github.com/aeschylus/Isfahan to host multiple instances of the UV. This would enable Mirador-style item comparison. Depends on #156 to provide external UV api. Could also potentially use a similar pattern to #212 if not 'Manifold' itself for state management?

**Comment by edsilv** [comment]
Investigate https://github.com/slightlyoff/cassowary.js as alternative layout system

**Comment by edsilv** [comment]
BL want a curated mult-up. 

http://special-1.bl.uk/treasures/SiqDiscovery/ui/search.aspx

Just make uv.js and 'uv-orchestrator.js'. No need for arbitrary "workspace" windowing system.

**Comment by mialondon** [comment]
@edsilv do you have all the information you need to work on this now?

**Comment by edsilv** [comment]
This has been approved as done: http://bltesters.azurewebsites.net/two-up.html
