### ISSUE TITLE
Autocomplete on Mac not opening

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#218]
Potentially related to #199 

Happens in Chrome and Safari

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity -- I'm assuming browser-specific issues from 2016 probably don't apply today.
