### ISSUE TITLE
"Download high res" and related functionality respects maxWidth, maxHeight and maxArea

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#219]
IIIF 2.1 allows a server to assert the maximum size of image it will return: https://github.com/IIIF/iiif.io/issues/663

(still in a little bit of flux but can assume maxWidth, maxHeight and maxArea will become part of standard).

This means that /full/full/... won't necessarily work for the "download high res" - need to either:

1) calculate the size parameter as per https://github.com/IIIF/iiif.io/issues/663
2) use /full/max/ if it's supported by the server (and in the spec)

**Comment by tomcrane** [comment]
Now in the spec:

http://iiif.io/api/image/2.1/#profile-description

maxWidth on its own is the most likely thing to encounter, and it implies that maxHeight is the same - i.e., it specifies a square bounding box for confinement.

UV currently uses the concept of maxWidth, from config, so basically maxWidth in an info.json overrides the one from config, and the UV then behaves the same wrt the download  w x h options. It needs to be a bit clever though, if the maxWidth means that there would be two options the same size, or roughly the same size (e.g., info.json has maxWidth 1000).

**Comment by edsilv** [comment]
maxwidth is now supported. @tomcrane please create a separate issue for maxarea.
