### ISSUE TITLE
Handle out of index exceptions in index passed in the URL

### ISSUE THREAD

**Issue by kenlt** [UniversalViewer/universalviewer#22]
Should be able to handle indexes that are out of range, e.g. 

http://bltesters.azurewebsites.net/?manifest=http://v8l-webtest1.bl.uk:88/IIIFMetadataService/004997222/manifest.json#?si=0&ci=10&z=0.5073%2C0.3848%2C0.186%2C0.1136

Should not fail without an error but default to the last possible image, which in this case is index 0 or at the very least provide an error indicating that the index is out of range.

**Comment by edsilv** [comment]
I think perhaps it should default to the first image?

**Comment by fractos** [comment]
Agreed in meeting to default to first image.
