### ISSUE TITLE
Support array of strings in Metadata without language

### ISSUE THREAD

**Issue by tpendragon** [UniversalViewer/universalviewer#220]
Language is an optional designator in the Presentation API, but because UV wants to filter values based on locale it requires them. We have metadata whose language we can't be sure of (because it was never entered), and so simply omit the language designation, and would like it to show up. Can we change https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/manifesto.js#L1536 to be "all those entries matching the configured locale, as well as those with no designation"?

**Comment by edsilv** [comment]
Hi, I think I'm misunderstanding the problem. I've added a new test to manifesto for the 'biocrats' manifest:

https://github.com/UniversalViewer/manifesto/blob/master/test/biocrats.js#L34

This manifest has untranslated metadata:

https://github.com/UniversalViewer/manifesto/blob/master/test/fixtures/biocrats.json#L9

If you set a break point in that test, the metadata array is coming through ok.

Could you see if you can write a test to demonstrate the problem?

If the resource to be localised is just a string not an array of language values, the string will be returned:

https://github.com/UniversalViewer/manifesto/blob/master/src/Utils.ts#L10

Also, I've had confusion in the past regarding the files in `src/lib`. These are just copies of the npm/bower installed files.

**Comment by tpendragon** [comment]
@edsilv 
```json
metadata: [
{
label: "Creator",
value: [
{
@value: "Antolini, Giovanni Antonio, 1754-1842."
}
]
},
{
label: "Date created",
value: [
{
@value: "1785"
}
]
}
]
```

Resources that have values, to support array values, but not language tags.

**Comment by edsilv** [comment]
Aha, I see. Yep, go ahead and make the changes to Utils.ts

https://github.com/UniversalViewer/manifesto/blob/master/src/Utils.ts#L7

and issue a pull request.

**Comment by edsilv** [comment]
Might be good to include your manifest in the test fixtures and write a test too.

**Comment by tpendragon** [comment]
@edsilv I can't seem to get the thing running locally - throwing dependency errors. Maybe an NPM problem?

**Comment by edsilv** [comment]
I was having issues with npm yesterday too. I tried again today on a fresh clone and it installed everything without a snag (on windows 8). Have experienced temporary npm glitchiness like this before. Hopefully we can ignore it.

I've updated the readme with a Developer Setup section listing the necessary commands to get it built and tests passing.

**Comment by tpendragon** [comment]
@edsilv I can't get manifesto's tests to pass - doesn't seem to be loading the manifest variable. Trying to times out at 2,000 ms.

**Comment by edsilv** [comment]
These are the paths to the manifests:

https://github.com/UniversalViewer/manifesto/blob/master/test/fixtures/manifests.js

Perhaps there's a problem with localhost:3000 not serving them?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
