### ISSUE TITLE
Internet Explorer 9 Loading never completes

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#227]
On IE9, the bootstrapping process no longer gets past the initial phase. No JavaScript errors are visible in the console, it just finishes execution. 

This is reproducible on Windows 8 / IE11/Edge in IE9 Document Mode, but not in Windows 10 / Edge where full Document Mode emulation has been removed from F12 developer tools.

The UV does work in IE9 (tested for BL and Wellcome) so this must be a recently introduced bug.

NB - not related to authentication - happens before we get to that stage.

IE does get as far as loading the manifest (via jsonp?), then it loads /lib/base64.min.js twice and that's the last network activity recorded.

**Comment by nicolasfranck** [comment]
I have a similar problem with IE9, when the page loads. The last thing I see in the console is:
```
SCRIPT1004: Expected ';'
File: app.html, Line: 2, Column: 12
```
It seems like the loaded HTML page "app.html" is interpreted as javascript (which is shouldn't),
even while the content type is set correct to "text/html". 
And it stills get injected in the iframe? I don't get it.

If you visit the app.html (with all of its parameters) itself, the viewer works fine.
What/who is trying to interpret the content of this iframe?

Higher versions do not have this problem.

**Comment by nicolasfranck** [comment]
Oops, sorry. I see now that it adds 'callback' parameter url to the config url to load it as javascript.

**Comment by dvhassel** [comment]
There seems to be a similar problem with UV2.0.2 and IE11 on Win7: "Object doesn't support property or method 'forEach'" in bundle.min.js ({baseCtors.forEach(function(baseCtor){Object.getOwnPropertyNames(baseCtor.prototype).forEach(function(name){derivedCtor.prototype[name]=baseCtor.prototype[name]})}) )
