### ISSUE TITLE
Download menu describes dimensions of image options

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#229]
If the config strings for the image download options contain {w} and {h} placeholders, the UV should determine what the values are and use them in the display - this gives the end user a much better idea about what they are about to request:

e.g, 
Current view {w} x {h} (jpg)
Whole image high res {w} x {h} (jpg)
Whole image low res {w} x {h} (jpg)

The high res option should take account of the max settings defined in the info.json, if present (see #219). If there is no maxWidth it should use the advertised size of the image. However, we should probably have an absolute max defined in UV config to prevent a poor user experience (e.g., hitting download high-res on a gigapixel image that doesn't declare a max). That is, if the info.json doesn't have a max the UV applies a configurable maxWidth for the current image. This can be very high, e.g. 10,000 - but prevents the open-ended "full" problem. If a user wants to make their own IIIF Image request because they want something bigger, they can do that themselves.

**Comment by edsilv** [comment]
if uv config is maxWidth=8000, and the image is a vertical scroll w=4000 h=160000, then /full/max/ would be 200 x 8000. And because the target info.json's image server won't support /full/max/ unless it's a 2.1 profile server that conforms to the as-yet-unreleased spec, the UV should construct a proper size parameter (/full/200,4000/). If the UV knows that the image service supports /max/ as a parameter, then it should use /max/.

**Comment by tomcrane** [comment]
http://wellcomelibrary.org/item/b23984958

This item is a single canvas with a single image.

In the manifest (http://wellcomelibrary.org/iiif/b23984958/manifest):

```javascript
{
  "@id": "http://wellcomelibrary.org/iiif/b23984958/canvas/c0",
  "@type": "sc:Canvas",
  "label": " - ",
  "thumbnail": "http://wellcomelibrary.org/thumbs/b23984958/0/4f48021d-a868-44b1-8d92-41b9871f780c.jpg",
  "height": 1800,
  "width": 2400,
  "images": [
    {
      "@id": "http://wellcomelibrary.org/iiif/b23984958/imageanno/4f48021d-a868-44b1-8d92-41b9871f780c",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@id": "http://wellcomelibrary.org/iiif-img/b23984958-0/4f48021d-a868-44b1-8d92-41b9871f780c/full/!1024,1024/0/default.jpg",
        "@type": "dctypes:Image",
        "format": "image/jpeg",
        "height": 768,
        "width": 1024,
        "service": {
          "@context": "http://iiif.io/api/image/2/context.json",
          "@id": "http://wellcomelibrary.org/iiif-img/b23984958-0/4f48021d-a868-44b1-8d92-41b9871f780c",
          "profile": "http://iiif.io/api/image/2/level1.json"
        }
      },
      "on": "http://wellcomelibrary.org/iiif/b23984958/canvas/c0"
    }
  ]
}
```

And the info.json for the service (http://wellcomelibrary.org/iiif-img/b23984958-0/4f48021d-a868-44b1-8d92-41b9871f780c/info.json):

```
height: 1800,
width: 2400,
```

The viewer config (https://wellcomelibrary.github.io/configuration/uv/uv-config.json) includes this:

```
"downloadDialogue": {
  "options": {
    "confinedImageSize": 1000,
    "maxImageWidth": 9000,
    "selectionEnabled": false
  }
```

http://wellcomelibrary.org/iiif-img/b23984958-0/4f48021d-a868-44b1-8d92-41b9871f780c/info.json

The download menu produced looks like this:

![download-opts](https://cloud.githubusercontent.com/assets/1443575/13730245/c2621e5a-e941-11e5-96c9-ce6e8d73fdae.png)

The first option is DownloadOption.currentViewAsJpg (the current viewport)
The second option is DownloadOption.wholeImageHighRes
The third option is DownloadOption.wholeImageLowResAsJpg

the first and third options are as expected - the third option uses confinedImageSize to determine what the low res image should be.

However, the second option doesn't let you download the best possible image the publisher is making available, because it uses the dimensions of the image resource (the image annotation on the canvas) to determine the size (in this case 1024 x 768) rather than the dimensions available from the image service (2400 x 1800):

https://github.com/UniversalViewer/universalviewer/blob/dev/src/extensions/uv-seadragon-extension/DownloadDialogue.ts#L153

The size comes from:

```
var size: Size = this.getDimensionsForCurrentCanvas();
```

But I think it should come from ```getDimensionsAvailableFromImageService()``` or something like that - which is an easy place to add support for "max" properties in the info.json later.

As the publisher, I could get round this by making my image annotations bigger - make them the biggest possible size - but there are reasons why a publisher might not want to do that, e.g., if the manifest is being used to drive a lo-fi viewing experience without deep zoom.

**Comment by tomcrane** [comment]
I'll reopen this - can move this to a new issue if preferred.

**Comment by tomcrane** [comment]
I have a feeling I might have suggested that the UV should use image annotation size for the hi-res image, but if I did suggest that I now think I was wrong - the "maxXXX" properties in the IIIF 2.1 spec change this because they allow a publisher to tell the UV (or any client) exactly what is permitted. I could have a 500000 x 200000 image and a maxWidth on the service of 9000; the UV can use the image service dimensions AND the maxWidth property and safely request a 9000 wide image for the "download hi res" option.

**Comment by tomcrane** [comment]
btw I have added support for maxWidth to Wellcome image services. I won't add an explicit maxHeight or maxArea, although the UV should also look for these constraints.

Currently deployed only to UAT (but publicly available), e.g., http://library-uat.wellcomelibrary.org/iiif-img/b23984958-0/4f48021d-a868-44b1-8d92-41b9871f780c/info.json

See http://iiif.io/api/image/2.1/#profile-description

UV support for "max" is not required to address the issue raised in the comment https://github.com/UniversalViewer/universalviewer/issues/229#issuecomment-196014695

**Comment by tomcrane** [comment]
See https://github.com/UniversalViewer/universalviewer/issues/277 for ordering
