### ISSUE TITLE
"Feedback" button

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#231]
This is a specific usage of a more general state management capability (and also extends #182).

Pressing this button fires an event to the containing page that dumps diagnostic info about the current state. The containing page can do whatever it wants with this data, but typically it could be used in "report a problem" scenarios. 

The UI for giving feedback is not the UV's concern - the containing page can provide that; if it chooses to launch a dialogue that is "on brand" with its UV theme then it can appear seamless, but it's up to the implementer.

**Comment by mialondon** [comment]
Options from Font Awesome include:
* http://fortawesome.github.io/Font-Awesome/icon/at/ @
* http://fortawesome.github.io/Font-Awesome/icon/envelope-o/
* http://fortawesome.github.io/Font-Awesome/icon/commenting-o/ (not comment, as that's used for annotations)
* http://fortawesome.github.io/Font-Awesome/icon/fax/ (I'm only partly kidding)

My preference is for '@' as hopefully users would associate it with email or 'get someone's attention on social media', both of which are relevant.

**Comment by mialondon** [comment]
For reference, this is the icon currently in use on Explore: 

![current bl catalogue feedback icon](https://cloud.githubusercontent.com/assets/380763/12887295/431165f2-ce6b-11e5-882a-a12de107025a.png)

**Comment by mialondon** [comment]
@edsilv @jennpb testing showed that people emphatically did not understand the @ symbol! Ed, can you please change it to http://fontawesome.io/icon/envelope-o/?

**Comment by mialondon** [comment]
@edsilv it'd be really good to get this one of the way as we already know it's going to confuse people. Can you squeeze it in?

**Comment by jennpb** [comment]
Envelope makes sense to me if it's triggering a mail form. Wellcome's not likely to use this option in future, but good to have the testing evidence!

**Comment by edsilv** [comment]
Updated to envelope: https://github.com/UniversalViewer/universalviewer/commit/144f462fb2d3ee1fedf02f03704c9c8e344ab9eb
