### ISSUE TITLE
Investigate implication of "members" resource in collection

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#233]
See https://github.com/IIIF/iiif.io/issues/697

The issue is whether the UV could support this. I think so, because it already builds a nav tree across collection/manifest/range structure.

The caveat is that the user can open and close nodes in the tree within the current manifest and its ancestors, but if you switch to a tree node that represents a different manifest, the UV reloads to render the new manifest (still maintaining the context of the collection). You can't currently have range nodes from two different manifests open at the same time - but that doesn't get in the way of supporting the "members" resource.

Example:

http://wellcomelibrary.org/item/b18031511

**Comment by tomcrane** [comment]
Fixed by #291 I think?

**Comment by edsilv** [comment]
Yep.
