### ISSUE TITLE
'Add to Bookmarks' not kicking off auth process

### ISSUE THREAD

**Issue by jennpb** [UniversalViewer/universalviewer#235]
Hi Ed
This may be limited to Wellcome's internal network. When clicking the 'Add to bookmarks' button, I would expect to be prompted to log in. Instead I'm getting the option to Save to a new folder.

![noauth](https://cloud.githubusercontent.com/assets/1446139/12720285/ee1c9a72-c8f1-11e5-8b7c-2d320b788f05.png)

This happens in Chrome and IE.

I tested this on my laptop in Chrome, Firefox and Safari and was prompted to log in (so, working as normal).

**Comment by edsilv** [comment]
@tomcrane will add this to JIRA, not a UV issue.
