### ISSUE TITLE
Settings panel configurations

### ISSUE THREAD

**Issue by jennpb** [UniversalViewer/universalviewer#236]
Hey
Sorry if this is covered elsewhere (I couldn't find it in GH or JIRA).

**Locale**
During the last community call, @tomcrane and I noted that the locale is duplicated in the settings: http://wellcomelibrary.org/item/b19520906

We also had hoped to disable the locale if only one locale is present. I couldn't find a related Github issue for this, though I'm certain there is one.

Is this still on the cards?

**Navigator enabled**
What's this meant to do? I couldn't discern any change between ticked and unticked, and it's definitely not something that users would know from its description.

**Comment by edsilv** [comment]
https://github.com/UniversalViewer/universalviewer/issues/151

If the `limitLocales` root-level config option is set to true, and there is only one locale specified in `data-locale` on the embedding div, the settings > locale menu will not appear.

The Navigator Enabled setting shows/hides OpenSeadragon's overlayed navigation window.

**Comment by jennpb** [comment]
@edsilv 
re: Navigator Enabled, I see no difference in the viewing experience if the box is ticked or unticked. 

I would like to not display it as an option at all.

**Comment by jennpb** [comment]
@edsilv 
re: Navigator Enabled, I see no difference in the viewing experience if the box is ticked or unticked. 

I would like to not display it as an option at all.

**Comment by jennpb** [comment]
@tomcrane @edsilv I don't see `limitLocales` or `data-locale` in our config, so I can't turn this off. @tomcrane  Maybe you can help with this today?
