### ISSUE TITLE
Ranges with overlapping canvases

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#239]
Example manifests:
All these include canvases that are members of more than one range. The navigation has a problem with that.

http://wellcomelibrary.org/iiif/b19646045/manifest
(e.g., first item in index)

http://wellcomelibrary.org/iiif/b19638425/manifest
(e.g., fourth item "Latin Poem")

http://wellcomelibrary.org/iiif/b19683704/manifest
(e.g., fourth, fifth and thirty-fourth items)

Wellcome asks "Is it possible to fix these or should the METS editors make the "Works" unique so that there is no cross-over between them in terms of images?" 

Overlapping ranges are valid constructions - especially prevalent in newspapers where, if ranges describe articles, many canvases appear in multiple ranges.

**Comment by tomcrane** [comment]
Look at as part of https://github.com/UniversalViewer/universalviewer/issues/319

**Comment by edsilv** [comment]
I've fixed the case where you're clicking on the ranges in the tree so it selects the correct one. However, when loading afresh with a given canvas index, it has no way of knowing which range you want selected, so picks the first one associated with that canvas. Later we could examine adding an 'r' parameter to persist the current range.
