### ISSUE TITLE
Option to remove Index in the Config

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#24]
There needs to be an option in the config for the removal of the Index tab in the treeViewLeftPanel

**Comment by edsilv** [comment]
I will raise this for comment with the BL.

**Comment by edsilv** [comment]
https://github.com/UniversalViewer/universalviewer/commit/000ed22332e3c44de9071b526629b5e66a392dcd

in the config editor, use treeviewLeftPanelModule's `treeEnabled` and `thumbsEnabled` settings.
