### ISSUE TITLE
Order of image downloads is configurable

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#247]
You might not want "current view" to be the first (and therefore default) option in the download menu. The order could be configurable. Maybe use "more info" config ordering as model.

**Comment by jenlindner** [comment]
Hi, I'm wondering about adding some new configurations to the download dialog box - links to some pre-determined sizes. Is this possible now? Or if not, is anyone else interested in adding new download configurations, or done any work to allow for them?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by tomcrane** [comment]
I'm not really bothered about this one and may well not be relevant 7.5 years of development later.
