### ISSUE TITLE
Avoid populating hash params until state actually changes from default?

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#248]
@demiankatz says:

Should hash parameters only be applied when default state is changed, for ease of URL sharing? Should entire hash feature be made configurable for those who don’t want/need it? (Problem: sharing URLs can be difficult/unwieldy when hash is present, if the very specific scope of the hashed URL is not what is desired).

Don't apply hash params until _user action_ has caused them to change, rather than initialisation of the UV.

**Comment by edsilv** [comment]
Developers have complete control over this is UV 3.0 using external 'data providers'. e.g.

```
uv.on('canvasIndexChanged', function(index) {
    dataProvider.set('cv', index);
});
```

The UV will have a bundled URLDataProvider that handles hash param get/set operations, but it's entirely up to the developer if they want to use this in their page. State could be persisted any way they choose.

cc @julsraemy
