### ISSUE TITLE
Config editor in examples - load from URL

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#249]
This would be a fantastically useful feature for @jennpb and others who maintain a fairly complex config of their own.

The examples repo config editor should allow the user to load an existing config from a URL. It then merges this with default config to generate the editable config user interface. The user can edit and copy the JSON back to wherever they keep their config.

The downside is that the user would take away and save the full "expanded" config, not just the overidden bits. However this is not as much of a problem as it seems and solves another issue - how does the user know when new config is added that needs attention? If the whole config is exposed, it's all there to see.

Extra bonus points - "Save" button. The config editor can use XmlHttpRequest to PUT the new config back to the same URL, thereby updating it, if the URL supports it (it can determine this with an OPTIONS request).

**Comment by edsilv** [comment]
Sounds good. I'd like to use IPFS to save the config as this does not tie
the UV to any particular data store. Will talk to the community to find out
the best path forward.

**Comment by tomcrane** [comment]
The browser has everything it needs right now to PUT the config to any URL that accepts it, and can send credentials so that some random person can't update your config.

The most important thing is being able to load the config from a URL, the save is later.

**Comment by edsilv** [comment]
This seems to me like a feature that's a "nice to have" and a good
opportunity to start as one means to go on and figure out the problems
around credentials etc as a learning exercise. There is also a need to
store the state of the UV in a shareable manner. We definitely don't want
that to be reliant on a central server in my opinion. It would be an IPFS
hash representing a json object that could be stored in any location,
"seeded" by the user who initially created it.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closing as the config editor no longer exists in the form described here. If we need a similar feature in future, this request will likely need to be respecified differently.
