### ISSUE TITLE
Expand thumbnails button

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#25]
Is it possible to have a hint on hover for the << and >> buttons in the treeViewLeftPanel? So that they say something like expand thumbnails to fill screen?

**Comment by edsilv** [comment]
This has been mentioned by the BL as well. I will raise it again with them.

**Comment by edsilv** [comment]
fixed by https://github.com/UniversalViewer/universalviewer/commit/796984f9e7a5d424f0b2d7db5f616ac256d282e7
