### ISSUE TITLE
Local javascripts

### ISSUE THREAD

**Issue by Daniel-KM** [UniversalViewer/universalviewer#250]
Hi,

Is it possible to use the library without external libraries (google fonts, jquery...)? They may be loaded from the original site aside the other js, not from a third party. This is important for privacy and practical reasons (possibility to use the universal viewer without connection, etc.).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by edsilv** [comment]
Hi,

I think the only external asset is jquery, which is loaded by embed.js when the page containing the UV doesn't already have a suitable version:

https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/embed.js#L160

If you include jquery in your page, this shouldn't be getting loaded. The fonts should all be sans-serif - not aware of any use of Google fonts?

**Comment by edsilv** [comment]
Just to note... Several libs are now being loaded from a CDN:

https://github.com/UniversalViewer/universalviewer/blob/dev/src/app.html#L6

This was a consequence of loading jquery in app.html to enable Google Analytics for embedded scenarios (events.js uses jquery to capture the UV events).

Once I'd done that, it seemed to make sense to load as many as possible from a CDN. This has reduced the size of app.js significantly, it also lessens the dependency on bower, which I'd ultimately like to remove from the project in favour of NPM.

If you were interested in loading these files from the original site, it should be straight-forward to concatenate them into a single file and replace the scripts with a single reference to that.
