### ISSUE TITLE
Configuration for just one language

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#254]
The Wellcome Library does not want to offer any language choice in the settings.

If you omit language configuration altogether, the UV defaults to English and Welsh:

![locales-gbcy](https://cloud.githubusercontent.com/assets/1443575/13599268/e803f592-e519-11e5-8bf3-9e9e36d98ddc.png)

If you override configuration for just one locale:

```
  "localisation": {
    "label": "English (GB)",
    "locales": [
      {
        "name": "en-GB",
        "label": "English (GB)"
      }
    ]
  },
```

...then you get a repeated locale in the settings dialogue:

![locales-gbgb](https://cloud.githubusercontent.com/assets/1443575/13599273/ed1691f2-e519-11e5-8f78-4091d6697752.png)

With only one locale configured, the settings shouldn't display the Locale user interface at all.

**Comment by LlGC-szw** [comment]
That sounds like a very sensible option. Thanks Tom.

**Comment by tomcrane** [comment]
The Wellcome Library has nothing against the beautiful Welsh language of course!

**Comment by LlGC-szw** [comment]
:D

**Comment by edsilv** [comment]
Setting `data-locale="en-GB:English"` on the embedding div, and `limitLocales: true` in the root config options will have the desired effect. I don't think it's necessarily a good idea to encourage altering elements of the config that are not accessible in the config editor.
