### ISSUE TITLE
support for attribute "within" to navigate upwards

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#258]
Now one can set the data-uri to a collection, and a whole collection tree loads in the UV.
But when you reference the manifest-uri (that is contained by a collection), the UV
does not seem to notice the containing collection in the tab "index". 

Or is this not supported yet? Not sure whether you should support multiple "within" or not.

**Comment by tomcrane** [comment]
This isn't supported yet, although it would be a nice feature. You'd have to be careful though, to avoid walking all the way up the tree to a collection's ultimate ancestor (which could be iiif-universe). This is where the "multi-part" viewingHint can be used:

* If the UV loads a manifest that has a "within" property, it should dereference the URI. If the resource is a iiif:Collection with a "multi-part" viewingHint, then load that collection. Repeat up the tree but only while the viewingHint is "multi-part".

In this way, an individual manifest that is a member of a collection that models the work (an issue of a periodical, a volume of a multi-volume work) will be rendered with its natural collection navigation intact.

**Comment by nicolasfranck** [comment]
Thanks for your quick reply!

I noticed the way UV loads the whole collection structure all at once, when you pass a collection uri. But should one do that? Walking down tree can be as long as walking up ;-)

Shouldn't be lazy? I.e. walk through a directory structure, where the subdirectories are not loaded, when not needed? And only show the current open "directory", with links to up and down.
Of course, in that case, the url in the browser should change to mark a change in environment.

I'm more worried about manifests that are part of multiple collections. Then one should place 
multiple "up-links", which makes all the more complicated ;-).

Complicated issue ;-)

**Comment by edsilv** [comment]
see #329
