### ISSUE TITLE
Use the collection label rather than the manifest label for the value of navigation tree nodes

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#260]
http://wellcomelibrary.org/iiif/collection/b18031511

This collection labels its child manifests "Volume 1", "Volume 2" etc:

```
"manifests": [
    {
      "@id": "http://wellcomelibrary.org/iiif/b18031511-0/manifest",
      "@type": "sc:Manifest",
      "label": "Volume 1"
    },
    {
      "@id": "http://wellcomelibrary.org/iiif/b18031511-1/manifest",
      "@type": "sc:Manifest",
      "label": "Volume 2"
    },
 ...
```

When you dereference the manifest, its label is something else:

```
{
  "@context": "http://iiif.io/api/presentation/2/context.json",
  "@id": "http://wellcomelibrary.org/iiif/b18031511-0/manifest",
  "@type": "sc:Manifest",
  "label": "The biological basis of medicine",
...
```

This isn't evil - the publisher has made one assertion of the manifest's label in the context of the collection graph and another in the manifest graph. 

Currently the UV overrides the node label in the tree when it loads the manifest.

The UV should use the label that the Collection uses for the manifest ("Volume 1") in the tree, I think, as that is a "navigation" context, but use the label used in the manifest itself as the main heading (in the centre panel). This leaves it up to publishers to use different labels on manifests referenced from collections if they want to:

* If publishers want the centre panel title to be the same as the tree node, then they can make the labels the same in their manifests and collections.
* If publishers want to have them different to produce a logically pleasing navigation, they can do that too.

So just change the behaviour rather than make it configurable, it's then a content issue.

**Comment by jennpb** [comment]
That makes sense to me! That means that - in the example posted above - the title 'The Biological Basis of Medicine' remains the header in the centre panel, while allowing the user to navigate through the volumes in the Index.
