### ISSUE TITLE
Download dialogue: on which sizes are the links based?

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#263]
The UV shows a tree links to download jpeg images:
- current view
- whole image (highres)
- whole image (lowres)

Is there a way to customize this behaviour and/or change this?
E.g:

```
http://shared.ugent.be/viewer/archive.ugent.be:EBFE8CFC-AC6F-11E1-81A7-AD7FAAF23FF7
```

reports in its manifest a resolution of 15261x54519, but the actual maximum resolution one can
fetch from the IIPServer is confined by MAX_CVT (which is 5000). This is reported in the attributes "sizes" of info.json:

```
http://shared.ugent.be/IIIF/images/archive.ugent.be%3AEBFE8CFC-AC6F-11E1-81A7-AD7FAAF23FF7%3ADS.2/info.json
```

Should the UV use this attributes, or are this just interpreted as "fast-retrievable-resolutions"?

I'm looking for a way to prevent users from overloading the IIPServer with heavy request like this.

**Comment by tomcrane** [comment]
By coincidence: https://github.com/UniversalViewer/universalviewer/issues/258

IIIF Image API 2.1 introduces the notion of maxWidth (and for specialist cases, maxHeight and maxArea). You would assert a maxWidth value the same as IIPImage's MAX_CVT setting. You can also configure your local viewer with an absolute maxValue to use - but as you can see from that comment, the UV needs to use the image service to decide what the hi-res image is.

**Comment by nicolasfranck** [comment]
I see, but does your solution already work  in the UV? It's part of a draft of the new api, and
is not implemented yet by the IIPServer..

The configuration option maxImageWidth doesn't have any effect, because it uses info.json 
directly, which does not state any maximum?

**Comment by nicolasfranck** [comment]
cf. https://github.com/ruven/iipsrv/issues/59

I spoke to the creator the iipsrv, and he agrees to add the maxWidth property if a MAX_CVT is defined, lower than the actual width of the image. Although no clients for the moment support them?
