### ISSUE TITLE
Need mechanism for label-based download stats

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#269]
Currently, the uv.onDownload event receives the ID of the download option chosen by the user.

Previously, the download ID was based on the label of the rendering being downloaded. However, this caused problems due to duplicate labels (see #266 and #268). However, the solution to this problem causes opaque IDs to be passed to the uv.onDownload event.

We should not be relying on IDs to convey specific information; instead, it would probably be wiser to retrieve the text of the label associated with the download ID. Perhaps uv.onDownload should receive an object containing both the ID of the clicked download option and the label associated with that control. However, changing this may have implications for existing Google Analytics configurations (backward compatibility break) and must be handled accordingly.

**Comment by tomcrane** [comment]
UV on Wellcome is not currently tracking uv.onDownload - it's tracking:

seadragonExtension.onDownloadWholeImageLowRes
seadragonExtension.onDownloadEntireDocumentAsPDF

...and similarly named events.

It would be straightforward to have a more generic download event object that the tracking code can inspect and fire the appropriate tracking event.
