### ISSUE TITLE
Rotate nav window?

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#271]
When rotating a scroll, should the nav window also be rotated?

**Comment by nicolasfranck** [comment]
I should think so. Great idea!

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive
