### ISSUE TITLE
Nav window styling

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#272]
Can we make the nav window look like a whole "slice" of the available area, rather than a box?

**Comment by mialondon** [comment]
@edsilv can you elaborate on this?

**Comment by edsilv** [comment]
I think this is referencing scrolls like this BL one:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fsanddragon.bl.uk%2FIIIFMetadataService%2For_1459.json

If the manifest's viewingHint is 'continuous' and the viewingDirection is 'left-to-right', the navigation window stretches to fill the viewport horizontally. If it's 'top-to-bottom', it stretches vertically.

![screengrab1](https://cloud.githubusercontent.com/assets/1334393/16337148/1d40d6f8-3a0b-11e6-9841-497a33eca13a.jpg)

You can see there's a white box showing your current view in the navigation window.

I think this issue is about making that box larger in this context, like so:

![screengrab2](https://cloud.githubusercontent.com/assets/1334393/16337172/36b9bd2a-3a0b-11e6-98da-aa4937ebb243.jpg)

Making it easier to click on and drag about.

**Comment by edsilv** [comment]
usually the tiles in the navigation window would not be partially loaded and would be the full width of the window. the BL server seems to be slow at the moment.

**Comment by mialondon** [comment]
Thanks @edsilv - in that case, a slice rather than a box seems a sensible improvement.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive
