### ISSUE TITLE
Disappearing chrome in Safari

### ISSUE THREAD

**Issue by jennpb** [UniversalViewer/universalviewer#273]
Here's something I've experienced in Safari. I'd be interested to know whether anyone else has seen this problem in other browsers...

When I have an item open in a tab and then navigate away to another tab, on my return the chrome has disappeared - the panels, parts of the top nav bar. It generally takes less than 5 minutes for this to happen.

![disappearing_safari](https://cloud.githubusercontent.com/assets/1446139/13854771/f7ba5132-ec64-11e5-946d-97f059e72476.png)

**Comment by tomcrane** [comment]
Resizing (i.e., re-flowing the DOM) brings the contents back.The content doesn't disappear immediately in the non-visible tab but only on returning after a couple of minutes or so. Maybe this is a memory optimisation feature - Safari is unloading something, or not maintaining a screen buffer, and then failing to realise that it needs to redraw the controls when focus returns.

**Comment by edsilv** [comment]
Fixed by https://github.com/UniversalViewer/universalviewer/commit/1e528772441ece39f6d799edd6979c40e123a025
