### ISSUE TITLE
titels in "index" not clickable anymore when loading collection

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#274]
The production website

http://universalviewer.io/examples

contains examples of collections that work.
The titles in the tab "index" are clickable.

But this behaviour seems to be broken in the master branch?

Try rebuild:
* grunt serve
* select a "collection" from the list
* go to tab "index"
* titles are not clickable, nor load a manifest

**Comment by edsilv** [comment]
The dev branch is where all the latest work is - also FYI it's encouraged to issue pull requests to dev, not master. I've merged dev into master and this seems to have fixed the issue.

**Comment by nicolasfranck** [comment]
Thanks! But now there is another strange behaviour:

     http://shared.ugent.be/IIIF/collections/jan-frans-willems works in viewer
     http://shared.ugent.be/collections/jan-frans-willems

while

     http://shared.ugent.be/IIIF/collections/rug01-002212499 does not show
     the leftPanel in the viewer http://shared.ugent.be/collections/rug01-002212499

     that collection contains 4 manifests. Inspecting the content, I see that "leftPanel" is
     not only empty, but also empty.

Is there something missing in the json files?

**Comment by nicolasfranck** [comment]
Just saw this in your code (lib/app.js):
```
BaseExtension.prototype.isLeftPanelEnabled = function () {
    if (Utils.Bools.GetBool(this.provider.config.options.leftPanelEnabled, true)) {                
        if (this.provider.isMultiCanvas()) {                   
            if (this.provider.getViewingHint().toString() !== manifesto.ViewingHint.continuous().toString()) {
                return true;
            }
        }
    }
    return false;
};
```

Looking at "isMultiCanvas" it appears that the leftPanel is only shown if the current manifest has more than one canvas. Obvious of course, but it also disables the "index" (within the leftPanel!) tab which is necessary to navigate through the collection.

So only the tab "thumbs" should be disabled, I think.
LeftPanel only none of the tabs are enabled.

**Comment by tomcrane** [comment]
I think this is the same issue as https://github.com/UniversalViewer/universalviewer/issues/206

**Comment by edsilv** [comment]
This should be fixed now on the dev branch:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fshared.ugent.be%2FIIIF%2Fcollections%2Frug01-002212499

I've also changed the layout strategy for the thumbs panel to match that of the gallery view. It now sets all thumb heights to their median height. I think this looks a lot better and fixes a wrapping problem that was happening for collections.

**Comment by nicolasfranck** [comment]
Thanks! It works
