### ISSUE TITLE
Download size ordering

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#277]
Order download options by size (smallest to largest). Could possibly change working to "current view", "medium sized", "full size"? @mialondon @jennpb

**Comment by tomcrane** [comment]
Remember that current view could be significantly larger than the confined (low res) image - e.g., full screen on a retina display. Which means ordering by size alone might result in

whole image lo
current view
whole image hi

**Comment by jennpb** [comment]
In that case, my feeling is that we should do:

Current View
Whole Image (lo res) ---- still don't know what the best wording is! 
Whole image (full size)

**Comment by tomcrane** [comment]
@jennpb - wording is configurable so we can experiment.

for http://wellcomelibrary.org/iiif/b18035723/manifest

Whole image 2569 x 3543px (jpg)
Whole image 1000 x 1379px (jpg)

If the original was only 800px, what should happen here? UV has "1000" for confined setting
If whole image < confined, don't show confined

**Comment by mialondon** [comment]
Within the canvas/sequence/manifest grouping, download options should be ordered by size.

**Comment by mialondon** [comment]
@edsilv if the current view is the same size as the 'whole image', can you suppress the 'current view' option? Currently it causes a moment of confusion as people don't understand why there are two options that appear to be the same.

**Comment by mialondon** [comment]
@edsilv Following discussion after the usability review, the options should be:
Normal
Large

Swapping 'large' for 'high quality' as the quality might actually be less than desirable.

**Comment by mialondon** [comment]
We've currently taken out the image format option in the config file, which has helped reduce visual clutter.

**Comment by edsilv** [comment]
This has now been implemented (dev branch).
