### ISSUE TITLE
Preserve relative sizes of tileSources when rendering pages in n-up mode

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#278]
Currently OSD scales the two tileSources to have the same width in 2-up mode. Instead it should render them aligned at the top, with the gutter between them, but UV should ensure that the ratio of the widths of the images is the same as the pixel widths of the image services.

**Comment by edsilv** [comment]
have pushed a fix in v1.7.17: 

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb13266330%2Fmanifest&locale=en-GB#?c=0&m=0&s=0&cv=6&z=-0.2317%2C-0.3998%2C2.4633%2C2.1955

**Comment by tomcrane** [comment]
This makes them the same height instead of the same width - but that causes problems too, although less often:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb13266330%2Fmanifest&locale=en-GB#?c=0&m=0&s=0&cv=352&z=0%2C-0.2047%2C2%2C1.7825

I want them to maintain the same relative sizes as their pixel dimensions, like this:

http://tomcrane.github.io/scratch/osd/preserve-rel-size.html

(need to recalibrate the coordinates, but you can see what's happening)

**Comment by tomcrane** [comment]
This might also fix #201 as the annotations #xywh is proportionally correct (allowing for offsets etc)

**Comment by edsilv** [comment]
try v1.7.18:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb13266330%2Fmanifest

**Comment by tomcrane** [comment]
nailed it I think.

**Comment by edsilv** [comment]
cool, closing then.

**Comment by tomcrane** [comment]
It now normalises to height or width, but I think if it defaulted to neither as in my example above it would fix #201
