### ISSUE TITLE
Default navigation UI - thumbs, index, or dynamic?

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#279]
The UV left content panel has two tabs - Thumbnails and Index. 

Index is generated from the ranges in the manifest and represents a table of contents. If the resource loaded into the UV is a collection that models a multi-part work, like a periodical or an encyclopaedia, the Index allows the user to browse around the collection structure too (from issue to issue).

Here's the problem:

For some works, it's really important to present the TOC navigation - e.g., a periodical with a rich structure, a manuscript with detailed identification of ranges. Just seeing the first thumbnails for a newspaper doesn't really help the user much, they need access to the tree structure.

![c_and_d](https://cloud.githubusercontent.com/assets/1443575/14256328/7378fc36-fa90-11e5-8575-58bba59355ff.png)

For other works, the range information is sparse, or not very interesting or useful. At the Wellcome Library many printed books are given four simple ranges to identify front cover, back cover, title page, table of contents, but that's it. For these works, although it's useful for the user to have the ability to jump via the nav, it's not a very useful _default_ user interface and the thumbnails are easier to use.

![atoms](https://cloud.githubusercontent.com/assets/1443575/14256332/7b96063e-fa90-11e5-93a5-f6423f1bfbf1.png)

Via config we could have the thumbs as default, or the index as default - but this would result in poor UI for one of other types of content.

Proposal - optional new feature:

The left panel defaults to thumbs if the number of nodes in the nav tree is less than n (where n is configurable), otherwise it defaults to index.

In other words, the default navigation user interface (thumbs or tree) is determined by the structural complexity of the work, rather than a global setting that must apply to all works.

Wellcome would set n to 5, which means that (front/back/title/toc) printed books get thumbnails (useful and interesting), whereas complex manuscripts and periodicals get a tree structure (useful and interesting).

This breaks a UI rule about consistency - but I'm willing to argue the case for it. We have to default to thumbs anyway if a manifest has no structure at all. It means that if a user suddenly encounters a nav structure after browsing around for a while seeing thumbs, it's because there's something useful in that structure that the UV is drawing attention to.

The nav structure is still available, the tabs are still visible and functioning.

Occasionally there will be a manuscript with only four identified ranges that defaults to thumbs - but the vast majority of works get default UI for navigation appropriate to their structure, which is not the case with either choice at present.

**Comment by tomcrane** [comment]
Ed - short term fix to do first - default to Index tab via configuration.

**Comment by edsilv** [comment]
I've added two config options to v0.7.19: `defaultToTreeEnabled` (default `false`) and `defaultToTreeIfGreaterThan` (default `0`)

If `defaultToTreeEnabled` is set to `true`, the tree will always show if there's any content in it at all, as `defaultToTreeIfGreaterThan` is 0.

`defaultToTreeIfGreaterThan` can be set to whatever the deploying institution thinks is appropriate.
