### ISSUE TITLE
Config to disable 2-up option completely

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#283]
Wellcome have asked for this feature, for A/B testing. Currently you can set pagingEnabled=false, which prevents the UV from automatically presenting a "paged" viewingHint sequence in 2-up mode, but the user can still switch to 2-up manually.

The additional config option (I don't think you can do this right now) would remove all trace of 2-up from the user interface (no button in top bar or option on settings dialogue).

@jennpb have I got this right?

**Comment by edsilv** [comment]
![screengrab](https://cloud.githubusercontent.com/assets/1334393/15392668/9519cfe8-1dc0-11e6-9856-bbe83ab190da.jpg)
