### ISSUE TITLE
Wrong collection chosen on navigation in collection

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#286]
http://wellcomelibrary.org/item/b19974760

- Open Index navigation
- Open 6 Jan 1940 issue
-  - correct issue opens - "Beef Juice" on the cover
- Open Index nav again
- Navigate to 13 Jan 1940 issue

This is not the right issue - it opens 15 October 1859

**Comment by tomcrane** [comment]
Looks like it's preserving the manifest index but not the collection index

**Comment by tomcrane** [comment]
Also in date mode the selection of an issue does nothing

**Comment by jennpb** [comment]
Another issue reported:

"I’ve just gone into C+D to check some references and it’s behaving very strangely (is it just me???).  The links from volumes and dates (I’ve tried both systems) are not linking to the correct editions e.g. 28 November 1925 is bringing up 20 Feb 1926, 31 March 1923 is bringing up 7 Jan 1922 and 12 Jan 1924 is bringing up 15 Feb 1869."

**Comment by tomcrane** [comment]
Not a UV issue - stale metadata in IIIF resources.
