### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#290]
Afternoon, is the transifex file the most up-to-date version? I'd like to update some of the terms in 1.7.11 but can't find them (eg volume). Let me know and I'll get the translations done by next week. Thanks.

**Comment by edsilv** [comment]
It isn't... I'll look at updating it tomorrow

**Comment by LlGC-szw** [comment]
Thanks Ed, there's no huge rush we're still testing manifests before releasing 1.7.

**Comment by edsilv** [comment]
that's now done. here's a video guide for updating the source strings:

https://www.youtube.com/watch?v=HDjLG2ro9VI

they've altered the UI slightly since then, but it's basically the same.

**Comment by LlGC-dwj** [comment]
Hello,

Could you clarify how you want us to translate the UV? Sara has updated a few strings in Transifex, but what then is the next step? Do we need to contact you to ask for the UV strings to be updated or have you got a way that automatically updates the strings on Github? Do you want us to create a pull request? As hopefully now we've done all the translation for the time being, but we don't want to be hassling you with small changes!

Kind Regards,
Dylan

**Comment by edsilv** [comment]
Hi,

There is a document here describing the update process:

https://docs.google.com/document/d/1SJm4G6twYTquLUb5nIE6gZbpzfQcvDTBFToq6a9P_-w/edit?usp=sharing

It's not terribly well organised at the moment and needs some more time spent on it, but hopefully it should tell you everything you need to do to update the l10n files in your fork of the UV.

We're looking at replacing Transifex:

https://github.com/UniversalViewer/universalviewer/pull/172

This would be quite a lot of work, but should ultimately be a much better set up.

**Comment by LlGC-dwj** [comment]
Thanks Ed, that answers my questions.

Regards,
Dylan
