### ISSUE TITLE
Tree navigation where multiple ranges correspond to the same canvas

### ISSUE THREAD

**Issue by emmastanford** [UniversalViewer/universalviewer#294]
We've created a manifest for our First Folio with ranges corresponding to each scene of each play: http://iiif.bodleian.ox.ac.uk/iiif/manifest/390fd0e8-9eae-475d-9564-ed916ab9035c.json. There are often multiple scenes per page, and therefore multiple ranges corresponding to the same canvas. In the Universal Viewer tree, clicking on the first range for a canvas appears to automatically jump you to the final range for that canvas. You end up looking at the right image, but the wrong item in the tree is highlighted. You can see this happening if you click through the tree for The Two Gentlemen of Verona or another play with a lot of scenes in it: http://iiif.bodleian.ox.ac.uk/iiif/viewer/390fd0e8-9eae-475d-9564-ed916ab9035c. I imagine this must also be a problem for digitized newspapers, so I'm hoping a solution is out there or in the works.

With apologies if the problem has already been fixed in a recent release of the UV--we don't have a very recent version installed on our server, but the problem is replicated if I load the manifest in http://universalviewer.io/examples/.

**Comment by LlGC-szw** [comment]
This is also important to us as we will be looking at defined areas (articles, images etc) within newspapers.

**Comment by tomcrane** [comment]
This is (I think) the same as #239

**Comment by emmastanford** [comment]
Ah, yes, that does seem the same.

**Comment by edsilv** [comment]
#239 is now closed
