### ISSUE TITLE
Support for continuous viewingHint

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#295]
(supersedes #209)

> Valid on manifest, sequence and range. Each canvas is a partial view and an appropriate rendering might display either the canvases individually, or all of the canvases virtually stitched together in the display (OSD Collection). Examples when this would be appropriate include long scrolls, rolls, or objects designed to be displayed adjacent to each other. If this viewingHint is present, then the resource must also have a viewingDirection which will determine the arrangement of the canvases.

Current implementation for BL (in progress):

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fsanddragon.bl.uk%2FIIIFMetadataService%2For_1459.json

**Comment by edsilv** [comment]
I think this is done now? https://librarylabs.ed.ac.uk/iiif/uv/?manifest=https://librarylabs.ed.ac.uk/iiif/manifest/mahabharataFinal.json
