### ISSUE TITLE
Support top viewingHint

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#296]
Supersedes #209 

Only valid on a range. 

> A range which has this viewingHint is the top-most node in a hierarchy of ranges that represents a structure to be rendered by the client to assist in navigation. For example, a table of contents within a paged object, major sections of a 3d object, the textual areas within a single scroll, and so forth. Other ranges that are descendants of the “top” range are the entries to be rendered in the navigation structure. **There may be multiple ranges marked with this hint.** If so, the client should display a choice of multiple structures to navigate through. 

We don't have any examples of this so need to make/obtain some.

This viewingHint would allow the viewer to present different navigation tree structures for the same work, if the manifest offers multiple ranges marked as "top" - e.g., to choose between two different interpretations of the structure of a work - toggle between two different navigation trees.

**Comment by tomcrane** [comment]
Look at as part of https://github.com/UniversalViewer/universalviewer/issues/319

**Comment by edsilv** [comment]
Use a drop down to switch between trees. Use range labels in drop down.

**Comment by escowles** [comment]
I've mocked up an example with two "top" Ranges: https://gist.githubusercontent.com/escowles/8ba9e9d3d9780993b4fd03fbe30b5008/raw/e600ac865187933a4db04e0af87773c850288bd4/f7623d04x.json
