### ISSUE TITLE
Vertical viewingDirections - top-to-bottom and bottom-to-top

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#297]
The UV already supports top-to-bottom:

http://universalviewer.io/examples/?manifest=http://tomcrane.github.io/scratch/manifests/top-to-bottom.json

What should the < and > nav arrows do? Should they be moved to the bottom and top of the viewport? Currently they don't seem to do anything.

The UV support for bottom-to-top is (I think) not right:

http://universalviewer.io/examples/?manifest=http://tomcrane.github.io/scratch/manifests/bottom-to-top.json

The thumbnails should look like this:

4
3
2
1

... and 1 should be the highlighted thumbnail and starting canvas, with focus on initialisation (UV scrolls to "bottom" of thumb panel).

**Comment by LlGC-szw** [comment]
If the viewing hints says:
- top-bottom then the thumbnails would be 1->4 with 1 highlighted at the top
- bottom-top then the thumbnails would be 4->1 with 1 highlighted at the bottom
the arrows would be at the top and bottom of the image and scroll up and down

- paged / L-R / R-L  the arrows would be at the left and right of the image and scroll left/right

Is this correct or will for t-b/b-t the arrows remain left and right on the image?

**Comment by edsilv** [comment]
should be fine to move the arrows into up/down positions as opposed to left/right

**Comment by LlGC-szw** [comment]
That would make the most sense to the user I think. We're trying to also find some examples in our collections to test on...

**Comment by edsilv** [comment]
example: http://universalviewer.io/examples/?manifest=http%3A%2F%2Ftomcrane.github.io%2Fscratch%2Fmanifests%2Fbottom-to-top.json
