### ISSUE TITLE
View all metadata option (not just locale-specific)

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#298]
The UV filters metadata (JSON-LD value objects with language) according to the locale preference, where possible. However, some users may wish to see all the metadata, even if there are two or more possible values. E.g., I want to see the English and Welsh versions of the metadata together.

I'm not sure what this means UI-wise:
- some indication that the current metadata is not all there is, that it is being filtered
- an option to un-filter it, that only appears when it is being filtered
- when un-filtered, the language label could be incorporated into the display

**Comment by tomcrane** [comment]
@LlGC-szw - you might have a view on this too

**Comment by LlGC-szw** [comment]
Thanks Tom, I'll have a chat with a few of my colleagues and see if there's a particular approach that would make the most sense.

**Comment by LlGC-szw** [comment]
We had a discussion about this issue this morning and it seems we wouldn't have any need to show metadata in both languages together. The user would change the interface language to Welsh to see the same metadata that was displayed in English on the English interface, in Welsh. We really tried to think of a use case where the user would want to see both languages together but we don't have one I'm afraid. 

I think this would apply more to institutions who don't have localised interfaces but do have localised metadata. Does this make sense?

**Comment by jpstroop** [comment]
Our use case at Princeton is that we often have CJK, Cyrillic, or Arabic script in our metadata that is also transliterated into Roman characters ([example](https://pulsearch.princeton.edu/catalog/5410918)). Taking the Arabic case, in an IIIF metadata list these would be coded with `ara` as the `@language` for for the native script and `ara-Latn` for the Romanized version. e.g.:
```javascript
"metadata" [
  { 
    "label" : "Title",
    "value": [ {
        @value: "كتاب شرح كافية المسمى بنجم سعيدي",
        @language: "ara"
      }, {
        @value: "Kitab-i Şerh-i Kāfiyah al-musammá bi-Najm Saʻīdī.",
        @language: "ara-Latn"
      }
    ]
  },
   // ...
]
```

We'd like to be able to always display both. I would expect that this is something we configure in our deployment of UV, and not something that a user can toggle.

Note that this applies to anywhere that an `@language` can appear as well (labels are the other major case, I guess), and not just in the metadata pool.

**Comment by edsilv** [comment]
call the config option `showAllMetadata`

**Comment by edsilv** [comment]
reference: http://iiif.io/api/presentation/2.1/#language-of-property-values
