### ISSUE TITLE
Right-to-left metadata

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#299]
Where metadata is in a language that should be read right-to-left, the display of metadata should be right-to-left.

The settings -> Locale choice could make CSS changes at the theme level, but this needs to work at the individual metadata item level too, for a mixture of metadata in different languages.

Here's a manifest I have modified to include lots of test case metadata:

http://tomcrane.github.io/scratch/manifests/vdc_100000004987.0x000001.json

This is a tricky one. Does it mean the UV needs to know that "@language": "ar" requires rtl styling on the corresponding metadata div? Is there a standard way of mapping from ISO lang code to text-direction (e.g., a lookup table everyone uses?)

**Comment by jpstroop** [comment]
Just to note: pulibrary/plum#580

i.e., it would be great to have r-t-l work on Range and Sequence labels as well.

I shared our string sampling method for doing this (in Ruby) here: https://github.com/UniversalViewer/universalviewer/issues/298#issuecomment-216899155, and it might be nice to have that in as a fallback when there is no script data.

**Comment by jpstroop** [comment]
I guess I didn't share our string sampling method (or can't find where I did). Here it is: https://github.com/pulibrary/string_rtl/blob/master/lib/string_rtl/string_patch.rb

**Comment by mialondon** [comment]
@tomcrane are there any questions it'd be useful to ask curators here, or is it a purely technical question?

**Comment by tpendragon** [comment]
> Does it mean the UV needs to know that "@language": "ar" requires rtl styling on the corresponding metadata div?

I'd be happy if it was even just a configuration thing - these language codes mean render in RTL.

**Comment by jpstroop** [comment]
Agreed on 7/5 that config file will be the approach

**Comment by tomcrane** [comment]
...and config file means that UV applies css class and dir="rtl" attribute to label and value of metadata elements for which it has identified lang tags that appear in its rtl config list.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dir
