### ISSUE TITLE
Change auth token property 'errorDescription' to 'description' in manifesto and UV

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#301]
A very easy issue!

https://github.com/UniversalViewer/universalviewer/search?utf8=%E2%9C%93&q=ErrorDescription

This was changed a while ago in the spec. Currently Wellcome emits both versions, so that nothing breaks when you change it over:

http://wellcomelibrary.org/iiif/token

```
{
error: "missingCredentials",
errorDescription: "No user could be found in request",
description: "No user could be found in request"
}
```

Once the updated UV has been out there for a bit I'll remove the old 'errorDescription' from the token error response.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by tomcrane** [comment]
> A very easy issue!

But not worth fixing as IIIF Auth v2 should really be the only flow supported going forward.
