### ISSUE TITLE
Page scrolls to last instance of embedded uv

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#304]
Our e-editor has come across a bug when embedding the UV within our website and blog. The page jumps down to the last instance of the UV on the page. See these 2 links as examples,

https://www.llgc.org.uk/en/collections/activities/exhibitions/words-of-war/
https://www.llgc.org.uk/blog

I've tested this with the latest build (outside our CMS and Blog) and get the same thing happening. Has this happened to anybody else? Is this an option I can switch off?

Thanks,
Dylan

**Comment by LlGC-dwj** [comment]
Hi, has anyone else found this an issue?

https://www.llgc.org.uk/blog/?paged=2 shows what I mean. Is there a way to stop the UV having priority on the page?

**Comment by LlGC-szw** [comment]
Duplicate issue to https://github.com/UniversalViewer/universalviewer/issues/267

**Comment by edsilv** [comment]
closing as dupe of #267
