### ISSUE TITLE
This manifest freezes the UV

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#311]
http://oni.mith.us/lccn/sn83045396/1911-09-17/ed-1.json

For me the point at which it freezes differs from attempt to attempt. Sometimes it gets to load the thumbs, sometimes not.

**Comment by azaroth42** [comment]
For me it pretty much always loads the thumbs and then locks up. If that helps :)

**Comment by edsu** [comment]
If oni.mith.us is somehow contributing to the problem I'd love to hear about it!

**Comment by edsilv** [comment]
That url isn't resolving.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by mialondon** [comment]
Closing as inactive (Community Call 28 September 2023)
