### ISSUE TITLE
If service doesn't have profile set, the viewer is "Unable to find TileSource"

### ISSUE THREAD

**Issue by jcoyne** [UniversalViewer/universalviewer#318]
The profile is recommended to be set, but is not required in the spec. A better error would be useful.

Fixed by adding `"profile":"http://iiif.io/api/image/2/level2.json"` in:

``` json
{"@context":"http://iiif.io/api/presentation/2/context.json","@id":"http://localhost:3001/concern/generic_works/n009w2500/manifest","@type":"sc:Manifest","label":"A title","viewingHint":"individuals","sequences":[{"@id":"http://localhost:3001/concern/generic_works/n009w2500/manifest/sequence/normal","@type":"sc:Sequence","canvases":[{"@id":"http://localhost:3001/concern/generic_works/n009w2500/manifest/canvas/rv042t299","@type":"sc:Canvas","label":"image.jpg","width":640,"height":480,"images":[{"@type":"oa:Annotation","motivation":"sc:painting","resource":{"@id":"http://localhost:3001/images/rv042t299%2Ffiles%2F6d71677a-4f80-42f1-ae58-ed1063fd79c7/full/600,/0/default.jpg","@type":"dctypes:Image","height":480,"width":640,"service":{"@context":"http://iiif.io/api/image/2/context.json","@id":"http://localhost:3001/images/rv042t299%2Ffiles%2F6d71677a-4f80-42f1-ae58-ed1063fd79c7/info.json","profile":"http://iiif.io/api/image/2/level2.json"}},"on":"http://localhost:3001/concern/generic_works/n009w2500/manifest/canvas/rv042t299"}]}]}]}
```

**Comment by edsilv** [comment]
relate to #317. I think this isn't urgent as OSD provides an error. @tomcrane - as resident IIIF editor, what is your opinion on this?

**Comment by tomcrane** [comment]
@jcoyne 

 Regarding the profile:

> If a IIIF Image API service is available for the image, then a link to the service’s base URI SHOULD be included. [...] A reference to the Image API context document MUST be included and the conformance level profile of the service SHOULD be included. Additional fields from the Image Information document may be included in this JSON object to avoid requiring it to be downloaded separately. [1]

If the profile for a service is not provided in the manifest, then the UV would need to dereference the service to find out what it is. The profile is REQUIRED in the image service API itself (i.e., in the info.json), so the UV will eventually find out what it is. So while not a MUST, including the profile in the manifest is a very strong SHOULD - it might be an image resource that doesn't have an Image API service but does have a different service (geoJson maybe, or anything) and it is very helpful to tell the client this up front without lots of avoidable following of links.

Summary - if no profile, UV should follow the @id to find out what the service is. But manifest publishers should try to avoid clients doing that by providing the info in the manifest up front.

@edsilv - both #317 and #318 would be fixed/helped by #78. An image resource is not required to have an image service. If the UV is unable to determine the profile for a service on an image resource, it can still display the image resource. 

[1] http://iiif.io/api/presentation/2.1/#image-resources

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by tomcrane** [comment]
Has this been superseded? I suspect this now works OK. I think the UV should only de-reference image services when showing the image in full (or in 2-up) and not generally for thumbnails; it encourages publishers who want to use the UV to put the information in their manifests that helps the UV generate a faster (and therefore better) user experience.
