### ISSUE TITLE
Create external tree control

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#319]
The current left-hand tree control should be a standalone component so that it can be used to navigate through collections, manifests and range structures in other user interfaces besides the UV.

**Comment by jennpb** [comment]
Would this mean that we could potentially divorce the navigation tree/structural elements from the thumbnails panel if we wanted to modify the UI based on user feedback?

**Comment by tomcrane** [comment]
Good question. If the Tree Control is a separate module, it needs to talk to an interface that allows it to control what's currently visible in the centre panel. Both the thumbnail view and the tree view are selection devices - either of a range or of an individual canvas. The end result is that one or more canvases are rendered in the centre panel. 

In a modular viewer, as long as it implemented all its required interfaces you could drop a different component into that "navigation" slot.

@edsilv This issue is about the Tree Control but is it actually about contentLeftPanel? Would the tree control within contentLeftPanel be the separate module, or all of contentLeftPanel, or all three are separate modules? e.g.,

```
[UV]
    [contentLeftPanel control]
        [thumbs control]
        [tree control]
```

Would you be able to swap just the tree out? And / or the entire contentLeftPanel? I think in @jennpb's scenario it would be a new navigation device in the contentLeftPanel slot.

**Comment by edsilv** [comment]
The idea is to make the tree view a separate control (like openseadragon or virtex). It should expose its own interface that is completely independent of the UV, as should the thumbs and metadata controls within their respective panels. @demiankatz's idea in NYC was to create an entirely new control modeled on a files/folders interface, where collections are folders and manifests are files. This might be more suitable for some scenarios where a tree view isn't appropriate, such as when there are many deeply nested collections, and you don't want to have to reassemble the tree, rather, open a folder and provide an 'up level' icon to go to the parent folder.

Perhaps there could be some kind of configurable rule or set of rules that replaces these controls dynamically based on the content. Similar to defaultToTreeIfGreaterThan.

**Comment by demiankatz** [comment]
I think there may be two separate issues wrapped up in here:

1.) Create a more agnostic version of the left panel that can be fed a tree and trigger arbitrary loading of content into the main panel. This would be basically similar to what we currently have, but less coupled with OpenSeadragon functionality. In some sense, the work I did on the resourcesLeftPanel (as opposed to contentLeftPanel) is a step in this direction, but it obviously needs to go a lot further. I'd love to see a generic left panel that can have different generic functionality composed into it as separate tabs, for example.

2.) Create a new center-panel view that replaces the OpenSeadragon view with a "files and folders" sort of metaphor that can be used to launch other manifests. The idea here is that if you load a collection manifest into the UV, you might actually want to view it as a collection (as opposed to the current behavior of "find the first available manifest and display that, while relegating the actual collection information to a hidden sidebar"). I think it would be nice to be able to treat collections as first-class citizens, at least optionally.

Please let me know if I can be of any assistance in advancing either of these things. As always, time is at a bit of a premium, but I'm happy to help whenever I'm able!

**Comment by tomcrane** [comment]
1) is what I was getting at. contentLeftPanel is a device for choosing what gets loaded into the center panel, and could have many different UI possibilities. Currently (and this may not be what happens internally, I'm just thinking about logical structure) it comprises two sub controls (thumbs and tree) that can both be use to make the selection. Thumbs shows the current manifest thumbs only.

I like 2) as well - the center panel can be a collection renderer. That implies a degree of coordination between the UV and the contentLeftPanel - at what point should a collection be rendered in the centerpanel rather than explored in the tree? 

This is what the "multi-part" viewing hint is for. 

So http://wellcomelibrary.org/item/b18031511 renders a collection, http://wellcomelibrary.org/iiif/collection/b18031511 - it has the viewingHint "multi-part" which hints to a viewer that it might want to present the work as a logical navigable unit, e.g., in a tree.

> **multi-part** Valid only for collections. Collections with this hint consist of multiple manifests that each form part of a logical whole. Clients might render the collection as a table of contents, rather than with thumbnails. Examples include multi-volume books or a set of journal issues or other serials.

If we have a collection called "my bookshelf" with sub collections "westerns", "sci-fi", "fluffy romance fiction with unicorns", and within each sub collection more members - these would NOT be multi-part collections, so the UV could use the collection browsing (probably with thumbnails) center panel Demian suggests in 2).

**Comment by edsilv** [comment]
Sounds good! I think step one to making the left panel generic is extracting the tree and thumbs controls. I could then build upon Demian's work on the ResourceLeftPanel to experiment with ways to 'inject' these controls in a generic way, creating accompanying tabs.

**Comment by demiankatz** [comment]
Sounds great! I'm happy to review / discuss architecture if that's helpful at any point. You can always find me on Slack.

**Comment by tomcrane** [comment]
(by the way, that wasn't really what I have on my bookshelf). Effectively the UV currently renders all collections as if they were "multi-part" - single conceptual works with a TOC. It should use the hint to distinguish between these and more "browsable" loose collections.

**Comment by edsilv** [comment]
Closing this as iiif-tree-component has been integrated as part of the 'manifold' port (now merged with dev). The title of this issue is 'Create External Tree Control', and that has been done. I'm not sure yet how to allow dynamic controls based on some config... I'm thinking that isn't actually necessary now given that we understand that a new component is needed for non-multi-part collections. If we can avoid more config I think we should. I will create an issue for the new control.
