### ISSUE TITLE
login service for info.json not called when called from another domain

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#321]
I added a login service to my info.json, so the UV would call it.
This only seems to work when served from the same domain:

viewer:
http://shared.ugent.be/IIIF/viewer/archive.ugent.be%3A00052E74-0C00-11E6-AB3D-C921F264C48D

manifest:
http://shared.ugent.be/IIIF/manifests/archive.ugent.be%3A00052E74-0C00-11E6-AB3D-C921F264C48D

The cross-origin headers are added to the response.

But when the above manifest is actually called from another domain:

http://universalviewer.io/examples/?manifest=http://shared.ugent.be/IIIF/manifests/archive.ugent.be%3A00052E74-0C00-11E6-AB3D-C921F264C48D

It only calls the token service after a 401, and skips the login service, which obviously fails.

What am I doing wrong?

Thanks in advance

P.S. the "service" is only added in the info.json, not in the manifest:
http://shared.ugent.be/IIIF/images-ugent/archive.ugent.be%3A00052E74-0C00-11E6-AB3D-C921F264C48D%3ADS.0_1/info.json

**Comment by nicolasfranck** [comment]
Note: when I access the login service myself in separate tab, authenticate, and then reload the viewer, then everything works fine. For the call to the token service succeeds in that case.

**Comment by edsilv** [comment]
Just stepping through the code, at this point:

https://github.com/UniversalViewer/universalviewer/blob/dev/src/modules/uv-shared-module/BaseExtension.ts#L963

this is your tokenUri:

http://shared.ugent.be/IIIF/token?messageId=http://shared.ugent.be/IIIF/token|1464279136050

here is the equivalent tokenUri for a working wellcome manifest:

https://wellcomelibrary.org/iiif/tokencas?messageId=https://wellcomelibrary.org/iiif/tokencas|1464279329857

If you view source on both you can see the difference. It looks like you need to send the correct error message to the UV.

**Comment by tomcrane** [comment]
@edsilv - see https://github.com/UniversalViewer/universalviewer/issues/301

Current Wellcome one has both errorDescription and description

**Comment by tomcrane** [comment]
I appreciate it's rather hard to implement the auth API right now because the published spec is out of date. It is a draft/beta spec, but still needs updating soon to introduce postMessage. I think I need to do this.

**Comment by nicolasfranck** [comment]
auch, I see now. So the token service needs to return a JSON response, like described here:
```
http://iiif.io/api/auth/0.9/index.html#error-conditions
```

I thought this was the response for the client identity service ;-)

Thanks!

**Comment by nicolasfranck** [comment]
Ok, I got it working. But it seems that the UV uses a different pattern for retrieving tokens from a remote server than from the same origin.

same origin: 
```
http://shared.ugent.be/IIIF/viewer/archive.ugent.be:0000563A-0BCC-11E6-9A4C-1A41F264C48D#?c=0&m=0&s=0&cv=0
```
which uses the "old" callback method

different origin:
```
http://universalviewer.io/examples/?manifest=http%3A%2F%2Fshared.ugent.be%2FIIIF%2Fmanifests%2Farchive.ugent.be%3A0000563A-0BCC-11E6-9A4C-1A41F264C48D
```
which uses the newer postMessage method
