### ISSUE TITLE
Support standard zoom/scroll gestures

### ISSUE THREAD

**Issue by adunning** [UniversalViewer/universalviewer#325]
Usability would be greatly improved by handling standard scrolling/zooming gestures in the browser. It's very difficult to get around a picture when UV interprets the standard scrolling gesture as zooming (at least on a Mac).

Documentation for doing this under Safari is at https://developer.apple.com/library/safari/documentation/InternetWeb/Conceptual/SafariVisualEffectsProgGuide/InteractiveControl/InteractiveControl.html.

**Comment by mialondon** [comment]
@adunning thanks for your comment! 

To put another perspective on it, in the usability tests we've done so far, people have liked that they can zoom with the mouse button. This might be partly because currently the zoom controls disappear from the screen quite quickly, or because they've learnt that behaviour from other sites. I'll note it as a point to look out for in other usability tests. cc @jennpb

**Comment by adunning** [comment]
Everything works just fine with a mouse, and I wouldn't suggest changing anything there: it's specifically with a trackpad or tablet that these gestures are needed. The two shouldn't conflict, as they're only applied when supported by the browser.

**Comment by edsilv** [comment]
The UV uses OpenSeadragon to provide zoomable images: http://openseadragon.github.io/

There is a discussion about enabling scroll gestures here: 

https://github.com/openseadragon/openseadragon/issues/584

I think it would be better to constrain this to an OSD-specific problem. If this proves to be a serious problem I can get in touch with Ian about overriding OSD's built-in gesture handlers.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
As this is a reference to an OpenSeadragon issue that still seems to be unresolved, I'm closing this for now. If it is sorted out on the OSD side, we'll get the fixes in a future upgrade.
