### ISSUE TITLE
BL UV - Titles are truncated after ':' and '/'

### ISSUE THREAD

**Issue by psooben** [UniversalViewer/universalviewer#326]
Select the following links:

http://access.bl.uk/UV/ark:/81055/vdc_100000041294.0x000002#?si=0&ci=0&z=-0.2402%2C0%2C1.4804%2C1.5563
http://access.bl.uk/UV/ark:/81055/vdc_100000041301.0x000002#?si=0&ci=32&z=-0.2195%2C0%2C1.4388%2C1.5125

--> There is no text after the '/' in the titles

(Text in Explore is displayed as "Vom Balkan nach Bagdad : militärisch-politische Erinnerungen an dem Orient [1912-1916]" and "Kurze Aufklärungen über Wesen und Ziel des Pazifismus / Alfred Hermann Fried" respectively)

Link to TFS work item 6567

**Comment by edsilv** [comment]
This was a problem with the manifest content.
