### ISSUE TITLE
BL UV - Search - Highlighting does not fit over word during rotation

### ISSUE THREAD

**Issue by psooben** [UniversalViewer/universalviewer#328]
1) Select an Ark, say:
http://accessdev.ad.bl.uk/item/viewer/ark:/81055/vdc_100022541999.0x000002#?si=0&ci=0&z=0.1965%2C-0.2922%2C2.2333%2C1.475&c=0&m=0&s=0&cv=22

2) Type say, cigar in the search box.
3) rotate the image by 90 degrees

--> Highlighted does not fit over the word cigar

TFS Ref: 12274

**Comment by irv** [comment]
Actually resolvable URL:
http://access.bl.uk/item/viewer/ark:/81055/vdc_100022541999.0x000002#?si=0&ci=0&z=-0.0172%2C0%2C2.0345%2C1.3005&c=0&m=0&s=0&cv=22

**Comment by edsilv** [comment]
related to #201 @kenlt

**Comment by edsilv** [comment]
https://github.com/openseadragon/openseadragon/issues/975
