### ISSUE TITLE
Create iiif-explorer-component

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#329]
Continuing from #319 - there is a need for a new component for collections without a multi-part viewingHint. This will (likely) be located in the center panel (although placement is not fixed due to it being a generic component) and provide a file explorer style interface for navigating "loose" collections of content. The explorer component would have an 'up level' icon to use in conjunction with the `within` IIIF linking property. This would reload the UV at the parent collection. Clicking on collections/manifests would reload the UV to the selected item. 

The tree component will continue to be used for multi-part collections as they comprise a single logical grouping. The tree component loses context for nested collections #312 #313. I suggest that instead of complicating the viewer state, we keep a single collection index which is used to select sub collections in a multi-part collection. Any further nesting of collections could exclude the multi-part viewingHint and the UV would default to the new explorer component, with the ability to navigate back to the parent using the up-level button. If the sub collection is multi-part, the UV treats this as the new tree root.

 It is the responsibility of the IIIF manifest creator then to ensure the correct use of the multi-part viewingHint to deliver the best user experience.

**Comment by edsilv** [comment]
initial setup: https://github.com/edsilv/iiif-explorer-component

**Comment by glenrobson** [comment]
I've updated my collections to include multi-part viewing hint and also included members as suggested in 2.1. The top level fonds collection is available at:

http://dams.llgc.org.uk/iiif/archive/3975658/fonds.json

When clicking around the tree it refreshes the UV each time and although it seems to go back to the correct place in the index (apart from when I click District appeal papers but that might be my caching issue) it may not be necessary to refresh the UV if what your click on is a collection rather than a manifest. Just expanding the index might be enough.

**Comment by glenrobson** [comment]
Just to note I've found an Archive that has been part digitised so if you go to the following:

http://dams.llgc.org.uk/iiif/archive/3984888/fonds.json

only one of the 10 files has been digitised. At the moment if you click on one of the files that hasn't been digitised you get to a collection with no manifests or collections. Not sure this is correct but its how my code works as it doesn't know if the digital file lives at the file or item level. 

Just wanted to flag this example up to test during the above development.

**Comment by edsilv** [comment]
@glenrobson I'm getting a CORS error for http://dams.llgc.org.uk/iiif/archive/3975658/vtls005019634/series.json which is part of http://dams.llgc.org.uk/iiif/archive/3975658/fonds.json cc @LlGC-szw

**Comment by LlGC-szw** [comment]
Try https://damsssl.llgc.org.uk/iiif/2.0/archive/3975658/fonds.json for the fonds level jason. I can't seem to guess a working url for the series json.

**Comment by LlGC-szw** [comment]
oh this loads for me https://damsssl.llgc.org.uk/iiif/archive/3975658/fonds.json

**Comment by LlGC-szw** [comment]
https://damsssl.llgc.org.uk/iiif/archive/3975658/vtls005019634/series.json works

**Comment by glenrobson** [comment]
I've fixed the above. It was broken on one of our two servers so every other time you would get a server timeout. Let me know if you have any other issues.

Cheers

Glen
