### ISSUE TITLE
Separating share and embed options into separate icons and dialogue boxes

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#330]
As far as I know having share and embed in the same section was a pragmatic decision during development rather than a design decision, so hopefully it's a relatively straightforward change.

As outlined in [UV UX / British Library and Wellcome Library](https://docs.google.com/document/d/1JpR90S2BS1h8XkCCrYA9PLlyeDOPrMbLgoXFDTn0MPo/):

The challenge is to make the current ‘Share/Embed’ module easier to use and understand. 
Problems with the current option are:
- No clear distinction between the URL and the embed code; difficult to understand which piece of ‘code’ to use. 
- No visual cues indicating that this information is both for sharing a link to the page and embedding the UV item on your own site. 
- Two options are unnecessarily bundled together; there may be cases where an institution does not wish to make ‘Embed’ an option, or show the link.
- 'Embed' is the less commonly-used option but currently has the most visual prominence

**Proposed solution:**

- Unbundle Embed and Share, splitting them into separate icons and screens
- Allow institutions to choose either/both
- Use network/share icon only for ‘share’ functionality
- Use conventional `</>` icon for Embeds 

**Other notes**

- 'Share' offers the ability to copy a URL rather than pre-populating tweets, Facebook, etc. The link as presented should be copyable as a URL so that it triggers any OS-specific ways of handling a URL (e.g. share to different apps on mobile devices)
- Should the embed function limit the ratios/minimum sizes for embed options?

**Comment by mialondon** [comment]
Following discussion with Digirati/the BL of YouTube's sharing options, this is the UI for sharing from embedded videos - it's nice and simple, though the swoopy arrow mightn't be the most recognisable icon.

![uv_youtube_share0](https://cloud.githubusercontent.com/assets/380763/16375919/bccc4f58-3c55-11e6-95fa-ebc0d52ae18c.png)
![uv_youtube_share1](https://cloud.githubusercontent.com/assets/380763/16375920/bcd06c32-3c55-11e6-938b-30b97fd83d73.png)

**Comment by edsilv** [comment]
YouTube also has this UX for separating embed and share functionality:

https://www.youtube.com/watch?v=lFmlaLDn5aQ

The share URL takes precedence here over the embed code, which is in a separate tab providing clear distinction of functionality.

Embedding and sharing a link both constitute sharing the content. If an institution did not want to allow embedding the tab could simply not be available.

The swoopy arrow is the single logical sharing icon for the embedded YouTube player, the 'share' button is its equivalent for the main site. In both cases there is a single share option.

The difference between YouTube and the UV is that you also have the option to embed in the embedded player. I suggest that we follow YouTube's example of always providing a single logical share option, making the URL the primary mode of sharing with the embed code available in a tab. 

Consider the UX if all current footer options were enabled with labels:

![screengrab1](https://cloud.githubusercontent.com/assets/1334393/16377665/56b243a8-3c5f-11e6-962c-ec6a0aca0484.jpg)

I think it's wise to to avoid any further buttons finding their way into the footer by following the practices established by sites like YouTube.

**Comment by mialondon** [comment]
@edsilv what's the 'open'? icon for?

If we want to encourage people to embed images on their sites, having a visible embed icon/label would presumably increase the number of people who realise it's an option, though I also appreciate that we risk a cluttered interface. Are there many more icons that could be added, based on features in development?

@jennpb I'd like to hear your thoughts too

**Comment by mialondon** [comment]
Screenshots of the YouTube 'share' screen and two versions of the 'embed' screen so that it's clear which version is referred to:

![youtube embed advanced option](https://cloud.githubusercontent.com/assets/380763/16379033/1dec8846-3c67-11e6-8ee4-bae5eece3106.GIF)
![youtube embed simple option](https://cloud.githubusercontent.com/assets/380763/16379032/1de75952-3c67-11e6-86da-e794bff64af7.GIF)
![youtube share embed options](https://cloud.githubusercontent.com/assets/380763/16379034/1decf8c6-3c67-11e6-806d-d1afd432251e.GIF)

**Comment by edsilv** [comment]
Those images above are all part of UI shown by the share button on the main site. If you click "show more" you get an expanded range of embedding options. I think that's smart as most people will simply want the iframe code. @jennpb has asked me to look at improving the embedding options. My expectation is that we'll end up copying the YouTube iframe method. 

The open icon (disabled by default) allows you to configure a link that opens the current content in the main site. So if BL content were embedded on a blog, you could provide a single link to view that content on your site.

**Comment by edsilv** [comment]
YouTube's tab approach also allow more share options to be added without clutter, such as email.

**Comment by jennpb** [comment]
We don't have any plans for future buttons along the bottom, though I see @edsilv 's point about clutter. 

In Wellcome's environment, we do not allow embeds on items that require a clickthrough on T&Cs. See this one for example: http://wellcomelibrary.org/item/b18225457. As a result, we don't have a Share option at all.

You can see from this open item that we now have an 'Embed' option, but using the Share icon, which is also wrong: http://wellcomelibrary.org/item/b18933415. We should have retained the </> icon for Embeds.

So the idea behind having two separate buttons - from my POV - was that a site like Wellcome could offer either / or without limiting availability of all.

The YouTube share option, where the embed is a sub-selection of the Share, could work for us as long as the UV is smart enough to recognize when embed is not an option, but share is.

**Comment by edsilv** [comment]
@jennpb no problem disabling an embed tab - would use the same logic.

**Comment by mialondon** [comment]
There's a clear request from our SRO for separate embed and share icons. Variations on 'share' can go on the Share button/screen as @edsilv suggests.

**Comment by edsilv** [comment]
We could potentially add a separate configurable embed icon that opens the same dialogue on the embed tab? The benefit of discussing these ideas in the open on Github is that all opinions can be heard and therefore a better decision reached via publicly accountable discourse.

**Comment by edsilv** [comment]
I forgot about the feedback button! Ideally, every fork of the UV would have the same basic UI options. This isn't strictly necessary though. As discussed on previous community calls, organisations can develop new features and issue pull requests to the main trunk to be accepted/denied by collective decree. I think it's better to avoid specialisation of this sort however as it increases maintenance overhead.

**Comment by mialondon** [comment]
@edsilv is there an advantage to re-using different tabs on the same dialogue for two different buttons? The 'share' options are pretty simple and have a small box, while the embed box is bigger (unless we went for the extreme simplicity of the YouTube version; they also have space to expand down the page, which the UV doesn't have?).

**Comment by edsilv** [comment]
The UV's floating dialogues are limited to the available size of the embedded UV. Best use of screen real estate is always a concern and why I (unsuccessfully) try to limit the number of new options being added to the footer. One advantage of using the same dialogue is that UV users who don't want two separate buttons won't have to use them. We can do things the YouTube way, and also accommodate an extra configurable embedding "shortcut" in the footer for those who want it. The UV's resizing system is capable of dynamically changing the size of the dialogue to accommodate extra embed options as per the YouTube approach. We'd need to be conscious of how much vertical space we use though as it is not as you say a scrolling page like YouTube. The other advantage to tabbing is that we won't have to introduce a completely new dialogue to the UV and can keep all sharing functionality logically grouped. It also permits extra sharing options being added without the necessity for further buttons in the footer..!

**Comment by mialondon** [comment]
@edsilv shall we try your tabbed approach with the two buttons then? 

Other sharing options wouldn't get new buttons, btw - this might put pressure on the ability of the icon and label chosen to represent the options, but we can see how it goes with the network graph icon for now.

**Comment by edsilv** [comment]
Ok, cool. I think @demiankatz likes that idea too.

**Comment by mialondon** [comment]
Noting a decision to try a youtube-style drop-down for different sizes - this deals with the excessive space taken up by the blocks and another noted UX issue where it wasn't clear which option was selected.

**Comment by jennpb** [comment]
@mialondon @edsilv sounds ok in practice, but would like to see sketches or mockups if available first. thanks!

**Comment by mialondon** [comment]
@jennpb in the absence of Photoshop... Share would be as on 'simple https://github.com/UniversalViewer/universalviewer/issues/330#issuecomment-228726398 but without the social media icons; embed would be like the simple embed screen but with the video size option. Hopefully @edsilv will have a version to look at soon!

**Comment by edsilv** [comment]
There's something we haven't considered about the share url. Currently, the share url is only shown if the UV is embedded on the 'home' domain, and it's the only instance of the UV on the current page. i.e. 'deep linking' is enabled using the hash params. YouTube's share URL always uses http://youtu.be/id as it's never going to vary from that. The UV however does not have a single domain to reference, it could be embedded from any institutions' site. Institutions have different url schemes for their canonical UV pages. Wellcome use:

http://wellcomelibrary.org/item/b18035978

Whereas Villanova use:

http://digital.library.villanova.edu/Item/vudl:296538

Perhaps we could use the IIIF `related` property for the share url when the UV is embedded on an external domain? See: http://wellcomelibrary.org/iiif/b18035978/manifest

**Comment by edsilv** [comment]
To simplify: If not embedded on the home domain, if there's a `related` property of format `text/html` in the manifest, show the share tab, otherwise hide it.

**Comment by mialondon** [comment]
@edsilv can you fix the emphasis on the headers? e.g. at the moment it looks like the header is 'embed' when you're on the 'share' screen, and vice versa.

Does the field need to be a form field or could it be plain text? In testing on tablets, clicking into it brought up the on-screen keyboard, which was an annoyance.

The screens may need some explanatory text. @jennpb do you have any thoughts?

**Comment by mialondon** [comment]
@edsilv the canonical URL will be in the IIIF related property, according to AI/DW.
