### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#331]
The BL requires a print button so that the new viewer has the same visible functionality as the existing viewer. This was ranked as high priority by internal stakeholders, and creating an MVP version would allow more content to be made available.

As a first pass for a minimum viable product, offering a PDF which can be printed should meet most people's needs. The Harvard Mirador viewer and the e-codices viewer (see attachments) are the only examples of viewers with print buttons that I could spot, and in both cases they use PDFs to deliver print options. 

Examples:
- http://www.e-codices.unifr.ch/en/bbb/0199/4r 
- http://iiif.lib.harvard.edu/manifests/view/drs:46053466$20i

![e-codices print](https://cloud.githubusercontent.com/assets/380763/16378481/0c886a6e-3c64-11e6-8bf2-e4f93f6d66c4.GIF)
![harvard mirador viewer - print screen - iiif_lib_harvard_edu_manifests_view_drs_46053466 20i](https://cloud.githubusercontent.com/assets/380763/16378599/a8cf2e58-3c64-11e6-85b8-be022d80199f.png)

Internally this is related to Product Backlog Item 9538:Develop Usability Concepts around Download/Print

**Comment by mialondon** [comment]
The implementation of this will need review before future BL work as the user experience for print and download is currently affected by implementation decisions. (e.g. you should be able to download or print from an embedded item).

**Comment by mialondon** [comment]
See also BL Product Backlog Item 13780:Print current view

**Comment by edsilv** [comment]
@davianrobinson

**Comment by edsilv** [comment]
http://universalviewer.io/examples/?manifest=https%3A%2F%2Fedsilv.github.io%2Ftest-manifests%2Fprint.json

if a print service is included it overrides the download pdf option

**Comment by mialondon** [comment]
Printing from the browser gives you a version of the page you're on. It's a little gnarly still (the overview box probably doesn't need to be there and it'd be great if the lefthand side panel was collapsed to allow more room for the image) but it's a good step forward. ![ctl-print-from-uv](https://cloud.githubusercontent.com/assets/380763/18680940/9bf6eb94-7f5d-11e6-8bd5-d13e28deefab.png)

**Comment by DavidWaldock** [comment]
The overview box is there because it's mouse over? What browser are you
using?

D
