### ISSUE TITLE
'Cite as' / 'Citation' panel

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#332]
A possible idea, based on other collections. NB: the British Library is increasingly using MHRA http://www.mhra.org.uk/Publications/Books/StyleGuide/index.html. 

Other examples:

**Rijksmuseum catalogue**
https://www.rijksmuseum.nl/en/collection/SK-A-3841/catalogue-entry
![citation example www_rijksmuseum_nl_en_collection_sk-a-3841_catalogue-entry](https://cloud.githubusercontent.com/assets/380763/16388654/03e476e0-3c92-11e6-878d-3657de40bcc9.png)

**Google Scholar - books**
![google cite as book](https://cloud.githubusercontent.com/assets/380763/16388657/0a7e6966-3c92-11e6-9100-d15dc809597d.GIF)

**Google Scholar - journal articles**
![google cite as](https://cloud.githubusercontent.com/assets/380763/16388672/1342d708-3c92-11e6-87cb-b5e4c97d19b8.GIF)

**Cooper Hewitt museum collection item**
https://collection.cooperhewitt.org/objects/18572415/
![cooperhewitt cite as collection_cooperhewitt_org_objects_18572415](https://cloud.githubusercontent.com/assets/380763/16388731/522b6bba-3c92-11e6-84ab-5f3726f97b33.png)

**NYPL**
http://digitalcollections.nypl.org/items/510d47da-c98a-a3d9-e040-e00a18064a99
![cite this item digitalcollections_nypl_org_items_510d47da-c98a-a3d9-e040-e00a18064a99](https://cloud.githubusercontent.com/assets/380763/16388795/a769501a-3c92-11e6-9a17-1476fc8b4359.png)

**Pleiades**
http://pleiades.stoa.org/places/423025
![cite as roma pleiades - pleiades_stoa_org_places_423025](https://cloud.githubusercontent.com/assets/380763/16388840/e7f767fc-3c92-11e6-8403-83c3c5f50d84.png)

**Coptic SCRIPTORIUM**
http://data.copticscriptorium.org/texts/abraham_our_father/xl93-94/norm
![how to cite data_copticscriptorium_org_texts_abraham_our_father_xl93-94_norm](https://cloud.githubusercontent.com/assets/380763/16416238/3c84ea46-3d39-11e6-8794-45e54554cccb.png)

*_Paradisec_
http://catalog.paradisec.org.au/collections/AA1/items/001
![cite as catalog_paradisec_org_a](https://cloud.githubusercontent.com/assets/380763/16416697/70d7e29c-3d3b-11e6-96c4-14e6f8a3d7a8.png)

**Harvard Mirador**
![harvard mirador viewer - citation detail - iiif_lib_harvard_edu_manifests_view_drs_46053466 20i](https://cloud.githubusercontent.com/assets/380763/17704865/47a25c5e-63ce-11e6-8204-6cf6fee977cd.png)

Text from The National Archives: http://www.nationalarchives.gov.uk/help-with-your-research/citing-documents-national-archives/

**Comment by mialondon** [comment]
Thanks to twitter users @ryanfb @PleiadesProject @MeghaninMotion @BergFulton @nypl_labs for their suggestions!

**Comment by mialondon** [comment]
Bonus points for citation-manager compatibility through metadata like COinS https://en.wikipedia.org/wiki/COinS (but this would presumably a requirement for the page rather than the Viewer).

**Comment by DavidWaldock** [comment]
As would compatibility with social media metadata.

D

**Comment by nicolasfranck** [comment]
Mm, seeing all these use cases, I think it's better to add the possibility to add panels yourself. Everyone has his/her own requirements that the creator of the viewer cannot make. The core of the viewer should remain simple and clean, but leave space for "plugins".

**Comment by mialondon** [comment]
@nicolasfranck it's just metadata. If you don't include it in the manifest, it won't display.
