### ISSUE TITLE
Trying to slim down UV viewer in production

### ISSUE THREAD

**Issue by matt-bernhardt** [UniversalViewer/universalviewer#333]
I'm wondering what the most minimal deployment of UV is? For example, looking over the files that are distributed, I have questions about:

- There appear to be two themes, one English and the other Welsh? Can one be removed?
- Ditto for Welsh configuration JSON files under `/schema` and `/lib`
- The `/lib` directory contains minified and non-minified javascript for things like `pdf.js` and `pdf.worker.js`. Can the non-minified variants be removed in a production context?
- I'm assuming that the localization files in `/l10n` should _not_ be removed, as those would be accessed by site visitors.

In general, we are trying to trim down our deployed file size as much as possible, and wondering what can be removed from UV safely without re-writing anything.

**Comment by edsilv** [comment]
Hi,

The themes are controlled by the bower.json. You can certainly remove `"uv-cy-GB-theme"` from there. 

The dev branch has the most up-to-date code. I'd like to do another proper release soon. On there the generated schemas are in `src/[extension]/build/`. These shouldn't be generated if you remove the welsh config json.

I think the unminified pdf.js was being used for testing. The pdf extension uses pdf_combined:

https://github.com/UniversalViewer/universalviewer/blob/dev/src/extensions/uv-pdf-extension/dependencies.js

So this won't get loaded. Extensions only load their dependencies when being used. Should be safe to delete pdf.js if you wish, although makes no difference at runtime.

Configs are merged with l10n files on build. So if you remove the config, you should remove the associated l10n file too. You can disable the welsh option like this:

https://github.com/UniversalViewer/universalviewer/issues/254

The dev branch has a minified `bundle.min.js` which should be an improvement. It also now uses cdnjs.com to load many of the other libs.
