### ISSUE TITLE
The 'Attribution' field

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#335]
The BL is considering whether it should be interpreted as 'provenance' or 'usage/licence information'.

From the POV of making the field useful for the reader and the institution (and copied in part from a post to the UV Slack):

We've been discussing the 'Attribution' requirement. It might be that the spec is usefully vague to allow for a range of use cases, but it's not clear what purpose it should have in our (BL) case. It currently has some usage/copyright information, but a human-readable statement of how the material can be used seems a better fit for the License section, assuming any requirements for displaying usage/rights information can be met by information provided in other fields.

I would assume that it has a role in providing provenance for digital objects (e.g. 'This item is held by the British Library') as it is for NLW http://universalviewer.io/examples/?manifest=http%3A%2F%2Fdams.llgc.org.uk%2Fiiif%2F2.0%2F4389767%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=0&z=-0.1233%2C-0.0556%2C1.2467%2C1.1111 and Villanova http://universalviewer.io/examples/?manifest=http%3A%2F%2Fdigital.library.villanova.edu%2FItem%2Fvudl%3A24299%2FManifest&locale=en-GB#?c=0&m=0&s=0&cv=0&z=-0.3363%2C-0.0745%2C1.6726%2C1.4907 (thanks Andy Irving for the examples)

@tomcrane pointed out that 'the specification attaches no semantics to the attribution property, it's simply some text that you want people to see if they open your IIIF resource in a viewer that respects the intention of this property' and that Wellcome have used it to 'credit the source repository if contributed, say, by King's or UCL'.

Conceivably, this could be extended to provide 'Cite as' text that concatenated vital information commonly used in scholarly referencing (see https://github.com/UniversalViewer/universalviewer/issues/332)

**Comment by DavidWaldock** [comment]
I would argue that "the specification attaches no semantics to the
attribution property" is part of the problem; without semantics, how can
its use be divined?

D

**Comment by mialondon** [comment]
@DavidWaldock agreed! But at least it leaves us free to make it useful for the reader...

**Comment by DavidWaldock** [comment]
Yes, but that might mean we don't have a place to put other key information.

For example, there should be metadata to describe who holds and cares for
the original item, and metadata to allow a human-readable mechanism for
describing usage rights. They're both essential, but both *could* in the
attribution property.

It strikes me that this is definitely a IIIF/IxIF problem and is probably
not a UV issue. This might be a useful location for capturing use cases
though.

D

**Comment by mialondon** [comment]
An update from the BL: we're labelling the Attribution field as 'Usage terms'. Our rights management staff pointed out that 'attribution' has a very specific meaning in their context, and we also felt that 'usage terms' content was more useful for people thinking about re-using or quoting from our material.
