### ISSUE TITLE
xywh hash param for current viewport

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#336]
The UV uses the `z` parameter to capture the current viewport as a region of the OSD World:

`?c=0&m=0&s=0&cv=0&z=-0.7105%2C-0.0833%2C2.421%2C1.6669`

This could be superseded by a #xywh=100,100,1000,2000 parameter that serves the same purpose, but captures the current visible part of a canvas in the same syntax and coordinate space as the canvas itself and annotations upon it.

This can be extended to n-up displays, as long as the canvases are to the same scale. By default the UV will now lay out the canvases to scale. If in future the UV makes use of a physical dimensions service and has differently-scaled canvases in view at the same time, a more complex solution is required.

**Comment by tomcrane** [comment]
From community call:

Xywh - need cv and xywh params in order to know which canvas the annotation is on. Can’t use world coords because these may vary across viewers. Add capability to UV to know which canvas is most in viewport.

**Comment by LlGC-szw** [comment]
Testing on this example at the moment. Seems to be working really well.

http://nlw.azurewebsites.net/?manifest=http%3A%2F%2Fdev.llgc.org.uk%2Fiiif%2Fsearch%2F4623730.json#?cv=0&h=A20&c=0&m=0&s=0&xywh=32922%2C57587%2C689%2C359

**Comment by nicolasfranck** [comment]
Is there a reason why the viewport bounds are used for xywh, instead of the image bounds? The viewport bounds depend on a specific viewport being opened.

One can easily convert from image bounds to viewport bounds when initializing the openseadragon viewer.

**Comment by edsilv** [comment]
@nicolasfranck Not sure I understand. It originally used the viewport bounds, but now uses the image bounds. Perhaps you could create a PR with your suggested changes?

**Comment by nicolasfranck** [comment]
mm, it works now as expected. Must have been a caching issue, or incorrect build. Sorry for the misunderstanding ;-)

**Comment by nicolasfranck** [comment]
This is a breaking change. And there are bookmarked urls all around the place that ask to be reused.
So we have two options:

* create some code IN the library that catches the old parameter "z" and convert it. For now the z parameter is added alongside the xywh. It should be removed from the url.

* create some code OUTSIDE the library that shows how to deal with this. This way you can keep old junk out of the library, while providing a sort of migration.

As the z parameter is OSD specific and needs the viewport of OSD, the first option is likely.

What do you think? Should we do this?
