### ISSUE TITLE
Two-up / one-up mode UX issues

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#338]
The user should not have limited functionality re download, print, etc because of the page view style they have chosen.

As @jennpb said on https://github.com/UniversalViewer/universalviewer/issues/142 Download current view as one-page only feels stingy; users shouldn't have to understand why images can/cannot be stitched together to form a 2-page view.

See also @edsilv https://github.com/UniversalViewer/universalviewer/issues/142#issuecomment-228310158

**Comment by nicolasfranck** [comment]
@mialondon : the user can also (and probably will) click right on the viewer and "save image" rather than looking for a button that says "save". It will be saved as "download.png". That is standard behaviour for canvas elements in HTML. Try it with two-page view.

UV provides IIIF compatible links to slices of one image. IIIF does not have support (yet?) for combining two images.

@edsilv : for the current view image, why not simply copying the canvas data, and provide it to download?

**Comment by edsilv** [comment]
@nicolasfranck yep, we've thought about using the canvas api. This would limit the downloaded image to quite a low resolution though. I asked @tomcrane if he could raise a question with the IIIF editors group regarding whether the image api could support requests for multiple image segments and return a combined response. It would be good to officially rule this out before attempting a client-side solution I think as other viewers may require this functionality. cc @azaroth42

**Comment by mialondon** [comment]
@nicolasfranck we suspect that our readers won't typically think to right- or control-click to download an image, which is one reason why a 'download' button is important.

**Comment by azaroth42** [comment]
Combination of multiple images into one (or more) is currently outside of the scope of the Image API.  The API is resource based -- there's only one slot for the "identifier" of the image.

However ... a "stitching" service would also be very valuable that sat __on top of__ the IIIF Image API, that you could pass a description of the images to, and it would then construct a new Image API endpoint. This seems like an interesting use case for REST/server management, as it doesn't involve sending new image content, just the creation of new identifiers that then do the math on where the image content comes from.

Could we take this to iiif-discuss for more brainstorming?

**Comment by edsilv** [comment]
We'd have to make it clear somewhere in the manifest whether this was available for a viewer to use (a service with a stitching profile at the root level?) Static "level 0" image services should be able to provide a stitching user experience too. This would have to use the canvas API, so maybe it's overkill to expect everyone to implement a stitching service on the server side?

**Comment by DavidWaldock** [comment]
Does it need to a local service? Couldn't a hosted service handle the work
independent on implementation by consuming the Presentation and Image APIs?

D

**Comment by azaroth42** [comment]
--> iiif-discuss please? :)

**Comment by mialondon** [comment]
While it's being considered on iiif-discuss, a possible solution discussed at the BL is to trigger two downloads in the browser, one for each image canvas. It might be a bit clunky but it's possibly the last clunky option while stitching is being discussed, and better than asking the user to adapt to the software model and switch between modes.

**Comment by mialondon** [comment]
You can see a version of this in action at http://universalviewer.io/examples/?manifest=http%3A%2F%2Fapi.bl.uk%2Fmetadata%2Fiiif%2Fark%3A%2F81055%2Fvdc_100022545251.0x000002%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=2&z=0%2C-163.2381%2C5004%2C3701.4761 if you click 'download' white in two-page mode - it should open two new tabs, one for each image.

Whether people will realise that's how it works is another question!

**Comment by edsilv** [comment]
Fixed by https://github.com/UniversalViewer/universalviewer/commit/44b4ee673ded6853cab5fcf0413fd0fe59953226

**Comment by mialondon** [comment]
So far our usability tests have shown that people expect a 'download' function will result in a file having been downloaded and stored somewhere on their system (downloads folder, desktop, etc). Opening the images in a tab for potential download is good but only gets us part of the way there. 

I'm re-opening this for discussion, not because further development work is required in the next BL sprints, because triggering the 'open or save as' dialogue might work for single page images, it appears it doesn't easily work for two.

**Comment by nicolasfranck** [comment]
Opening multiple windows in Chrome is disabled by default, so it does not work in that browser. Only the first image opens in a tab, and the second is ignored (it does not even show a warning in the log).

**Comment by mialondon** [comment]
@DavidWaldock did you see @nicolasfranck 's comment? Something of a spanner in the works!

**Comment by DavidWaldock** [comment]
It was always a temporary fix, but I'm surprised that hasn't come up before.

D

**Comment by mialondon** [comment]
@edsilv where did we get to with this? There are currently different options in one-up/two-up view on http://bltesters.azurewebsites.net/?manifest=http%3A%2F%2Fapi.bl.uk%2Fmetadata%2Fiiif%2Fark%3A%2F81055%2Fvdc_100022545251.0x000002%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=0&z=-1029.8196%2C0%2C4562.6392%2C3375

**Comment by mialondon** [comment]
From the last Fluent usability tests:

The   difference between the download options is not always clear. 

Consider   communicating the differences between resolutions and the ability to select   pages for download more clearly

**Comment by edsilv** [comment]
UV dev call design idea:

![Frame 1 (1)](https://user-images.githubusercontent.com/1334393/162248383-efc7ac6e-812a-432a-bb58-c353c97a314d.png)


We think that the radio buttons are unnecessary. The list items can be links and we can do away with the download button.

**Comment by LlGC-szw** [comment]
Please don't forget that there should be a Download TITLE (pdf) link too as this implementation was paid for by NLW. See https://journals.library.wales/view/2104777/2104983/#?xywh=-1582%2C-171%2C5141%2C3391

**Comment by stephenmcconnachie** [comment]
> Please don't forget that there should be a **Download TITLE (pdf)** link too as this implementation was paid for by NLW. See https://journals.library.wales/view/2104777/2104983/#?xywh=-1582%2C-171%2C5141%2C3391

@LlGC-szw Does that service behind that link gather all images in a single Manifest and generate a PDF containing them all? I guess that service is NLW-created, not inherent in the U.V.? I was considering building a similar function as a Flask app that could be called, would love to learn more about the NLW service, if possible

**Comment by edsilv** [comment]
@LIGC-szw The download menu will keep all of the same options, just with the extra ability to specify which page.

**Comment by mialondon** [comment]
> @LlGC-szw Does that service behind that link gather all images in a single Manifest and generate a PDF containing them all? I guess that service is NLW-created, not inherent in the U.V.? 

That's how it works at the British Library. The folk who created it are long gone but I could ask the current team if they could share.

**Comment by LlGC-dwj** [comment]
> > Please don't forget that there should be a **Download TITLE (pdf)** link too as this implementation was paid for by NLW. See https://journals.library.wales/view/2104777/2104983/#?xywh=-1582%2C-171%2C5141%2C3391
> 
> @LlGC-szw Does that service behind that link gather all images in a single Manifest and generate a PDF containing them all? I guess that service is NLW-created, not inherent in the U.V.? I was considering building a similar function as a Flask app that could be called, would love to learn more about the NLW service, if possible

Hi we generated a pdf for each article on our journals site (https://journals.library.wales/home) and added a link to them in the manifest via the rendering section. This then gets picked up by the UV.

"rendering": {
"@id": "https://datasyllwr.llgc.org.uk/journals/pdf/AWJAC004003.pdf",
"format": "application/pdf",
"label": [
{
"@value": "Download 'Mary Silyn Roberts'",
"@language": "en"
},
{
"@value": "Lawrlwytho 'Mary Silyn Roberts'",
"@language": "cy-GB"
}
]
}
