### ISSUE TITLE
Navigation tweaks - thumbnail/single/double page view; sequence controls

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#339]
As @jennpb and I discussed earlier in [UV UX / British Library and Wellcome](https://docs.google.com/document/d/1JpR90S2BS1h8XkCCrYA9PLlyeDOPrMbLgoXFDTn0MPo/edit?pref=2&pli=1#heading=h.hasd4osf0a9b) it'd be good to move the thumbnail gallery option to the header bar, and to make the single/double page viewing options visible at the same time.

@edsilv has mocked up a version of this based on [e-codices](http://www.e-codices.unifr.ch/en/bbb/0199/3r/0/Sequence-29) 'view mode'. In this mock-up he has also moved the sequence controls to the left (which may increase their use as people currently don't seem to associate them with the item they're viewing). The zoom and rotate icons have also been moved.

The grid/thumbnail icon is a shortcut to the gallery view, meaning the chevrons on the left-hand side may no longer be needed (in instances where ranges are not present in the supplied manifest).

![design](https://cloud.githubusercontent.com/assets/380763/16626101/5bd2e7a6-439f-11e6-9337-daf128cb5af0.jpg)

**Comment by jennpb** [comment]
That might work. Will any proposed changes be tested on users before implementation? (e.g. not on staff or us?)

**Comment by mialondon** [comment]
@jennpb I wanted to get your and Donald's opinions first then work out how we might test it. Could we do guerilla usability testing at your gaff?

**Comment by jennpb** [comment]
With Wellcome's being the old version, and BL's being the new one, I assume? Biggest problem for us right now is UX resource. We've got a lot going on at the moment with no help to spare. But it depends on when there is something ready to test, and how quick your turnaround time needs to be. When were you thinking this might happen?

**Comment by mialondon** [comment]
@edsilv how much time would it take to update the top right-hand corner to add icons for thumbnail view (which opens the fully expanded thumbnail panel), double page view, single page view? There should be a visual signifier for the option that's currently selected (e.g. greyed out vs white, active buttons).

**Comment by mialondon** [comment]
@edsilv I can create a separate issue for this if you like, but just to note it quickly - the double page icon should probably literally be two versions of the single page icon so the link between them is visually clear.

**Comment by edsilv** [comment]
![image](https://cloud.githubusercontent.com/assets/1334393/19068738/bf1f9814-8a1b-11e6-97cd-01cf139fb3e5.png)

Implemented on the dev branch.
