### ISSUE TITLE
Link for IIIF manifest address

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#340]
A future BL requirement is providing a link to the IIIF manifest so that people can open collection items in other viewers (e.g. Mirador).

This link could either go on the 'share' dialogue box (see https://github.com/UniversalViewer/universalviewer/issues/330) or on the 'More information' panel (or both).

Are there any strong preferences or cases for or against?

NB: digital Bodleian currently uses the IIIF logo to link to the manifest file - clicking it in the screenshot below takes you to http://iiif.bodleian.ox.ac.uk/iiif/manifest/d4a23501-0b98-4aff-acd6-fe06fe9b62e3.json

e-codices show the link with a label 'IIIF Manifest URL' on one page ([e.g. on the 'how to quote' tab](http://www.e-codices.unifr.ch/en/bbb/0199/4r)) and use the IIIF logo on another ([e.g.](http://www.e-codices.unifr.ch/en/list/one/bbb/0199)) 

![iiif link digital_bodleian_ox_ac_uk_inquire_discover_search_ __p c 2 t euclid rsrs 0 rsps 10 fa so ox 3as](https://cloud.githubusercontent.com/assets/380763/16627065/7f7e36d4-43a3-11e6-813b-9e736c36ab19.png)

**Comment by DavidWaldock** [comment]
I'd say both personally; don't go for an OR if you can go with an AND.

D

**Comment by jennpb** [comment]
For us, again configurability is mega-important. I want to be able to turn off options in the share/download/more info panels. The large majority of our users aren't going to be IIIF-heads, so littering the viewer with mentions of IIIF is only going to offer more complexity. We've gone for sharing the IIIF manifest on the item page itself, along with other data formats: http://wellcomelibrary.org/item/b19968899#?c=0&m=0&s=0&cv=0&z=-1.4249%2C-0.0978%2C3.8499%2C1.9557

**Comment by irv** [comment]
General consensus in the community is the iiif logo is a link to manifest address and you can usually drag and drop that into a different viewer

**Comment by mialondon** [comment]
@jennpb good point re config. Would you want the IIIF manifest available for embedded items or would you assume that people would click through to the source if they were serious enough about an item to view it in another viewer? (I think I just answered my own question)

**Comment by jennpb** [comment]
Viewer Jumping seems like such an edge case to me. It'd be interesting to know if we could actually track viewing of one manifest from viewer to viewer to viewer...

**Comment by mialondon** [comment]
It's mostly driven by manuscript readers, for us.

**Comment by mialondon** [comment]
@edsilv the viewer should only display the IIIF logo with manifest link if the collection item is available for reuse (embedding, downloading) outside the host site, and the option to display it at all should be configurable.

**Comment by mialondon** [comment]
Putting it on the 'share' dialogue seems to make the most sense at the moment. The 'More information' panel doesn't currently have any other active functions, so as a MVP one simple button gives us enough to learn from for future iterations.

**Comment by edsilv** [comment]
![image](https://cloud.githubusercontent.com/assets/1334393/19068670/65ade88a-8a1b-11e6-910a-e3b80ae63409.png)

Implemented on the dev branch.

Clicking on this will open the manifest in a new window. It can also be dragged into another instance of the UV/Mirador.

**Comment by mialondon** [comment]
Thanks @edsilv ! In a future iteration we might want to add some explanatory text, but this is a good MVP.
