### ISSUE TITLE
dev branch not working in firefox

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#344]
e.g. http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&z=-1376.4762%2C-196.8333%2C5321.9525%2C3936.6667

**Comment by edsilv** [comment]
looks like a problem with iiif-tree-component:

http://edsilv.github.io/iiif-tree-component/examples/

**Comment by edsilv** [comment]
@nicolasfranck The problem was with https://github.com/edsilv/base-component using a global `Components` namespace. I've renamed it to `_Components`:

https://github.com/edsilv/base-component/blob/master/src/BaseComponent.ts#L3
