### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by Myrav** [UniversalViewer/universalviewer#347]
I have noticed that Universal Viewer can't handle chapter bookmarks. When we click on one of them, the link refers to the wrong page. I checked my chapter bookmarks outside the plugin, and all of the links are ok.

Do you think this bug could be fixed soon ? 

Thanks in advance, 

M. Ravereau

**Comment by edsilv** [comment]
Hi, do you mean in the tree view? These are IIIF ranges. They seem to be working fine for me with my usual test manifests. Could you post a link to the manifest that the UV is having problems with?

**Comment by Myrav** [comment]
Hi, 

I apologise I don't understand what you mean by tree view... 

Indeed, when I go on the Wellcome Library or the National Library of Wales websites, Universal Viewer displays well the chapter bookmarks (we can go on the title page directly by clicking on the [link.](http://digidol.llgc.org.uk/METS/SEW00002a/frames?div=1&subdiv=0&locale=en&mode=reference) 

I use a version of UV developed for the CMS omeka. I first asked omeka's plugin developer if the issue comes from his code but he didn't thought so and suggested to ask you. 

Unfortunately I work on a local server and can't give you a public link. I tried to find someone using UV with omeka (and chapter bookmarks) but unsuccessfully. The only thing I can do is to show you a screenshot ... 

![8d7ea382-500e-11e6-88db-27aeb3febbbc](https://cloud.githubusercontent.com/assets/19977800/17094293/9a60cec6-524e-11e6-9882-95dcca67f1f8.gif)

Thanks for your quick answer, 

Sincerely, 

Mylène R.

**Comment by Daniel-KM** [comment]
Hi,

The plugin integrated the vanilla version of UV (1.7.27), without any change. Here, the issue is about a pdf, not about iiif. It seems to be related to her file. But the pdf viewer is the Mozilla one, so it should be checked with pdf.js too.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
