### ISSUE TITLE
Search inside feature does not work without autocomplete service

### ISSUE THREAD

**Issue by jronallo** [UniversalViewer/universalviewer#348]
UV search inside does not work unless there is also an autocomplete service. Search inside ought to be able to work even if a nested autocomplete service isn't given. This is with uv-1.7.27.

https://github.com/UniversalViewer/universalviewer/issues/132#issuecomment-145510329 claims that "assumed autocomplete" is fixed, but it does not seem to be.

Putting this in a manifest does not work:

``` json
"service": [
    {
        "@context": "http://iiif.io/api/search/0/context.json",
        "@id": "http://localhost:3000/catalog/technician-v9n22-1929-03-09/search_inside.json",
        "profile": "http://iiif.io/api/search/0/search",
        "label": "Search within this thing"
    }
]
```

Adding in an autocomplete service to the manifest--even a dummy one--allows UV to work for search inside. Note that the autocomplete service here just returns an empty 200 OK for every request.

``` json
"service": [
    {
        "@context": "http://iiif.io/api/search/0/context.json",
        "@id": "http://localhost:3000/catalog/technician-v9n22-1929-03-09/search_inside.json",
        "profile": "http://iiif.io/api/search/0/search",
        "label": "Search within this thing",
        "service": {
            "@id": "http://localhost:3000/catalog/technician-v9n22-1929-03-09/autocomplete.json",
            "profile": "http://iiif.io/api/search/0/autocomplete",
            "label": "Get suggested words in this manifest"
        }
    }
]
```

**Comment by glenrobson** [comment]
I don't know if it helps but we have search only working in uv-v1.7.11. Our service section looks as follows:

```
"service": {
    "profile": "http://iiif.io/api/search/0/search",
    "@id": "http://caneri.llgc.org.uk/cynefin/4546256/search",
    "@context": "http://iiif.io/api/search/0/context.json"
}
```
which looks to match yours. I can also confirm it works for uv-v1.7.27 at http://universalviewer.io.

**Comment by edsilv** [comment]
I've created a test manifest without the autocomplete service:

http://universalviewer.io/examples/?manifest=https%3A%2F%2Fedsilv.github.io%2Ftest-manifests%2Fno-autocomplete.json

Search _does_ work, but only when clicking on the search button, not when hitting Enter. I think this is related to @nicolasfranck's PR https://github.com/UniversalViewer/universalviewer/pull/345

**Comment by jronallo** [comment]
Yes, I was expecting that hitting Enter would launch the search and hadn't realized that there was a button there that could be clicked. When suggestions are provided hitting enter does already work.

**Comment by edsilv** [comment]
This is fixed now on dev.
