### ISSUE TITLE
search inside should clearly indicate matching thumbnails in the left panel

### ISSUE THREAD

**Issue by jronallo** [UniversalViewer/universalviewer#350]
It would be nice when a canvas has a search hit on it that the thumbnail in the left panel is changed in some way to indicate that there's a hit on the page. This could be adding a background color to the page number. Another possibility is adding a symbol or text below or over part of the image. This could could include the number of hits from that page.

**Comment by edsilv** [comment]
Here are some designs following a discussion with the NLW:

![image](https://cloud.githubusercontent.com/assets/1334393/20525275/8b4e7ff2-b0b6-11e6-829f-24634b44a512.png)

![image](https://cloud.githubusercontent.com/assets/1334393/20525283/92c38f8e-b0b6-11e6-9ae7-426767c5a836.png)

**Comment by edsilv** [comment]
fixed on the dev branch.
