### ISSUE TITLE
search inside "next result" link does not display in Firefox

### ISSUE THREAD

**Issue by jronallo** [UniversalViewer/universalviewer#351]
I thought it odd there was a "previous result" link but not a "next result" one, so I opened the page in Chrome which does display the "next result" link. In Firefox the "next result" link does not show up though it is there in code.

![uv-search-inside-next-result-link-in-firefox](https://cloud.githubusercontent.com/assets/66485/17460217/5c0feffe-5c2a-11e6-8c3a-3d5ac47f4a39.png)

![screenshot_2016-08-06_23-07-58](https://cloud.githubusercontent.com/assets/66485/17460228/d68f03aa-5c2a-11e6-803b-73e598dcb983.png)

**Comment by edsilv** [comment]
Hi Jason, I'm not seeing this in my Firefox (v47.0.1) which version are you running?

If you open dev tools and select `<div class="searchResultsInfo">` you can change the width in the css rules panel:

![image](https://cloud.githubusercontent.com/assets/1334393/17483689/f9eaf660-5d7e-11e6-8ac0-2a37c1078b3a.png)

If you reduce the width, at what width does the button reappear?

**Comment by jronallo** [comment]
I'm using Firefox 48.0 where it is an issue (before when I reported this issue I was using 47). If I bring the width of .searchResultsInfo down to 337px (but no more) then the next result link displays.

**Comment by edsilv** [comment]
I've just pushed v1.8.14 which has a searchResultsInfo div 337px in width. Could you try clearing your cache and looking again? http://universalviewer.io/examples/

**Comment by jronallo** [comment]
This is fixed on the example page now.
