### ISSUE TITLE
_Components is not defined

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#355]
The dev branch fails with the following javascript error (in console):

```
iiif-tree-component.js:246 Uncaught ReferenceError: _Components is not defined
```

Seems like the namespace _Components is not compiled from TypeScript to Javascript?

**Comment by edsilv** [comment]
could you try running:

    npm update
    grunt sync

then another build?

**Comment by nicolasfranck** [comment]
nope doesn't change anything

**Comment by nicolasfranck** [comment]
ok, after removing the directory "node_modules" and all over again, it worked ;-)
