### ISSUE TITLE
Show all image specific information in two-up mode

### ISSUE THREAD

**Issue by john-root** [UniversalViewer/universalviewer#356]
When in "two-up mode" two images are shown at a time but the image specific information is only shown for one of them on the right hand panel.

**Comment by DavidWaldock** [comment]
How could it display two-up image-specific metadata at the same time?

**Comment by john-root** [comment]
There is a definite UI issue for sure. At the moment there is a heading shown (e.g. "about the image"), one possible solution is to have two headings.  ("about the left image" and "about the right image").

<img width="422" alt="screen shot 2016-08-10 at 10 47 28" src="https://cloud.githubusercontent.com/assets/14330103/17549432/0a859baa-5ee8-11e6-8b26-a5520c5ba480.png">

**Comment by edsilv** [comment]
I will be doing some work soon to add range metadata to the more info panel as part of #188 for Princeton. The pages could potentially be members of different ranges too.

The UV can display arbitrary numbers of canvases (2-up just being another example of this):

https://docs.google.com/presentation/d/19v2I4JSTmKBPMsmOOVDdd5k0pnc4c2qxBmArZHDNCTQ/edit#slide=id.gee37657e1_0_65

"Continuous" scroll:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fsanddragon.bl.uk%2FIIIFMetadataService%2For_1459.json

Would we expect to show their combined metadata, or is 2-up a special case?

What if we were viewing an arbitrarily-sized collection of 3D models at once in a 3D space? You'd expect to be able to select each model to view its metadata. Individual scans of pages in books are no different to my mind.

The UV always knows which specific individual canvas index it is looking at. This is the baseline functionality.

Clicking on the right thumbnail in the thumbs panel would update the more info panel contents, but we can't expect users to know that.

Maybe we provide a shortcut button in the more info panel when in two-up mode to switch between the right and left images as a special case for the OpenSeadragon metadata panel.

**Comment by john-root** [comment]
Yes, it makes sense to consider the most general case too, but if we already have some specific UI elements for two-up as a special case it would seem sensible to ensure that we at least support that case, either by showing both (possibly with a UI clue as to the label for the canvas its annotating as part of the heading?) or using the shortcut you mention.

**Comment by edsilv** [comment]
I'm thinking that as the canvas is the ultimate target, there could be a utility that you pass a canvas to (and an optional current range as they can be members of multiple ranges). This would walk up the tree to the root combining all metadata. You could then call this utility for any number of canvases being displayed. The collections could then be de-duped into a single collection.

**Comment by jpstroop** [comment]
I think combining is a problem, if I understand what you're suggesting. Given a photo album with different photos on the left and right that having nothing to do with each other, combined metadata could get pretty strange.

When multiple canvases with `metadata` are in the view port, why not create a heading using the label of the canvas for each and display the metadata under each:

> 
> ### Canvas 1 Label
> 
> Title: Foo
> Creator: Bar 
> ________

> 
> ### Canvas 2 Label
> 
> Title: Baz
> Creator: Quux
