### ISSUE TITLE
enable/disable infinite zoom in branch dev

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#357]
In the branch "dev", one can now zoom in infinitely. Is there
a way to disable this behaviour, and make 100% the maximum
zoom level?

**Comment by edsilv** [comment]
Strange... I've created an issue on OSD: https://github.com/openseadragon/openseadragon/issues/1003

**Comment by mialondon** [comment]
We've had that reported as a bug a few times too.

**Comment by mialondon** [comment]
Feedback from a stakeholder: I’ve just been looking at this example (in Internet Explorer), and the zoom in button seems to go on ad inifinitum, i.e. well beyond the level where the image starts pixellating, whereas in DM [Digitised Manuscripts e.g. http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_36823_fs001r] the magnifier only allows you to go to the maximum level where the image is still sharp, which seems to be a better option.

**Comment by edsilv** [comment]
this is fixed now on dev.

**Comment by nicolasfranck** [comment]
Ok, that's fixed, but now the viewer does not fully load anymore:

http://camus1.ugent.be/local/uv_dev.html

It does after clicking on a thumbnail..

I see this error in the console:
```
app.js:3 Uncaught TypeError: this.extension.helper.getShareServiceUrl is not a function
```

**Comment by edsilv** [comment]
try doing an `npm update` then `grunt sync`

**Comment by nicolasfranck** [comment]
ok, thanks! Again the npm modules ;-)
