### ISSUE TITLE
switch to fullscreen in chrome moves UV to the right

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#358]
Switching to fullscreen mode on your demo website works perfectly in chrome:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fshared.ugent.be%2FIIIF%2Fmanifests%2Farchive.ugent.be%3A9B3B47F6-E235-11E5-9659-9EABD43445F2

But when I do this on my own website, the box holding the UV is moved to the right (click on "fullscreen")

http://shared.ugent.be/local/uv_dev.html

I only see this behaviour in Chrome, not in other browsers.

I do not see any difference in the html. Are there things I should be aware of?

**Comment by nicolasfranck** [comment]
Strange, I moved the CSS rules:
```
     div.uv {

        display: block;
        width: 924px;
        height: 668px; 
        background-color: rgb(0, 0, 0);
        margin: 0px;
        padding: 0px;

      }
```

To the style attribute of the UV element itself, and then it works..

**Comment by edsilv** [comment]
Glad you fixed it!
