### ISSUE TITLE
Highlight colours for search results

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#359]
As reported in guerilla usability tests to date, the current highlight colour #869f33 rgb(134, 159, 51) is hard to read against yellowed pages. 

Wellcome currently use #ffb81d rgb(255, 184, 29). The blue in use on http://universalviewer.io/examples (e.g. http://universalviewer.io/examples/?manifest=http%3A%2F%2Fapi.bl.uk%2Fmetadata%2Fiiif%2Fark%3A%2F81055%2Fvdc_100022545251.0x000002%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=10&z=2504.6554%2C399.3374%2C969.8088%2C717.3709) is #14a4c3;

Highlight colours tested by Donald (BL UX manager): 
Green - #00fe04 
Yellow - #ffff00
Blue - #05f7f9

**Comment by mialondon** [comment]
**Various current and suggested highlight colours on a grey page**
Which is the most readable?

![grey page universalviewer io uv wellcome yellow highlight](https://cloud.githubusercontent.com/assets/380763/17586927/b54ca950-5fbc-11e6-86bb-b35e4c7bcf4b.png)
![grey page universalviewer io uv donald yellow highlight](https://cloud.githubusercontent.com/assets/380763/17586924/b54b9e02-5fbc-11e6-9fd2-92cf37a56a73.png)
![grey page universalviewer io uv donald green highlight](https://cloud.githubusercontent.com/assets/380763/17586923/b54b0654-5fbc-11e6-8d96-ad83f40f6258.png)
![grey page universalviewer io uv donald blue highlight](https://cloud.githubusercontent.com/assets/380763/17586928/b54db976-5fbc-11e6-8401-35737e2bbb12.png)
![grey page universalviewer io uv current green highlight](https://cloud.githubusercontent.com/assets/380763/17586926/b54c3b3c-5fbc-11e6-94d5-02f635c8dd89.png)
![grey page universalviewer io uv current blue highlight](https://cloud.githubusercontent.com/assets/380763/17586925/b54c22d2-5fbc-11e6-8a56-ebffac85cebf.png)

Screenshots on Firefox, Windows.

**Comment by mialondon** [comment]
**Various current and suggested highlight colours on a yellowed page**
Which is the most readable?

![yellow page bltesters azurewebsites net uv wellcome yellow highlight](https://cloud.githubusercontent.com/assets/380763/17586972/05ebe2d6-5fbd-11e6-90a8-ada0436ee9f1.png)
![yellow page bltesters azurewebsites net uv donald yellow highlight](https://cloud.githubusercontent.com/assets/380763/17586974/05ec8d80-5fbd-11e6-8a36-01c66b67b303.png)
![yellow page bltesters azurewebsites net uv donald green highlight](https://cloud.githubusercontent.com/assets/380763/17586976/05f52bca-5fbd-11e6-99f1-11b1c5b5d328.png)
![yellow page bltesters azurewebsites net uv donald blue highlight](https://cloud.githubusercontent.com/assets/380763/17586971/05e9ec06-5fbd-11e6-87ac-38a1080897d1.png)
![yellow page bltesters azurewebsites net uv current green highlight](https://cloud.githubusercontent.com/assets/380763/17586975/05f02a08-5fbd-11e6-913c-61081da261bc.png)
![yellow page bltesters azurewebsites net uv current blue highlight](https://cloud.githubusercontent.com/assets/380763/17586973/05ec3be6-5fbd-11e6-88d5-d2d6f2373a25.png)


Screenshots on Firefox, Windows.

**Comment by mialondon** [comment]
@edsilv @kenlt there's no clear consensus, particularly as contrast is so dependent on the text and page colour of the original, but #05f7f9 is the colour we're going with for now.

**Comment by adikeinan** [comment]
I like the bright yellow (second from the top) for both grey and yellowed pages.

**Comment by ratanass** [comment]
For me bright yellow or bright blue work equally well for both grey and yellowed pages. Bright blue offers a bit more contrast I think.

**Comment by mialondon** [comment]
Thanks @ratanass @adikeinan and all the twitter/email commentators for your feedback, it's been really helpful (if not totally decisive).
