### ISSUE TITLE
Config option to make the floating 'Attribution' box appear or not appear

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#360]
**Reason**
Usability tests showed that people find the current interface too busy and they're not sure where to start using the viewer. As a result, we're looking to remove visual clutter.

The screenshot below shows the panel.

![screenshot showing acknowledgements panel and info repeated in more information](https://cloud.githubusercontent.com/assets/380763/17588593/085b2044-5fc8-11e6-9c62-684d7284c718.png)

The information in this 'Acknowledgements' field is now also repeated in the 'More information' tab, where we feel that scholars will naturally expect to find it. It's also repeated on the Share dialogue so that people can see Usage terms (BL's use of the Attribution field) at the point where they're looking to re-use it.

Currently the only way not to show the floating panel is to remove the Attribution field from the manifest root.

**Task**
Add an option to the UV config so that BL can choose not to show the floating Acknowledgements panel.

**Comment by mialondon** [comment]
@edsilv does this describe things well enough for you?

@jennpb just an FYI

**Comment by edsilv** [comment]
closing as done
