### ISSUE TITLE
Download dialogue text explaining that images open in new tabs

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#361]
**Reason**
Until the wonderful day when we can automatically trigger the browser's 'open or save as' dialogue, we need to explain that the Download options will open images in a new tab.

The new tabs opened with downloadable images might also be suppressed by some browser pop-up blockers.

**Task**
Add text to the Download dialogue box. As a first pass: 

Downloadable images will open in a new tab.

**Comment by mialondon** [comment]
Someone asked on the UV slack if we could use the "download" attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes so here's more context. There's an earlier Two-up / one-up mode UX issues https://github.com/UniversalViewer/universalviewer/issues/338

And specifically for this issue, while we could do it when we're triggering the download of a single image, there's a workaround for downloading both images (so that access to functions isn't affected by whether you're looking at one page or two) that opens two tabs, and if we triggered download on one but not the other then we'd be back to having a different user experience depending on your current page view.

**Comment by mialondon** [comment]
...but at least the single page user would get a 'normal' download experience.

**Comment by edsilv** [comment]
![image](https://cloud.githubusercontent.com/assets/1334393/19068590/161f21d0-8a1b-11e6-913b-32c1379ace13.png)

Implemented on the dev branch.

To enable in config: `modules > downloadDialogue > options > optionsExplanatoryTextEnabled` = `true`

**Comment by mialondon** [comment]
Thanks @edsilv ! My only quibbled (sorry) is that they actually open in new tabs but I can see that we can change that in config (wholeImagesHighResExplanation) and probably should adjust it for other download options while we're at it.
