### ISSUE TITLE
prevButton and nextButton never disabled

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#362]
Source: 
```
src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
```

The methods "isFirstCanvas" and "isLastCanvas" need a canvasIndex as argument, but
do not get one, and therefore always return false. Result: prevButton and nextButton are
never disabled. I'm not sure how to retrieve that canvasIndex.

**Comment by edsilv** [comment]
fixed

**Comment by nicolasfranck** [comment]
Nice!
