### ISSUE TITLE
Simplified 'download selection' view

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#363]
Our usability tests showed that people are confused by the extraneous buttons available in the Download selection screen. 

For example, in this screenshot, the 'Search within' field draws the eye. Some people also expected the image/page indicator to change as they selected or deselected pages. There's no obvious way to close the download process in this current screen.

![download selection screen bltesters_azurewebsites_net](https://cloud.githubusercontent.com/assets/380763/17667203/ce631310-62fb-11e6-9d37-59324a957a6e.png)

A gallery component would present a simplified screen, with dedicated controls to close the window and ideally headings/backgrounds like those on other dialogue boxes.
![download selection screen annotated](https://cloud.githubusercontent.com/assets/380763/17667253/0dc33508-62fc-11e6-8625-e34c35b2bf0c.png)

@edsilv estimates five days' work to make a gallery component so the "download selection" option could move to a separate dialogue.

**Comment by mialondon** [comment]
BL TFS link: Product Backlog Item 13649:Update Download selection dialogue to use a gallery component for better UX

**Comment by mialondon** [comment]
Download selection - there's no visible way to cancel the process. People click around randomly until they get out of that mode. Needs a 'close' or 'cancel' button.

**Comment by mialondon** [comment]
@edsilv what does the 'close' button look like to get out of the gallery component, and does it need to differ between the 'download selection' version and the thumbnail view version?

**Comment by edsilv** [comment]
![image](https://cloud.githubusercontent.com/assets/1334393/19068317/21f28f48-8a1a-11e6-9348-dcbd055fc537.png)

implemented on the dev branch.

**Comment by edsilv** [comment]
To enable this in config: `modules > downloadDialogue > options > selectionEnabled` = `true`

**Comment by edsilv** [comment]
To listen for the event on the containing page:

```
$(document).bind('seadragonExtension.onMultiSelectionMade', function (event, obj) {
    console.log('seadragonExtension.onMultiSelectionMade', obj);
});
```

**Comment by mialondon** [comment]
@edsilv on http://bltesters.azurewebsites.net/?manifest=http%3A%2F%2Fapi.bl.uk%2Fmetadata%2Fiiif%2Fark%3A%2F81055%2Fvdc_100022545251.0x000002%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=0&z=-1283.2996%2C-187.5%2C5069.5991%2C3750 'Select all' doesn't do anything in Firefox or IE.

**Comment by mialondon** [comment]
@edsilv I don't suppose anything has happened on this since October 2016?

**Comment by m-art-in** [comment]
I confirm, it's still open. To do selections is not possible, so I deactivated this in config.json on my server

**Comment by irv** [comment]
Hi,

This feature does work; it raises an event to the containing page, which you can see in operation at the BL: http://access.bl.uk/item/viewer/ark:/81055/vdc_100022545251.0x000002

I'm afraid you then need some backend service to generate a PDF or a zip file or whatever.

And to answer Mia's question, this has absolutely changed

![image](https://user-images.githubusercontent.com/390869/72079020-155b4980-32f2-11ea-9034-67428a920e5c.png)

**Comment by m-art-in** [comment]
Ah ok, I will have a look. What is the event's name? Do you have some code examples for the server side?

**Comment by edsilv** [comment]
The event is named `multiSelectionMade`. Here's an example of how to listen for it: https://codesandbox.io/s/uv-download-selection-example-4d8rur?file=/index.html
Unfortunately the BL's manifest is broken at the moment - following up with them.

**Comment by edsilv** [comment]
Please see [this UV wiki page for the Multiselection Example](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples).
