### ISSUE TITLE
show selected manifest in index

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#365]
The index tab does not show you which manifest exactly is selected,
neither does it show in which range the viewer is.

**Comment by edsilv** [comment]
This could be a good one to discuss on the community call in order to flesh out a bit.

**Comment by edsilv** [comment]
Related? https://github.com/UniversalViewer/universalviewer/issues/302

**Comment by nicolasfranck** [comment]
Yes indeed ;-)

**Comment by edsilv** [comment]
closing as duplicate of #302
