### ISSUE TITLE
show labels next to buttons in header panel

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#366]
The labels in the headerPanel (one-up, two-up, settings) do not have a label
attached to it. In the footerPanel, this is configurable with the option "miniseButtons".
This would explain the purpose of these buttons to the end user.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
