### ISSUE TITLE
Passing search parameters through to the viewer

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#367]
Has anyone attempted to pass search parameters through to a viewer? 

Both our Places of Wales site and Collections Viewer query solR to produce search results but we need to be able to connect the two.

Each PoW result has a link to a primary source (an apportionment and a map) which when displayed need to zoom in and highlight that particular entry or location. We have previously created links where the user can go directly to a page but we are struggling with the other parameters.

The annotation, page number, pixel co-ordinates are all in the database but we need to pass all of this information over from the site search to the viewer so the user doesn't have to redo their search in the viewer itself. Is there any documentation available to help us do this? 

PoW site (in development):  http://places.library.wales/ 
(ID: cynefin / PW: cynefin, Search for 'cae')

Collections Viewer - search example:  https://github.com/UniversalViewer/universalviewer/issues/166

We can provide more detailed information if needed.

**Comment by glenrobson** [comment]
From slack discussion possible parameters:

 * h - highlight a search term
 * cv - canvas number (1 to number of canvases - need to add to solr).
 * z - viewport - would have to work out how to transform from image coords to viewport coords or wait for the following development: 

​https://github.com/UniversalViewer/universalviewer/issues/336

Example highlight term: http://wellcomelibrary.org/item/b18031407#?h=tangled+bank 

In theory the following link should open the correct page with the text highlighted but not zoomed into the text:

​http://universalviewer.io/?manifest=http%3A%2F%2Fdev.llgc.org.uk%2Fiiif%2Fsearch%2F4546256.json#?cv=7&h=cae

**Comment by tomcrane** [comment]
Glen beat me to it...

**Comment by jronallo** [comment]
Note also this related issue regarding "h": https://github.com/UniversalViewer/universalviewer/issues/349

**Comment by glenrobson** [comment]
So now the search service is working the following works:

http://universalviewer.io/?manifest=http%3A%2F%2Fdev.llgc.org.uk%2Fiiif%2Fsearch%2F4546256.json#?cv=11&h=cae

(Changing page to 11 as page 7 had results on a different results page).

**Comment by glenrobson** [comment]
We've also been testing maps and the following link does work:

http://universalviewer.io/?manifest=http%3A%2F%2Fdev.llgc.org.uk%2Fiiif%2Fsearch%2F4623730.json#?cv=0&h=A20&c=0&m=0&s=0

but without zooming into the result its impossible to see where the highlight box is. @tomcrane is this part of Ed's highlighting work at all?

Cheers

Glen

**Comment by tomcrane** [comment]
@glenrobson - that's a really useful example, thanks. What should the UV do? It needs to draw the user's attention to the highlight, so it needs to zoom in far enough for the highlight to be visible. This could be configured as a certain proportion of the viewport (e.g., shortest dimension of the highlight is 5% of the equivalent viewport dimension). 

There may be more than one hit on the same canvas, and zooming in enough to see the first one might hide the others from view. Perhaps the "next result" and "previous result" would pan the viewport within the same canvas to move between adjacent results, using the same sizing logic.

**Comment by LlGC-szw** [comment]
Panning the viewport to visibly navigate between the results would definitely work.

**Comment by LlGC-szw** [comment]
Article navigation technique on our newspapers site (with openseadragon) http://newspapers.library.wales/view/3063140/3063142/23/drunken%20women

**Comment by jronallo** [comment]
PDF viewers will pan the viewport to move through next/previous search results, so that is one way.

I like the map example too because I have the same thing when I have a large page in a smallish viewer with small text in the original that is zoomed out. My initial search may just be to help me find the portion of the page rather than wanting to zoom into results. Without looking closely it seems as if there are no results because the scaled down bounding boxes get to be so slim. It would be nice to add some padding around small bounding boxes so that they are more visible.

**Comment by tomcrane** [comment]
From community call:

Ensure highlight rect is at least a certain proportion of the viewport. Clicking next/prev result should be “the thing you can’t see” - either moving within the zoomed in page, or moving to the next page. Highlight both teardrops if all highlights on both pages are visible.

**Comment by edsilv** [comment]
http://www.dolmenweb.net/viewer/openseadragon/test/demo/fitboundswithconstraints.html

**Comment by LlGC-szw** [comment]
An example of where the two-page view zooms to the first page rather than the result on the right hand page in the view:

Search for 'melyn'

[http://nlw.azurewebsites.net/?manifest=https://damsssl.llgc.org.uk/iiif/2.0/4566425/manifest.json](http://nlw.azurewebsites.net/?manifest=https://damsssl.llgc.org.uk/iiif/2.0/4566425/manifest.json)

hit #2 (p. 71) should hightlight number 42 on the list on the second page.

**Comment by LlGC-szw** [comment]
Feedback on the zoom level today is that it may be too deep. Taking it back slightly will allow the user to see the beginning of the highlighted area, especially when viewing an apportionment (same example link as above).

**Comment by LlGC-dwj** [comment]
Further to Sara's comment above about 'melyn' here's a screenshot I've made that explains (excuse the very poor paint work!)

![highlighting_wrong_location](https://cloud.githubusercontent.com/assets/1083554/20136694/1553d1b4-a66e-11e6-9793-be2d60ddef54.jpg)

Hope this clarifies it further.

**Comment by LlGC-dwj** [comment]
More examples for you,

http://nlw.azurewebsites.net/?manifest=https://damsssl.llgc.org.uk/iiif/2.0/4642022/manifest.json

This has less transcription errors so a good one to test.

--------------

http://nlw.azurewebsites.net/?manifest=http://dev.llgc.org.uk/iiif/search/4623730.json

Possible search term on this: A20
Searching for 'cae' (welsh for field) on this map brings back 830 results

**Comment by LlGC-szw** [comment]
Search result highlighting is now going to the correct page when in two-up view.
