### ISSUE TITLE
URL field on share, embed dialogues triggers on-screen keyboard on devices

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#371]
It would be great if the field was plain text rather than a form field. In testing on tablets, clicking into it brought up the on-screen keyboard, which was an annoyance

**Comment by edsilv** [comment]
This is now solved on the dev branch. The UV detects if a mobile device is being used and renders a link instead that will not navigate when clicked, but can be held to show a "Copy link" dialogue.
