### ISSUE TITLE
Collections manifest - load issue in Safari

### ISSUE THREAD

**Issue by brutaldigital** [UniversalViewer/universalviewer#372]
I'm trying to load a long collections manifest in UV (circa 100 individual canvases) but am getting an infinite page load when using Safari. If I reduce the number of items it loads correctly, and the full manifest works in all other browsers. 

Collection manifest here: https://raw.githubusercontent.com/paulmelloncentre/manifest/master/doddington/collection/full

Any ideas?

**Comment by edsilv** [comment]
Sorry I missed this one, did you get to the bottom of it?
I haven't run into this myself.

**Comment by brutaldigital** [comment]
Didn't get any further, but that manifest now loads correctly.
