### ISSUE TITLE
Master branch out of sync with Manifesto and Utils

### ISSUE THREAD

**Issue by Edminsson** [UniversalViewer/universalviewer#373]
I get some typescript errors when I run the build task in the master branch after running the sync task. It seems to be related with changes in the Utils master branch and in the dev branch of Manifesto. Should UV's master branch have a dependency to Manifesto's dev branch? Should the UV's dev branch have a dependency to Utils dev branch?

**Comment by edsilv** [comment]
The UV dev branch has had a lot of work the last few months. I should merge it to master and merge manifesto's dev branch and point to that instead.

Is your fork of the UV building?

**Comment by Edminsson** [comment]
That would be great! We (Riksarkivet) took a break from UV development, but we are back again and have started to update our forks. We could see that there has been a lot of changes. You've been working hard.

**Comment by edsilv** [comment]
Have merged dev to master. Dependencies on manifesto and manifold's dev branches have also been changed to point to their respective master branches.

**Comment by Edminsson** [comment]
Excellent! Looking forward to dive into the new code.
