### ISSUE TITLE
Table of contents (ranges) not showing for manifest

### ISSUE THREAD

**Issue by glenrobson** [UniversalViewer/universalviewer#375]
Hi,

Do you know why the ranges aren't showing in the UV for the following manifest:

http://dams.llgc.org.uk/iiif/2.0/4642022/manifest.json

It works OK in Mirador:

http://www.llgc.org.uk/llyfrycofio

and I can't see any errors in the browser console and as far as I can tell the manifest looks OK. I've tested it in our viewer:

http://viewer.library.wales/4642022

and in the universalviewer.io:

universalviewer.io/?manifest=http%3A%2F%2Fdams.llgc.org.uk%2Fiiif%2F2.0%2F4642022%2Fmanifest.json#

Thanks for your help

Glen

**Comment by irv** [comment]
It doesn't seem to like you having one huge "table of contents" range with loads of sub ranges.
If I remove that from the manifest but leave the rest (after removing the "on" property where necessary), they display. I'm only guessing, but it could be because it does some kind of canvas de-duplication across ranges, then removes empty ranges. I'm too lazy to investigate properly and JavaScript is evil :)

**Comment by glenrobson** [comment]
Thanks Andy, that gives me a place to start. As its a nested table of contents I think I repeat all of the canvases which are part of a particularly level so there will be a lot of duplication.

**Comment by glenrobson** [comment]
Created three versions of the manifest one which has no duplication and canvases only at the leaf level:

http://dev.llgc.org.uk/iiif/range/4642022-range-no-dup.json

and a manifest with the top level containing no canvases but all other levels with canvases and neither seems to work for me.

http://dev.llgc.org.uk/iiif/range/4642022-range-no-top.json

Removing the top level range completely but leaving the duplicated canvases at each level gives  the following which does show the tree:

http://dev.llgc.org.uk/iiif/range/4642022-no-root.json

but its flat without the hierarchy. Also using this in Mirador produces an empty table of contents. 

Thanks for your help

Glen

**Comment by irv** [comment]
I have to admit it's never occurred to me to do it that way, and wasn't aware that's how it works in Mirador! 

Reading the 2.1 spec;

> In order to present a table of the different ranges to allow a user to select one, every range must have a label and the top most range in the table should have a viewingHint with the value “top”. A range that is the top of a hierarchy does not need to list all of the canvases in the sequence, and should only give the list of ranges below it. Ranges may also have any of the other properties defined in this specification, including the startCanvas relationship to the first canvas within the range to start with, if it is not the first listed in canvases or members.

admittedly it's "should only give the list of ranges below it", so i would have expected your second example to be OK.

**Comment by edsilv** [comment]
This is due to ranges using the `within` property. Now recommended to use the `members` property. @glenrobson is updating manifests.

**Comment by glenrobson** [comment]
I've redone this using members rather than within:

http://dev.llgc.org.uk/iiif/range/4642022-topdown.json

but unfortunately I'm now getting type errors from:

http://nlw.azurewebsites.net/?manifest=http%3A%2F%2Fdev.llgc.org.uk%2Fiiif%2Frange%2F4642022-topdown.json&locale=en-GB#

it works OK in mirador:

http://dev.llgc.org.uk/iiif/mirador2/bor.html#3ea581a8-2705-4d66-82e1-3d57e591fcaa

Thanks

Glen

**Comment by edsilv** [comment]
@glenrobson There appear to be 3 ranges that are being referenced but do not exist:

http://dams.llgc.org.uk/iiif/2.0/4642022/range/2-2-0
http://dams.llgc.org.uk/iiif/2.0/4642022/range/54-5-0
http://dams.llgc.org.uk/iiif/2.0/4642022/range/100-2-0

I've updated manifesto so that it does a console.warn in this eventuality. Mirador must be failing silently?
