### ISSUE TITLE
Allow quote marks in the search box

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#377]
The BL want to enable simple 'exact phrase' searches to a) intuitively group terms separated by whitespaces into a single search phrase and b) allow people to workaround stemming.

However, users can't currently enter ' or " into the search box. (However, they do seem to be added to the search term?)

Internal 'see also': Product Backlog Item 13401

**Comment by mialondon** [comment]
An example test - I want to search for 'shipbuilding conference' on http://bltesters.azurewebsites.net/?manifest=http%3A%2F%2Fapi.bl.uk%2Fmetadata%2Fiiif%2Fark%3A%2F81055%2Fvdc_100022545251.0x000002%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=4&z=1042.0346%2C1645.9275%2C1396.5246%2C1033.0141 and only get back references to the exact phrase, not to either of the individual words.

**Comment by edsilv** [comment]
Fixed on dev branch.
