### ISSUE TITLE
Switching language breaks the Full Screen Option

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#38]
I've deployed the latest version of the Universal Viewer but when I switch languages the Full Screen function breaks. Nothing flags up in the console log and all the other functions like embed and the switch between single page view and two page view still works.
I've tested this in Chrome, Firefox an IE and get the same result. It's also been tested with the original language in English switching to Welsh, and vice versa.

Have you had anything similar happen?

Thanks,
Dylan

**Comment by edsilv** [comment]
I've been looking at this the last couple of days. I've recently pushed to the NLW demo site:

http://nlw.azurewebsites.net

Should be fixed now if you do a pull.

Also, you'll notice new `master.bat` and `nlw.bat` files in the root. I'm creating one of these for each branch of the UV. This runs a bunch of git commands to ensure that all submodules are up to date and checked out on the correct branch. You can run them to switch branch, or refresh the current branch.

Unfortunately these are windows-specific files, but I'd welcome a shell script equivalent!
