### ISSUE TITLE
Stickiness when panning around zoomed images

### ISSUE THREAD

**Issue by emmastanford** [UniversalViewer/universalviewer#381]
If you zoom in on an image in the viewer and then pan around it by dragging the image with your mouse, the image tends to "stick" to the mouse, making it impossible to continue to pan. (Panning around using the inset thumbnail works fine, but everyone seems to want to pan around by dragging the main image.)

I was able to reproduce this reliably using this manifest: http://iiif.bodleian.ox.ac.uk/iiif/manifest/1159e59e-b06e-44d9-bb0a-b5127a5b36fe.json (The fact that the image thumbnails don't show up in the index is a separate problem, which we've addressed in our installation of the viewer, but the panning problem persists.)

Apologies if this issue has already been raised, but I couldn't find it anywhere.

**Comment by edsilv** [comment]
Is this happening when you drag outside of the UV bounds? There was an issue with OpenSeadragon regarding dragging outside of an iframe, but it looks like @bazer may have fixed it:

https://github.com/openseadragon/openseadragon/pull/790

This will only work if the UV is being hosted from the same domain as the containing page though. The current latest UV code is using v2.2.1 of OpenSeadragon and it appears to be fixed when dragging outside of the frame.

http://universalviewer.io/examples

**Comment by edsilv** [comment]
Closing as I think this just requires updating your UV
