### ISSUE TITLE
Change the background color

### ISSUE THREAD

**Issue by MinOZMel** [UniversalViewer/universalviewer#382]
Hi Guys,

I changed the background color in embed code, but it doesn't make any difference in html page. Can anyone help me with it?

Cheers

**Comment by edsilv** [comment]
Hi,

The background on the embed div is really only there so the loading spinner gif has something to appear above. You'll need to look at creating your own custom theme. I have a tutorial here:

https://universalviewer.gitbooks.io/custom-themes/content/theme.html
