### ISSUE TITLE
Implement IIIF Auth 1.0

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#386]
The UV's current auth implementation mixes support for the login profile (from IIIF Auth <0.9.3) with additional support for two UV custom profiles, "clickthrough" and "restricted". In each case the UV's behaviour is different. These two use cases came out of Wellcome Library requirements.

However, similar requirements were provided by other institutions, and these different behaviours are now synthesised into the four interaction patterns (each identified by a profile) in the new 0.9.3+ Auth spec:
- Login (just like UV's existing login - used for "clinical" at Wellcome)
  - UV current: "profile": "http://iiif.io/api/auth/0/login"
  - UV new: "profile": "http://iiif.io/api/auth/0/login" **(i.e., the SAME)**
- Clickthrough (just like UV's existing clickthrough)
  - UV current: "profile": "http://iiif.io/api/auth/0/login/clickthrough"
  - UV new: "profile": "http://iiif.io/api/auth/0/clickthrough" **(different)**
- Kiosk 
  - _(no UV support for this, but it would be simple)_
  - UV new: "profile": "http://iiif.io/api/auth/0/kiosk"
- External (just like UV's existing **restricted**)
  - UV current: "profile": "http://iiif.io/api/auth/0/login/restricted"
  - UV new: "profile": "http://iiif.io/api/auth/0/external" **(note difference)**

I was about to make some changes to Manifesto, Manifold and the UV to add support for the new spec. There is not much to change because the UV's implementation is essentially a draft for the new auth spec. The quick code changes would be :
- (Don't bother implementing Kiosk yet)
- Adding the new profiles to the recognised lists of service profiles
- Renaming restricted to external throughout codebase
- Adding an additional parameter "origin" to the query string for both access cookie (login) service calls and token service calls - the value is the origin of the app.js code (i.e., the origin of the window the postMessage must call - the UV already knows this)
- Making use of strings provided in the service descriptions

On the last point - there is now more than just `label` and `description`, there is an explicit `header` to use for dialogue boxes, there is `confirmLabel` to use as the call-to-action button text, there is `failureHeader` and `failureDescription` to use for the "your login was unsuccessful..." message. The UV can still use strings from its config but should use the provided service strings (which can be JSON-LD value objects in multiple languages just like other metadata) in preference. This allows publishers greater control over messaging in dialogue boxes.

However, looking at the code I think the Manifesto model should change to reflect the terms used in the Auth spec, now that there is no need for UV-specific extensions, otherwise it will be confusing to developers trying to match the spec to the implementation. It will also be easier to add new interaction patterns in the future without adding more and more parameters to function calls.

https://github.com/viewdir/manifesto/blob/master/src/IExternalResource.ts

Rather than IExternalResource having loginService, clickthroughService, restrictedService, tokenService and logoutService, it should I think have a new single property:

`accessCookieService: IAccessCookieService[]`

...where IAccessCookieService is an IService with extra bits (like the string fields, its own token service and logout service). Although there will usually be only one, it's an array because in theory an external resource could assert more than one access cookie service. The auth code that orchestrates the flow (chain of promises) can look at the IAccessCookieService's profile (probably via a helper function isClickthrough() etc) to decide what to do just as it currently tests each of loginService, clickthroughService etc on IExternalResource to see whether they are null or not.

Access Cookie is how the spec describes the service formerly known as the login service, to allow for the fact that "logging in" is just one kind of interaction a user might perform to acquire an access token - the job of the service is to acquire a cookie, not necessarily to type a username and password. There are many ways to acquire a cookie, only one of which is "login".

The logic in the chain of promises would still be pretty much the same as it is now, but the introduction of a new type would make it easier to understand and maintain in future (adding Kiosk doesn't introduce a new property to externalResource, just a new flow logic).

**The order of release**

The UV shouldn't use the new auth profiles and behaviour by default until existing server implementations (Wellcome, DLCS, BL?) have updated - but there can be a branch of the UV for testing that does this. I have a server side implementation of 0.9.3 for Wellcome content available for testing. While servers (Wellcome and DLCS at least) will need to support old and new Auth models (to allow for UV instances in the wild) for a short period, the UV can just be deployed with the new model once we know servers are live with support.

I know Andy Irving (not in this gh org) has a server implementation, anyone else? I'll ask on Slack.

**Comment by irv** [comment]
:+1:

**Comment by tomcrane** [comment]
(renamed title of this issue - same description applies)
