### ISSUE TITLE
download option "currentViewAsJpg" does not honour maxWidth/maxHeight

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#387]
If I add maxWidth and maxHeight to info.json,
then this is honoured by both download options wholeImageHighRes and wholeImageLowRes
(who use the method getCanvasComputedDimensions to limit their width and height),
but not by currentViewAsJpg where the maximum dimensions are not taken into account.

**Comment by nicolasfranck** [comment]
never mind, I was using older code. It is working correctly in the current dev branch.

**Comment by nicolasfranck** [comment]
https://github.com/UniversalViewer/universalviewer/pull/389

**Comment by edsilv** [comment]
merged

**Comment by edsilv** [comment]
merged

**Comment by nicolasfranck** [comment]
https://github.com/UniversalViewer/universalviewer/pull/392
