### ISSUE TITLE
Adding extension dependency with jQuery dependency

### ISSUE THREAD

**Issue by Edminsson** [UniversalViewer/universalviewer#388]
We are adding constrast/brightness controls to our UV fork. For this we are using openseadragon-filtering and rangesliderjs as extension dependencies. 
Rangesliderjs has a dependency on jQuery, and tries to require jquery if it detects requirejs.
jQuery is loaded in app.html in a script element before requirejs which should mean that jquery does not get defined and requirejs is not aware that its already loaded.
So when rangeslider gets loaded it can't require jquery.
We've solved the problem by adding this to the start of app.ts:
```
define('jquery', [], function() {
    return jQuery;
}); 
```
Which is basically the definition in jQuery that never got executed.
We could also have declared a path to jQuery in require.config but then jQuery would get loaded twice.

**Comment by edsilv** [comment]
Sounds ok. I'll accept a pull request for that.

**Comment by Edminsson** [comment]
great. Do you think the contrast/brightness control would be of any interest to you?

**Comment by edsilv** [comment]
Potentially. I think a pull request for the extra `define` statement would be good for now. Perhaps when you have something to demo we could discuss on the community call?

**Comment by ra-magnus-welander** [comment]
I could demo something. When's the next community call?

**Comment by edsilv** [comment]
Thursday 13th
