### ISSUE TITLE
Viewing multiple PDFs, clicking thumbnail doesn't switch files

### ISSUE THREAD

**Issue by WaltRiceJr** [UniversalViewer/universalviewer#394]
When I'm viewing multiple PDF files, I can't click on a thumbnail and switch to another one. 

In the Extension.ts file for the pdf extension, it seems canvasIndex is being provided as the full thumb object, instead of the index number.

```
        $.subscribe(BaseCommands.THUMB_SELECTED, (e, canvasIndex: number) => {
            this.viewCanvas(canvasIndex);
        });
```

I'm mucking in Javascript, not in your source files, but changing this to `n.viewCanvas(t.index)` seems to fix the issue without affecting other things.

**Comment by edsilv** [comment]
Yep, using the thumb.index sounds like a good solution. I'd accept a pull request for that in the Extension.ts file. Would be useful to have that manifest URL for reference - assuming it's permanently available somewhere.

**Comment by WaltRiceJr** [comment]
Manifest URL: http://omeka.wabcphilly.org/items/presentation/32/manifest
Main URL: http://omeka.wabcphilly.org/items/show/32

**Comment by edsilv** [comment]
fixed by: https://github.com/UniversalViewer/universalviewer/pull/398
