### ISSUE TITLE
Error: Load timeout for modules: openseadragon.min

### ISSUE THREAD

**Issue by jronallo** [UniversalViewer/universalviewer#395]
I'm getting frequent errors like this. Is there any way to set a longer timeout or to retry in the case of failures?

**Comment by edsilv** [comment]
I haven't seen one of these errors for a while. You can increase the timeout in requirejs:

http://stackoverflow.com/questions/14511036/how-to-change-module-timeout-in-require-js

Here's where the UV is loading deps for the current extension:

https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-shared-module/BaseExtension.ts#L602

Not sure exactly how to achieve a different timeout programmatically...

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
