### ISSUE TITLE
Create ambient i18n setting "currentLocalisation"

### ISSUE THREAD

**Issue by fractos** [UniversalViewer/universalviewer#4]
Viewer has an “ambient”  i18n setting – say, currentLocalisation – which determines two things:
1)	Which chrome file to load and use for labels
2)	Which language-tagged metadata values to display from a manifest, where multiple languages are available (see Appendix 1)
The ambient setting could be a full localisation “en-GB”, or it could be just a language code “en”.

**Comment by tomcrane** [comment]
The exact implementation of this is TBC
