### ISSUE TITLE
Settings.ts

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#40]
The options.pagingEnabled config property currently determines paging state on load. Users may want to disable paging altogether. This should be set with the options.pagingEnabled property.

There should be an additional options.settings object in the config that contains any settings that can be changed at runtime in the settings dialogue.

A Settings class should be created in the root of the project, which is inherited in each extension to add extension-specific settings.

The config.json options would then look like this:

```
"options":
{
    "theme": "uv-default-theme",
    "leftPanelEnabled": true,
    "rightPanelEnabled": true,
    "overrideFullScreen": false,
    "pagingEnabled": true,
    "searchWithinEnabled": true,
    "settings": {
        "pagingEnabled": true,
        "preserveViewport": false
    }
},
```

options.pagingEnabled controls whether paging is possible. options.settings.pagingEnabled controls whether (if possible) paging is on or off by default.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive (discussed on 28/09/2023 Community Call)
