### ISSUE TITLE
Preserve Zoom and images of different sizes

### ISSUE THREAD

**Issue by Edminsson** [UniversalViewer/universalviewer#404]
We've had some issues with Preserve Zoom when browsing images. It does not behave the way it used to and zoom preserving works badly when the images have very different sizes.
When calling viewer.viewport.getBounds(true) the bounds are no longer in Viewport Coordinates, this can also be observed in the z-parameter in the querystring of the url.
I believe there is an error when calling addTiledImage. The width or height in the options parameter should be in Viewport Coordinates which I think it is not. I've also tried to remove the width from the options parameter completely and things seem to work better.

**Comment by Edminsson** [comment]
It seems that the addTiledImage can be called that way https://github.com/openseadragon/openseadragon/issues/1053
We have this issue with a serie of images that have different sizes. We zoom one of the images and drag the image so only the upper right corner is visible. We then browse to another image. What happens is that fitBound is called with the coordinates of the previous image but the new image has a different size and when the coordinates are applied to the new image its rendered outside the viewport. What also happens in our case is that the tile-drawn event never gets fired so the spinner never gets hidden.
This does not happen when using viewport coordinates because it's not pixel based.

**Comment by Edminsson** [comment]
We've solved the problem by simply calling fitBoundsWithConstraints instead.

**Comment by Edminsson** [comment]
Sorry for misunderstanding the coordinate systems in openseadragon. Would you, nevertheless be interested in a pull request for fitBoundsWithConstraints? Shouldn't the image always be within the configured constraints?

**Comment by edsilv** [comment]
I recently changed the coordinate system to use image coords instead of viewport coords. 

https://github.com/openseadragon/openseadragon/issues/975

I think adding a call to fitBoundsWithConstraints on load sounds ok. Yep, please create a PR.

**Comment by edsilv** [comment]
Merged https://github.com/UniversalViewer/universalviewer/pull/408
