### ISSUE TITLE
'Select all' checkbox doesn't select anything

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#406]
Tested on http://bltesters.azurewebsites.net/?manifest=http%3A%2F%2Fapi.bl.uk%2Fmetadata%2Fiiif%2Fark%3A%2F81055%2Fvdc_100022545251.0x000002%2Fmanifest.json&locale=en-GB#?c=0&m=0&s=0&cv=0&z=-1029.8196%2C0%2C4562.6392%2C3375

The 'select all' checkbox on the Select Pages for Download dialogue doesn't change the selection.

However, if you select three or more pages, then click it, it does select all.

**Comment by edsilv** [comment]
works for me in chrome?

https://www.youtube.com/watch?v=lLGso3M1fkU

**Comment by mialondon** [comment]
It hasn't been in Firefox, and someone else just said it doesn't in Safari.

**Comment by mialondon** [comment]
@edsilv were you selecting the name or the check box itself?

**Comment by edsilv** [comment]
ah, clicking on the box itself doesn't work. ok will take a look

**Comment by edsilv** [comment]
fixed on dev
