### ISSUE TITLE
Show Gallery shows blank area

### ISSUE THREAD

**Issue by BinaryRoads** [UniversalViewer/universalviewer#407]
If the left panel is Collapsed and the Galery button is pushed in the right upper corner. 
The Left panel stretches the viewer with a blank area. 
After clicking on the arrow for hiding, it suddenly shows the Galery. 

I am using version 1.8.36 of the Universal Viewer.

**Comment by nicolasfranck** [comment]
Same issue here: https://github.com/UniversalViewer/universalviewer/issues/369

**Comment by edsilv** [comment]
Have added this to https://github.com/UniversalViewer/universalviewer/projects/1

**Comment by edsilv** [comment]
That's now fixed on the dev branch.

**Comment by nicolasfranck** [comment]
src/modules/uv-multiselectdialogue-module/MultiSelectDialogue.js now fails with this error:
```
  app.js:6 Uncaught TypeError: this.component.on is not a function
```
and therefore the UV does not load at all

**Comment by edsilv** [comment]
@nicolasfranck Try dev now. You'll need to do an `npm update` and `grunt sync`

**Comment by nicolasfranck** [comment]
excellent thanks!
