### ISSUE TITLE
Problem while running viewer for one file (created to full understand data model, package configuration and deep zoom image)

### ISSUE THREAD

**Issue by antimoroma** [UniversalViewer/universalviewer#41]
I have write same posto to 
https://groups.google.com/forum/?hl=en#!topic/universalviewer/YWiOscbr4QI
Don't know if better to post here or in google groups? If it's better to use google group please delete or close this issue.

I'm trying to create a sample with only one image using the web server available in the sample.

So this are the step:
* Build the viewer as per https://github.com/UniversalViewer/universalviewer 
* First time Setup
  *Grunt Serve -> example work fine
* Create a TIF deep zoom image with Deep Zoom Composer
* In the example directory create one directory (deepzoomimage) and put in the attached files and
dzc_output_files (directory generated from Deep zoom Composer)

Call the file myindex.html from the browser 
Nothing appear in the viewer and in Chrome console appear:

Uncaught TypeError: Cannot read property 'appendChild' of nullJSONEditor.init 
@ jsoneditor.js:225JSONEditor 
@ jsoneditor.js:203createEditor 
@ examples.js:849(anonymous function) 
@ examples.js:821jQuery.Callbacks.fire 
@ jquery.js:3143jQuery.Callbacks.self.fireWith 
@ jquery.js:3255jQuery.extend.ready 
@ jquery.js:3467completed 
@ jquery.js:3498

I could'nt attach here the file i have created but i could  expose the web server to do some test, or other debug as requested (i'm not a javascript expert but i'm a programmer)

Thanks in advance for any help you are able to provide.

**Comment by edsilv** [comment]
Reposted from: https://mail.google.com/mail/u/0/#inbox/14ce70a73306480e

The UV consumes IIIF Presentation API manifests via the data-uri attribute. The dzc_output.js file won't work I'm afraid. It also uses the IIIF Image API to make tile requests.

If you take a look at this example manifest:

http://wellcomelibrary.org/iiif/b18035723/manifest

(taken from the default "Wunder der Vererbung" example here: http://universalviewer.azurewebsites.net)

Then look at the first item in the "canvases" array. This has a service with an @id pointing to:

http://wellcomelibrary.org/iiif-img/b18035723-0/ff2085d5-a9c7-412e-9dbe-dda87712228d

If you append "info.json" to this url you can see the file that OpenSeadragon (the zooming component of the UV) is requesting:

http://wellcomelibrary.org/iiif-img/b18035723-0/ff2085d5-a9c7-412e-9dbe-dda87712228d/info.json

This lets OpenSeadragon know where to request the tiles, e.g:

http://wellcomelibrary.org/iiif-img/b18035723-0/ff2085d5-a9c7-412e-9dbe-dda87712228d/2048,1024,512,512/256,/0/default.jpg

You can see that the IIIF Image API parameters for region (2048,1024,512,512), size (256,), rotation (0), quality (default), and format (jpg) are being appended to this url.


There currently (as far as we know) isn't a tool that you can use to convert the deep zoom assets you've generated into an info.json file that will work as described above.

My colleague Tom has asked a question regarding this on the iiif-discuss forum:

https://groups.google.com/forum/#!topic/iiif-discuss/qgCm53Ez9mM

This would be a very useful tool for users such as yourself who want to consume IIIF manifests using static files.


In the meantime I suggest perhaps trying out the OpenSeadragon DZI examples here: https://openseadragon.github.io/examples/tilesource-dzi/

**Comment by antimoroma** [comment]
Thank you for all the detail.

Actually we have an IIPImage server configure on a Linux Ubuntu 12.04 with an IIPMooviewer client.
I was using static files only to create a simple environment to understand how to configure the json file  (package , asset), anyway i can use the IIPImage server that support  IIIF Presentation API so this step could be resolved.

I have some question, sorry to boring you i'm not a subject expert on IIIf and similar thing :) :

1) i see the file http://wellcomelibrary.org/iiif/b18035723/manifest . As far as i understand actually it have to be generated manually ? i see in it some info connected to the "More information" panel , thumbnail and so on that seems to be related to manual generated content.
2)  Given an IIPServer and a correctly generated manifest file, the universal viewer need some other info (file etc) to work fine?
 As far as i understand this specification
 http://player.digirati.co.uk/data-model.html
are not actual i'm right (different product) ?
(I'm confused this file http://player.digirati.co.uk/digitised/britainUnderFire.js is for the old player not an iiif specification file i'm right?)

Did you have any hint on how to produce manifest file.

May be this are "stupid" question but i'm try'ng to understand how to build those file dinamically.

Thank you 

Antimo

**Comment by fractos** [comment]
Hi Antimo,

The information on the player.digirati.co.uk site is prior to the work on the IIIF-compatible player. You should familiarise yourself with the Image and Presentation API documentation at <http://iiif.io> in order to better see how the various bits fit together.

Currently, manifest contents is created on the fly for the iiif requests to Wellcome as it is not a core feature yet.

You might like to join the iiif-discuss newsgroup <https://groups.google.com/forum/#!forum/iiif-discuss> where there are many people who are at this moment talking about and implementing solutions using the IIIF standard.

Hope that helps!

Adam.
