### ISSUE TITLE
Download alternatives sort order seems weird

### ISSUE THREAD

**Issue by ra-magnus-welander** [UniversalViewer/universalviewer#411]
At some time the download alternatives started sorting by size. This seems a bit strange when the order is
* Whole image (lores)
* Current view
* Whole image (hires)

I'd like to see the current view on top always, nevermind how big it is. This is how it used to work. What was the reasoning behind these changes?

![download sort order](https://cloud.githubusercontent.com/assets/14177560/20302960/7ba4292c-ab29-11e6-9b8d-40957231974b.PNG)

**Comment by edsilv** [comment]
This was part of the recent BL work. The reasoning was just that the options should be sorted by size (area).

Current view is also hidden now if you can see over 90% of the image.

cc @mialondon

**Comment by mialondon** [comment]
This was based on really strong user feedback. It might make more sense to split the 'current view' option from the various 'whole image' options and retain the size ordering within that.

**Comment by edsilv** [comment]
Hi, after some discussion on the community call we think splitting current view to be above whole images is the best option. Whole images retain their size ordering.

**Comment by edsilv** [comment]
This appears to be fixed now:

![image](https://user-images.githubusercontent.com/1334393/36984387-aef753b0-208c-11e8-85e6-52e523d82b9a.png)
