### ISSUE TITLE
mentioning too many pages on a single page item

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#412]
We have an example of a single page map on the following link
http://nlw.azurewebsites.net/?manifest=http://dev.llgc.org.uk/iiif/search/4623730.json

As you can see in the bottom left corner it displays **page 252 (380 x 240) of -** is it possible for this to be hidden? As it's a bit misleading with only one page to display.

![page 252](https://cloud.githubusercontent.com/assets/1083554/20344208/b74b5af2-abe9-11e6-9cd6-82445e327270.png)

**Comment by irv** [comment]
if you set searchFooterPanel.positionMarkerEnabled then the teardrop is no longer displayed (and neither is the label), but that's across the board rather then just the case where only one canvas is available

**Comment by edsilv** [comment]
fixed on dev branch.
