### ISSUE TITLE
Show annotation when hovering/clicking on a higlighted search area

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#415]
The ability to hover/click on a highlighted area after searching and view the annotation to allow the viewer to see what has actually been annotated/transcribed for that section of the image.

The manifest is currently structured as follows but there may be more suitable fields to use rather than 'chars' (will ask @glenrobson to comment on this possibility)
{
      "@id": "http:\/\/data.llgc.org.uk\/def\/cynefin\/annotation\/20462373046237313362039972296256",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "||no owner|no occupier|L177|Cae thws & Cae Tynant||6 acres,2 roods,37 perches| 18s  ||"
      },
      "on": "http:\/\/dams.llgc.org.uk\/iiif\/2.0\/4623730\/canvas\/4623731.json#xywh=33620,39972,296,256"
    },
    {
      "@id": "http:\/\/data.llgc.org.uk\/def\/cynefin\/annotation\/20462373046237313310839980320280",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "||no owner|no occupier|L173|Cae mawr & Cae main||6 acres,3 roods,18 perches|\u00a31.5s 6d||"
      },
      "on": "http:\/\/dams.llgc.org.uk\/iiif\/2.0\/4623730\/canvas\/4623731.json#xywh=33108,39980,320,280"
    },
    {
      "@id": "http:\/\/data.llgc.org.uk\/def\/cynefin\/annotation\/20462373046237312503649204264256",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@type": "cnt:ContentAsText",
        "chars": "||no owner|no occupier|G2|Cae Crwyn||22 acres,2 roods,21 perches|\u00a33.3s 6d||"
      },
      "on": "http:\/\/dams.llgc.org.uk\/iiif\/2.0\/4623730\/canvas\/4623731.json#xywh=25036,49204,264,256"
    },

The only similar example of annotations shown on hover that I've found is 

http://bl.ocks.org/mejackreed/2724146adfe91233c74120b9056fba06

**Comment by glenrobson** [comment]
Yes chars is the field to use. Note some of our annotations contain HTML for example:

https://damsssl.llgc.org.uk/iiif/4642022/search?q=aber

the chars in the above example was done by Jenny and if we're going to show the annotations she can change the text to make it more useful.

**Comment by edsilv** [comment]
I've added a title to each overlay rect showing the chars property.
