### ISSUE TITLE
License/licence link isn't hyperlinked

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#419]
e.g. on http://bltesters.azurewebsites.net/#?c=0&m=0&s=0&cv=0&z=-390.1176%2C-196.8333%2C3349.2354%2C3936.6667 https://creativecommons.org/licenses/by-nc/4.0/ isn't hyperlinked. 

The link http://creativecommons.org/publicdomain/mark/1.0/ works on http://universalviewer.io/?manifest=http%3A%2F%2Fv12l-pres1%3A8080%2FR7%2FPresentationService.svc%2Fark%3A%2F81055%2Fvdc_100022589104.0x000002%2Fmanifest.json#?c=0&m=0&s=0&cv=0&z=0.4118%2C0.8098%2C0.213%2C0.1904

@edsilv could it be that it works for http but not https links?

**Comment by DavidWaldock** [comment]
Ed won't be able to see that latter example because its internal to the BL…

D

**Comment by irv** [comment]
Using that same wellcome manifest, universalviewer.io seems to make it a hyperlink whereas bltesters does not: http://universalviewer.io/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest#?c=0&m=0&s=0&cv=0&z=-1.8189%2C-0.0766%2C4.6379%2C1.5324

**Comment by mialondon** [comment]
And it's not a link on http://access.bl.uk/item/viewer/ark:/81055/vdc_100000041309.0x000002#?#loaded&c=0&m=0&s=0&cv=18&z=2404.8075%2C1354.0698%2C930.1735%2C1151.6434

**Comment by mialondon** [comment]
@edsilv live example here http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589022.0x000002#?c=0&m=0&s=0&cv=4&z=1455.9054%2C511.9171%2C696.6068%2C1239.2673

**Comment by edsilv** [comment]
https://github.com/viewdir/iiif-metadata-component/issues/3

**Comment by edsilv** [comment]
Fixed on dev branch.
