### ISSUE TITLE
'Share' dialogue provides different link than location bar

### ISSUE THREAD

**Issue by mialondon** [UniversalViewer/universalviewer#421]
I noticed that links copied from the Share URL box don't include the same zoom levels as those in the browser location bar.

e.g. http://access.bl.uk/item/viewer/ark:/81055/vdc_100000041309.0x000002#?c=0&m=0&s=0&cv=23&z=275.0597%2C941.1613%2C1200.0409%2C1497.4148&r=90

http://access.bl.uk/item/viewer/ark:/81055/vdc_100000041309.0x000002#?c=0&m=0&s=0&cv=23&z=223.9321%2C455.4253%2C1187.8852%2C2587.5327&r=90

**Comment by edsilv** [comment]
related? https://github.com/UniversalViewer/universalviewer/issues/426

**Comment by mialondon** [comment]
@edsilv I reckon so

**Comment by edsilv** [comment]
Fixed on dev branch.
