### ISSUE TITLE
Make the embed code a textarea

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#422]
https://github.com/UniversalViewer/universalviewer/pull/401

This will allow it to be larger if needed using the theme.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing since #401 is fixed
