### ISSUE TITLE
Inconsistent download menu behavior

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#425]
On the latest dev code, there seem to be a couple of problems with the download menu (tested with the Villanova "Bride of the Tomb" manifest):

- When in 2-up mode, the "whole images" option appears when two pages are visible in the screen, but does not appear when only one page is visible (i.e. the first page). It seems there should be a singular "whole image" option to mirror the plural "whole images" option.

- There used to be a message provided in the download menu when in 2-up mode to indicate that more options were available in 1-up mode. This appears to have gone away, but it is still needed, for example when a manifest uses renderings to provide alternate formats of individual pages (like the OCR, etc., in the Bride of the Tomb example).

**Comment by edsilv** [comment]
@mialondon

What is the thinking here? Should we show the one-up options when a single page is visible in two-up mode, or bring back the "switch to one-up for more options" message?

**Comment by mialondon** [comment]
@edsilv I still think users should have the same access to download options from either view, so if we're stuck with a compromise for now, making the 'you're viewing a single page even though you're actually in double page mode' experience more consistent with 'you're viewing a single page in single page mode' and offer the one-up options when there's only one page shown.
