### ISSUE TITLE
MP4 not playing 

### ISSUE THREAD

**Issue by sophiedixon** [UniversalViewer/universalviewer#429]
I'm trying to load an mp4 from Omeka using Chrome on a Mac. Omeka's built in player works but in the UV I can just see a spinner.

**Comment by edsilv** [comment]
Here are Amazon's default mp4 encoding settings:

![mp4-export-settings](https://cloud.githubusercontent.com/assets/1334393/21752791/9eac0606-d5d6-11e6-8548-b9370d2a332f.png)

Does using these make a difference?

**Comment by sophiedixon** [comment]
Thank you, that seems to have worked. The only settings I changed were the Bit Rate - for that I used the default settings in Adobe Premiere.
