### ISSUE TITLE
Browser's native PDF viewer opens inside UV

### ISSUE THREAD

**Issue by pfabri** [UniversalViewer/universalviewer#430]
Dear Development team!

## Background ##

I run an Omeka archive portal, for which I'd like to use Universal Viewer as the only viewer. I've installed the UniversalViewer plugin for Omeka, with success.

# Problem #

## Expected Behaviour ##

When the user navigates to a page which has a `.pdf` Universal Viewer (and Universal Viewer alone!) should open the pdf file.

## Actual Behaviour ##

Universal Viewer opens, and _inside it_ the browser's native pdf viewer opens as well:

![uvshot](https://cloud.githubusercontent.com/assets/16960025/21741478/21e2bd86-d4d7-11e6-83a0-9ff8b79a90bd.jpg)

## Question ##

How can I prevent the browser's pdf viewer from loading? I'd like to make all my content available for viewing online, but prevent downloading. Once the built-in pdf viewer opens, that itself always provides a download link regardless of the Universal Viewer settings.

The problem persists across multiple browsers. (Tested: Firefox and Ubuntu's built-in browser)

Please help, if you can.

Many thanks in advance!

**Comment by edsilv** [comment]
Apologies for the delayed reply. The UV is using pdf.js to display the file (which is the native viewer for Firefox 19+).  There's a thread here where disabling the download button is discussed: 

http://stackoverflow.com/questions/17547956/how-to-make-pdf-undownloadable-using-pdf-js 

There doesn't seem to be a better option than hiding it with css unfortunately:

https://github.com/mozilla/pdf.js/issues/2611

You could potentially add a rule to a custom theme: https://universalviewer.gitbooks.io/custom-themes/content/

Alternatively, a config option might be better. I think this is something to discuss on a future community call.

**Comment by tomcrane** [comment]
http://stackoverflow.com/questions/39505505/hide-disable-download-button-on-chrome-pdf-viewer suggests that this is not possible.
