### ISSUE TITLE
Show/filter annotations on user

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#432]
The manifest search within now delivers a list of annotations.

But if there is any "annotatedBy" in an annotation, it is ignored, I think?
At least I haven't seen an example of this at work.

Shouldn't it by good to add these:

* when hovering over the annotation, show not only the text, but also the user (in the right corner for example)
* add a facet "annotated by" next to the buttons "previous result" and "next result" to filter. This could easily be select tag to make it more condense. Of course only if there are any users found in the annotations.

I would be glad to help

**Comment by edsilv** [comment]
I'll add this to the next community call agenda.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
