### ISSUE TITLE
Improve canvas level metadata rendering

### ISSUE THREAD

**Issue by azaroth42** [UniversalViewer/universalviewer#434]
The current rendering for canvas level metadata does not include the label, and instead assumes a paged object with static labels of "page 1" and "page 2" if in two-up mode.  For artworks where there is significant information about different views (back of the painting, N/S/E/W of the statue, etc) and even for manuscripts where the digitization was for art historical purposes and only included illuminated folios, this is insufficient.

It would be great if, for each canvas being shown:

- [ ] Canvas label is used instead of "page 1"
- [X] Metadata is displayed
- [ ] Other properties are displayed (description, related, etc)

**Comment by emmastanford** [comment]
Canvas-level metadata now appears (hooray!) but it's way at the bottom of the metadata panel underneath all the object-level metadata. Is it possible to configure this to appear higher up?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
