### ISSUE TITLE
Profile in info.json and download of images

### ISSUE THREAD

**Issue by Daniel-KM** [UniversalViewer/universalviewer#438]
Hi,

When the profile section in the info.json is a like that:
```
  "profile" : [
     "http://iiif.io/api/image/2/level2.json",
     {
       "supports" : ["regionByPct","sizeAboveFull"]
     }
  ]
```
or  like that:
```
  "profile" : [
     "http://iiif.io/api/image/2/level2.json", {}
  ]
```
the download of images is available, but when the section is like that: 
```
  "profile" : [
     "http://iiif.io/api/image/2/level2.json"
  ]
```
this is not possible. The level options are not used by default?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by edsilv** [comment]
Do you have a public manifest to test with?

**Comment by Daniel-KM** [comment]
I don't have. This was an issue I saw when I was building the module to integrate UniversalViewer in the new Omeka release (Omeka S). I can rebuild one if needed.
