### ISSUE TITLE
Canvas for pdf media sequences incorrect size

### ISSUE THREAD

**Issue by jenlindner** [UniversalViewer/universalviewer#440]
I'm unable to get the viewer to draw its canvas properly with a pdf media element. Here's a screenshot of the problem, and here's my manifest, and here are all of the page's xhr requests and responses. The viewer reads and responds correctly to all other important data about the pdf - its number of pages, titles, labels, thumbnails, etc. Can you tell me how my manifest needs to be adjusted?

<img width="470" alt="viewer" src="https://cloud.githubusercontent.com/assets/186452/23580677/c0d922ac-00cb-11e7-8098-764bebb26c54.png">

[example_manifest.txt](https://github.com/UniversalViewer/universalviewer/files/818797/example_manifest.txt)

<img width="716" alt="requests" src="https://cloud.githubusercontent.com/assets/186452/23580779/93ab079e-00cd-11e7-8ad8-29bce26e37d4.png">

**Comment by edsilv** [comment]
Hi,

I've added your manifest to this repo:

https://github.com/edsilv/test-manifests/tree/gh-pages

(pdf.json)

Would you mind creating a PR with the pdf itself and I can see if I can reproduce the issue on universalviewer.io?

http://universalviewer.io/examples/?manifest=https%3A%2F%2Fedsilv.github.io%2Ftest-manifests%2Fpdf.json

**Comment by jenlindner** [comment]
Thank you -- I greatly appreciate your help. I will.

**Comment by jenlindner** [comment]
Thanks so much. I'm still having the same problem, but it's clearly not due to the manifest. It must be caused by the front end code in my app. I'm glad to have ruled out so many other factors.
