### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by pamev** [UniversalViewer/universalviewer#442]
I would like to eliminate this part in the URL #?c=0&m=0&s=0&cv=0. This refers to data-collectionindex="0" data-manifestindex="0" data-sequenceindex="0" data-canvasindex="0"
Does anybody know how to do it? Or which file or part of the code should be changed? Thank you!

**Comment by edsilv** [comment]
Hi, if you remove calls to `setParam` this should be disabled:

https://github.com/UniversalViewer/universalviewer/search?utf8=%E2%9C%93&q=setparam

I'm working on a refactor of this at the moment which will abstract responsibility for updating the fragment parameters out of the UV itself. This won't be ready for a while though.

**Comment by pamev** [comment]
Thank you very much. It was very helpful!

**Comment by edsilv** [comment]
Glad to help!
