### ISSUE TITLE
Download link has problem with extensionless URI

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#444]
Wellcome PDFs used to have a .pdf file extension, and the download link would say "Entire file (pdf)"

Now they don't have a file extension, and the download link says:
Entire file (io/file/wellcome/1/38365a65-5dbe-4939-8de3-1d28062ad8f3)

...which is what you get if the extension is defined as whatever string comes after the last index of "."

Example:
http://universalviewer.io/examples/?manifest=http://wellcomelibrary.org/iiif/b16423021/manifest

The UV could maybe not regard it as a file extension if it's longer than a certain number of chars, or contains a "/" (or both). Alternatively it could use the "format" property (application/pdf) although it can't rely on that being there, it's not mandatory (although should be there).

If UV is reworking IxIF could fix this as part of that work.

**Comment by edsilv** [comment]
Now defaults to "Entire File" if it can't find a valid file extension:

http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb16423021%2Fmanifest
