### ISSUE TITLE
two page view is not accessible by keyboard

### ISSUE THREAD

**Issue by hannolans** [UniversalViewer/universalviewer#459]
The two page view is not accessible by keyboard.

**Comment by edsilv** [comment]
I can't reproduce this. I'm able to tab onto the 1/2-up icons and press enter to change the view.

**Comment by hannolans** [comment]
I tested again and you can tab to it,  the real problem is that there is no visible focus when you arrive on the single or double page button.

**Comment by mejackreed** [comment]
I think this is only happening in Firefox. Perhaps similar to the issue outlined in #461. Seems like there needs to be some work on Firefox focus.
