### ISSUE TITLE
Accept IIIF-Discovery pattern as hash parameter for deep linking

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#462]
You can use the UV's hash params to deep link to a particular region of a particular canvas within a manifest.

http://universalviewer.io/uv.html?manifest=https://wellcomelibrary.org/iiif/b19431132/manifest#?c=0&m=0&s=0&cv=13&xywh=3684%2C901%2C3512%2C1897

The c, m and cv params are the indexes of those resources in their parent, and are as compact as can be. That's good, but you don't always have that information. The UV could offer a verbose form that takes the resource @ids, e.g., `cid=https://wellcomelibrary.org/iiif/b19431132/canvas/c13`

Scenario - suppose you have this information:

```
{
    "@type":"oa:Annotation",
    "motivation":"sc:painting",
    "resource":  {
        "@id": "https://example.org/annotation/1",
        "@type": "cnt:ContentAsText",
        "chars": "some text annotation"
    },
    "on":  {
        "@id": "https://data.ucd.ie/api/img/ivrla:36803/canvas/ivrla:36810#xywh=58,3252,1189,67",
        "@type": "sc:Canvas",
        "within" : {
            "@id" : "https://data.ucd.ie/api/img/manifests/ivrla:36803",
            "@type" : "sc:Manifest"
        }
}
```

You could generate a link that would open the UV on this annotation target - the right region of the right canvas.

With just the index, you'd need to load the manifest to count canvases to find the target for cv.

Related to #270 and logical conclusion of #336

**Comment by tomcrane** [comment]
The above comment is a precursor to the work of the Discovery group on _Import to Viewers_:

https://docs.google.com/document/d/1LKhEWWuYF-8KLkKcW_u2GlvX0epohwc7OYOVjICie5M/edit

@jronallo suggests the pattern:

```
https://example.org/viewer#?iiif_import={...}
```

...where `{...}` is an annotation in a form suggested by that document.

**Comment by edsilv** [comment]
Extend `URLAdapter` to look for `?iiif_content=`. This can specify either a url to a manifest, or a base64 encoded string of an annotation targeting a canvas.

https://base64url.herokuapp.com/

https://iiif.io/api/content-state/1.0/#5-examples-of-content-states

Parsing logic:

```
- is it a URL or anno?
- If it's a URL, load that manifest.
- if it's an anno, what's the target?
- load the target's `partOf` if not already loaded.
- If the `target` includes an `#xywh`, zoom to that region.
```

**Comment by tomcrane** [comment]
If it's a URL it could be a link to manifest, a collection, or a content state annotation (e.g., in a bookmarking system).

I think client needs to:

Is this a URL? if so, fetch to see what it is.
Is it a base64 encoded content state? decode and see what it is.

The fetched thing might be something UV can just load at the top level - a Manifest or a Collection.
Or it might be something within a top-level resource; a bookmark could be a part of a canvas that's part of a manifest.

**Comment by edsilv** [comment]
for reference: https://github.com/digirati-co-uk/iiif-canvas-panel/blob/main/packages/canvas-panel/src/web-components/canvas-panel.tsx#L158-L170
