### ISSUE TITLE
possible to constrain zooming to boundaries of images?

### ISSUE THREAD

**Issue by jenlindner** [UniversalViewer/universalviewer#464]
Hi, I'm having a problem where I can sometimes view and/or zoom outside of an image's boundaries, and the download sizes will be broken because some of the coordinates will be negative. Is there a way to configure the viewer to prevent bad coordinates in the download from this situation, maybe a way to ensure the viewer only zooms or displays within an image's boundaries? I included some examples below, I got this result from zooming in two depths (all that was allowed).

**Comment by jcoyne** [comment]
I'm also seeing this.  When I select "Current view 640 x 480px (jpg)", it requests an image where the region portion of the URI is `/-893,0,640,480/`

**Comment by edsilv** [comment]
Hi @jenlindner

Would it be possible to include the examples for me to try? Once I can reproduce this I'll have a way to narrow down the issue.

**Comment by edsilv** [comment]
This only happens for image servers that can't handle negative numbers in regions. Wellcome's IIP Image servers must be rounding these off, which are what I use to test this stuff.

I've altered the `getCroppedImageDimensions` method to always set the x and y components of the region to 0 if negative: 

https://github.com/UniversalViewer/universalviewer/commit/3ce65de76b584837e4bbff0e4813c4207ad1dbc7

**Comment by jcoyne** [comment]
Yay! Thanks.
