### ISSUE TITLE
Attribution Overlay only displays English Label

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#465]
Hello, since upgrading to version 2 the attribution overlay only displays the English text
![attribution](https://user-images.githubusercontent.com/1083554/26840673-cc856c5c-4ade-11e7-908e-bbe4fca50404.png)
It's correct in the right-hand menu.

The repository details in the right-hand menu also displays the English text
![ystorfa](https://user-images.githubusercontent.com/1083554/26840758-1cb11a46-4adf-11e7-9e91-d9f774ec80f9.png)

`label: [
{
@value: "Repository",
@language: "en"
},
{
@value: "Ystorfa",
@language: "cy-GB"
}
],
value: [
{
@value: "This content has been digitised by The National Library of Wales",
@language: "en"
},
{
@value: "Digidwyd y cynnwys hwn gan Lyfrgell Genedlaethol Cymru",
@language: "cy-GB"
}
]`

**Comment by edsilv** [comment]
We'll discuss this on the next community call.

**Comment by LlGC-szw** [comment]
Any news on when this could be fixed?
