### ISSUE TITLE
embed.js is dynamically loading jquery even when it's already loaded

### ISSUE THREAD

**Issue by jcoyne** [UniversalViewer/universalviewer#471]
https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/embed.js#L158

Here's a sample URL: https://hyphy.demo.hydrainabox.org/concern/generic_works/7e60c9a5-85f3-4590-8cbb-fbc339ffdc8b?locale=en#?c=0&m=0&s=0&cv=0&xywh=0%2C-15%2C1501%2C632

jQuery 3.2.1 is already loaded.

When I run a debugger, it seems that the `callback()` method is returning `undefined`. I'm not sure what that means.

**Comment by jcoyne** [comment]
I *think* the problem here is that compareVersionNumbers returns -1, which in javascript is a truthy value.

**Comment by edsilv** [comment]
@jcoyne Hmm, that sounds feasible. Have you tried changing it? If it works, please create a PR.

**Comment by jcoyne** [comment]
@edsilv I did try changing the middle term. However, I don't understand the third (callback) term in that test.  Would it ever return something besides undefined?  Does that mean it always loads the version of jquery?

**Comment by edsilv** [comment]
@jcoyne I've created a PR here: https://github.com/UniversalViewer/universalviewer/pull/475

Above `compareVersionNumbers` it has an explanation of what values it returns:

https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/embed.js#L105

I think we want to check whether v1 (desired version of jquery) is greater than v2 (available version of jquery). If so, it will return a positive integer, which I'm now testing for:

https://github.com/UniversalViewer/universalviewer/pull/475/files#diff-3456e8f52f32f9f1146e17f16553ffcdR160
