### ISSUE TITLE
Support smooth zoom transitions

### ISSUE THREAD

**Issue by snydman** [UniversalViewer/universalviewer#472]
Most OpenSeadragon implementations feature a zoom animation that is smooth, and obscures the transitions between zoom levels.  The UV implementation does not have this interaction, but rather transitions between zoom levels very abruptly.  It results in a less appealing user experience (IMO).  Was this intentional or can the smooth zoom transition be easily added?

**Comment by edsilv** [comment]
You can override the `animationTime` property in your custom config.json:

https://github.com/UniversalViewer/universalviewer/blob/v3/src/extensions/uv-seadragon-extension/config/en-GB.json#L143

Use the `configUri` property of the UV v3 options object to set the path to your custom config json:

https://github.com/UniversalViewer/universalviewer/wiki/V3

Try setting it to 1 second.
