### ISSUE TITLE
Consider making the location indicator into a navigation control

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#474]
![image](https://user-images.githubusercontent.com/1443575/27954078-481dc21c-6306-11e7-849a-7ae227754279.png)

(discussed on UV community call 2017-07-06)

One thing that showed up repeatedly in Julien Raemy's usability tests was that people mistook what is a purely informational device for a navigation device, and attempted to drag the marker through the sequence.

So why not make it into a navigation control?

Optional extra - make use of thumbnails on the canvases to preview the canvas at a position, like a video scrub bar with keyframes.

**Comment by mialondon** [comment]
This was a key finding in British Library's tests too. People just didn't understand what it was, and it takes up a lot of screen space for limited return. The previous BL item viewer navigation bar showed your place in a text as well as providing controls, so this UV function is a step backward for our users.
![Uploading itemviewer_bl_uk__itemid=ark__81055_vdc_100022555291_0x000001#ark__81055_vdc_100022.png…]()


Riksarkivet seem to have removed it, and it was in the BL backlog too.

I love the optional extra!

**Comment by mialondon** [comment]
Is there any real benefit to the user in having two places where they can drag and scroll across the item? This does assume the thumbnail view is always a tap away.

**Comment by tomcrane** [comment]
I think the problem is that the thumbnail view is only _partly_ or indirectly a means of navigating through the object; it may not always be available, it may be coarse-grained (only two or three views). The scroll bar in the thumbnails panel, when present, is really just a means of navigating through the thumbnails; the thumbnails represent views of the object. For books, manuscripts etc., these views correspond exactly to pages, and therefore to a linear reading experience of the object. This falls out quite naturally in a bookreader UI. The UV looks the way it does because it started in a library and the things it showed were often books or booklike in behaviour (but even then, many were not...). The UV ends up looking like a book reader.

The problem becomes harder when the "view" of the object represented by one of those thumbnails is an extent of time (like one side of a tape in BL examples) which has its own linear navigation space, best represented by a scrub bar. Then you have navigation through views and navigation within views, and both are linear controls. 

I need to state the problem better; the UV doesn't have to offer a perfect solution for all types of content, but it needs to offer a simple UI for all types of content. What I don't know is how consistent it needs to be across paged objects, single images, video, audio, archive material, and if consistency is important, what does consistency mean?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
