### ISSUE TITLE
Returning from full screen does not return to correct size

### ISSUE THREAD

**Issue by michaelrlevy** [UniversalViewer/universalviewer#476]
There have been two reports of an embedded Universal Viewer failing to properly return to its normal display size after being in Full Screen mode. Refer to discussion in Google Groups URL at bottom.

Two example UV instances embedded in pages:
[https://ntnu.tind.io/record/129763](url)
[https://collections.ushmm.org/search/catalog/irn531331](url)

One person commented that clicking the "Exit Full Screen" icon once does not fully return the UV to its original size, which would be the expected behavior; and yet clicking the ESC does result int he expected behavior.

Another person (me) describes exactly the opposite behavior: clicking the ESC key once causes the UV to shift its position so that the upper left corner is moved to the initial position, but it is still too big--and clicking ESC a second time results in the expected behavior of returning to original size and position. However, clicking the "Exit Full Screen" icon once does result in the expected behavior.

I will add here a further observation: as the one reporting the "ESC" key misbehavior, that was occurring on a desktop with a somewhat wider screen that has a 2nd monitor extended to the right. As I write this on a laptop, I cannot recreate any misbehavior at all, neither with ESC nor with "Exit Full Screen" icon,.

Perhaps this behavior is dependent in some complex way on screen resolution.

Discussed here:
[https://groups.google.com/forum/#!topic/universalviewer/0OOhXNRf-yI](url)

**Comment by edsilv** [comment]
To reproduce this, view a collection: 

http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb19974760

Switch to another manifest in the tree view.

Fullscreen, then exit fullscreen.

**Comment by edsilv** [comment]
Closing as fixed by #500
