### ISSUE TITLE
Respect `maxArea` when offering downloads

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#478]
Successor to #219

`maxArea` is a more specialised constraint on what an image server might permit, and will probably be rare in the wild, but it is a real use case that the UV might encounter. 

Recording here so that there is an issue for it; will see if it gets many votes.

spec:
http://iiif.io/api/image/2.1/#profile-description

source issues:
https://github.com/IIIF/iiif.io/issues/620
https://github.com/IIIF/iiif.io/issues/663

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.

**Comment by LanieOkorodudu** [comment]
> Closed due to inactivity.

@demiankatz though the issue still open?

**Comment by demiankatz** [comment]
Thanks for pointing that out, @LanieOkorodudu -- I must have pushed the wrong button. :-) Closing now!

**Comment by demiankatz** [comment]
On reflection, though, this still seems like something we might eventually want to do. I don't see a reason to close it. Maybe that comment was posted to the wrong ticket. I'm reopening for now.

**Comment by LanieOkorodudu** [comment]
> On reflection, though, this still seems like something we might eventually want to do. I don't see a reason to close it. Maybe that comment was posted to the wrong ticket. I'm reopening for now.

agree. probably revisit it when we have the opportunity
