### ISSUE TITLE
Could anchors acting as buttons be transitioned to buttons?

### ISSUE THREAD

**Issue by mejackreed** [UniversalViewer/universalviewer#479]
Within UV, there are a lot of UI buttons that are expressed as "links" (anchors) without text. Would the UV community be open to moving these anchors to `<button>` elements instead?

![screen shot 2017-07-18 at 5 06 35 pm](https://user-images.githubusercontent.com/1656824/28339840-836d87b6-6bdb-11e7-84f7-1d4b76bcca10.png)

These changes may help with overall accessibility assessments by adopter institutions.

**Comment by edsilv** [comment]
This has been done now on the v3 branch.
