### ISSUE TITLE
Should UV have a default confirmLabel for auth login?

### ISSUE THREAD

**Issue by mejackreed** [UniversalViewer/universalviewer#484]
Looks like implemented here:

https://github.com/UniversalViewer/universalviewer/commit/6924d407dd5eea004934376f043f0fccca851843#diff-2e73ebf17ea0263d9c99aab0b6023ca1R34

But if `confirmLabel` is not provided, the viewer will display "undefined". Should there be a fallback or default?

<img width="189" alt="screen shot 2017-07-31 at 3 27 00 pm" src="https://user-images.githubusercontent.com/1656824/28801123-e1d61e48-7604-11e7-9b0e-c8cc22ebe585.png">

**Comment by edsilv** [comment]
Fallbacks for the message and label might be a good idea, yes. Perhaps we need to reinstate `degradedResourceMessage` and `degradedResourceLogin`:

https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/l10n/en-GB.json#L12

https://github.com/UniversalViewer/universalviewer/blob/ada52898e10a8a9282ba520c0b80fddc14e0c42e/src/modules/uv-shared-module/InformationFactory.ts#L25

Perhaps renaming to `degradedResourceMessageFallback` and `degradedResourceLoginFallback` ?
