### ISSUE TITLE
Border-radius inconsistent with defined button classes... what should it be?

### ISSUE THREAD

**Issue by mejackreed** [UniversalViewer/universalviewer#493]
The `.btn` class uses and defines a `border-radius` here: https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-shared-module/css/buttons.less#L22

Yet, `styles.less` removes that for `.btn-*` styles here: https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-shared-module/css/styles.less#L37

Is that the intention? Or could this be better configured by an adopter setting `@border-radius-base` to zero instead of overriding the border-radius?

**Comment by edsilv** [comment]
Sounds like a better option to set `@border-radius-base` to `0`.
