### ISSUE TITLE
Some manifests do not load correctly from within collections

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#499]
There seems to be a problem with loading certain manifests from within collections. Steps to reproduce:

1.) Go to http://universalviewer.io/uv.html?manifest=https://digital.library.villanova.edu/Collection/vudl:3/IIIF
2.) Click the Index tab
3.) Click the "Philadelphia Ceili Group" subcollection

This causes a chain of manifests to load, culminating in a `TypeError: manifest is undefined` error.

The bottom manifest in the chain is https://digital.library.villanova.edu/Item/vudl:467625/Manifest, which loads successfully if accessed directly -- but it's not working in the context of the collection.

There are two possible theories:

1.) Because the first non-collection manifest encountered is an IXIF audio manifest, perhaps something about this format is causing a problem.

2.) Because this manifest is found in a deeply-nested tree of collections, perhaps this has to do with collections inside collections that do not also contain manifests (which may be an existing issue).

**Comment by Geoffsc** [comment]
We were able to reproduce this issue with a manifesto test in this PR: https://github.com/viewdir/manifesto/pull/28
We need to figure out the strategy to solve the underlying problem.

**Comment by demiankatz** [comment]
This may be a duplicate of #447.
