### ISSUE TITLE
Smaller UV width, single canvas objects show more info that disappears

### ISSUE THREAD

**Issue by mejackreed** [UniversalViewer/universalviewer#502]
For a UV with a width that doesn't quite trigger the mobile view, the right panel "More Information" will be presented to a user. When a user clicks the panel, it opens and then immediately closes.

![sidepanel](https://user-images.githubusercontent.com/1656824/30700785-6fc5fc6c-9e9d-11e7-94d6-bf5a742ac5f4.gif)

## Expected behavior
The panel should not be presented if it will be unable to display

## Actual Behavior
The panel is presented collapsed on the right side, but when clicked opens briefly and then immediately closes

## Steps to reproduce the behavior
1. Modify the width to be `465px` https://github.com/UniversalViewer/examples/blob/v3/index.html#L18
1. Load a single canvas object http://wellcomelibrary.org/iiif/b23984958/manifest

Locally reproducible at http://localhost:8002/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb23984958%2Fmanifest&xywh=0%2C-600%2C2400%2C2998

**Comment by edsilv** [comment]
I can't reproduce it:

https://youtu.be/OZJ9Naa7VL4

The width that triggers mobile view is < 641px. In the video when I toggle between those it works as expected, using the latest on v3 branch.

I tried 465px width too but it exhibited the correct behaviour.

**Comment by mejackreed** [comment]
What branch of https://github.com/UniversalViewer/examples are you using? I'm having trouble recreating your version.

**Comment by edsilv** [comment]
gh-pages

**Comment by aeschylus** [comment]
This may have something to do with the link styling coming into the iFrame from our contexts (dotted lines, padding).

It's also worth noting that the entire DOM element disappears when this occurs (it doesn't just pop out underneath the other DOM elements).
