### ISSUE TITLE
Consider handling of linking annotations

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#505]
If the UV detects a hotspot linking annotation, it should render the targeted area as clickable, and fire an event when clicked on (via the usual event system) so that the containing page can react to a click on a linking annotation and deal with it as it sees fit. The event data would include the annotation itself. 

This feature enhancement does not throw up too many problems about display of additional content, as it is left for the containing page to deal with and is therefore highly customisable.

Linking annotations would be in `otherContent` linked resources (or in external AnnotationPage in Presentation 3) so there is a wider issue about how much the UV follows links to more annotations and how it handles each type/motivation.

**Comment by edsilv** [comment]
Could you give a concrete use case/user story? Just so it's easy to understand :-)

**Comment by edsilv** [comment]
https://github.com/UniversalViewer/user-stories

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
