### ISSUE TITLE
Support image segments

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#507]
The annotation that paints an image resource onto the canvas does not always have to paint the full extent of the source image. The annotation could specify a crop, as per http://iiif.io/api/presentation/2.1/#segments.

Both syntaxes should be supported, although the simpler non-Image API version requires #78 first.

Test fixtures:

* http://iiif.io/api/presentation/2.0/example/fixtures/35/manifest.json (image resource)
* http://iiif.io/api/presentation/2.0/example/fixtures/36/manifest.json (with Image Service)

**Comment by edsilv** [comment]
Perhaps a user story could be created for this?

https://github.com/UniversalViewer/user-stories

**Comment by tomcrane** [comment]
Example - the source image from scanning a book or painting includes the scanning bed, colour chart etc, but I want the viewer to crop all that out.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
