### ISSUE TITLE
Remove Cloudflare dependencies (embed.js)

### ISSUE THREAD

**Issue by dvhassel** [UniversalViewer/universalviewer#508]
UV relies on the Cloudflare CDN to load jquery (if needed), easyXDM and json2. 
This breaks UV if you don't have internet access (or are behind a proxy, firewall, ..)

**Comment by edsilv** [comment]
I think we chatted about this on Slack, but posting here for reference:

v3 (v3 branch) has an offline.js that concats all of these dependencies together along with uv.js etc. Hoping to release this soon. 

stenciljs.com has an interesting PWA approach that uses a service worker to cache your assets in workbox for offline use. We could potentially do something like this in future.

At LDCX I demoed the UV being loaded entirely over IPFS. This is made possible using offline.js
