### ISSUE TITLE
How to implement v3 version?

### ISSUE THREAD

**Issue by unmecduweb** [UniversalViewer/universalviewer#513]
I've tried many times but i've never find a way to implement universalviewer in v3 version.
There is not a v3 relesae version in the relases page on github, but the uv example is using it : http://universalviewer.io/examples/

Is this v3 under development or am i missing something?

Thanks in advance

**Comment by edsilv** [comment]
Hi, we're getting close to a release of v3. It's currently available on the v3 branch. I will produce documentation for it when ready. Until then, if you look at index.html in the examples repo this should provide some guidance, but please ask me any questions you may have on the UV Slack (https://universalviewerinvite.herokuapp.com/)

**Comment by edsilv** [comment]
Hi @unmecduweb 
The v3 branch has now been merged with master and there is minimal starter project here: https://github.com/UniversalViewer/uv-app-starter
Does this help?

**Comment by unmecduweb** [comment]
Yes it does thanks a lot!
