### ISSUE TITLE
TypeError: cyclic object value when multiple audio or video files

### ISSUE THREAD

**Issue by jajm** [UniversalViewer/universalviewer#514]
Hi,

I discovered a bug that happens only when multiple audio or video files are displayed in UniversalViewer.
When I click on a thumbnail in the left panel, an error is printed in the console:

    TypeError: cyclic object value

This seems to be caused by this line

https://github.com/UniversalViewer/universalviewer/blob/8ecb057f49fbf4371fb2073dfe99c1656cf3f960/src/modules/uv-shared-module/BaseExtension.ts#L663

You can reproduce the error by running `grunt examples` and using this manifest https://gist.githubusercontent.com/jajm/e89f9171ee59dfacb5efc7e2d67e7795/raw/7471ae6f213dea94fe0242226783696f43125b24/gistfile1.txt

I tried to use https://www.npmjs.com/package/cycle to fix the problem, without success (I'm not a JS developer and I don't know how to add and use a new dependency)

**Comment by edsilv** [comment]
It looks like this is fixed in v3: http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=https%3A%2F%2Fgist.githubusercontent.com%2Fjajm%2Fe89f9171ee59dfacb5efc7e2d67e7795%2Fraw%2F7471ae6f213dea94fe0242226783696f43125b24%2Fgistfile1.txt

**Comment by edsilv** [comment]
Closing as inactive
