### ISSUE TITLE
Use iiif-explorer instead of iiif-tree-component for collections without viewing-hint: multi-part

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#515]
On the community call we discussed how to address these issues around preserving state and "lazy loading" content in the tree view:

https://github.com/UniversalViewer/universalviewer/issues/302
https://github.com/UniversalViewer/universalviewer/issues/446

We thought about making the tree use web workers to load whichever manifests are currently visible in the scroll area - much like the way thumbnails are loaded. However, it seemed that there was a possibility of causing memory leaks due to the potential number of manifests to be loaded and parsed.

We also thought about changing the `c` hash parameter to be an array instead of an integer. Thus storing the nested collection path between reloads.

However, after a bit more thought it seemed that the best course of action would be to use iiif-explorer:

https://github.com/iiif-commons/iiif-explorer

This would reload the UV when clicking on a collection (folder) or manifest (file) and preserve the path in the breadcrumb trail. This is generated by walking upwards through the `within` properties of collections. It's possible to have multiple `within`s, but we decided that it would be acceptable to use the first one found for now until other use cases arose.

The tree view would now only be shown when a collection has a `multi-part` viewing hint: http://iiif.io/api/presentation/2.1/#viewinghint Otherwise for "loose" collections the UV would default to the explorer. This is in keeping with the presentation api spec and requires users to add the correct viewing hint to their manifests if they desire to use the tree view for a given collection.

The `c` hash parameter now no longer really makes sense as the explorer component reloads the UV when clicking on a folder, unlike the tree view which uses the `c` parameter to load a child manifest in place.

To find a solution that worked for both the explorer and tree we decided to use resource ids instead of indices as per https://github.com/UniversalViewer/universalviewer/issues/462
So `cid`, `mid`, `cvid` hash parameters that specify the `id` of the resource. Keeping the old index parameters for backwards compatibility. For the explorer and tree views it would simply recursively search for a given id and select it.

We don't foresee this being part of a v3 release. We will work to release a beta of v3 soon without introducing any more new features. The above would constitute a v3.1 release (as there are no breaking changes, only UI behavioral differences and additional functionality). The British Library have kindly expressed an interest in supporting this work

Related: https://github.com/UniversalViewer/universalviewer/issues/462

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
