### ISSUE TITLE
minimiseButtons in V3

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#517]
Setting minimiseButtons to false in the config doesn't have an effect on the embed and full screen buttons. Inspecting in the console shows that the strings are missing from the HTML.

![missing_string](https://user-images.githubusercontent.com/1083554/33372451-0453c4ca-d4f6-11e7-87f9-4496c4424a55.png)

I think they're there for everything else.

**Comment by edsilv** [comment]
cc @mejackreed

**Comment by mejackreed** [comment]
I believe this was resolved in 88dc5cc80aa526553dbd42346e578dc9a9b87a69

**Comment by edsilv** [comment]
Yep, closing as fixed.
