### ISSUE TITLE
Support legacy Auth in v3

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#518]
The pre-v3 Universal Viewer doesn't quite implement the Auth 1.0 spec

compare http://universalviewer.io/examples/#?manifest=https://wellcomelibrary.org/iiif/b24941931/manifest with https://wellcomelibrary.org/item/b24941931

If anyone wants to view Wellcome, some BL and a few other experimental pre 1.0 implementations, the UV3 needs to support the 0.9.x interaction pattern (it's not too different).

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by mialondon** [comment]
Is v3 still relevant at this point? Closing in community call 28 September 2023
