### ISSUE TITLE
Loading doesn't complete in IE 9

### ISSUE THREAD

**Issue by adolski** [UniversalViewer/universalviewer#523]
**UV version:**

`universalviewer@2.0.2` (have tried 2.0.1, 2.0.2, and latest snapshot of `v2` branch)

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Loading in IE 9 stalls on the spinning square. The console says:

```
SCRIPT1004: Expected ';' 
uvconfig.json&s=0&cv=0..., line 1 character 12
```

**Expected behavior:**

Successful load

**Steps to reproduce:**

As far as I can tell this is reproducible using the various 2.x releases (such as `dist/uv-2.0.1` or `dist/uv-2.0.2`), or by building a snapshot of the `v2` branch. My invocation HTML looks similar to the following, and works in most other browsers including Chrome, FF, Safari, and later versions of IE:

```
<div class="uv"
    data-locale="en-GB:English (GB)"
    data-config="uvconfig.json"
    data-uri="http://example.org/manifest.json"
    data-sequenceindex="0"
    data-canvasindex="0"
    data-rotation="0"
    style="margin: 0 auto; width:800; height:500; background-color:#000;">
</div>
<script src="/universalviewer/lib/embed.js" id="embedUV"></script>
```

The particular IE is from the [IE9 on Win7 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) from modern.ie, but I also can reproduce on a local desktop Win7 running IE 9.

**Other information:**

I see that this was initially reported [here](https://github.com/UniversalViewer/universalviewer/issues/227#issuecomment-222447469), but it's different from that issue, so I thought I'd create a new one for it.

**Comment by edsilv** [comment]
I'm seeing this:

![image](https://user-images.githubusercontent.com/1334393/35164753-93f6c094-fd43-11e7-97f7-0368e11f9ca3.png)

Does that chime with what you're seeing?

**Comment by edsilv** [comment]
I think this may have been introduced when updating the Auth pipeline for v1...

**Comment by adolski** [comment]
Unfortunately I can't even get that far. Here's what I see...
![uv2-ie9](https://user-images.githubusercontent.com/6854505/35165954-d48c4fc6-fd15-11e7-8e7a-2a9ac1c3d4de.png)

The page URL if it helps any is: https://digital.library.illinois.edu/items/7278cf30-421e-0134-1da0-0050569601ca-8

**Comment by edsilv** [comment]
Can reproduce that, but we'd need a debug build of the UV to be able to step through it in the debugger.

What happens when you run the examples on localhost with `grunt examples`? Please ensure you're using the latest code on the `v2` branch.

**Comment by adolski** [comment]
I'm trying to compile a debug build from the `v2` branch according to the README on that branch:
```
npm install -g grunt-cli
npm install -g bower
git clone https://github.com/UniversalViewer/universalviewer.git --recursive
cd universalviewer
npm install
bower install
grunt sync
grunt
```

But that last command exits with:
```
Running "ts:dev" (ts) task
Compiling...
Using tsc v2.6.1
error TS2688: Cannot find type definition file for 'jquery'.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:dev" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by edsilv** [comment]
I just did a fresh clone and build and all seemed fine. Which version of node are you using? I'm on node v8.9.1 and npm v3.10.8

**Comment by adolski** [comment]
You're right, my node and npm were old. I upgraded them and was able to build successfully. I assume then that the product of that build resides in `src`? Using that, I'm able to produce a different series of errors in IE 9:

http://universalviewer-v2-sscce.s3-website.us-east-2.amazonaws.com/

![ie9](https://user-images.githubusercontent.com/6854505/35587301-041e9338-05c3-11e8-9486-90f99e048f5e.png)

**Comment by edsilv** [comment]
I'm going to take another look at this next time I have some "open collective time". Full time on another project right now. I have win 7 on a VM to test with.

**Comment by edsilv** [comment]
@adolski Hi, just wanted to check if this was still a problem?

**Comment by adolski** [comment]
Hi,

We worked around this by displaying static images for IE 9 users. That seems to be working out fine, so this is a very low priority for us. I completely understand if you want to consider it a "wontfix."

**Comment by demiankatz** [comment]
Death to IE9! I don't think we need this anymore.
