### ISSUE TITLE
Merge conflicts in master

### ISSUE THREAD

**Issue by jcoyne** [UniversalViewer/universalviewer#524]
See https://github.com/UniversalViewer/universalviewer/blob/37260e369bb639bb5ed60db8238b01a437da6380/src/lib/embed.js#L1

**Comment by edsilv** [comment]
cc @Geoffsc

**Comment by edsilv** [comment]
embed.js has been reverted to https://github.com/UniversalViewer/universalviewer/commit/b41a4a47af00c8ada186819d682ba91a33780e72
