### ISSUE TITLE
Broken thumbnails if service uri contains trailing slash '/'

### ISSUE THREAD

**Issue by datazuul** [UniversalViewer/universalviewer#525]
**UV version:**

```
 universalviewer@2.0.2
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Thumbnails in sidebar not shown.

**Expected behavior:**

Thumbnails shown.

**Steps to reproduce:**

Open Manifest http://manifests.ydc2.yale.edu/manifest/BodleianMS_Bodley716

**Related code:**

Thumbnail code is rendered as:

```
http://scale.ydc2.yale.edu/iiif/63aad7a2-fbe6-4375-9be5-be2cdfa6819a//full/90,/0/native.jpg
```

**Other information:**

Problem is: service uri (@id) in manifest ends with a slash '/': http://scale.ydc2.yale.edu/iiif/63aad7a2-fbe6-4375-9be5-be2cdfa6819a/
UV should check this and truncate trailing slashes before adding region/size/...

Otherwise server responds with:

```
{
message: "6 segments",
parameter: "invalid request",
status: 400
}
```

**Comment by edsilv** [comment]
I've pushed a fix for this to the v2 branch.
