### ISSUE TITLE
assets from folder "img" in theme repo not copied during npm install

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#526]
**UV version:**
```
 universalviewer@v3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When I add my custom theme to package.json
```
{
    ..
    "dependencies": {
        "uv-en-gb-theme": "git+ssh://git@github.ugent.be:Universiteitsbibliotheek/uv-en-GB-theme.git#v3"
         ..
     }
}
```
The assets located in folder "img" (e.g. hamburger.png) are not copied after running:
```
npm install
```
Same thing happens using the official theme.

For some reason in the resulting theme a folder is created called "assets" (having a subdirectory uv-mediaelementcenterpanel-module ), but I don't know where this comes from.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by mejackreed** [comment]
I've run into this same problem before. I think I had to resolve it by doing the following:

```
rm -rf node_modules/uv-en-gb-theme/ && npm install && rm -rf src/themes && grunt build`
```

For me, some of the themes were being cached somewhere.. I did not ever get the root cause just went with the solution of blowing everything away.

**Comment by edsilv** [comment]
@nicolasfranck did this solve it?

**Comment by LlGC-dwj** [comment]
I've just tried to do the same and followed the instructions, nothing happened for me.

**Comment by nicolasfranck** [comment]
Unfortunately not.

**Comment by edsilv** [comment]
I'll have to schedule an open collective day soon to look into this.

**Comment by edsilv** [comment]
Just looking at this. Can't install from that location (`git+ssh://git@github.ugent.be:Universiteitsbibliotheek/uv-en-GB-theme.git#v3`) - would need your ssh login.
Tried using just `"uv-en-gb-theme": "Universiteitsbibliotheek/uv-en-GB-theme.git#v3"` instead, but it doesn't appear to exist?

**Comment by nicolasfranck** [comment]
I just made a copy of it here:

https://github.com/nicolasfranck/uv-en-GB-theme

thanks!

**Comment by edsilv** [comment]
That should be fixed now. You need to use an `assets` not `img` folder. There was some code missing in the UV's theming code to copy the assets to the `.build` folder too.

I've created a PR on your theme: https://github.com/nicolasfranck/uv-en-GB-theme/pull/1

Also, regarding @mejackreed's comment about needing to "blow everything away". I think I ran into the same issue - this is related to copying the npm modules multiple times, instead of just once on `npm install`. The themes are now "blown away" for you each time they are synced to avoid issues around files with the same names not getting replaced.

**Comment by nicolasfranck** [comment]
ok, this seems to work. Thanks! ;-)
