### ISSUE TITLE
Object navigation slider has confusing labels generated for paged objects.

### ISSUE THREAD

**Issue by aeschylus** [UniversalViewer/universalviewer#531]
**UV version:**
v2.0.1 according to package.json (but also tru on current v3 branch

**I'm submitting a:**

- [X] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)

**Current behavior:**
Currently, the navigation slider in the footer of the UV (in the searchResults div) has a label that tells the user how far into the work they are currently navigated. When viewing paged objects, it currently looks like this:

*Example 1*
![screen shot 2018-01-24 at 16 36 41](https://user-images.githubusercontent.com/145874/35364963-d618f8de-0126-11e8-960b-f6cb61deb4bc.png)
![screen shot 2018-01-24 at 16 36 36](https://user-images.githubusercontent.com/145874/35364964-d646bcd8-0126-11e8-94c8-a4466ad52eee.png)

*Example 2*
![screen shot 2018-01-24 at 16 35 44](https://user-images.githubusercontent.com/145874/35364966-d6789bd6-0126-11e8-94f9-f5c00ee6b11c.png)
![screen shot 2018-01-24 at 16 35 49](https://user-images.githubusercontent.com/145874/35364965-d65e0b54-0126-11e8-8eb4-8c1da78ae67e.png)

The second example shows the problem most clearly. Because this label is built up from the canvas `label` in the IIIF manifest, its text can be anything, so in this case it says "page Page 1 of -", which isn't very user friendly. In the first example above, the actual canvas label is "-" for the first few canvases, so that is what is shown. As a sillier, but very plausible example that I don't have screenshots for right now, if the first canvas were to have a label like "Homily of March" and the last canvas had a label like "appendices", the slider label as currently implemented would read "page Homily of March of appendices", which would be very confusing.

**Expected behavior:**
 Ideally it would say "page 1 of 46", basing the label on the number of canvases, and not using the canvas label for this particular part of the interface (but we still want the full text labels in the thumbnail view). I've implemented this in a local [PR](https://github.com/sul-dlss/universalviewer/pull/48/files) by removing most of the page label based logic (the distinction between paged and non-paged still causes the viewer to render the "image" or "page" prefix). However, we'd like to submit this upstream to the v3 branch if possible to avoid maintaining a divergent codebase, assuming the fix does not go against the intent of the label. It may seem like losing a feature, but I wonder what the intended behaviour was for using page labels in the slider, since it often leads to these kinds of results. The purpose is to tell the user how deeply into the object they are currently focusing, for which using the canvas indices seems reasonable to me.

The fixed version looks like this for paged objects:

![screen shot 2018-01-24 at 17 09 18](https://user-images.githubusercontent.com/145874/35365424-63565b22-0129-11e8-9497-1c68855d7695.png)
![screen shot 2018-01-24 at 17 09 25](https://user-images.githubusercontent.com/145874/35365423-633b5b4c-0129-11e8-9e08-eca9ee75d802.png)

I'm submitting this here before putting in a PR because it seems like a minor design choice that the community might want to discuss. For example, what was the original motivation for using the IIIF canvas labels in this part of the UI?

**Steps to reproduce:**
Load the uv with any manifest that used a "paged" viewingHint. Most valid IIIF labels will produce an odd result for the slider label. The default UV examples page exhibits the error. See: https://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest&xywh=-1116%2C0%2C4800%2C3542

**Related code:**
https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L629-L651

https://github.com/sul-dlss/universalviewer/pull/48/files

**Comment by edsilv** [comment]
I've added this to the Community Call agenda for Feb 1st. https://github.com/UniversalViewer/universalviewer/projects/3

Please feel free to join if you'd like to discuss. I think labels in the footer were a hard requirement at some stage, possibly while at Wellcome? cc @jennpb

**Comment by aeschylus** [comment]
@edsilv Great. I'll be there to discuss. Thanks Ed.

**Comment by edsilv** [comment]
Solved by adding `forceImageMode` to `searchFooterPanel` config options.

**Comment by jennpb** [comment]
Chiming in very late as ever

> I think labels in the footer were a hard requirement at some stage, possibly while at Wellcome?

The UX designer added labels to follow best practice (you shouldn't use obscure iconography without a text label), but this was never fully tested with users so I don't have any evidence to say whether that is a meaningful label or not.
