### ISSUE TITLE
PDF Sidebar Display Issue

### ISSUE THREAD

**Issue by yanrubi** [UniversalViewer/universalviewer#532]
**UV version:**

```
2.0.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
After toggling the sidebar, The pdf thumbnail view doesn't fill up the whole sidebar container and the thumbnailSelectionRing shifts to the upper left a little (see the following screenshot).

**Expected behavior:**
Thumbnail view should fill up the whole sidebar and the thumbnailSelectionRing should cover the thumbnail perfectly

![image](https://user-images.githubusercontent.com/18058881/36983630-d222e3bc-2060-11e8-8252-011bb1a7e2fd.png)

**Comment by edsilv** [comment]
I think the screen shot didn't upload.

**Comment by yanyufish** [comment]
Sorry for the trouble. The post has been updated.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
