### ISSUE TITLE
When 'image unavailable' show this in full image not just thumbnail

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/universalviewer#534]
**UV version:**

```
 v2 and v3
```
**I'm submitting a:**

- [ x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
When an image is unavailable the thumbnail shows a broken image icon (v3) or image unavailable text (v2) but the main image continues to try to load.

**Expected behavior:**

Message to say image unavailable instead of continuing to load. Or default image can be set to load if no image found?

**Steps to reproduce:**

http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=https%3A%2F%2Fdamsssl.llgc.org.uk%2Fiiif%2F2.0%2F2854668%2Fmanifest.json

https://syllwr.llyfrgell.cymru/2854668#?c=0&m=0&s=0&cv=0

**Comment by edsilv** [comment]
I'm adding this to the next community call agenda to agree on the best approach.

**Comment by peetucket** [comment]
There are some specific cases of images with access restrictions where the behavior is correct in that it does not the images when the access restriction (e.g. location specific or log in required), but where the user is not given clues as what the restriction is.  For example, this manifest is for a location restricted image: 

https://purl.stanford.edu/yw340tg3386/iiif/manifest  

The behavior (https://purl.stanford.edu/yw340tg3386) shows a thumbnail for image 1 (ok) and broken images for images 2 and 3 (these are not allowed to be viewed), but gives the user no clue as what is happening.  The manifest has the correct information: "Restricted Material": "Restricted content cannot be accessed from your location" but this is never shown to the user, leading them to believe there is just some problem with the viewer.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
