### ISSUE TITLE
Thumbnails broken if service url has a ? in it

### ISSUE THREAD

**Issue by ojlyytinen** [UniversalViewer/universalviewer#537]
**UV version:**

```
 universalviewer@v2.0.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Thumbnails not shown in the sidebar because of invalid requests

**Expected behavior:**

Thumbnails should be shown and the request built correctly

**Steps to reproduce:**

Try this manifest https://iiif.durham.ac.uk/manifests/trifle/32150/t1/mz/02/t1mz029p473h/manifest. The thumbnails won't load.

**Related code:**

```
// insert any relevant code here
```

**Other information:**

It seems that UV appends a t parameter in the image requests (for example ?t=1517827833181) for the thumbnail images. If the image server service url already has a question marks in it then this will break the request. You get urls like https://iiif.durham.ac.uk/iipsrv?IIIF=trifle/32150/t1/mz/02/t1mz029p473h/58bed104c3644e562e2db3241103a0ca.jp2/full/90,/0/default.jpg?t=1517827833181. The image server interprets the last bit to be part of the request format and responds with 400 Bad Request - IIIF :: Only JPEG output supported.

**Comment by nicolasfranck** [comment]
The url you posted is typical to the IIP Image Server (it's an FCGI server), but is not considered an IIIF Image API url, where the iiif parameters must be stored in the path, and not in the query (where order is not important). No query parameters should be present in an url like that.

You should create a new base path like this:

https://iiif.durham.ac.uk/iiif/images/trifle%2F32150%2Ft1%2Fmz%2F02%2Ft1mz029p473h%2F58bed104c3644e562e2db3241103a0ca.jp2/full/90,/0/default.jpg

and let the server internally rewrite these requests. If you're using nginx, you can make the route /iipsrv an internal route.

**Comment by ojlyytinen** [comment]
I see, I had not realised that the IIIF API specifies that everything must be in the path rather than the query. I will try to get our server to do the rewriting.

Nevertheless, since urls of this kind appear to work fine, except for the thumbnails, and as I imagine the fix to support this would be fairly simple, I think UniversalViewer would benefit from this kind of extra compatibility.

In any case, thanks for your advice.

**Comment by edsilv** [comment]
I've added this to the next community call agenda for discussion.

**Comment by tofkamp** [comment]
Proposal:
Have a config option specify the behaviour: Value 0 (default) do not add ?t=123454.. (why do we need it anyway ?)
Value 1, add the t= parameter, If there is already an "?" in the url, add "&t=12345" else add "?t=12345"

**Comment by tomcrane** [comment]
Agree it should be an optional config setting, but also that the mechanism changes - see my comment here: https://github.com/UniversalViewer/universalviewer/issues/431#issuecomment-274100861

**Comment by mejackreed** [comment]
I'm not sure if this issue changes now, the config issue was only related to a way to test it, no?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Confirmed as fixed.
