### ISSUE TITLE
When first search result is on a later page, the "previous result" button is not disabled.

### ISSUE THREAD

**Issue by aeschylus** [UniversalViewer/universalviewer#542]
**UV version:**
Master branch (non-released)

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Currently, if the UV is loaded with a manifest linking to a search service, and the user searches for a term in the manifest using the footer search box, results appear on the navigation line as pins, and the "next result" and "previous result" pages appear. If the first result appears on a later canvas than the one currently focused, the "previous result" button does not style itself appropriately, and appears to be clickable (not "disabled"). If the user clicks it, nothing will happen.

**Expected behavior:**
From the perspective of consistency with the non-edge-case behaviour:  the "previous result" button should have a disabled style if the first result in the manifest appears on a canvas later in the sequence than the currently displayed canvas. UV shows this disabled style when the first result does appear on the currently selected page/canvas.

**Steps to reproduce:**
Using the default settings, and the standard UV example page, view the "Wunder der Vererbung" object, staying focused on the first page of the sequence. Then, search for "einfach". This will have a result on a successive page. The "previous result" button will now have an "active" style, but clicking it will not do anything.

**Related code:**
There are a few events that trigger a restyling of the button by calling the `isPreviousButtonEnabled` function in footer.ts ([262](https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L262-L283)) to check if it is available and then adding styles in `updatePrevButton` ([346](https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L346-L356)). This re-rendering is only triggered in response to two events: [`CANVAS_INDEX_CHANGED`](https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L48-L53) and [`ANNOTATION_CHANGED`](https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L77-L80). When the current page is earlier than the page with the first search results on it, neither of these events is fired, so the update is not executed. In this case, would adding the update to the subscription for [`ANNOTATIONS`](https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L68-L71) be enough to fix it?

**Comment by edsilv** [comment]
Adding calls to `.updatePrevButton() and .updateNextButton()` on the `ANNOTATIONS` event fixed it.
