### ISSUE TITLE
When ZoomToSearchResultEnabled is false, "next result" button does not go to end of all search results.

### ISSUE THREAD

**Issue by aeschylus** [UniversalViewer/universalviewer#544]
**UV version:**
Current master branch (pre-release - 35feb1356ff0b3316b7540bf05bae847f6fbfb4a)

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
When the `ZoomToSearchResultEnabled` is set to false, disabling the zoom behaviour on search result navigation, the "next result" button does not allow the user to navigate all the way to the end. If the user clicks it, it will navigate to the next result, but only until the second-to-last result.

**Expected behavior:**
Clicking the "next result" button should navigate to the end of the sequence if clicked enough times.

**Steps to reproduce:**
Disable the `ZoomToSearchResultEnabled` option in the configuration of the example page, and then use a search-enabled manifest to attempt to navigate results.

**Related code:**
This is probably happening somewhere in the [`isNextButtonEnabled`](https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-searchfooterpanel-module/FooterPanel.ts#L285-L306) function in footer.ts in the searchfooter module, but I haven't debugged it more deeply than that.

**Comment by edsilv** [comment]
Closing as fixed
