### ISSUE TITLE
Update content search zoom behavior

### ISSUE THREAD

**Issue by ggeisler** [UniversalViewer/universalviewer#545]
This is an updated version of #529, focusing only on the zoom behavior when searching within the viewer, with mockups that don't assume any changes to the viewer UI.

The fundamental idea is, I believe, straightforward:

- After a successful (one or more matches) search is performed, the page of the document with the first match is displayed, at 100% zoom level
- If the user uses the "Previous Result" or "Next Result" links to move between matches, the current zoom level is maintained, even if the next or previous match is on a different page of the document
- If the user uses any control other than the  "Previous Result" or "Next Result" links to move between pages in the document, the new page is displayed at 100% zoom, even if the user previously adjusted the zoom level

### New search results
The user executes a search that returns 24 results, the first of which is on page 2 of a 46 page document:

<img width="568" alt="pg2-hit-1-zoom-100" src="https://user-images.githubusercontent.com/101482/36322007-1200877e-1309-11e8-8517-e42575ee1e7a.png">

- The sidebar changes to reflect that page 2 is the current document
- Page 2 of the document is shown in the viewer, at 100% zoom (even if immediately before executing the search the user had been viewing at a zoom level other than 100%)
- (The mockup also indicates that the current match is highlighted with a different color than the other matches on the page, but in the interests of separating concerns I'll write that up in a different ticket; it's just easier to convey what's going on in the mockups if it's clear what the current match is)

### Navigating search results using "Next Result"
The user starts moving through the results using the "Next Result" link:

<img width="570" alt="pg2-hit-2-zoom-100" src="https://user-images.githubusercontent.com/101482/36322334-291bfa28-130a-11e8-83fa-2866422b690f.png">

- Nothing (other than the highlighted match) changes, since the user hasn't adjusted the zoom level and we're still on the same page

Assume that the user now decides to zoom in on the current page, to 150% zoom level, to better read the text.

### Navigating search results using "Next Result" at adjusted zoom level
The user now uses "Next Result" to move to the third match on page 2:

<img width="567" alt="pg2-hit-3-zoom-150" src="https://user-images.githubusercontent.com/101482/36323277-9bca7b8c-130d-11e8-972f-7270f2690214.png">

- The highlighted match is now the third one on page 2, but the zoom level is maintained at 150%

The user continues to navigate matches using the "Next Result" link. Since the next match is on page 4, the displayed page changes:

<img width="570" alt="pg4-hit-1-zoom-150" src="https://user-images.githubusercontent.com/101482/36323397-0c473bca-130e-11e8-8ec7-371ddd2ce7ad.png">

- The zoom level is still at 150%, despite the page change, because the user used the "Next Result" link to navigate the matches
- If the user next used the "Previous Result" link, we'd go back to the third match on page 2, with the zoom level remaining at 150% 

### Navigating search results using other UI controls
The user decides to jump to the end of the matches, using the rightmost blue match indicator icon, by scrolling through the sidebar and clicking on the page 18 page icon, or by using the page navigator icon available on hover in the main page area:

<img width="566" alt="p18-hit-1-zoom-100" src="https://user-images.githubusercontent.com/101482/36323586-9bf51648-130e-11e8-99ac-ca929b1a1f38.png">

- Page 18 is now displayed at 100% zoom, despite the fact that the user was previously at 150%. This is because the user navigated in the content search context using a control other than the "Previous Result" or "Next Result" links.

**Comment by mialondon** [comment]
Makes sense to me! Thanks for outlining the options.

**Comment by aeschylus** [comment]
I'll add one other case that I think might need different handling here. Trying out the recent example implementation, it seems to be behaving as described above, with the exception of the initial result behaviour. Leaving that aside for a moment, I wonder if we can specify the behaviour of clicking the next/previous result button _after_ the user has already navigated using a different control. So, picking up at the end of @ggeisler 's example 4 ("Navigating search results using other UI controls") above, if the user _then_ clicks the "next result" button, is:

*1.* the zoom level "maintained" at 100% (the "current zoom level"), or
*2.* is the next result focused at the "current" zoom level held over from the last time(s) they clicked next or previous result?

The current de facto behaviour is (2). I think (1) would be more fluid.

**Comment by edsilv** [comment]
Please try the latest code at universalviewer.io/examples and let me know if we're ready to close this. Many thanks

**Comment by ggeisler** [comment]
@edsilv Looks good to me, nice work! I'd like someone else at Stanford to also take a look before we close this ticket, @mejackreed, @snydman, or @aeschylus?

**Comment by aeschylus** [comment]
Yes, I've gone through the cases and this seems to be the behaviour described above. Looks good!
