### ISSUE TITLE
Update content search matched term highlighting

### ISSUE THREAD

**Issue by ggeisler** [UniversalViewer/universalviewer#547]
As noted in #545, our recommendations for updating the zoom behavior for content search includes adjustments to the search result matched term highlighting. The viewer currently marks all matches with blue highlighting. When navigating the results there doesn't appear to be a clear visual distinction that would enable the user to understand what is the currently active match and what are all the non-active matches:

<img width="408" alt="ce-spsc_final_decisions_2001_04b-2001_sabino_gouveia_leite_judgment_pdf__-_virtual_tribunals__test__-_online_exhibits" src="https://user-images.githubusercontent.com/101482/36324893-2bf8f4a4-1313-11e8-8451-0142c9add435.png">

We'd like to see the currently active match highlighted with a different color than the other matches on the page. (We might have to work on exact colors to ensure accessible contrast.) As an example, here the user has navigated to the third match on the page:

<img width="234" alt="spotlight_graffle__public___document_show_-_full-text_viewer_uv" src="https://user-images.githubusercontent.com/101482/36325022-985821f6-1313-11e8-8473-b24837a5ecae.png">

**Comment by edsilv** [comment]
Closing as fixed
