### ISSUE TITLE
Content search UI updates

### ISSUE THREAD

**Issue by ggeisler** [UniversalViewer/universalviewer#548]
Below are recommendations for updating the UV UI elements related to the content search experience. These were previously included in #529 but as part of separating different aspects of #529 into distinct chunks of work this ticket will just focus on the UI recommendations. For reference, here's the current UI in a content search context:

<img width="485" alt="ce-spsc_final_decisions_2001_04b-2001_sabino_gouveia_leite_judgment_pdf__-_virtual_tribunals__test__-_online_exhibits" src="https://user-images.githubusercontent.com/101482/36326087-236d77f2-1317-11e8-80c3-5fc3b7fb6958.png">

## Recommendations

- Eliminate the two rows that contain the teardrop icons and the previous/next result links.

- Eliminate the blue-bordered highlight that surrounds the thumbnail area (not visible in the screenshot above) when a document is selected.

- Eliminate the white-bordered styling on the currently selected thumbnail (covered by the more prominent document highlight shown in the examples below).

- Update the sidebar scrollbar to more closely resemble a browser scrollbar.

- Add small arrow icons next to the sidebar scrollbar to indicate which pages have search result hits (similar in function to the current teardrop icons).

- Add a search box to the bottom of the sidebar.

- Add hit count indicator and hit navigation adjacent to the search box.

## Examples

<img width="569" alt="34732217-d36266e0-f521-11e7-9678-d41a1fb32055" src="https://user-images.githubusercontent.com/101482/36325621-a294a0f2-1315-11e8-8191-0afcc6252c7e.png">

- Arrow icons next to the scrollbar show which pages in the document have hits. In the example above, there are hits on pages 2, 4, 6, 7, 8, 9, 18, and 46 (in a 46-page document). The first page in the document with a hit is selected and indicated by the colored arrow icon and the rectangular border.

- The hit indicator in the search box shows the currently active hit with the total number of matches (17/25). The previous and next icons enable the user to move through the matches, replacing the function of the current  "Previous Result" or "Next Result" links.

For comparison, here's how the elements above change when the user moves through the matches to arrive at a different page:

<img width="569" alt="34732251-f466264c-f521-11e7-81bd-c41c20d13945" src="https://user-images.githubusercontent.com/101482/36325869-59c820f0-1316-11e8-8495-21cf79136f27.png">

---

When the user first encounters the viewer, or clears the terms in the search box, the search box is empty but should show a search icon to make clear the purpose of the control. Ideally, the search icon is just implemented like placeholder text; it is visible when the search box is empty, but as soon as the user clicks in the box or the box contains search terms, the search icon is not visible (this saves on horizontal space, which is tight in this design):

<img width="197" alt="34732009-32b1de4c-f521-11e7-8c29-8cddb6c4e555" src="https://user-images.githubusercontent.com/101482/36325961-b4fd574c-1316-11e8-89f4-7d52fec61577.png">

If the user hovers over a page indicator when results are displayed, a tooltip displays the page number and number of hits on that page. Ideally, if the page is not the currently displayed page, the hit indicator text is linked so the user can click directly in the tooltip to move to that page in the viewer:

<img width="173" alt="34732004-2b228eb0-f521-11e7-9b49-1a1284ec9c95" src="https://user-images.githubusercontent.com/101482/36325976-c3574fc8-1316-11e8-8d2d-541b1d250448.png">

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
