### ISSUE TITLE
broken thumbnails

### ISSUE THREAD

**Issue by edsu** [UniversalViewer/universalviewer#549]
Does anyone have an idea why thumbnails are broken when viewing this manifest? 

http://universalviewer.io/uv.html?manifest=http://aadhum.mith.us/manifests/mdu-062626.json

The manifest appears to validate in http://iiif.io/api/presentation/validator/service/

**Comment by edsilv** [comment]
Hi, they're 404ing. I tried loading the URLs directly:

http://aadhum.mith.us/images/e183afbb18ee2e71d86e87238d4645b0/full/90,/0/default.jpg?t=1519032793864

Thought maybe the `t=` timestamp was throwing it. But it didn't work without it either?

**Comment by edsu** [comment]
But why isn't UV using the thumbnail that is designated in the manifest? Am I expressing it incorrectly?

**Comment by edsu** [comment]
Ahh, thanks. I subscribed to that & will close this. My issue is that I have a level 0 manifest (a bunch of static tiles) so I cannot respond to dynamic requests for images.
