### ISSUE TITLE
Explore how to (usefully) pass query terms to UV

### ISSUE THREAD

**Issue by ggeisler** [UniversalViewer/universalviewer#550]
This might be a design-needed ticket at this point. The goal is to explore potential approaches for passing query terms -- from a discovery environment, for example -- to the viewer when the user wants to look at a document in more detail. This feature was previously described in #529 but that ticket is going to be closed in favor of multiple, more specific tickets.

Useful comments on this feature were provided by @tomcrane and @edsilv:

- https://github.com/UniversalViewer/universalviewer/issues/529#issuecomment-364250257
- https://github.com/UniversalViewer/universalviewer/issues/529#issuecomment-364853659
- https://github.com/UniversalViewer/universalviewer/issues/529#issuecomment-364880911
- https://github.com/UniversalViewer/universalviewer/issues/529#issuecomment-367257813

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
