### ISSUE TITLE
New approach to PDF support

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#551]
(this originates from https://github.com/sul-dlss/universalviewer/issues/16#issuecomment-344985069)

## Background

UV originally used pdf.js and the viewer.js that goes with it. This was replaced by pdfobject for the reasons discussed in the above link. Updates to Firefox mean this approach is no longer workable if we want to maintain consistent UX across browsers. And, Bug: it doesn't work in Firefox!

## Proposal

Drop PDFObject and reintroduce pdf.js, this time without using viewer.js.

## Details

Re-implement PDF support, building up from pdf.js but using the UV's existing user interface approach for page-to-page navigation, thumbnails, and search if possible. That is, the UV drives the pdf.js library directly instead of offloading UI to viewer.js. 

This is an iterative process that can be split into further issues as the work progresses.The first task is to render a navigable PDF.

**Comment by edsilv** [comment]
Rendering a navigable pdf using pdf.js is complete. Closing

**Comment by mejackreed** [comment]
Gotcha thanks @tomcrane . I was just reviewing what was currently in master and making sure that I was seeing the correct thing locally.
