### ISSUE TITLE
Image sizing issues when navigating from manifest to manifest within a collection

### ISSUE THREAD

**Issue by terrywbrady** [UniversalViewer/universalviewer#555]
#**UV version:**

```
 universalviewer@2.0.2
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
We have deployed a manifest containing 14 collections.  Each collection has multiple items.  See https://repository.library.georgetown.edu/handle/10822/1044538

Manifest: https://repository.library.georgetown.edu/manifests/keller.json

We notice that when we navigate between canvases within a single manifest, images size properly in the UV.  When we switch from manifest to manifest via the collection index, the first canvas displayed in the new manifest does not size properly within the viewer.  Using the url above, navigate to "Box 4 Folder 43".  When the image first displays, it does not size properly.  If you navigate between canvases within that manifest, image sizing behaves as desired.

**Expected behavior:**
Images of any size should fit within the UV window when (1)navigating between canvases or (2)navigating between collection manifests.

**Steps to reproduce:**
Instructions listed above

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
![image](https://user-images.githubusercontent.com/1334393/36989009-54ea251c-2098-11e8-9c84-909b1547a838.png)

May need to clear xywh values between reloads to prevent larger images being zoomed in.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Appears to be fixed.
