### ISSUE TITLE
Extra height allocated to thumbnails in Contents sidebar

### ISSUE THREAD

**Issue by ggeisler** [UniversalViewer/universalviewer#557]
When looking at the latest updates we noticed that there is sometimes significant empty space between the bottom of a thumbnail image in the sidebar and its title. It appears that all thumbnails+titles are allocated the same vertical space, based on the tallest thumbnail in the object. This makes sense for images that are side-by-side (to keep the row even, height-wise) but would it be possible to adjust based on actual height of the images, so that in the example below the first row wouldn't have the extra space indicated by the red arrow?

<img width="989" alt="atari_competition___stanford_digital_repository" src="https://user-images.githubusercontent.com/101482/37124465-906c3632-2225-11e8-94b4-76c460c5c7a2.png">

I realize this isn't a new problem and the new border color probably just makes it more obvious, but I'm still curious if the fixed space allocated for all thumbnails is unavoidable.

**Comment by edsilv** [comment]
It chooses the median height of all thumbnails if I remember correctly.

This is so that it can reliably auto-load them on scroll.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity (and answer to question above).
