### ISSUE TITLE
pagingEnabled not inherited anymore from config?

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#558]
**UV version:**
```
 current master branch ( commit 7f8c7cb64185837a971739346bb50283f1a17b91 )
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When options.pagingEnabled is set to true, and the sequence has viewingHint "paged",
the two-page-view should be enabled.

This two-page-view is only enabled after using the button "two page view" in the settings dialogue.
All internal methods like "isPagingEnabled" all return true.

**Expected behavior:**
When options.pagingEnabled is set to true, and the sequence has viewingHint "paged",
the two-page-view should be enabled.

**Steps to reproduce:**
e.g. https://adore.ugent.be/IIIF/manifests/archive.ugent.be%3A1A63E728-1005-11E3-B305-6CDE97481370

current code here seems to work:

http://universalviewer.io/examples/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb19974760-0%2Fmanifest&locale=en-GB#?c=0&m=0&s=0&cv=2&manifest=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Farchive.ugent.be%253A1A63E728-1005-11E3-B305-6CDE97481370&xywh=-1%2C-1629%2C8092%2C7198

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by nicolasfranck** [comment]
Maybe because the method updateSettings isn't called on the Extension while loading the config?
Anyway, when calling this method (by clicking on the button "two-page-view"),
it works.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
