### ISSUE TITLE
viewingHint generates invalid thumbnails in download dialogue

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#559]
**UV version:**
```
https://github.com/UniversalViewer/universalviewer/commit/7f8c7cb64185837a971739346bb50283f1a17b91
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Links to invalid iiif thumbnails from download dialogue.
This happens when the viewingHint is "continuous".

**Expected behavior:**
Don't know. This has the same problem as the two-page-view.
Can one generate a thumbnail link to something that has been
stitched in the browser? A link to the canvas data url (png)?
(would only work for the "current view"). Seems like download
options should be disabled..

**Steps to reproduce:**
http://universalviewer.io/examples/?#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fhamsun0.ugent.be%2FIIIF%2Fmanifests%2FRUG01-001872682&xywh=9065%2C-4704%2C22662%2C14197

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
related: https://github.com/UniversalViewer/universalviewer/issues/338

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity. #338 has been closed.
