### ISSUE TITLE
uv.getContentState / uv.setContentState

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#562]
As a user, I want to capture the state of the **content** (what I'm looking at) for bookmarking/sharing purposes. This is distinct from viewer state (what panels are open etc).

So that I can open it in another viewer/annotation tool

As a user, I want to mark the start and end points of a piece of video to describe a clip
So that I can cite it.

This second example is NOT a function of the UV. But you can write some simple script that uses the UV to achieve this, if the UV's API has a getter and setter for the precise content state.

See https://iiif.slackarchive.io/softwaredevs/page-10/ts-1508144299000347 for more context.

Also see https://github.com/UniversalViewer/universalviewer/issues/439 which is basically the same info, in a dialogue.

Example:

UV is playing a video; containing page calls `uv.getContentState()`
UV returns:

```
{
  "type": "Annotation",
  "motivation": "highlighting",
  "target": {
   {
	  "start": {
	    "type": "SpecificResource",
	    "source": {
	      "id": "https://example.org/iiif/id1/canvas1",
	      "type": "Canvas",
	      "within": {
		"id": "https://example.org/iiif/id1/manifest",
		"type": "Manifest"
	     }
	    },
	    "selector": {
	      "type": "PointSelector",
	      "x": 10,
	      "y": 10,
	      "t": 14.5
	  }
   },
   "generator": { // UV state encoded here? }
}
```

**Comment by tomcrane** [comment]
motivation could be `linking` instead. Or something else.

**Comment by tomcrane** [comment]
Implement another UV data provider that understands the info in the form given in that annotation.
Make a test page to listing some manifests that can be opened in UV (and Mirador) using that syntax.
Update UV's drag and drop impl to _also_ support that syntax.

**Comment by tomcrane** [comment]
Cut and paste INTO UV is tricky because there's nowhere to open a new URL - that's not what the UV is really for.
But reading from URL params is easy as above^^
And drag and drop should be OK too.

**Comment by tomcrane** [comment]
IIIF Discovery import to viewers format proposal:

https://docs.google.com/document/d/1LKhEWWuYF-8KLkKcW_u2GlvX0epohwc7OYOVjICie5M/edit

The UV query string (# fragment) could be an annotation, or at least use the same fields in such a way that the #fragment to anno to #fragment conversion is trivial.

**Comment by tomcrane** [comment]
This and #462 are different aspects of the same problem.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity. #462 is related and has been closed.
