### ISSUE TITLE
Netlify to build Pull requests and master branch builds

### ISSUE THREAD

**Issue by stephenwf** [UniversalViewer/universalviewer#564]
**UV version:** N/A

**I'm submitting a:**
- [ ] bug report
- [x] feature request 
- [ ] support request 

**Current behavior:**
Manual process to publish to Github pages, not built on pull requests. The source control contains the built assets, including minified assets.

**Expected behavior:**
N/A

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
Link to netlify: https://www.netlify.com/

**Comment by edsilv** [comment]
related: https://github.com/UniversalViewer/universalviewer/issues/342

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
@edsilv, is this done already? I think it might be, but I'm not 100% sure.

**Comment by edsilv** [comment]
This is working with Vercel

**Comment by demiankatz** [comment]
Thanks, @edsilv, closing as done.
