### ISSUE TITLE
Document all configuration options

### ISSUE THREAD

**Issue by hackartisan** [UniversalViewer/universalviewer#565]
on the wiki.

**Comment by gschechter84** [comment]
With the configuration editor being unavailable for the newer version this documentation would be extremely helpful!!!

**Comment by edsilv** [comment]
I want to reinstate the config editor if possible as a generic json-editing web component using stencil.js

**Comment by edsilv** [comment]
related:  https://github.com/UniversalViewer/universalviewer/issues/605

**Comment by mialondon** [comment]
Is there any movement on this?

**Comment by edsilv** [comment]
@mialondon I think we should discuss this on the next steering group call. We're going to need to make it part of the next community sprint, which needs organising.

**Comment by mialondon** [comment]
@edsilv when is that? (Not that BL people can join, I assume)

**Comment by edsilv** [comment]
It's on the 18th at 3pm. I think we can probably allow it just this once :-)

**Comment by m-art-in** [comment]
Looking for this, too - since the editor is gone.....

**Comment by edsilv** [comment]
Our next community sprint is supposed to be about documenting config. However, I'm wondering if the priority should be getting the config editor reinstated...

**Comment by hackmastera** [comment]
How would one use the config editor, if it existed? I suspect I would prefer to have documentation than figure out how to spin up and use such a tool. I'd likely have to re-learn how it works each time I want to make a change.

**Comment by edsilv** [comment]
Previously it used this npmjs.com/json-editor, but I think this is looking
pretty unmaintained now... People seemed to find it quite intuitive though.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by mialondon** [comment]
If there's documentation now, please link to it and close the issue - otherwise we still need documentation for configuration options! 

Ideally documentation would be public and human-readable so that we can share it with internal stakeholders to help them specify which options they'd like configured in specific instances. As the UV/IIIF is embedded in more projects, helping people articulate more precisely what they want will save a lot of time all round.

**Comment by edsilv** [comment]
This is related to our work on setting up Storybook as interactive documentation: https://github.com/UniversalViewer/universalviewer/pull/892#issuecomment-1342923698

However, this is currently blocked.

**Comment by demiankatz** [comment]
In old ticket #217, @edsilv proposed that we use "description" in json schema to provide inline help. Description is at the same level as type and properties for every object. Not sure if this idea is still applicable, but just capturing here for the record.

**Comment by edsilv** [comment]
I've pushed this to `main`. You need to run `npm run docs` to generate the contents of a `/docs` folder. This is available to view at `localhost:8080/docs`

Ideally it would also be available at https://docs.universalviewer.io. I've tried following the github docs to set this up, but there's something wrong with it. I'll leave it to a future community call to figure that out.
