### ISSUE TITLE
AR Interface Issues

### ISSUE THREAD

**Issue by doingandlearning** [UniversalViewer/universalviewer#587]
**UV version:**
```
 universalviewer@2.0.2
```

**I'm submitting a:**
- [x] bug report

**Current behavior:**
When viewing UV in Arabic there are some formatting issues 
- the blue 'OK' button at the top of the page is mis-aligned.  Rather than making room for the longer text, the button shifts down and out of line with the rest of the interface.
- 'About the item' is left-aligned, even in RTL languages.

**Expected behavior:**
- The blue button should remain in-line no matter how long the text on the button
- All of the labels should take alignment based on whether the text is RTL/LTR - most do, but 'About the item' currently doesn't'.

**Steps to reproduce:**
Open the viewer in AR (I've just logged a pull request that has the AR translations)

**Comment by edsilv** [comment]
@doingandlearning just catching up with issues..! Is this still a problem? I think you got the Arabic translation working in the end in v3? Did you see my comment on slack about just needing to add the remaining translations to `contentLeftPanel` in https://github.com/UniversalViewer/universalviewer/pull/586 ?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
