### ISSUE TITLE
Add zoom and pan of PDF pages

### ISSUE THREAD

**Issue by mejackreed** [UniversalViewer/universalviewer#589]
** New Feature **

For a pdf, create functional zoom and pan buttons (similar to uv-osd controls)

**Comment by tomcrane** [comment]
Hi @mejackreed 

Current implementation:
http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17502792%2Fmanifest

Is there anything further to do on this in the current schedule of work?

**Comment by mejackreed** [comment]
Thanks @tomcrane . Zoom is working great! Though I'm not seeing the pan buttons, not sure if that was also wanted by @snydman .

@snydman ^^ see the above comment, are there other things on the current schedule of work?

**Comment by edsilv** [comment]
We went with using scroll bars for this functionality.
