### ISSUE TITLE
Navigation Thumbnail

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#59]
Hi, I've noticed that changing to "Full Screen" makes the navigation thumbnail in the bottom right corner go smaller. This happens in both Chrome and Firefox on Ubuntu and Windows 7.

Dylan

**Comment by edsilv** [comment]
linked to https://github.com/UniversalViewer/universalviewer/issues/39

**Comment by LlGC-dwj** [comment]
Thanks Ed
