### ISSUE TITLE
Embedded iframes not working

### ISSUE THREAD

**Issue by stephenwf** [UniversalViewer/universalviewer#590]
**UV version:** master branch

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
[Embedded iframes](http://uv.netlify.com/uv/uv.html#?manifest=https://wellcomelibrary.org/iiif/b29828764/manifest&c=0&m=0&s=0&cv=0&config=examples-config.json&locales=en-GB:English%20(GB),cy-GB:Cymraeg&xywh=-1928,-627,6497,4795&r=0) currently fail to load the manifest

**Expected behavior:**
Should load the manifest, like the [main viewer](https://uv.netlify.com/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb29828764%2Fmanifest)

**Comment by edsilv** [comment]
The path to `examples-config.json` in the hash params was incorrect, needed to be: http://uv.netlify.com/uv/uv.html#?manifest=https://wellcomelibrary.org/iiif/b29828764/manifest&c=0&m=0&s=0&cv=0&config=../examples-config.json&locales=en-GB:English%20(GB),cy-GB:Cymraeg&xywh=-1928,-627,6497,4795&r=0
