### ISSUE TITLE
Origin parameter appended to login URL

### ISSUE THREAD

**Issue by exlcodeshare** [UniversalViewer/universalviewer#591]
**UV version:**

```
 universalviewer@3.x (no output, blank in cog)
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Authentication API - login. UV seems to always append the 'origin' parameter using a '?' (instead of a '&' when the login URL already contains a query parameter), so that the user is redirected to https://host/login?param=abc?origin=https://host/uv instead of

**Expected behavior:**
https://host/login?param=abc&origin=https://host/uv 

**Steps to reproduce:**
define an auth service id as 
```
service": {
    "@context": "http://iiif.io/api/auth/1/context.json",
    "@id": "https://host/login?param=abc",
...
}
```

**Related code:**
Seems to be caused by modules/uv-shared-module/Auth1.ts:
```
 static getCookieServiceUrl(service: Manifesto.IService): string {
        let cookieServiceUrl: string = service.id + "?origin=" + Auth1.getOrigin();
        return cookieServiceUrl;
    }
```

**Other information:**
Is this something you'd like us to try to fix?

**Comment by edsilv** [comment]
Adding this to the next community call agenda.

**Comment by edsilv** [comment]
Perhaps you could try using: https://github.com/edsilv/utils/blob/master/src/Urls.ts#L50

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity; auth needs to be updated to v2 anyway.
