### ISSUE TITLE
Presentation v3 manifests should not require a separate thumbnail property on a canvas to display a thumbnail

### ISSUE THREAD

**Issue by jronallo** [UniversalViewer/universalviewer#593]
**UV version:**
Unknown. What version is http://universalviewer.io/examples running?

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

UV will not show a thumbnail in the left side panel for a v3 manifest unless the `thumbnail` property is populated for a canvas. Even if the canvas has an image annotation with an image service, UV will not show a thumbnail for the canvas.

**Expected behavior:**

This is something of a regression in behavior. UV should have some algorithm for determining an appropriate thumbnail to display. Here's a quick shot at what this might look like:

First look for a thumbnail property. If there is a thumbnail property then look for a service within. If there is an image service on the thumbnail use the service. If there is not an image service on the thumbnail use the `id`. If there is no thumbnail property then look for the first image annotation. If the resource has an image service use that. Otherwise fallback to the static image annotation.

**Steps to reproduce:**
This manifest works: http://universalviewer.io/examples/#?manifest=https%3A%2F%2Fd.lib.ncsu.edu%2Fcollections%2Fcatalog%2Fnubian-message-2003-04-01%2Fmanifest%3Fv3%3Dtrue

If you remove the thumbnail properties. it fails to show thumbnails in the side pane.

**Comment by tomcrane** [comment]
@jronallo related: https://github.com/UniversalViewer/universalviewer/issues/102

**Comment by rosetta-development** [comment]
Hi, 

Please task a look at -
https://github.com/IIIF-Commons/manifesto/issues/24

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by kirschbombe** [comment]
I think this issue was resolved with the work to support IIIF Image service?

**Comment by demiankatz** [comment]
Does anyone have an example manifest without thumbnail properties that we can test with to confirm?

**Comment by kirschbombe** [comment]
Here is a cookbook recipe for a simple book manifest that has no thumbnail properties: https://iiif.io/api/cookbook/recipe/0009-book-1/. This generates thumbnails in UV 4.0.25: https://www.universalviewer.dev/#?xywh=-1565%2C-257%2C6333%2C5125&iiifManifestId=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0009-book-1%2Fmanifest.json

**Comment by demiankatz** [comment]
Very helpful, @kirschbombe! Thank you! I'll close this as resolved.
