### ISSUE TITLE
Duplicate collections

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#594]
**I'm submitting a:**
- [x] bug report

With the online version of UV, I'm getting an error when trying to use the following collection:

http://presentation.bdrc.io/2.1.1/collection/wio:bdr:W22084

(see [here](http://universalviewer.io/uv.html?manifest=http://presentation.bdrc.io/2.1.1/collection/wio:bdr:W22084) live).

The reported error in the Javascript console of Firefox 60.0.1  under Debian Linux is:

```
TypeError: manifest is undefined
```

and under Chrome 66 (seems to be basically the same, but with an interesting stacktrace):

```
bundle.min.js:4 Uncaught (in promise) TypeError: Cannot read property 'options' of undefined
    at Collection.getManifestByIndex (bundle.min.js:4)
    at bundle.min.js:9
Collection.getManifestByIndex @ bundle.min.js:4
(anonymous) @ bundle.min.js:9
Promise.then (async)
Bootstrapper._loaded @ bundle.min.js:9
(anonymous) @ bundle.min.js:9
Promise.then (async)
(anonymous) @ bundle.min.js:9
Bootstrapper.bootstrap @ bundle.min.js:9
loadManifest @ bundle.min.js:10
e.bootstrap @ app.js:1
(anonymous) @ app.js:8
execCb @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
(anonymous) @ require.min.js:1
setTimeout (async)
req.nextTick @ require.min.js:1
localRequire @ require.min.js:1
requirejs @ require.min.js:1
(anonymous) @ app.js:8
```

All the collections and manifests are valid according to the iiif presentation validator.

What I'm trying to achieve is to lazy-load a huge collection by just loading one level after another. For instance if I have (`C` is for Collection, `M` is Manifest)

```
C1
|- C11
   |- M111
   |- M112
|- C12
```

I want to first load

```
C1
|- C11
|- C12
```

then if the user opens `C11`, I want UV to fetch `C1` that will give:

```
C11
 |- M111
 |- M112
```

is that something that could theoretically be achieved?

**Comment by edsilv** [comment]
Sorry for the delayed response. I'm adding this to our next community call agenda.

**Comment by edsilv** [comment]
Looks like it's working with lazy loading in the latest version here: http://universalviewer.io/examples/#?c=&m=&s=&cv=1&manifest=http%3A%2F%2Fpresentation.bdrc.io%2F2.1.1%2Fcollection%2Fwio%3Abdr%3AW22084&xywh=757%2C-77%2C485%2C438. Is it possible to upgrade? `npm i universalviewer@beta`

**Comment by eroux** [comment]
Oh that's really great! thanks a lot! There are still a few problems though:
1. only the first section displays with a `+` button that I can unfold, while the others should too (see screenshot below)
2. when I unfold the S001 section, I'm getting the subcollections twice while the json contains them only once (you can also see it in the screenshot)

The screenshot is taken from you link with a recent Chrome:

![buguv](https://user-images.githubusercontent.com/60868/44921608-537e4b80-ad43-11e8-827c-4ab16cb37938.png)

**Comment by edsilv** [comment]
We think there should probably be a plus sign for collections even if we don't know if there are any contents yet - @LlGC-szw is going to write a user story as we're not 100% on the UX for that yet.
In the meantime I'll look at the doubled-up contents bug.

**Comment by eroux** [comment]
great, thanks!

**Comment by eroux** [comment]
@edsilv maybe I should close this issue and open a new one for the duplicate manifests?

**Comment by eroux** [comment]
Another instance of the problem, just to record tests: http://eroux.fr/buguv2/buguv3.html , using the collection at http://eroux.fr/buguv2/tibcolldemo2.json

(see the correct result in Mirador for the same collection: http://eroux.fr/tibcolldemo2.html )

**Comment by eroux** [comment]
thanks!
