### ISSUE TITLE
French version of the viewer

### ISSUE THREAD

**Issue by JBPressac** [UniversalViewer/universalviewer#596]
Hello,
They are many unreviewed french translations for UV on Transifex which prevent those to be integrated in UV. I would be pleased to review them if you give me the rights to do so.
Thanks,

**Comment by edsilv** [comment]
Hi, thank you - that would be great. Let me know your email and I'll add you.

**Comment by JBPressac** [comment]
Hello,
I revised many french translations in Transifex but I have some questions about the meaning of some expressions as "Manifest Ranges": is range a synonym of order ? Does it refers to [Range](http://iiif.io/api/presentation/2.1/#range) ?. 

In which context the "Opens in a new window" is displayed (do you have any examples) ? 

Same for "placeholder text" (is placeholder a synonymous of [filler text](https://en.wikipedia.org/wiki/Filler_text) ?).

Does "Volume" refers to a sound volume ?

Does "Locale" which is used to select the language setting of the viewer should not be replaced by "Language" ?

Thanks,

**Comment by edsilv** [comment]
Hi,

I think "Manifest Ranges" was added so that there's an aria-label on the drop down box for selecting which top-level tree to use when you have multiple top-level ranges. Maybe a label of "structure" would be better?

"Opens in a new window" is for when the `downloadDialogue.optionsExplanatoryTextEnabled` option is enabled.  This shows a piece of text below each download option explaining what will happen when you click on them.

I'm not sure why "placeholder text" is necessary... I think "filler text" could be used instead. The help dialogue where it is used isn't enabled by default.

"Volume" refers to sound volume.

"Language" is fine instead of "Locale".

**Comment by edsilv** [comment]
I will add this to the v3 board along with completing arabic translations.

**Comment by edsilv** [comment]
You will need to create a custom theme for the french translation:

![image](https://user-images.githubusercontent.com/1334393/43992822-37f7f202-9d7c-11e8-92d7-713ce6f29e4a.png)

**Comment by edsilv** [comment]
e.g. https://github.com/UniversalViewer/uv-cy-gb-theme

**Comment by JBPressac** [comment]
Do you mean a theme for instance to make adjustment to the gap between the "Aller" blue button and the page number ?

**Comment by JBPressac** [comment]
Hello,
Should the themes (e.g. https://github.com/UniversalViewer/uv-cy-gb-theme) be build or modified "by hands" ? As the themes repositories are ditinct from UV repository, I am a bit puzzled about the right way to generate the french custom theme.
Thanks,

**Comment by JBPressac** [comment]
Hello,
I have found you [tutorial to create custom themes](https://universalviewer.gitbooks.io/custom-themes/content/). However, I am stuck to the `grunt sync:bowerComponents` step with the error:
```
Running "sync:bowerComponents" (sync) task
Verifying property sync.bowerComponents exists in config...ERROR
>> Unable to process task.
Warning: Required config property "sync.bowerComponents" missing. Use --force to continue.
```
I also tried `grunt sync:bowerComponents --force` and got the new error:

```
Verifying property sync.bowerComponents exists in config...ERROR
>> Unable to process task.
Warning: Required config property "sync.bowerComponents" missing. Used --force, continuing.
```

Any ideas about this problem ?
Thanks,

**Comment by mejackreed** [comment]
I think that tutorial is likely out of date now @JBPressac . 

Have you tried just `grunt sync` instead?

**Comment by JBPressac** [comment]
Hello,
Actually, I am stuck before the `grunt sync` step. When I execute `bower update`  after modifying bower.json and deleting src/themes/uv-en-GB-theme directory as mentioned in the tutorial, I have got this error message:

```
bower                     invalid-meta for:/home/jean-baptiste/Dev/universalviewer/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower uv-en-GB-theme#*          cached https://github.com/JBPressac/uv-en-GB-theme.git#1.1.1
bower uv-en-GB-theme#*        validate 1.1.1 against https://github.com/JBPressac/uv-en-GB-theme.git#*
bower uv-cy-GB-theme#*          cached https://github.com/UniversalViewer/uv-cy-GB-theme.git#1.1.1
bower uv-cy-GB-theme#*        validate 1.1.1 against https://github.com/UniversalViewer/uv-cy-GB-theme.git#*
bower uv-cy-GB-theme#*         install uv-cy-GB-theme#1.1.1
bower uv-en-GB-theme#*         install uv-en-GB-theme#1.1.1
bower                      postinstall grunt sync:bowerComponents
bower                      postinstall Running "sync:bowerComponents" (sync) task
bower                      postinstall Verifying property sync.bowerComponents exists in config...
bower                      postinstall ERROR
bower                      postinstall >> Unable to process task.
bower                      postinstall Warning: Required config property "sync.bowerComponents" missing. Use --force to continue.
bower                      postinstall Aborted due to warnings.
bower                          ECMDERR Failed to execute "grunt sync:bowerComponents", exit code of #3
```
I modified bower.json as follow:

```
  "dependencies": {
    "uv-cy-GB-theme": "UniversalViewer/uv-cy-GB-theme",
    "uv-en-GB-theme": "JBPressac/uv-en-GB-theme"
  },
```
This problem occured with a today clone of https://github.com/UniversalViewer/universalviewer.git.

Thanks,

**Comment by m-art-in** [comment]
Any Process here? I also tried to modify the theme. Is there a new tutorial?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
I see that the UV now contains a French-language theme, so I believe this is resolved. If there are pending translations somewhere that need to be added, please open a new issue.
