### ISSUE TITLE
IIIF Collections don't let you re-navigate to the first manifest

### ISSUE THREAD

**Issue by tpendragon** [UniversalViewer/universalviewer#600]
**UV version:**

```
 universalviewer@3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When loading a multi-volume work as a IIIF Collection with a viewing hint of "multi-part", if you navigate in the table of contents to the second manifest, and then attempt to click the first manifest again, it takes you to the first canvas of the manifest you're on rather than back to the first manifest.

You can see it here: [http://universalviewer.io/examples/#?c=1&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb19974760&xywh=-1173%2C0%2C5109%2C3770](http://universalviewer.io/examples/#?c=1&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb19974760&xywh=-1173%2C0%2C5109%2C3770)
**Expected behavior:**

Clicking the first manifest after navigating away should return you to the first volume.
**Steps to reproduce:**

1. Navigate to [http://universalviewer.io/examples/#?c=1&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb19974760&xywh=-1173%2C0%2C5109%2C3770](http://universalviewer.io/examples/#?c=1&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb19974760&xywh=-1173%2C0%2C5109%2C3770)
2. Click a child of "Volume 5, 1864"
3. Click a child of "Volume 1, 1859"

Notice you're on the first page of "Volume 5, 1864"

**Comment by eroux** [comment]
also exemplified on http://eroux.fr/buguv2/buguv2.html

**Comment by edsilv** [comment]
I've followed the steps to reproduce, but am not seeing an issue... (I think). Could someone make a screencast and talk over it describing what they expect to see? That would really help, sorry!

**Comment by eroux** [comment]
here is a screencast:

[uvbug2.zip](https://github.com/UniversalViewer/universalviewer/files/2911246/uvbug2.zip)

- on volume 1
- click on volume 2
- on volume 2
- click on volume 1
- still on volume 2 instead of on volume 1 (bug)
- click on volume 3
- on volume 3

**Comment by tpendragon** [comment]
We've seen this fixed since February 20 - sorry for not closing it earlier!
