### ISSUE TITLE
Error when trying to enable branchNodesSelectable

### ISSUE THREAD

**Issue by escowles** [UniversalViewer/universalviewer#606]
**UV version:**
```
 universalviewer@3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
When I configure `modules.contentLeftPanel.options.branchNodesSelectable = true` and click a branch node with children in the index tab, the viewer does not navigate to the node, and I see an error in my console.

**Expected behavior:**
When I configure `modules.contentLeftPanel.options.branchNodesSelectable = true` and click a branch node with children in the index tab, I expect the viewer to navigate to the first child of that branch node.

**Steps to reproduce:**
* Go to https://figgy-staging.princeton.edu/catalog/35e4c85b-61da-4640-844e-68e6844f2a4a
* Click on "Chapter 2" — which expands/collapses, but does not navigate to a new page.

**Related code:**

The error is being triggered here: https://github.com/UniversalViewer/universalviewer/blob/55f031bd7a34886c350ce77c4b5d0912da3d5ce8/src/extensions/uv-seadragon-extension/lib/iiif-tree-component.js#L101

**Other information:**
* Stack trace: see [gist](https://gist.github.com/escowles/e2f5632ec2a3dba41242b55b3062b4c4)
* Related to https://github.com/pulibrary/figgy/issues/859

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
This refers to a legacy UV version and cannot be easily reproduced. Please open a new issue if this is still a problem.
