### ISSUE TITLE
Viewer does not gracefully exit full screen mode when a new tab is opened

### ISSUE THREAD

**Issue by terrywbrady** [UniversalViewer/universalviewer#609]
**UV version:**

```
v2.0.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
- Navigate to page containing the viewer: https://repository.library.georgetown.edu/handle/10822/1044538
- Open full screen mode
- Navigate to a different object
- Download an object (a new tab will open)
- Return to the original tab - the viewer will have exited full screen
- The viewer displays behind other elements on the page

**Expected behavior:**
- The viewer should display normally and not be hidden behind other elements

**Steps to reproduce:**
See the description above.  We have seen this behavior in multiple browsers.

The screenshot here is from Chrome.

**Related code:**

```
// insert any relevant code here
```

Here is a screenshot:

![image](https://user-images.githubusercontent.com/1111057/44555283-4b8e2e00-a6e9-11e8-821c-6f1e3e14b046.png)

Please let me know if you recommend that I adjust CSS to resolve this issue.

**Other information:**

**Comment by stephenwf** [comment]
The UV currently listens for `fullscreenchange` and relies on this to detect if we've been toggled. Due to some browsers security, you don't actually get these events fired off if you come out of fullscreen without using the fullscreen API.

https://github.com/UniversalViewer/universalviewer/blob/197cc1938c70dd5f8fd4688c672c31c00311e1f5/src/helpers.js#L121-L127

We could, for external links, manually fire the close fullscreen function before then opening the link.

**Comment by terrywbrady** [comment]
I have a partial work-around for this issue.  I am adding the following javascript to app.html.

    <script type="text/javascript">
    $(document).ready(function(){
      $("div.rightPanel a,div.download a.btn-primary").on('click', function(e) {
        var e = document.createEvent('HTMLEvents');
            e.keyCode = 27;
            e.initEvent(type, false, true);
            document.dispatchEvent(e);;
      });
    });
    </script>

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
I cannot reproduce the problem as described; I believe that this has been fixed.
