### ISSUE TITLE
support fragmentselector

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#610]
**I'm submitting a:**
- [x] feature request

Following a discussion on slack (\#general), I would like to request UV to be able to understand `oa:FragmentSelector` in annotation targets. For instance I'd like to be able to replace

```json
"on": "http://dams.llgc.org.uk/iiif/2.0/4574752/canvas/4574755.json#xywh=2218,3217,371,78"
```

with

```json
"on" : {
   "@type" : "oa:SpecificResource",
   "full" : "http://dams.llgc.org.uk/iiif/2.0/4574752/canvas/4574755.json",
   "selector" : [
   {
     "@type" : "oa:FragmentSelector",
     "value" : "xywh=2218,3217,371,78"
   }]
}
```

**Comment by tomcrane** [comment]
See https://github.com/ProjectMirador/mirador/issues/1137 for fuller discussion

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
A search of the UV code turns up some processing related to SpecificResource and FragmentSelector; I'm not sure if this exactly addresses the issue highlighted here, but given the age and inactivity of this issue and the lack of a manifest for testing purposes, I'm going to close this for now. Feel free to open a new issue with a live example manifest if further action is still needed.
