### ISSUE TITLE
XSS vulnerability: executing code in HTML tags included in labels

### ISSUE THREAD

**Issue by escowles** [UniversalViewer/universalviewer#612]
**UV version:**

```
 universalviewer@3.0-alpha
```

**I'm submitting a:**

- [x] bug report

**Current behavior:**
When I load a manifest with a `label` that includes Javascript in HTML tags (e.g., https://figgy-staging.princeton.edu/concern/scanned_resources/f022b69d-f2b2-40c3-a34f-4d21af5be276/manifest), the Javascript is executed.

**Expected behavior:**
I expect the Javascript to be sanitized or escaped, and not executed.

**Steps to reproduce:**
Here is a URL that loads a manifest that demonstrates this issue: https://figgy-staging.princeton.edu/uv#?manifest=https://figgy-staging.princeton.edu/concern/scanned_resources/f022b69d-f2b2-40c3-a34f-4d21af5be276/manifest

**Other information:**

**Comment by escowles** [comment]
See https://github.com/samvera/hyrax/issues/3187 Vulnerability 4

**Comment by edsilv** [comment]
I've created a PR here adding img protocols to the sanitizer, but it's not the solution: https://github.com/IIIF-Commons/iiif-metadata-component/pull/9

Unfortunately it's to do with how the sanitize.js `clean_node` function works. It accepts a DOM element which means you have to put the HTML into an element before sanitizing it... 

https://github.com/IIIF-Commons/iiif-metadata-component/blob/master/examples/index.html#L134

I think we're probably going to have to use an alternate regex-based method.

**Comment by irv** [comment]
i know we don't want to add any more dependencies, and i'm not an expert, but this looks like a reasonable thing to replace with? https://github.com/leizongmin/js-xss

**Comment by edsilv** [comment]
Looks good. 24,786,094,770 downloads last month :-O

**Comment by edsilv** [comment]
This is now fixed using xss.js:

http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Ffiggy-staging.princeton.edu%2Fconcern%2Fscanned_resources%2Ff022b69d-f2b2-40c3-a34f-4d21af5be276%2Fmanifest&xywh=-838%2C-412%2C8506%2C5407

https://iiif-commons.github.io/iiif-metadata-component/examples/ (click on the xss button)
