### ISSUE TITLE
Incorrect `root` configuration value silently fails

### ISSUE THREAD

**Issue by stephenwf** [UniversalViewer/universalviewer#618]
**UV version:**
```
 universalviewer@dev-master
```

**I'm submitting a:**
- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
If you do not pass in the configuration value `root` and the configuration does not exist 

**Expected behavior:**
Throw an error or some other indication that a configuration value is incorrect or wrong.

**Steps to reproduce:**
N/A

**Related code:**
N/A

**Other information:**
N/A

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
