### ISSUE TITLE
Minus button is not working in PDF Viewer (at universalviewer.io)

### ISSUE THREAD

**Issue by terrywbrady** [UniversalViewer/universalviewer#621]
**UV version:**

```
 Hosted at universalviewer.io
```

**I'm submitting a:**

- [ x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
When viewing the following PDF, the minus button does not work.  The plus button does work.

http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Frepository.library.georgetown.edu%2Fmanifests%2Fpdf.json

**Expected behavior:**
The minus button should reduce the zoom in the viewer

**Steps to reproduce:**
See the link above for a sample manifest.

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
Fixed by: https://github.com/UniversalViewer/universalviewer/pull/625
