### ISSUE TITLE
PDF Viewer should detect PDF's with inconsistent page sizes and should scale the first page display to show the full page

### ISSUE THREAD

**Issue by terrywbrady** [UniversalViewer/universalviewer#622]
**UV version:**

```
Version at universalviewer.io
```

**I'm submitting a:**

- [ x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
The following PDF has inconsistent page sizing. Note that the first page is partially rendered.  In full screen mode, the full page does render.

http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Frepository.library.georgetown.edu%2Fmanifests%2Fpdf.json

**Expected behavior:**
The first page view should scale to reveal the full contents of the first page.

When paging through the document at the default zoom level, each page should render completely within the viewer.

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Cannot reproduce; problem appears to be resolved.
