### ISSUE TITLE
Don't show deprecation warnings for getAttribution

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#634]
Fix deprecation warning in UV (don’t call getAttribution anywhere).
In manifesto make getAttribution a proxy of getRequiredStatement and put the attribution fallback logic into getRequiredStatement.

Related: https://github.com/IIIF-Commons/manifesto/issues/37

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive
