### ISSUE TITLE
Viewer doesn't exit full screen when in Full Screen Mode (SHFT-CMD-F) of Chrome browser.

### ISSUE THREAD

**Issue by mccallum** [UniversalViewer/universalviewer#635]
**UV version:**

```
 universalviewer@3.0.32
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Exit from full screen doesn't size back when in Full Screen Mode of the Chrome Browser.

**Expected behavior:**

**Steps to reproduce:**

Open Universal Viewer in latest Chrome on Mac.
Use Shift-Command-F to enter Chrome's Full Screen Mode.
Click button in lower right corner to enter Universal Viewer's full screen.
Click button in lower right corner to exit UV's full screen.
UV doesn't recover. 
(In some implementations online of unknown version, UV resizes only on the vertical. Problem appears to only be in Chrome.)

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
I'm unable reproduce this on http://universalviewer.io/examples using Chrome Version 71.0.3578.98 (Official Build) (64-bit) on High Sierra v10.13.4. Are you seeing any console errors?

**Comment by mccallum** [comment]
Here's a screen shot with console warnings using Version 71.0.3578.98 (Official Build) (64-bit) and High Sierra 10.13.6:
<img width="2560" alt="screenshot 2019-01-15 09 26 53" src="https://user-images.githubusercontent.com/1591022/51198166-591a9f00-18a8-11e9-9288-ef0514f1314a.png">

Note the padding on top and left and the fullscreen button in lower right bumped out so it can't be used.

**Comment by edsilv** [comment]
That's odd, this is for the same page as well? http://universalviewer.io/examples

**Comment by edsilv** [comment]
Can you try setting a breakpoint in http://universalviewer.io/examples/uv/helpers.js on line 94 and letting me know wht happens?

![image](https://user-images.githubusercontent.com/1334393/51245669-50959780-1980-11e9-9c27-018d05f1dc67.png)

**Comment by mccallum** [comment]
The viewer _does_ return to original size if I step over 95-97 after the breakpoint, yes.

**Comment by edsilv** [comment]
Is `getExitFullScreen` returning anything?

![image](https://user-images.githubusercontent.com/1334393/51307476-babd4380-1a37-11e9-9ded-3d768865f8f8.png)

**Comment by edsilv** [comment]
Not sure - wasn't that related to dispaying the "Exit Fullscreen" text correctly? It sounds like the button is visible and triggering `toggleFullScreen` correctly - just something is happening between lines 95-97 that's going awry...

**Comment by mccallum** [comment]
Yes, [Native Code] is returned. WebkitExitFullScreen is hit in Safari where the resize is working. I've disabled all my extensions in Chrome and can make a little video if that is helpful.

**Comment by edsilv** [comment]
I'm noticing that pressing escape when in full screen in Chrome on Windows is exhibiting the behaviour you describe. Have a feeling it's related.

**Comment by edsilv** [comment]
Have pushed v3.0.33 to http://universalviewer.io/examples/
I know I've fixed exit fullscreen bugs in Chrome and Firefox on Windows, but curious to see if it helps with the issue you're seeing.

**Comment by mccallum** [comment]
Yes! Looks and performs great.
