### ISSUE TITLE
Attribution overlay positioned too low on AV extension

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#638]
**UV version:**

```
 universalviewer@3.0.32
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

![image](https://user-images.githubusercontent.com/1334393/51803766-9f7ce000-2250-11e9-9a3e-24d39de95899.png)

**Expected behavior:**
Should appear above the playhead bar.

**Steps to reproduce:**

Happens sporadically, suggesting it's something related to load order.

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive
