### ISSUE TITLE
Wrong CSS path for uv-mediaelement-extension using custom theme

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#642]
**UV version:**

```
 universalviewer@3.0.32
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

I've added our custom theme to the UV but when testing one of our AV manifests the UV isn't rendered correctly. There is a uv-av-extension folder in my theme, but the UV is looking for it in the default theme which isn't present. Chrome console log shows that it's looking for uv-en-gb-theme in offline.js.

I have the following in my package.json

```
"@llgc/uv-llgc-cy-gb-theme": "git+https://github.com/LlGC-dwj/uv-cy-GB-theme.git",
"@llgc/uv-llgc-en-gb-theme": "git+https://github.com/LlGC-dwj/uv-en-GB-theme.git",
"@universalviewer/uv-cy-gb-theme": "1.1.2",
"@universalviewer/uv-en-gb-theme": "1.1.2",
```

**Expected behavior:**

The manifest https://datasyllwr.llgc.org.uk/manifests/dlg/VISIT_OF_THE_RT_HON.json should run as it does on universalviewer.io.

**Steps to reproduce:**

**Related code:**

```
http://localhost/uv/themes/uv-en-gb-theme/css/uv-mediaelement-extension/theme.css net::ERR_ABORTED 404 (Not Found)
```

**Other information:**

**Comment by edsilv** [comment]
I solved this by changing this line in my `config.js`: `npmthemes: './node_modules/@llgc',`

I also needed to rename the repos in the UV's package.json to `uv-en-gb-theme` instead of `uv-llgc-en-gb-theme` and rename them in the each theme's package.json: https://github.com/LlGC-dwj/uv-cy-GB-theme/blob/master/package.json#L3
