### ISSUE TITLE
impossible to open manifest in a mixed (manifests/collections) collection

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#644]
**UV version:**

```
 universalviewer@2.0.2
```

(from http://universalviewer.io/vendor/uv/lib/embed.js )

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

I load the following collection:

http://eroux.fr/buguv.json

in UV. It contains a manifest and a collection (in that order). Example with an embedded UV:

http://eroux.fr/buguv2.html

The collection, in second position is displayed instead of the manifest, in first position. When I click on the label corresponding to the manifest in the Index tab of the left panel, UV remains open on the collection and doesn't switch to the manifest.

**Expected behavior:**

The manifest opens first. If I am in the collection, when clicking on the manifest label in the Index tab of the left panel, the manifest is displayed.

**Steps to reproduce:**

Look at

http://eroux.fr/buguv2.html

**Other information:**

**Comment by edsilv** [comment]
Is this solved by upgrading to v3? https://github.com/UniversalViewer/universalviewer/issues/594#issuecomment-417700480

**Comment by eroux** [comment]
No: http://eroux.fr/buguv2/buguv2.html (using 3.0.16) still displays the problem

**Comment by eroux** [comment]
Another instance of the problem, just to record tests: http://eroux.fr/buguv2/buguv3.html , using the collection at http://eroux.fr/buguv2/tibcolldemo2.json

(see the correct result in Mirador for the same collection: http://eroux.fr/tibcolldemo2.html )

**Comment by eroux** [comment]
thanks!

**Comment by LlGC-szw** [comment]
Did you manage to successfully test this @eroux ?

**Comment by eroux** [comment]
I have not, is there an easy way to do that?

**Comment by LlGC-szw** [comment]
There is! https://uv-community-sprint-1.netlify.com/ is the community sprint test deployment. You need to press 'set' once you've pasted your manifest into the box - don't be fooled return will work, it won't :D

**Comment by eroux** [comment]
Thanks! I've fixed the ssl certificate errors and a few others so now http://eroux.fr/buguv2/tibcolldemo2.json can be tested again. The issue seems fixed, but there's a weird bug where UV doesn't follow 302 redirects for manifests... Is it really that or is this a side effect of another bug?
