### ISSUE TITLE
more control over initial view

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#647]
When loading a collection, UV opens the first manifest and the left pane is on the "Thumbnails" tab. For our use of UV it would be much easier if this was adjustable, we would want no manifest open and the left pane on the "Index" tab. I think these could be two configuration options.

**Comment by edsilv** [comment]
I think you need to use `defaultToTreeEnabled: true` leaving `defaultToTreeIfGreaterThan: 0`.  This will mean it always defaults to showing the tree panel:

https://github.com/UniversalViewer/universalviewer/blob/master/src/extensions/uv-seadragon-extension/config/en-GB.json#L68

**Comment by eroux** [comment]
thanks, it works!
