### ISSUE TITLE
document v3 embedding

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#648]
I tried to embed UV3 but I cannot find any up to date documentation to do so. On the wiki:

https://github.com/UniversalViewer/universalviewer/wiki/Embedding

the advise is to use the script at

http://universalviewer.io/uv/lib/embed.js

which advertises version 2.0.2.

I tried to find the file [embed.js](https://github.com/UniversalViewer/universalviewer/blob/master/src/lib/embed.js) in [jsdelivr](https://www.jsdelivr.com/package/npm/universalviewer?path=uv) for version 3.0.16 but it doesn't seem to be there.

Is there a way to embed a version of UV in a webpage without doing the npm install/build process? If so can it be documented on the wiki?

Possibly related:
- https://github.com/UniversalViewer/universalviewer/issues/156
- https://github.com/UniversalViewer/universalviewer/issues/528

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
The [examples page](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) should address this, including an example of loading UV3 from a CDN.
