### ISSUE TITLE
gratuitous reloading when clicking on a manifest in a collection

### ISSUE THREAD

**Issue by eroux** [UniversalViewer/universalviewer#649]
Exemplified in http://eroux.fr/buguv2/buguv2.html : 
- open collection "Derge Kangyur" (which unfolds the collection)
- click on any volume
- click on another volume

the entire UI gets reloaded and the collection is folded again.

**Comment by eroux** [comment]
(note that looking at the developer console, UV also reruns requests on the collections and manifests URLs. Most of the time they're cached in the browser so it's sort of ok, but I don't think it's a good thing to do)

**Comment by eroux** [comment]
here's a screencast of what I see (Firefox / Linux):

[uvbug.zip](https://github.com/UniversalViewer/universalviewer/files/2910746/uvbug.zip)

**Comment by edsilv** [comment]
possibly related: https://github.com/UniversalViewer/universalviewer/issues/603

**Comment by geekscruff** [comment]
I'm seeing gratuitous reloading in the main panel on my site - https://archive.kingsfund.org.uk

**Comment by edsilv** [comment]
We're thinking to use https://github.com/edsilv/utils/blob/master/src/Utils.ts#L328 to cache manifests in local storage in manifold here: https://github.com/IIIF-Commons/manifold/blob/master/src/Manifold.ts#L5
(more discussion on #community-sprint https://universalviewer.slack.com/archives/CA2RSMW31/p1562592551084100)

**Comment by eroux** [comment]
Great, thanks! That will solve the network calls, but I'm not sure this is really the core of this issue though, which is more a UI reloading problem than a network problem

**Comment by edsilv** [comment]
@stephenwf and I have been talking about this. Really we need to think about moving over to webpack or similar. The UV Steering Group call is on Thursday and the roadmap for future community sprints is on the agenda. I think everyone understands that the UV is a very long-running project and in need of a bit of a refresh - it's just how to plan this in a way that works for everyone :-)

**Comment by eroux** [comment]
sure! looking at what Mirador does, it sure looks like a big update is a good thing! I can't say I'm not annoyed by being in the space in between an unmaintained Mirador 2 and a not ready Mirador 3, but I still think it's going in the right direction

**Comment by edsilv** [comment]
I think the UV is in a good place in terms of being able to incrementally improve (we're calling it the "Ship of Theseus" plan). It's already highly componentised, and TypeScript makes refactors _ridiculously_ easier. At the end of the day the BL, NLW, etc are in for the long haul. We have to move slowly, but (to labour the nautical analogies) we've charted a course and the winds are at our backs :-)

**Comment by eroux** [comment]
good to read! :)

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity -- this conversation pre-dates the migration to WebPack.
