### ISSUE TITLE
Remove flatmap-stream and event-stream module dependencies

### ISSUE THREAD

**Issue by Geoffsc** [UniversalViewer/universalviewer#651]
Remove flatmap-stream and event-stream module dependencies which are malicious:
https://www.npmjs.com/advisories/737
event-stream references flatmap-stream
event-stream is included in lib/utils/dist/utils.js

**Comment by edsilv** [comment]
I just tried an `npm i universalviewer@beta` and didn't get any warnings. Could you tell me the steps to reproduce? Many thanks!
