### ISSUE TITLE
Metadata values aren't being localised

### ISSUE THREAD

**Issue by mel-mason** [UniversalViewer/universalviewer#652]
**UV version:**

```
 universalviewer@2.0.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
With a bilingual english/german manifest and locale set to English the metadata labels are correctly localised to English, but any metadata values with multiple language choices stay in German. I.e. with a manifest containing the metadata block in 'related code' I get the following metadata in the universal.io demo
```
Date: 1462
Digitization Project: Handschriften aus dem deutschen Sprachraum
```

**Expected behavior:**
Metadata values with multiple language choices should be localised to the correct language. I.e. with a manifest containing the metadata block in 'related code' and locale set to English I should get the following metadata
```
Date: 1462
Digitization Project: Manuscripts from German-Speaking Lands
```

**Steps to reproduce:**
Use a manifest with the following top level metadata block in the UV demo (I can't currently give you the full manifest I was using, sorry)

**Related code:**

```
"metadata": [
  {
    "label": [
      {
        "@language": "en",
        "@value": "Date"
      },
      {
        "@language": "de",
        "@value": "Datierung"
      }
    ],
    "value": "1462"
  },
  {
    "label": [
      {
        "@language": "de",
        "@value": "Digitalisierungsprojekt"
      },
      {
        "@language": "en",
        "@value": "Digitization Project"
      }
    ],
    "value": [
      {
        "@language": "en",
        "@value": "Manuscripts from German-Speaking Lands"
      },
      {
        "@language": "de",
        "@value": "Handschriften aus dem deutschen Sprachraum"
      }
    ]
  }
]
```

**Other information:**

May be an issue with only some of the values having multiple language choices? Although this is permitted in the presentation spec. All of the labels have multiple language choices.

**Comment by irv** [comment]
can confirm this also seems to be the case in UV 3

**Comment by mel-mason** [comment]
Example manifest in presentation API 2: https://iiif.hab.de/object/mss_272-helmst/manifest.json

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Cannot reproduce -- I believe this problem has been fixed.
