### ISSUE TITLE
Zoom to result not working

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#653]
**UV version:**

```
 universalviewer@3.0.33
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Since upgrading our test viewers to version 3.0.33 I've been unable to zoom to results a feature we need for our Places of Wales website.
I've set the following in the config settings

> "zoomToSearchResultEnabled": true

But that doesn't seem to take any effect.

**Expected behavior:**

I should be able to zoom to the result if this setting is set.

**Steps to reproduce:**

**Version 2 example**
http://universalviewer.io/uv.html?manifest=https://damsssl.llgc.org.uk/iiif/2.0/4642022/manifest.json

**Version 3 example**
Not sure if this setting is set on this example but it works the same as our internal examples.
http://universalviewer.io/examples/#?c=&m=&s=&cv=602&manifest=https%3A%2F%2Fdamsssl.llgc.org.uk%2Fiiif%2F2.0%2F4642022%2Fmanifest.json&xywh=-3008%2C-409%2C10885%2C8177

Searching for **Jones** shows what I mean.

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
This was a combination of `zoomToBounds` being `false` in the config, and `zoomToBoundsEnabled` looking in the wrong place: https://github.com/UniversalViewer/universalviewer/commit/8ef2508bfe63fdd082b5bdaf59b0c9807badfe30#diff-19807bfc80c3793851c564cc9b7c38deR888

**Comment by LlGC-gel** [comment]
@edsilv Is this issue fixed in v4? I'm having the same issue in v4 and can't seem to get it to work.
