### ISSUE TITLE
Question regarding disabling of downloads within Presentation Manifests

### ISSUE THREAD

**Issue by jrgriffiniii** [UniversalViewer/universalviewer#656]
Currently, the IIIF Presentation 2.1.1 and 3.0 ALPHA specifications provide one with the ability to encode manifests with information regarding the service used for providing additional information about the image resource (please see https://iiif.io/api/annex/services/#requirements and https://iiif.io/api/presentation/3.0/#service).  The Universal Viewer does support these, but I've been struggling to use this in order to disable downloads (I believe that this feature is offered in https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-dialogues-module/DownloadDialogue.ts#L222, via Manifold in https://github.com/IIIF-Commons/manifold/blob/master/src/Helper.ts#L750).

For a V2 Presentation Manifest, I have the following:

```
service: {
  @context: "http://universalviewer.io/context.json",
  profile: "http://universalviewer.io/ui-extensions-profile",
  disableUI: [
    "mediaDownload"
  ],
},
```
(please see https://gist.githubusercontent.com/jrgriffiniii/db690cc6c89b818d45dffa9773dbcd44/raw/505968e8b47aa5d2d4959c63fc7291dd7c756e5b/manifest_v2.json and http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fgist.githuebusercontent.com%2Fjrgriffiniii%2Fdb690cc6c89b818d45dffa9773dbcd44%2Fraw%2Fbf70bffe9eb8996d6dbed6dcf59045b9c0680559%2Fmanifest_v2.json&xywh=-1827%2C886%2C7659%2C4869)

For V3, I have attempted this:
```
service: [
  {
    @context: "http://universalviewer.io/context.json",
    profile: "http://universalviewer.io/ui-extensions-profile",
    disableUI: [
      "mediaDownload"
    ],
  }
],
```
(please see the examples at https://gist.githubusercontent.com/jrgriffiniii/45fba6407b87cf453a22da0cc11febad/raw/8836ee9b41b115954e97e34d1df8dda6fe608c8b/manifest_v3.json and http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fgist.githubusercontent.com%2Fjrgriffiniii%2F45fba6407b87cf453a22da0cc11febad%2Fraw%2F8836ee9b41b115954e97e34d1df8dda6fe608c8b%2Fmanifest_v3.json&xywh=-3464%2C-547%2C12160%2C7730).

In the V2 case, downloads don't seem to be disabled at all.  In the V3 case, there seems to be a note that download options are not available, but there are still radio buttons offered which permit clients to download the images.  Are these manifests malformed in their structure in any way?

**Comment by irv** [comment]
`mediaDownload` controls if the UV offers the source image for download. if you want to restrict all the download options, you'll need to set `footerPanel.options.downloadEnabled` to `false`

see http://access.bl.uk/item/viewer/ark:/81055/vdc_000000021732 for an example,
https://api.bl.uk/configuration/universalviewer/v2/ark:/81055/vdc_000000021732 is the linked config

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity.
