### ISSUE TITLE
Error when clicking on any Table of Content elements

### ISSUE THREAD

**Issue by julsraemy** [UniversalViewer/universalviewer#658]
**UV version:**

```
 universalviewer@2.0.2
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
I’ve been asked by the Swiss National Library to verify the IIIF Manifest that their software provider created for them (Veridian). They have created a demo site with IIIF Manifests and for instance, when https://demos.veridiansoftware.com/swisspressonline/iiif/issue/EIZE18451025-01/manifest.json is loaded onto the UV, it is not possible to click on any elements of the table of content (index or thumbnails) without crashing the viewer (cf. Image below).

<img width="925" alt="image" src="https://user-images.githubusercontent.com/17925031/54703728-a382fb00-4b39-11e9-9870-19740cce5ede.png">

It could be that there is a problem with the Manifest itself though.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Cannot reproduce.
