### ISSUE TITLE
detectPageModeEnabled setting

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#66]
During recent discussion with @kenlt regarding the British Library's requirements, a new global setting called `detectPageModeEnabled` was suggested. If set to true, on load the UV would check if any canvases in the manifest had a label property, and if none do, the `pageModeEnabled` config setting for the `pagingHeaderPanel`, `searchFooterPanel`, and `treeViewLeftPanel` modules would be set to false.

**Comment by edsilv** [comment]
This may be of interest to @demiankatz

**Comment by demiankatz** [comment]
@edsilv, thanks for bringing this to my attention. It doesn't directly affect me, since all of my canvases are guaranteed to have labels all the time (my manifest generator fills them in if they're missing), but it definitely makes sense in theory.

**Comment by tomcrane** [comment]
According to the spec, label is mandatory on canvas (i.e., it's not a valid IIIF manifest without them).

http://iiif.io/api/presentation/2.0/#b-summary-of-metadata-requirements

**Comment by edsilv** [comment]
hmm, I'll mention this to @kenlt
