### ISSUE TITLE
Preventing from asking user to login repetitively

### ISSUE THREAD

**Issue by berger-n** [UniversalViewer/universalviewer#664]
Building upon the following issues:
https://github.com/UniversalViewer/universalviewer/issues/624
https://github.com/IIIF/api/issues/1732
https://github.com/UniversalViewer/universalviewer/issues/631

My concern is that the "please login" message is shown everytime a thumbnail is clicked and opened in OpenSeaDragon though user is logged in.

After clicking on the login button a request is successfully made to a `/iiifcookielogin` route which returns an authentication token and then allows the user to see the restricted image.

But I suspect that sending a cookie along with the request to the `info.json` in OSD could avoid to trigger this repetitive login process, and that's why I am wondering why this parameter: https://github.com/UniversalViewer/universalviewer/blob/b90f79ec8a7d7854462a8a0db504ac9878d3fd4c/src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts#L155
cannot be set when instantiating UV - the point is that's how we managed to make Auth work in Mirador (v2.7) although they don't implement the IIIF Auth spec at all.

Also, I am afraid that bypassing `beforeSend` ajax parameter using `ajaxSetup` is not working because this parameter is explicitly redefined when ajax is called later on: to my understanding, `beforeSend` is set when ajax call is made which prevents from default value previously set in `ajaxSetup` to be used; furthermore, experiments show that a custom `beforeSend` function set as default value with `ajaxSetup` is never called.

**Comment by eroux** [comment]
Just to clarify: the user is already logged in and the cookie to our iiif server is already set when we open UV, and we would want UV not to ask the user to log in again

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to age/inactivity. I am aware that authentication is going to be (or has been) significantly revised since 2019. If there is still a problem, a new issue would be in order.
