### ISSUE TITLE
Uncaught error: language must have a value.

### ISSUE THREAD

**Issue by micheljp** [UniversalViewer/universalviewer#670]
I'm attempting to run the examples using my own manifest files.  I'm using index.html in the examples folder and replacing the manifests file in the getJson call with a copy of the manifest file complete with links to my own manifests.

This is what my manifest file looks like:

In the console i'm getting this error: `Uncaught Error: language must have a value at uv.js:5`

```{
  "@context": "http://iiif.io/api/presentation/2/context.json",
  "@id": "http://universalviewer.io/manifests.json",
  "@type": "sc:Collection",
  "collections": [
    {
      "@context": "http://iiif.io/api/presentation/2/context.json",
      "@id": "osul-manifests.json",
      "@type": "sc:Collection",
      "label": "OSUL",
      "manifests": [
        {
          "@id": "https://library.osu.edu/dc/concern/generic_works/sn00bs181/manifest.json",
          "@type": "sc:Manifest",
          "label": "Beer Barnes"
        },
        {
          "@id": "https://library.osu.edu/dc/concern/generic_works/sn00bj95p/manifest.json",
          "@type": "sc:Manifest",
          "label": "Beer Barnes 2"
        }
      ]
    }
  ]
}```

I'm looking at the example manifest files and I don't see a language field in any of them.  What am i missing?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Cannot reproduce.
