### ISSUE TITLE
Gallery component emits more canvases than user has selected

### ISSUE THREAD

**Issue by irv** [UniversalViewer/universalviewer#671]
**UV version:**

```
 universalviewer@2.0.2 (also HEAD)
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

when selecting some canvases which appear in more than one range, extra canvases are emitted in the event from the gallery component

**Expected behavior:**

only the selected canvases are emitted
**Steps to reproduce:**

http://access.bl.uk/item/viewer/ark:/81055/vdc_100025703033.0x000001

Select "some or all pages" to download. select pages 2-4 and 10-12 only. check console and see that the event emitted appears to include 54 canvases(!)

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity. Cannot reproduce as example URL is no longer loading.
