### ISSUE TITLE
left panel does not show thumbnails side by side

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#680]
**UV version:**

```
 universalviewer@3
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

In UV version 2, all thumbnails were shown per 2 in the left panel:

http://universalviewer.io/uv.html?manifest=https://adore.ugent.be/IIIF/manifests/archive.ugent.be%3A018970A2-B1E8-11DF-A2E0-A70579F64438#?c=0&m=0&s=0&cv=0&xywh=-5331%2C-516%2C22660%2C10311

In version 3, this does not work anymore:

http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fadore.ugent.be%2FIIIF%2Fmanifests%2Farchive.ugent.be%3A018970A2-B1E8-11DF-A2E0-A70579F64438&xywh=5216%2C1999%2C5999%2C5416

Strangely enough, all goes well when viewingHint is set to paged:

http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest&xywh=4%2C1016%2C2620%2C1968

I've looked in the source code, but all seems well there:
classes like oneCol and left-to-right are used correctly,
width and height of the images are set correctly.

**Expected behavior:**

Thumbnails in the left panel should be shown per 2.

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
I think this is the correct behaviour. You now need to have viewingHint: paged to see thumbs side by side. There are use cases where you want the thumbs to appear in a single column.

**Comment by nicolasfranck** [comment]
I understand, but in that case the panel becomes too wide. If you set the option `panelExpandedWidth` to a smaller value, then it becomes a problem for manifests
where the `viewingHint` is `paged` (thumbnails do not fit next to each other). 

And what about the fully expanded gallery?
There the thumbnails are always arranged from left to right. I think we should always
use all available space. It is simply more condense.

**Comment by edsilv** [comment]
`viewingHint` now deliberately applies to the thumbnail panel as not all manifests are `paged`. But I take your point about the gap... Maybe we should increase the size of the thumbs to fit the whole width of the panel? The expanded gallery just lists the thumbnails left-to-right without grouping them into pages, so should be ok as is.

**Comment by nicolasfranck** [comment]
ok

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
This appears to be resolved.
