### ISSUE TITLE
Two Page Thumbnails and viewer - Start with 2 pages view

### ISSUE THREAD

**Issue by rafaeluriarte** [UniversalViewer/universalviewer#684]
I couldn't find the correct configuration options for this so, so I'd appreciate if you can help me. When the viewer (set to show two pages) is opened, it shows the first page (in most implementations, the cover). However, since I do not have a cover image, I'd like to show straight 2 pages. 

The same for the thumbnails, the first page is always shown single (on the top right) and then they are shown in pairs. I'd like to show them in pairs from the first image. Is it possible?

Thank you

**Comment by adehner** [comment]
I'm interested in this too.

**Comment by stephenwf** [comment]
@rafaeluriarte @adehner Do you have IIIF example JSON for this behaviour (Presentation 2 or 3)? I don't think inline UV configuration would really work well in this case, since IIIF itself describes how they should be presented through it's behaviours.

**Comment by nicolasfranck** [comment]
@rafaeluriarte it's a problem in the specification of IIIF: it treats the first canvas as the cover, and there is no way to circumvent this. If your first canvas happens to be a right page, then you won't have this problem.

**Comment by rafaeluriarte** [comment]
Thank you @nicolasfranck . It would still be great to implement this feature or, if not possible,  this issue could be discussed in the IIIF consortium. With old documents, sometime you do not have a cover page (or it is missing) and having one single page on the top changes the order of the whole document...

**Comment by stephenwf** [comment]
Maybe the UV could allow for a "missing page" canvas, or some semantic description of a canvas without any content to act as the first page, and then the UV will notice this and remove it from the UI.

**Comment by nicolasfranck** [comment]
The problem is that such a solution would only work here, in the UV, completely discarding the purpose of IIIF: interoperability..

**Comment by stephenwf** [comment]
I would disagree, by adding a missing page you're conforming to the IIIF specification. For viewers that did not treat an empty canvas in any different way, they would simply see an empty canvas. So the data remains within the IIIF specification. The UV specific change could be to improve the user experience in the case where an empty canvas appears.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity. If the need still exists and @stephenwf's proposed solution does not meet it, please open a new issue.
