### ISSUE TITLE
Fall-back language choices

### ISSUE THREAD

**Issue by fractos** [UniversalViewer/universalviewer#7]
Both issues 5 and 6 require some form of fall-back – if “en” is required, choose the first “en” in the list (i.e., “en-GB” in this case). If “en-US” is required, the list does not contain it, but the viewer can fall back to “en”. The algorithm tries to match the language part if it doesn’t find an exact match for the whole string.

The viewer needs to pick the best match, both for available localisation files, and for JSON-LD value objects it encounters in the IIIF presentation API. Typically the “ambient setting” would be locale-language (e.g., “en-GB”), the chosen localisation file would be locale-language (“en-GB”), but the manifest value objects would just be language (“en”).

We can then produce variants of this file, one for each language we wish to support (or language and locale).

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
