### ISSUE TITLE
Set up prettier linting

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#712]
Set up prettier linting on build/CI, and add note to CONTRIBUTORS.md to set up prettier in vscode/IDE before submitting PRs.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as fixed
