### ISSUE TITLE
dom element id "content" may conflict with other systems like Drupal

### ISSUE THREAD

**Issue by akohlbecker** [UniversalViewer/universalviewer#713]
**UV version:**

```
 universalviewer@3.0.36
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

This is not actually a report for a bug which exists per se in Universalviewer but for a problem which arises when UV is integrated into Drupal for example.

**Description of the problem**

Universalviewer uses  the DOM element-id "content"  `<div id="content" class="content">` (see `src/modules/uv-shared-module/CenterPanel.ts`).
This conflicts directly with Drupal pages where "content" is used to identify the main content area. This causes the styles applied to the Drupal content also being applied to the UV content div which results in severe layout problems.

**Suggested solution:**

As far as I have seen the `id="content"` is not being used in universalviewer. Therefore removing the id from the content div should not cause any problems in UV but would avoid conflicts with applications into which UV is to be integrated and would avoid invalid DOMs when multiple UV instances are used in the same page. (Solution updated, see comment below)

**Comment by akohlbecker** [comment]
Over night I was re-thinking my suggestion to solve this issue. In the examples the usecase of placing multiple UV instances in one and the same page is demonstrated. In this case multiple dom elements with the same id would be in that page, rendering the dom invalid. Ids must be unique!

Therefore I suggest to remove the id from the content div completely. this would not cause any problem to the UV since it is not being used anyway.

**Comment by edsilv** [comment]
Sounds good to me! Please send a PR with the change :-)

**Comment by akohlbecker** [comment]
The PR is already there (https://github.com/UniversalViewer/universalviewer/pull/714) awaiting its acceptance.
