### ISSUE TITLE
Allow settings dialogue to highlight an option on open

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#72]
As per comment https://github.com/UniversalViewer/universalviewer/pull/71 pass the setting id to highlight:

```
$.publish(settings.SettingsDialogue.SHOW_SETTINGS_DIALOGUE, ["pagingEnabled"]);
```

Rather than passing a string for the id, it would be better to pass a typed property of a Settings class:

https://github.com/UniversalViewer/universalviewer/issues/40

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as inactive (discussed on 28/09/2023 Community Call)
