### ISSUE TITLE
Patch lodash vulnerability

### ISSUE THREAD

**Issue by darrowcousc** [UniversalViewer/universalviewer#726]
**UV version:**

```
 universalviewer@3.1.0
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Vulnerability description:
[High severity vulnerability in 4.17.11 #4348](High severity vulnerability in 4.17.11 #4348)
[Prototype Pollution](https://www.npmjs.com/advisories/1065)

**Expected behavior:**

Patched vulnerability.

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```
Available patches:
[fix: prototype pollution in _.defaultsDeep #4336](https://github.com/lodash/lodash/pull/4336)
[fix: prototype pollution in several npm packages #4337](https://github.com/lodash/lodash/pull/4337)

**Other information:**

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Lodash is now on 4.17.21
