### ISSUE TITLE
Use bower to manage extensions, modules, and themes

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#73]
Create repos for each extension and module on the UniversalViewer gh org (as per previous Wellcome Player setup).

However, instead of using git sub modules, use bower to install to a gitignored `/bower_components` directory.

Use a bower postinstall script (https://github.com/bower/bower/blob/master/HOOKS.md) to check the installed components for the `uv-(.*)-(extension|module)` pattern.

If an extension is matched, copy it to `src/extensions`. If a module is matched, copy it to `src/modules/`.

Using the convention of `uv-(.*)-(extension|module)` instead of examining the url of each component's repo is optimal as it allows forks of extensions/modules to be used.

Using `bower uninstall` will trigger a preuninstall script that removes the corresponding extension/module from src/.

**Comment by edsilv** [comment]
This would apply to themes as well. Remove the current git sub modules. Add uv-enGB-theme and uv-cyGB-theme repos to the gh org.

**Comment by edsilv** [comment]
Have decided against this. It resulted in an unwieldy workflow - developers want to be able to edit extensions and modules inline in the project, not as separate individual projects. Will keep the idea of "core" extensions and modules that are included in the repo by default. If valuable extensions/modules are created in forks of the UV, these can be pulled into the upstream repo when ready.

However, I'm keeping the themes as bower components. This makes sense as they no longer need to be git sub modules \*shudder\*, and there will ultimately be many of these to include as more languages are added. Themes are by nature stand-alone collections of images and css and lend themselves to this format.

In forks of the UV, the bower.json file can be altered to include custom themes, which may themselves be forks of existing themes:

    "dependencies": {
        "uv-cy-GB-theme": "UniversalViewer/uv-cy-GB-theme",
        "uv-en-GB-theme": "UniversalViewer/uv-en-GB-theme",
        "uv-custom-theme": "edsilv/uv-custom-theme"
    }

**Comment by edsilv** [comment]
@demiankatz I've just pushed this to master. Themes are now bower components.

After pulling, you'll need to do an `npm install` to get the new modules and then a `bower install` which will install the themes and copy them to the `src/themes` directory.

Obviously you'll need to have the bower CLI installed too.

You'll need to manually delete the old git sub module directories from `src/themes`.

**Comment by edsilv** [comment]
Have added the option to include extensions and modules as bower components:

https://github.com/UniversalViewer/universalviewer/commit/5d95327600fc7e344fa6341c4ff448e3d99077d9

I think this could be a convenient "try before you buy" option for trying out other extensions and modules without needing to include the files in your repo.

**Comment by edsilv** [comment]
Unlike the gitignored /themes directory, you would need to specify which extensions and modules to ignore yourself.

**Comment by demiankatz** [comment]
@edsilv, this seems to be causing some problems for me. Workflow:

1.) Check out clean copy.
2.) npm install
3.) bower install
4.) grunt build

output:

<pre>
Running "theme:dist" (theme) task
Warning: grunt is not defined Use --force to continue.

Aborted due to warnings.
</pre>

If I apply --force to push past the warning, some of the build completes, but the themes are missing. Am I doing something wrong (I am a Bower newbie) or is something incorrect in one of the repos? Thanks!

**Comment by edsilv** [comment]
Woops! If you pull:

https://github.com/UniversalViewer/universalviewer/commit/3c6a0f78797e109324fd79757bdb48fab4cbd3ef

It should now work.

**Comment by demiankatz** [comment]
Wonderful -- I'm back in action. Thanks!

**Comment by edsilv** [comment]
Just wanted to check - do you know that you can use `grunt` instead of `grunt build`? This will do a 'dev' build and produces source maps to the individual .ts files. You can inspect these in dev tools and set breakpoints etc. Makes debugging much easier.

**Comment by demiankatz** [comment]
Good to know! I was dimly aware that there was a way to do a dev build, but the need hadn't arisen yet. I'm sure I'll need to know this before too long, so thanks!
