### ISSUE TITLE
Support for audio only resources

### ISSUE THREAD

**Issue by glenrobson** [UniversalViewer/universalviewer#730]
**UV version:**
```
 universalviewer@v4.0.0-pre.12
```

**I'm submitting a:**

- [ x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
When loading the basic [audio IIIF Cookbook recipe](https://preview.iiif.io/cookbook/0002-simplest-audio-update/recipe/0002-mvm-audio/) I get an error in the console to say `Unable to determine media type`. 

**Expected behavior:**
To load the audio file. 

**Steps to reproduce:**
Go to: https://uv.netlify.app/#?c=&m=&s=&cv=&manifest=https://preview.iiif.io/cookbook/0002-simplest-audio-update/recipe/0002-mvm-audio/manifest.json

**Related code:**
When stepping through the code it seems this method `isVideo` should return false if its not a video but currently it throws `unable to determine media type` if it isn't a mp4 video or webm:

https://github.com/UniversalViewer/universalviewer/blob/d8f9ec7f1fb1beeb9e6198ca4f27e189aea92b00/src/extensions/uv-mediaelement-extension/Extension.ts#L184

**Comment by irv** [comment]
Works in https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fpreview.iiif.io%2Fcookbook%2F0002-simplest-audio-update%2Frecipe%2F0002-mvm-audio%2Fmanifest.json
So this is probably because the av component hasn't been ported to the webpack branch yet

**Comment by glenrobson** [comment]
This now works so closing.
