### ISSUE TITLE
Search and autocomplete on JP2 images

### ISSUE THREAD

**Issue by broy-github** [UniversalViewer/universalviewer#734]
Hello,

I have the JP2 images and now showing them using IIPServer in Universal Viewer.
Now, I want to implement the search and autocomplete functionality on those JP2 images in Universal Viewer.
I have a very large number of JP2 images.
The search and autocomplete functionality will have to be worked for all text inside the image.
Please guide me the implementation process in details.

Thanks

**Comment by broy-github** [comment]
Hello,

Can Manifest.json be created dynamically from my .Net application for all the images stored in IIPServer?
I have heard about creating annotations for searching and autocomplete.
I want to create dynamic annotations for all the texts from OCR without storing it anywhere.
How can I link the OCR to manifest.json? and how can I create dynamic annotations from it to use in search-api?
Please explain me in details.

Thanks

**Comment by edsilv** [comment]
Hi,
I'm afraid we have to limit use of github issues to bug reports. If you join the IIIF slack you may be able to get better answers there: https://iiif.io/community/
