### ISSUE TITLE
Browser freezes when browsing tiffs

### ISSUE THREAD

**Issue by kgronowski** [UniversalViewer/universalviewer#735]
**UV version:**

```
 universalviewer@3.1.1
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Browser's tab freezes entirely while browsing tiff images. Problem occurs in many browsers (Chrome, Firefox, Opera, MS Edge)

**Expected behavior:**

Browser is not freezing, you can freely browse tiffs.

**Steps to reproduce:**

Demo: https://rcin.org.pl/demo//dlibra/applet/publication/18329/edition/84065?handler=iiif&format_id=3
Browse for a while: change files, zoom in and out

**Other information:**

High CPU usage during freeze.

**Comment by stephenwf** [comment]
Was not able to replicate the browser tab freezing. I think I have an idea of what it could be though.

In your info JSON you have quite a few tile sizes available:
https://rcin.org.pl/demo/iiif/image/84065-1088014/info.json

When OpenSeadragon requests an image, it will create an HTML Canvas and paint that image on it as a sort of cache. This stores the images as a bitmap.

With 4 channels (rgba), each tile in memory is roughly: `4 bytes * width * height` ~ 1.5mb for a 672x560 tile

OpenSeadragon is most often used with 256x256 tiles which is about 260kb bitmap per tile. I think what might be happening is the graphics memory is being filled up more quickly with the larger tiles and is slower to swap (1.5mb vs 260kb) and is affecting performance there. 

I used Safari's "Graphics" tab to debug this, but I think FireFox has a similar dev-tool for debugging offscreen canvases.

A few options: 

- Change your image server configuration to serve 256 tiles and see if that fixes your issue
- Report the same bug to OpenSeadragon and see if they can improve the tile cache, maybe eject old caches when world items are removed or prefer loading tiles closer to 256x256.

**Comment by iangilman** [comment]
@stephenwf in UniversalViewer, when you switch between images, I assume it's removing the image from the OpenSeadragon viewer, right? That should clean out the tile cache for that image. If it's not doing so, perhaps OpenSeadragon has a leak of some sort?

I've added some thoughts to https://github.com/openseadragon/openseadragon/issues/1852, including that it's worth trying setting the `maxImageCacheCount` to something smaller than the default 200.

**Comment by stephenwf** [comment]
@iangilman UV calls `viewer.close();` and then `viewer.addTiledImage(...)` when switching images. I think the close should clean that out. To be honest, I think if the default is 200 – which is reasonable for 260kb – that's sounds like the cause. Maybe the default for that maximum could be based on the size of the tiles? Or maybe have a max cache "size" and approximate using the sizes of tiles in the cache

**Comment by iangilman** [comment]
Cool. Sounds like UV is doing the right things; thanks for confirming!
