### ISSUE TITLE
UV with Angular 2+

### ISSUE THREAD

**Issue by pawelprochnicki** [UniversalViewer/universalviewer#737]
Is there any doc / tutorial / explanation how to use UV in Angular 2+ application?

**Comment by stephenwf** [comment]
We're putting together https://github.com/UniversalViewer/uv-examples which contains some example integrations. This is running on version `^4.0.0-pre.16`

I think with any integration though the import parts are the files external to the UV that need to be available when you deploy your site (usually a `public` folder or similar).

Here's the. files currently required:
https://github.com/UniversalViewer/uv-examples/blob/master/react/package.json#L18-L21

I think we can reduce this further as we use more features of webpack.

As for the javascript side, you should be able to run:
```js
import { init } from "universalviewer";

const uv = init(htmlElement, { manifestUri: ' ... url here ... ' });

uv.on('created', () => {
    uv.resize();
}, false);
```

For an Angular integration, you need 2 requirements. 1 is the `htmlElement` variable that gets passed to the init. That needs to be the HTML element where you want the UV to appear. In React there is a way to get a "ref" to the underlying HTML element, I expect there is something similar for Angular.

The other requirement is to get that code snippet above, init and the resize event, to run only once. 

If you want to control the UV externally, then you could optionally save that `uv` variable to a model or similar in angular and use it in closures to bind to the UI.

**Comment by pawelprochnicki** [comment]
Thanks for answer :-)
I have some problems. When a try `npm instal` version 4.0.0-pre.16 or 3.1.1, I've get error:
`> universalviewer@3.1.1 postinstall /Users/pawelprochnicki/webdev/uv-examples/js/node_modules/universalviewer
> opencollective postinstall

/Users/pawelprochnicki/webdev/uv-examples/js/node_modules/core-js/modules/_typed-buffer.js:157
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
                                ^

RangeError: Wrong length!
    at validateArrayBufferArguments (/Users/pawelprochnicki/webdev/uv-examples/js/node_modules/core-js/modules/_typed-buffer.js:157:39)
    at new ArrayBuffer (/Users/pawelprochnicki/webdev/uv-examples/js/node_modules/core-js/modules/_typed-buffer.js:247:29)
    at zlib.js:334:28
    at NativeModule.compile (internal/bootstrap/loaders.js:285:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:220:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Function.Module._load (internal/modules/cjs/loader.js:698:15)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/pawelprochnicki/webdev/uv-examples/js/node_modules/node-fetch/index.js:12:12)
npm WARN worker-loader@1.1.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN uv-examples@1.0.0 No repository field.
npm WARN uv-examples@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universalviewer@3.1.1 postinstall: `opencollective postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the universalviewer@3.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pawelprochnicki/.npm/_logs/2020-07-15T16_41_24_179Z-debug.log`

Have anyone idea whats wrong?

**Comment by stephenwf** [comment]
Added issue to track: https://github.com/UniversalViewer/uv-examples/issues/2
