### ISSUE TITLE
Audio and video transcription

### ISSUE THREAD

**Issue by Sozialarchiv** [UniversalViewer/universalviewer#741]
Is it possible to show audio and video transcriptions in the universal viewer as sub titles?

I only found these tow examples http://wellcomelibrary.org/iiif/b16748967/manifest and https://iiif-commons.github.io/iiif-av-component/examples/data/iiif/lunchroom-manners.json, but this not really what I am looking for.

**Comment by edsilv** [comment]
Not right now I'm afraid. Although it's come up in meetings with the BL.
Not sure what they're planning on that front right now...

**Comment by Sozialarchiv** [comment]
Thank you very much for your answer
