### ISSUE TITLE
Add a shortcut link to the download menu button before main content in case there's a text equivalent

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#748]
Would be a temporary solution for WCAG 2.1 1.1.1, 1.2.1, 1.2.3 until maybe we introduce Choice?

https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=122%2C123%2C125%2C127%2C134%2C111#audio-only-and-video-only-prerecorded

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by LlGC-szw** [comment]
Completed.
