### ISSUE TITLE
Extending the thumbnail label to reveal more text

### ISSUE THREAD

**Issue by WilsonAndrewWilson** [UniversalViewer/universalviewer#758]
**UV version:**
```
 universalviewer@4.0.0-pre.12 (although affects all)
```

**I'm submitting a:**

- [ ] bug report
- [x] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Currently,  only a small part of thumbnail label text appears in the contents tab in UV. CSS is used to hide the overflow:
```
#app .leftPanel .views .thumbsView .thumbs .thumb .info .label {
    float: left;
    overflow-x: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
   ```
Is it possible to either have a configurable option to "show full labels", or default to showing more of the label.  Not sure the effects on just changing the CSS - I'm currently experimenting with the following, although not perfect (and seem to have a weird thing where the thumbs aren't appearing 2-up any more!).

 ```
overflow-x: visible;
  text-overflow: inherit;
  white-space: break-spaces;
```

**Expected behavior:**

The entire label appears.

**Steps to reproduce:**

[https://universalviewer.io/uv.html?manifest=https://collections.st-andrews.ac.uk/762295/manifest?manifest=https://collections.st-andrews.ac.uk/762295/manifest#?c=0&m=0&s=0&cv=0&xywh=-3432%2C-425%2C15366%2C8463](https://universalviewer.io/uv.html?manifest=https://collections.st-andrews.ac.uk/762295/manifest?manifest=https://collections.st-andrews.ac.uk/762295/manifest#?c=0&m=0&s=0&cv=0&xywh=-3432%2C-425%2C15366%2C8463)

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by thattonBL** [comment]
Still active. Yeah I can see how this is not a good user experience from the example. See the thumbnail labels. I suppose this could be slightly mitigated by adding the Index tab in config.
