### ISSUE TITLE
Can't load UV from a separate server

### ISSUE THREAD

**Issue by minusdavid** [UniversalViewer/universalviewer#765]
Hi, I'm trying to host UV on a server, and then have a different server serve HTML pages pointing to that other server. 

I've updated the root to "http://<your third party hostname>/uv-3.0.35" and that resolved a few issues, but now I'm stumped by the following error:

uv.js:1 GET http://<your third party hostname>/uv-3.1.1/lib/uv-seadragon-extension-dependencies net::ERR_ABORTED 404 (Not Found)

Now http://<your third party hostname>/uv-3.1.1/lib/uv-seadragon-extension-dependencies.js exists... so I'm thinking that uv.js is having some issues trying to determine what file to get. I've seen things like this with TinyMCE. The Javascript trying be too smart for its own good...

**Comment by edsilv** [comment]
Hi, does this example help? 

https://github.com/UniversalViewer/uv-examples/tree/master/js

**Comment by minusdavid** [comment]
I don't think so but I realize now that my comment was a bit vague.

I don't want to use Node/npx as a HTTP server. I want to just unpack the UV dist and serve it via a web server like Nginx, Apache, IIS, etc. I want to have a "universalviewer.domain" hostname and point to UV at "universalviewer.domain/uv" in my HTML served at "library.domain/library". 

It seems to me that the UV Javascript doesn't expect you to have a different "root" set in the options, and that's causing problems properly building filepaths.

Note in my original comment that the 404 was for http:///uv-3.1.1/lib/uv-seadragon-extension-dependencies rather than http:///uv-3.1.1/lib/uv-seadragon-extension-dependencies.js. It seems that UV isn't even generating the correct filepath.

**Comment by edsilv** [comment]
In the example above it's just using node to download everything and the scripts in package.json (`npm run copy`) will just copy what you need into the project root. This could equally be a "public" folder, which is a common pattern for RoR or nodejs sites.
How you serve those files is up to you - it could be a node server, or Nginx, Apache, IIIS etc.
If you need the UV to load dependencies from a different location, see: https://github.com/UniversalViewer/universalviewer/wiki/Migrating-from-v3-to-v4


```
If you copy the contents of node_modules/universalviewer/dist into something other than the root of your project, you need to change the UV's webpack.config.js publicPath to match that folder's path, e.g. publicPath: "my-uv/uv-dist-umd/" and rebuild the UV using npm run build:dist
```

**Comment by minusdavid** [comment]
Thanks, Edward. It sounds like v4 will be what I want.
