### ISSUE TITLE
Index with UV

### ISSUE THREAD

**Issue by meboutroue** [UniversalViewer/universalviewer#770]
I try to install our digital library with Omeka and UV and need some help to answer these two questions :
- How can I have a TOC without the plugins available on githum. My problem comes from the library pdftk that I can't install on the server. Is there another way to have a TOC? 
- When I upload my pdf on the server, there is no problem to visualize the item when the language setting is on "english"; very long time with "french".. Arghhhhhhh!
Is there an Omeka specialist to help me? Thanks.
MEB

**Comment by edsilv** [comment]
Hi, sorry - please limit issues to specific bug reports. You could try the UV or IIIF slack channels for more general help. Many thanks.
