### ISSUE TITLE
Subcollections not highlighted in v4 (webpack)

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#773]
This works in v3:

![image](https://user-images.githubusercontent.com/1334393/103927380-2f508780-5112-11eb-9501-418c2b81773f.png)

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as fixed by https://github.com/UniversalViewer/universalviewer/commit/c820a25f48bd8826879fcdf12031b5d934c8b466
