### ISSUE TITLE
Accessibility Nice to Haves

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#775]
- [ ] #1101
  - [ ] Header nav
  - [ ] Thumbnails
- [ ] #1102
- [ ] #1103

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by LlGC-szw** [comment]
Closing as breakout issues created.
