### ISSUE TITLE
Slack signup link goes to nonexistent Heroku app

### ISSUE THREAD

**Issue by mhucka** [UniversalViewer/universalviewer#793]
The signup for Slack in the README at https://github.com/UniversalViewer/universalviewer goes to a Heroku URL that has nothing in it:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1450019/120019409-44349700-bf9d-11eb-817a-f8e6f5d8063a.png">

This is the link titled `#slack` near the top of the README:

<img width="1023" alt="uv" src="https://user-images.githubusercontent.com/1450019/120019638-8cec5000-bf9d-11eb-9324-9314abff288f.png">

**Comment by edsilv** [comment]
Thanks - that's now fixed
