### ISSUE TITLE
UniversalViewer image is blur in deep zoom

### ISSUE THREAD

**Issue by ZelCole** [UniversalViewer/universalviewer#794]
Hi, I am using Omeka-S UniversalViewer 3.6.4.4, when I zoom the image, the image are still blurry, the jpeg that I uploaded is high resolution and is quite clear when using openseadragon viewer.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Closed due to inactivity -- sounds like potentially a problem with Omeka's manifest generation. If this is still an issue, please share an example manifest and we can reopen to investigate further.
