### ISSUE TITLE
"ReferenceError: createUV is not defined" when loading UV 4.0.0.pre.54 from CDN

### ISSUE THREAD

**Issue by dmolesUC** [UniversalViewer/universalviewer#798]
**UV version:**

4.0.0.pre.54

**I'm submitting a:**

- [x] bug report

**Current behavior:**

- `Uncaught ReferenceError: createUV is not defined` when trying to initialize viewer
- Searching for `createUV` in `UV.min.js` returns no results

**Expected behavior:**

- Viewer is displayed
- `createUV` is somewhere in the delivered package
- Failing that, README links somewhere to a clearly documented example of how to use UV without `helpers.js`

**Steps to reproduce:**

Following the `uv-hello-world` example more or less as closely as possible without Node, create a self-contained HTML page that loads Universal Viewer from a CDN and displays a viewer.

**Related code:**

```html
<html>
  <head>
    <title>UV demo</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/universalviewer@4.0.0-pre.54/dist/uv-dist-umd/UV.min.js"></script>
    <script>
      let manifestUrl = new URL('http://wellcomelibrary.org/iiif/b18035723/manifest')
      const viewer = createUV('#iiif_viewer', { iiifResourceUri: manifestUrl }, new UV.URLDataProvider())
  viewer.on('created', function (_) {
    console.log('parsed metadata', viewer.extension.helper.manifest.getMetadata())
    console.log('raw jsonld', viewer.extension.helper.manifest.__jsonld)
  }, false)
    </script>
  </head>
  <body>
    <div id="iiif_viewer"></div>
  </body>
</html>
```

**Comment by edsilv** [comment]
We have updated examples here for UV v4: https://github.com/UniversalViewer/uv-examples/blob/master/js/index.html#L28
It now uses `UV.init` instead of `createUV`
