### ISSUE TITLE
Setting for auto-detect current language or default to first in list

### ISSUE THREAD

**Issue by fractos** [UniversalViewer/universalviewer#8]
The behavioural config should also contain the following setting:

Whether to auto-detect current language settings and pick an appropriate localisation, or whether to default to the first one in the list.

Appendix 2:

What we’re really interested in is determining from JavaScript what the browser is going to send in its “Accept-Language” header. Turns out this is not possible in the general case across all browsers:
http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference
BUT – scroll down to Tim Babych’s answer of Sep 1 2014 – is now possible in new builds of Firefox and Chrome.

The proposed (highest scoring) answer is to deploy some server-side functionality that will echo the Accept-Language header back to the browser, but this isn’t ideal for the viewer which should be independent of any server side implementation.

**Comment by edsilv** [comment]
The UV supports a `data-locale` attribute on the embedding div ('en-GB', 'cy-GB', etc), which is included in the generated embed code. My opinion is that until there is a sufficiently well implemented cross-browser solution, perhaps we should detect the language in the containing page using whatever method is deemed fit, then pass this to the UV.
