### ISSUE TITLE
Ability to configure `crossorigin` attribute for Video content

### ISSUE THREAD

**Issue by donaldgray** [UniversalViewer/universalviewer#802]
**UV version:**

```
 universalviewer@v4.0.0-pre.54
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

(Tested on v3.1.1) Rendering a manifest that contains Video content renders a `<video/>` element in the format:

```html
<video class="anno" src="default.mp4" preload="auto"></video>
```

This works with `default.mp4` without needing any CORS headers set.

However, for the same manifest `v4.0.0-pre.54` renders a `<video/>` element in the format:

```html
<video preload="none" crossorigin src="default.mp4">
  <source src="default.mp4" type="video/mp4" title="">
</video>
```

The `crossorigin` property in the `<video/>` element prevents playing any mp4 content that _doesn't_ have CORS headers set. 

**Expected behavior:**

Expected behaviour is for manifest to work as it did in the UV v3.

**Steps to reproduce:**

Behaviour can be viewed by viewing either a of the following manifests in https://uv-v4.netlify.app/  (same content but one is Presentation 2.1 and the other Presentation 3):

* P2.1 - https://iiif.wellcomecollection.org/presentation/v2/b16756654
* P3 - https://iiif.wellcomecollection.org/presentation/b16756654

**Related code:**

```
// insert any relevant code here
```

**Other information:**

Can the output/value of the `crossorigin` property be controlled by configuration?

Tried to test with "Sound" content but ran into issue that is resolved with this commit: https://github.com/UniversalViewer/universalviewer/pull/799

**Comment by edsilv** [comment]
Need to detect if there's an auth service on the manifest, and if the video is on another domain? Then enable `crossorigin` attribute
