### ISSUE TITLE
Incorrect language order

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#81]
In Welsh the order of words for some phrases are the reverse of the English. So "Next Page" would be "Tudalen Nesaf", but at the moment the alt text for the navigation buttons are displaying "Nesaf Tudalen" which would mean "Page Next". It's the same for all the navigation options in the uv-pagingheaderpanel-module. Is it possible to have these changed?

Thanks,
Dylan

**Comment by edsilv** [comment]
Hi,

You should receive an email with an invitation to the transifex.com project for the UV. It's not the most intuitive UI to navigate... but you should be able to find the Welsh translation under Languages > Welsh (United Kingdom) then click on "source.js" and "Translate" in the popup.

In that same popup there's a button labelled "download for use". If you click that to download the json file when ready, you can then overwrite `src/extensions/uv-seadragon-extension/l10n/cy-GB.json` in the UV project.

You can then commit the new l10n file to your fork of the UV and issue a pull request.

Ed

**Comment by LlGC-dwj** [comment]
Hi thanks for that Ed, but unfortunately I can only translate the words which have been correctly translated already.

In pagingHeaderPanel.js on line 134 the code states

this.$firstButton.prop('title', this.content.first + " " + mode);

Which comes out with title="Next Page", but in Welsh this title would be title="Nesaf Tudalen" which is the reverse of what we'd say.

The code would have to be
 
this.$firstButton.prop('title', mode + " " + this.content.first);

To work in Welsh. Is there a way round this?

Thanks,
Dylan

**Comment by edsilv** [comment]
Ah, this has come up before. We'd need to have an entry in the l10n file for "firstPage", "lastPage", "prevPage", "nextPage", "firstImage", "lastImage" ...etc

**Comment by LlGC-dwj** [comment]
Is this something that's likely to change in the short term?

**Comment by edsilv** [comment]
The earliest I'll be able to look at this is next week.
