### ISSUE TITLE
Thumbnail images broken when selected for level 0 manifests

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#813]
https://uv-v3.netlify.app/#?c=&m=&manifest=https%3A%2F%2Fbiiif-template-zine.vercel.app%2F&s=&xywh=-382%2C-126%2C1678%2C1517&cv=

![image](https://user-images.githubusercontent.com/1334393/134226173-dacd7aae-0f19-4477-bfa6-7268f7e8e43f.png)

**Comment by edsilv** [comment]
This isn't a regression in v4, so a "nice to have".

**Comment by glenrobson** [comment]
This seems to be working! We came across this a lot in the training as we use level 0 images but it seems to be working in uv3 and uv4:

https://uv-v4.netlify.app/#?manifest=https://iiif-test.github.io/Space/manifests/ganymede-2021-06-07.json&c=&m=&cv=1&xywh=0%2C-1763%2C3249%2C5124

Manifest:
https://iiif-test.github.io/Space/manifests/ganymede-2021-06-07.json

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as fixed
