### ISSUE TITLE
Can not load GLB/GLTF models

### ISSUE THREAD

**Issue by markozar** [UniversalViewer/universalviewer#814]
Hi!
I'm testing the Universal Viewer as 3D viewer for the company I work for, Ericsson, for a digitalization project.

I downloaded the Hello World example (https://github.com/UniversalViewer/uv-hello-world) and managed to start it successfully. I then changed the manifest and tried to load a 3D model exported in Three.js json format (using the https://threejs.org/editor/). It worked.
I then tried to load the same model exported, using Blender, in glb and gltf, but both formats do not work. It remains in the loading state.

For the **gltf** I set the "format":"model/gltf+json" and @type":"dctypes:PhysicalObject". In this case I see in the console:
```
THREE.ObjectLoader: Can't load http://localhost:5000/621-KRP-252.reduced5.normal.gltf. Use THREE.JSONLoader instead
```

If I set @type":"dctypes:model" I do not get errors, but the viewer remains black.

For the **glb** I set the "format":"model/gltf-binary" and @type":"dctypes:PhysicalObject". In this case I see in the console:
```
virtex.js:545 SyntaxError: Unexpected token g in JSON at position 0
    at JSON.parse (<anonymous>)
    at three.min.js:700
    at XMLHttpRequest.<anonymous> (three.min.js:638)
three.min.js:700 THREE:ObjectLoader: Can't parse http://localhost:5000/621-KRP-252.reduced5.normal.glb. Unexpected token g in JSON at position 0
```
Why JSON? it is binary and the token g is the first character of the first 4 characters glTF.

I do not know if this is important or not, but I noticed that in the UniversalViewer src code, in the `uv-virtex-extension/dependencies.ts` the GLTFLoader is listed in
```
async: ['VRControls', 'VREffect', 'stats.min', 'OBJLoader', 'MTLLoader', 'PLYLoader', 'GLTFLoader', 'Detector', 'WebVR', 'virtex', 'IIIFMetadataComponent']
```

while in the Hello World example, in the `uv-virtex-extension-dependencies.js` the GLTLoader is commented out:
```
sync: ['three.min'],
async: ['VRControls', 'VREffect', 'stats.min', 'OBJLoader', 'MTLLoader', 'PLYLoader', 'Detector', 'WebVR', 'virtex', 'iiif-metadata-component']
// sync: ['three.min', 'draco_decoder'],
// async: ['VRControls', 'VREffect', 'stats.min', 'DRACOLoader', 'GLTFLoader', 'OBJLoader', 'MTLLoader', 'Detector', 'WebVR', 'virtex', 'iiif-metadata-component']
```

I tried also to put add the GLTFLoader to the async. It missed the GLTFLoader.js, so I added it to the uv/lib from:
https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/GLTFLoader.js
but I'm getting the same errors.
[models.zip](https://github.com/UniversalViewer/universalviewer/files/7224936/models.zip)

I'm attaching a zip with the 3D models.

So the question is: how can I load a GLB model? What I'm doing wrong?
Thank you so much for your time and help!

Marco Zaratti
[models.zip](https://github.com/UniversalViewer/universalviewer/files/7224941/models.zip)

**Comment by markozar** [comment]
I forgot to attach the manifest we are generating.
[manifests.zip](https://github.com/UniversalViewer/universalviewer/files/7225790/manifests.zip)
I just replaced the model link to a local link (http://localhost:5000/621-KRP-252.reduced5.normal.glb)

**Comment by edsilv** [comment]
Hi,

It looks like you're using UV v3, which uses the old Virtex extension.
I'd strongly recommend trying v4, which is still in development, but uses Google model-viewer which has very good support for gltf. e.g.

https://uv-v4.netlify.app/#?c=&m=&cv=&manifest=https%3A%2F%2Fbiiif-template-example-9cf4ez68i-mnemoscene.vercel.app%2F3d%2Findex.json

Here's what the IIIF manifest looks like: https://biiif-template-example-9cf4ez68i-mnemoscene.vercel.app/3d/index.json

(generated using [biiif-template](https://github.com/IIIF-Commons/biiif-template))

Here are some examples of how to set up UV v4: https://github.com/UniversalViewer/uv-examples
