### ISSUE TITLE
Missing support for Image API v3.0

### ISSUE THREAD

**Issue by ra-magnus-welander** [UniversalViewer/universalviewer#817]
**UV version:**

```
 universalviewer@3.1.1 and v4
```

**I'm submitting a:**

- [X] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

In a presentation v3 manifest we reference a v3 image service. The UV does not recognize this and decides we're an unknown level0 Image API.

**Expected behavior:**

The UV would recognize our v3 image service, call the info.json and adjust its behavior accordingly.

**Steps to reproduce:**

Create a manifest with images using ImageService3.

**Related code:**
manifest snippet:
```
              "body": {
                "id": "http://localhost:58982/arkis!C0002787_00001/full/max/0/default.jpg",
                "type": "Image",
                "width": 3507,
                "height": 2480,
                "format": "image/jpeg",
                "service": [
                  {
                    "id": "http://localhost:58982/arkis!C0002787_00001",
                    "type": "ImageService3",
                    "profile": "level1"
                  }
                ]
              },
```

**Other information:**

One of the problems is apparently with manifesto, which does not recognize ImageService3 profiles. See https://github.com/IIIF-Commons/manifesto/blob/master/src/Utils.ts and the function isImageProfile().

**Comment by edsilv** [comment]
Hi Magnus, is your manifest live so that I can test with it?

**Comment by ra-magnus-welander** [comment]
Try this one: https://lbiiif.riksarkivet.se/arkis!00147269/manifest

The images have two possible services, one v2 and one v3.

**Comment by glenrobson** [comment]
We also have this recipe with an example manifest and image for v3 which we would love to add UV support to:

https://iiif.io/api/cookbook/recipe/0005-image-service/

**Comment by edsilv** [comment]
This is now fixed on the dev branch, will merge soon: 

https://www.universalviewer.dev/#?xywh=-309%2C-121%2C3660%2C2418&iiifManifestId=https%3A%2F%2Flbiiif.riksarkivet.se%2Farkis!00147269%2Fmanifest

https://www.universalviewer.dev/#?xywh=-457%2C-122%2C3954%2C2417&iiifManifestId=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0005-image-service%2Fmanifest.json

**Comment by ra-magnus-welander** [comment]
I've been looking at https://www.universalviewer.dev/#?xywh=-309%2C-121%2C3660%2C2418&iiifManifestId=https%3A%2F%2Flbiiif.riksarkivet.se%2Farkis!00147269%2Fmanifest.

It seems to behave a bit odd. For the info.json it uses the v2 version of the API. The thumbnail pane uses v3, but the main pane seems to be using v2. Maybe it's a bit random? But shouldn't UV always choose the latest version when available?

![bild](https://user-images.githubusercontent.com/14177560/201852022-57d652d6-e259-4304-9575-af22ac5526a0.png)
