### ISSUE TITLE
Multi page PDF becomes blurrier with each click in V4

### ISSUE THREAD

**Issue by Geoffsc** [UniversalViewer/universalviewer#825]
Noticed with this Manifest:
https://digital.library.villanova.edu/Item/vudl:294631/Manifest

As I click through each page, the PDF gets increasingly blurry to the point I see no text at all. I noticed if I first zoom in on the first page on the initial load, then click through the pages the issue does not happen.

**Comment by edsilv** [comment]
related? https://github.com/UniversalViewer/universalviewer/issues/805

**Comment by Geoffsc** [comment]
> related? #805

@edsilv I'm not sure -- I tested the manifest above in [UV 3](https://uv-v3.netlify.app/) and it worked as expected, so it's possible #805 is a separate issue. If there's a manifest to reproduce #805 it might be useful to compare/contrast different PDF manifests between V3 and V4.

**Comment by edsilv** [comment]
Need to test if it also happens in PDFObject or is limited to PDF.js

**Comment by edsilv** [comment]
If you zoom in a step it seems to fix it.
