### ISSUE TITLE
Tall videos exceeding available space in  UV

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#826]
![image](https://user-images.githubusercontent.com/1334393/144084575-4064ab1a-1d1f-48d4-b168-e0986d334956.png)

**Comment by dhrobinson** [comment]
IIIF manifest:
https://digitalcollections-api.arts.ac.uk/iiif/objects/koha:1482749

**Comment by dhrobinson** [comment]
@edsilv Do you know when this issue might be scheduled in?

**Comment by dhrobinson** [comment]
@edsilv Just to add some more info around this after further testing. 

It looks like the video player in v4.0.0-pre.103 is sized to 100% of the width of the available area; however it is not checking the height of the available area, so it will happily crop a 4:3 video that is displayed in a 16:9 frame for example.
Previous versions fit videos correctly to the available area.

Live example: https://digitalcollections.arts.ac.uk/object/?code=calm:UAL/OH/3 
UV v4.0.0-pre.53

**Comment by stephenwf** [comment]
@dhrobinson How is this looking: https://deploy-preview-858--uv-v4.netlify.app/#?manifest=https://digitalcollections-api.arts.ac.uk/iiif/objects/koha:1482749&c=&m=&cv=&xywh=

**Comment by ksclarke** [comment]
I'm interested in this ticket too. With Firefox, and the zoom on the browser up to %120, it scales just fine. On Chrome, and the zoom on the browser up to 125%, the bottom part of the video falls off-screen. This causes the controls at the bottom to not be visible and, if closed captions are used (like in https://deploy-preview-858--uv-v4.netlify.app/#?manifest=https://gist.githubusercontent.com/stephenwf/4fe098a9faf8a141ae71a50e2939eaf4/raw/e782e0a1fd1599baea900247186d52592d2878f5/vtt.json&c=&m=&cv=&xywh=), they fall off the bottom of the screen too.

**Comment by stephenwf** [comment]
@ksclarke I'm sorry I was not able to replicate that sizing on Chromium/macos - but manually changing the line-height of the title seemed to push the video down slightly. I would be inclined to keep the issue open to maybe improve the sizing, but remove as a v4 regression.

**Comment by dhrobinson** [comment]
> @dhrobinson How is this looking: https://deploy-preview-858--uv-v4.netlify.app/#?manifest=https://digitalcollections-api.arts.ac.uk/iiif/objects/koha:1482749&c=&m=&cv=&xywh=

Looks good to me - will try a build at this end and test it out. Thanks

**Comment by ksclarke** [comment]
@stephenwf Did you change your mind about keeping open for sizing refinements? Or, is there another ticket that I should follow now? Fwiw, a colleague tested on Windows too. It seems to just be a Linux issue, and I understand the Linux + Chrome + using browser Zoom user base is probably pretty small in numbers.

**Comment by stephenwf** [comment]
Sorry! Forgot about that, thanks!

**Comment by edsilv** [comment]
Is it ok to close this?

**Comment by stephenwf** [comment]
@edsilv I still think we could improve how much of the available space a video uses within the UV, but I think the original issue of exceeding the available space has been resolved.

<img width="943" alt="Screenshot 2022-08-31 at 10 16 01" src="https://user-images.githubusercontent.com/8266711/187643922-c9462e1e-f452-4d7b-9321-0d0be023cf02.png">

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
