### ISSUE TITLE
Support Deep Viewing with Basic Use of a IIIF Image Service

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#830]
https://preview.iiif.io/cookbook/viewer_matrix/recipe/matrix/

https://uv-v4.netlify.app/#?manifest=https://preview.iiif.io/cookbook/viewer_matrix/recipe/0005-image-service/manifest.json&c=&m=&cv=&xywh=759%2C786%2C2721%2C1683

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
Closing as fixed
