### ISSUE TITLE
UV4 - manifests with multiple canvases not working as expected?

### ISSUE THREAD

**Issue by adamtovell** [UniversalViewer/universalviewer#836]
**UV version:**

```
 universalviewer@v4.0.0-pre.77
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
For manifests with multiple canvases (in this example, sides of a tape) and either single or multiple ranges: when the playhead reaches the end of the extent of the first canvas, playback continues, but the player repeats the audio from the first canvas instead of playing audio from the next canvas. See https://uv-v4.netlify.app/#?manifest=https://dl.dropboxusercontent.com/s/n3594lmqxo7k5bg/Canvas_issue.json

**Expected behavior:**
The expected content should play 

**Steps to reproduce:**
Open an AV manifest with multiple canvases and one or more ranges
Select the first recording in the Index
Play (or queue the playhead up to near the end of the extent of the first canvas and play)
Let the playhead continue to the end of the first canvas
The playhead continues but repeats audio from the first canvas instead of playing the second

**Related code:**

```
// insert any relevant code here
```

**Other information:**
This issue seems to be present in v3 as well.

**Comment by stephenwf** [comment]
Interesting, it also does not appear to be possible to select canvases either from the thumbnail view, which feels related.

Link to range debugging tool here: https://iiif-ranges.netlify.app/#manifest=https://dl.dropboxusercontent.com/s/n3594lmqxo7k5bg/Canvas_issue.json

I wonder if it's something in the `set(data)` or perhaps in the glue between the AVComponent + the UV.

cc @edsilv

**Comment by adamtovell** [comment]
If helpful, the same manifest is kind of working in this earlier dev build, in that the correct content is being played, but the range indicators aren't showing, so still not quite right. But might be useful to compare: https://5ea2100e7961c5bec41411ec--digirati-bl-2020.netlify.app/template.html#?manifest=https%3A%2F%2Fdl.dropboxusercontent.com%2Fs%2Fn3594lmqxo7k5bg%2FCanvas_issue.json

**Comment by stephenwf** [comment]
Hi @adamtovell the issue with the example manifest is that the Identifiers were not valid URIs. There may be somewhere where we could improve how we parse them, but changing these fixed the issue for me:

Here is the example you provided with rewritten URLs:
https://gist.githubusercontent.com/stephenwf/611a03965e955f9d1b78c27a13d2d6d5/raw/a3f0c0e58615f67f80d29a817a0319a54f19e641/manifest.json

(With a working UV link: https://uv-v4.netlify.app/#?manifest=https://gist.githubusercontent.com/stephenwf/611a03965e955f9d1b78c27a13d2d6d5/raw/a3f0c0e58615f67f80d29a817a0319a54f19e641/manifest.json&c=&m=&cv=1)

**Comment by stephenwf** [comment]
Found the missing canvas change here: https://github.com/IIIF-Commons/iiif-av-component/pull/53

**Comment by stephenwf** [comment]
@adamtovell Here's a preview URL to test the fix with: https://universalviewer-git-feature-update-av-mnemoscene.vercel.app/#?manifest=https://gist.githubusercontent.com/stephenwf/fdde8b5a71e446312a7ebc8d8c7c2fb7/raw/d70a635887528a79ecbb776a0517b067168f9acd/manifest.json

**Comment by adamtovell** [comment]
@stephenwf thanks for looking into this :) I'm seeing different behaviour in the link above now - the correct audio is being played after the end of the first canvas, but I'm afraid something still not quite right - the range indicator shows the correct range in the scrub bar, but the index is now still highlighting the first item in the index, even after moving into the second range. DItto, the more information panel is still showing metadata from the first range, when playing the second.

Let me know if a separate issue and I'll raise something separately.

Attached a screengrab showing range highlighting vs. index.
![Canvas_issue](https://user-images.githubusercontent.com/846997/154919638-a4ab3740-dfb6-41f3-81e9-3e71fa5ca856.png)

**Comment by stephenwf** [comment]
@adamtovell A separate issue would be best I think. I can see that this issue was present prior to this issue (and not introduced by it)  I think your example is still a good minimum replication.
