### ISSUE TITLE
Port PDF support from Wellcome Player

### ISSUE THREAD

**Issue by tomcrane** [UniversalViewer/universalviewer#84]
A special case of Born Digital

**Comment by demiankatz** [comment]
As with #83, this is something we're going to need, so I might be able to put some cycles into this if my help would be useful. Just let me know!

**Comment by edsilv** [comment]
@demiankatz This is now done:

http://universalviewer.azurewebsites.net/?manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fcollection%2Fb20432963

**Comment by demiankatz** [comment]
Thanks. This is working for me for single-PDF manifests. However, I have several manifests with multiple PDFs, where each canvas represents a different segment of a larger document. In these cases, I get only the first PDF displayed, and the left panel seems to be trying to offer some navigation, but it doesn't actually work. I'm also seeing a lot of "#thumb_page_canvas is undefined." messages in my console.

I'm happy to put some time into cleaning this up, but I'll wait to hear from you before I dive in, in case you can deal with some of this or have advice on how I should proceed.

Thanks!
