### ISSUE TITLE
UV4 - Configuration for mini player display

### ISSUE THREAD

**Issue by adamtovell** [UniversalViewer/universalviewer#845]
**UV version:**

```
 universalviewer@v4.0.0-pre.86
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Configuration options for displaying the player in it's 'mini' mode that were available in UV3 are not available for UV4

**Expected behavior:**
The player should be configurable to display in it's 'mini' mode in the same way as UV3: ![mini-player](https://user-images.githubusercontent.com/846997/157235311-c93a20d3-465f-4df2-893f-a2e324e3257e.png)

**Steps to reproduce:**
Use UV3 config for mini player in UV4

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by stephenwf** [comment]
Fixed by #854

**Comment by edsilv** [comment]
can we close this?

**Comment by adamtovell** [comment]
Yep, fixed

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by thattonBL** [comment]
Close please

**Comment by LlGC-szw** [comment]
Close at the request of the BL
