### ISSUE TITLE
UV4 - Timecode links in metadata no longer working

### ISSUE THREAD

**Issue by adamtovell** [UniversalViewer/universalviewer#846]
**UV version:**

```
 universalviewer@v4.0.0-pre.86
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Timecode links in the more information panel should be clickable to move the current time to the value recorded in the metadata, e.g.: 

![timecodes](https://user-images.githubusercontent.com/846997/157236535-4fe84a8f-f37d-43fe-948f-ef8ef2b684bc.png)

"value" : {
                "en" : ["<span>Part 1 [Tape 1 (F2499) Side A] <span data-uv-navigate='#?t=0'>[00:00:00]</span>: Nina Jenkins (NJ) born in 1946, in East London, then moved to Essex. Mother: legal secretary; father: Education Officer. Catholic education; post-war London; move to Cardiff: Welsh roots. Her crush on hockey captain.</span>", "<span>Part 2 [Tape 1 (F2499) Side B] <span data-uv-navigate='#?t=1832'>[00:30:32]</span>: Sexual encounters with boys. Sexual naivety. Her resolution to stay single; mother remarried. NJ forced to leave home: joined the Royal Air Force (RAF) as physical trainer. Discusses lesbianism in RAF; her first lesbian sexual relationship; subsequent lesbian lovers.</span>", "<span>Part 3 [Tape 2 (F2500) Side A] <span data-uv-navigate='#?t=3676'>[01:01:16]</span>: Being the object of recruits' attentions; fear of witch hunts; implications of being gay in Armed Forces. Transferred to Berkshire; relationships; interrogation and near discrimination by investigators. Re-instated for position overseas: posted to Cyprus - details. Describes witch hunt in Cyprus: being forced to confess her lesbianism; describes opions given by the Forces.</span>", 

**Expected behavior:**
Clicking the links should move the current time to the value recorded in the #?t values recorded in the metadata

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
related: https://github.com/UniversalViewer/universalviewer/issues/849

**Comment by adamtovell** [comment]
Yes, can close

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by LlGC-szw** [comment]
Closed at the request of the BL.
