### ISSUE TITLE
UV4 - Timecode links in More Information panel broken?

### ISSUE THREAD

**Issue by adamtovell** [UniversalViewer/universalviewer#849]
**UV version:**

```
 universalviewer@v4.0.0-pre.99
```

**I'm submitting a:**

- [x ] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
Hyperlinks are no longer appearing as links:

![image](https://user-images.githubusercontent.com/846997/163146993-1068e4f5-cc4d-4376-b589-8b02e3b10bc0.png)

vs

![image](https://user-images.githubusercontent.com/846997/163147117-6826e042-b9b0-44d0-8bb1-157877d0e89e.png)

**Expected behavior:**
The timecode values should appear as hyperlinks

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by stephenwf** [comment]
Do they still work if you click on them? Also @adamtovell can you remind me why we didn't make them links in the metadata? Something like:
```html
<a href="#t=123.45">[00:02:03]</a>
```

**Comment by adamtovell** [comment]
@stephenwf no, they're not clickable anymore - just appearing as text.

Don't think I was involved in spec'ing how they should appear in the json, but this is what they look like atm:

              "label" : {
                "en" : ["Summary"]
              },
              "value" : {
                "en" : ["<span>Part 1 [Tape 1 (F2499) Side A] <span data-uv-navigate='#?t=0'>[00:00:00]</span>: Nina Jenkins (NJ) born in 1946, in East London, then moved to Essex. Mother: legal secretary; father: Education Officer. Catholic education; post-war London; move to Cardiff: Welsh roots. Her crush on hockey captain.</span>", "<span>Part 2 [Tape 1 (F2499) Side B] <span data-uv-navigate='#?t=1832'>[00:30:32]

**Comment by stephenwf** [comment]
Fixed by #854

**Comment by edsilv** [comment]
Can we close this?

**Comment by adamtovell** [comment]
Reckon we can, yep

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by thattonBL** [comment]
close please
