### ISSUE TITLE
UV image caching bug with required statement

### ISSUE THREAD

**Issue by stephenwf** [UniversalViewer/universalviewer#857]
**UV version:**
```
 universalviewer@4.0.0-pre-108
```

**I'm submitting a:**
- **bug report**
- feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

Sometimes a manifest will fail to load if the required statement contains an <img/> tag and the `load` event is not fired (i.e. the image is cached).

**Expected behavior:**

Not crash

**Steps to reproduce:**

Manifest with requiredStatement.value containing a non-zero `<img />`

**Related code:**

```ts
$attributionText.find('img').one('load', () => {
    this.resize();
}).each(function() {
    if (this.complete) $(this).load();
});
```
https://github.com/UniversalViewer/universalviewer/blob/master/src/modules/uv-shared-module/CenterPanel.ts#L148-L152

**Comment by attonbomb** [comment]
We were wondering if it was related to this commit: https://github.com/IIIF-Commons/manifesto/commit/0876ba4b0756cbfa03a5566c2c63aa2f9dc9a0e6#diff-30389f5faccfe79c8642ff01933d5cd1069c62cca9a9e8291ea3f8df17073ed5
