### ISSUE TITLE
More Information panel contents not appearing in IE < 9

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#86]
linked to https://github.com/UniversalViewer/universalviewer/pull/68

**Comment by demiankatz** [comment]
Since this seems to be related to work done by @crhallberg and myself, please let us know if you'd like us to investigate further. I don't want to invest time in it if you're already in the middle of a fix, but if you haven't gotten to it yet, please feel free to pass it along to us.

**Comment by crhallberg** [comment]
I think this is related to Issue #64, the only error I'm getting is from jsoneditor.js.

**Comment by edsilv** [comment]
try: http://localhost:8001/examples/noeditor.html

**Comment by crhallberg** [comment]
Thank you! The problem persists so it's not the jsoneditor.

Is there a way to get more detailed error messages? All I'm getting is 'error'.

**Comment by demiankatz** [comment]
When I was troubleshooting IE problems, I ended up adding lots of console.log lines all over the place for lack of a better way to get verbose information out of the browser... but perhaps there's a better way that I'm not aware of.

**Comment by edsilv** [comment]
I'd usually use IE11 in IE8 emulation mode and set breakpoints in the F12
debugger.
