### ISSUE TITLE
Thumbnail layout for unpaged manifests changed in v4

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#873]
Somewhere between 4.0.0-pre.53 and the release of 4.0.0 there has been a change to the thumbnails in the LHS column.
Previously the default was single column, but this seems to have changed to two-column.
We'd like to revert to single column - I have found that by setting options->pagingEnabled: false accomplishes this, but the thumbnail bounding boxes are much bigger than the thumbnails displayed.
What combination of options can I use to revert to the previous rendering?

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/V4-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
![image](https://user-images.githubusercontent.com/1334393/184900160-033b1f1b-5ba4-4eee-bd8c-79b503a2ee1a.png)

**Expected behavior:**
![image (1)](https://user-images.githubusercontent.com/1334393/184900190-5c895111-4fe2-4cba-9772-69f5972c69c6.png)

Example manifest: https://digitalcollections-api.arts.ac.uk/iiif/objects/calm:CCAD/1/1

**Comment by nicolasfranck** [comment]
Similar to https://github.com/UniversalViewer/universalviewer/issues/872?

Why should the rendering of two columns be depending op `pagingEnabled` in the UV configuration?
Isn't that something to derive from the the manifest? Or did I read you wrong?

**Comment by edsilv** [comment]
fixed: https://www.universalviewer.dev/#?xywh=-722%2C-123%2C3636%2C2433&iiifManifestId=https%3A%2F%2Fdigitalcollections-api.arts.ac.uk%2Fiiif%2Fobjects%2Fcalm%3ACCAD%2F1%2F1
