### ISSUE TITLE
AV Downloads Requires Work

### ISSUE THREAD

**Issue by attonbomb** [UniversalViewer/universalviewer#876]
The Download popup content no longer appears using the previously defined standard BL manifest structure.  The "rendering" object

`"rendering" : [{
      "id" : "[https://some-file-url/"]
      "type" : "Audio",
      "label" : {
        "en" : ["Download this recording (Opens in new tab)"]
      },
      "format" : "audio/mp4"
    }]`

appears as a child of the "structures" element and then subsequently as a child of each "item" object within "structures".

This no longer works and produces the "No Download is available for this content" message in the popup.

Moving the "rendering" object to the root of the manifest works for downloading the whole set of recording as one file but we would like to be able to download individual ranges from within "structures". This was the case previously I understand.

The peculiarity is that when I add a "rendering" object to each "items -> "items" object outside of "structures" it triggers the renderings within the "structures -> items" to work.

In addition the rendering is bad see screenshots with a radio button plus bullet point.

Happy to provide an example manifest for whoever works on this. Essentially the presence of "rendering" as a child of structures used to cause UV to populate the download popup with content. It no longer does. Could it do that again please.

Adding the "rendering" to "items -> items" first object causes UV to pick up the first "rendering" within "structures -> items" signified by "range" in the display text.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/9397185/185664797-fa1297b6-32b1-40dc-be97-46c0f254bdd7.png)

Adding the "rendering" to "items -> items" second object causes UV to pick up the second "rendering" within "structures -> items" signified by "range" in the display text.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/9397185/185664832-5e4129c9-6a8e-41e5-a19a-3164acb913fb.png)

Adding Rendering to the root under @context produces this.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9397185/185664829-67e6d829-d7a3-45f2-b0bf-1a80082fc6bc.png)

**Comment by kevanwood** [comment]
An example manifest
[manifest.txt](https://github.com/UniversalViewer/universalviewer/files/9475912/manifest.txt)

**Comment by edsilv** [comment]
UV v3 has the same issue: https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https://edsilv.github.io/test-manifests/bl-av-download-rendering-ranges.json
