### ISSUE TITLE
Class and styling not applied on clicking link in left panel.

### ISSUE THREAD

**Issue by LydiaWallaceJisc** [UniversalViewer/universalviewer#887]
**UV version:**

```
 universalviewer@4.0.9
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/V4-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
The index items (tree links) do not add the 'selected' class correctly when clicked and therefore do not get styled in blue. 

**Expected behavior:**
You should be able to click on the links and it gains the selected class and are styled appropriately.

**Steps to reproduce:**
in the left panel, select a link to another page.

**Related code:**

```
<a id="tree-link-0-1" href="#" title="Title Page" class="selected">Title Page</a>
```

**Other information:**
When you first open the index view the correct page is marked as 'selected', but it loses this when you select another page. Interestingly, after clicking a link to a page none of the links have the 'selected' class, but if you then click on the thumbnail tab and go back to index the class and styling do get applied. 

This issue from 2019 could be related: https://github.com/UniversalViewer/universalviewer/issues/668.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.
