### ISSUE TITLE
Previous button is accessible via keyboard when it's disabled

### ISSUE THREAD

**Issue by RobertWilliamsCymro** [UniversalViewer/universalviewer#888]
**UV version:**
` universalviewer@4.0.9
`
**I'm submitting a:**
`[ x]` bug report

**Current behaviour:**

At the moment, a keyboard user can use the previous button in the header panel even if it's disabled via CSS. When the button is clicked, it will produce an error:

![image](https://user-images.githubusercontent.com/110839347/198987581-8ec6a3b7-f619-4187-a33e-111be49ff55b.png)

The position placemaker will also go off the screen when the previous button is clicked enough times:

![image](https://user-images.githubusercontent.com/110839347/198988254-cdbdfe0a-d726-47dd-b088-81705ee78cb9.png)

**Expected behavior:**

The button should be disabled for all users.

**Steps to reproduce:**
Use the tab key to get to the previous button in the header panel, and when the page no is 1 or less, press the enter key. The error will then appear.

**Other information:**

It might be better to use Javascript to disable the button, adding something like below into **PagingHeaderPanel.ts**  would do the trick.

In the **disablePrevButton** method, add:
`this.$prevButton.attr("disabled","disabled");`

and in **enablePrevButtion**, remove the attribute:
 
`this.$prevButton.removeAttr("disabled");`

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by demiankatz** [comment]
Resolved by #1093.
