### ISSUE TITLE
Error embedding uv-1.2.4

### ISSUE THREAD

**Issue by LlGC-dwj** [UniversalViewer/universalviewer#89]
Hi, I've been trying to embed the latest version of the uv, but for some reason app.js is missing from the /lib after building. Do you have any ideas why this might be the case?

Thanks,
Dylan

**Comment by edsilv** [comment]
Hi,

Just gave this a try.

- followed setup instructions: 
  https://github.com/UniversalViewer/universalviewer#first-time-setup

- ran


build, dist

**Comment by LlGC-dwj** [comment]
Hi Ed, thanks for your reply.

I've been following your setup instructions as well. app.js is appearing again now but I'm getting a error message trying to find /js/uv-seadragon-extension.cy-GB.config.js which is /lib/uv-seadragon-extension.cy-GB.config.js in this version. I had to change quite a few file pointers to get the build to run so might be something odd happening on my local version, it says it's up-to-date with origin/master but I suspect that git is lying to me somehow! Might have to try a fresh checkout.

**Comment by edsilv** [comment]
I renamed a lot of files recently. I think you're better off cloning it afresh. Are you using a fork? I recommend forking the repo.

**Comment by LlGC-dwj** [comment]
Hi Ed,

I've forked the UniversalViewer and cloned afresh. While running bower install noticed that json-schema-generator throws out an error (Can't find krg7880/json-schema-generator). I changed the value to the latest version of it (2.0.0) and it works fine thereafter.

But running grunt build in the latest release doesn't work, it reaches configure:apply then aborts "Warning: object is not a function Use --force to continue." I've tried grunt build --force and it seems to go through with the build but I then get the following error message universalviewer/build/uv-1.2.10/lib/uv-seadragon-extension.en-GB.config.json 404 (Not Found) when deploying the code to the server. Is there something I've missed?

Thanks again,
Dylan

**Comment by edsilv** [comment]
I just tried a fresh clone and it's building for me. I'm on Windows 8, are you on Mac/Linux?

Could you reply with the package.json value you're using for json-schema-generator?

I have a feeling that you might be getting an older version which doesn't have the PR I issued a few days ago:

https://github.com/krg7880/json-schema-generator/pull/9

If you're lacking that export you would get an error like the one you mention.

**Comment by LlGC-dwj** [comment]
I'm using Ubuntu.

This was the original

{
  "name": "UniversalViewer",
  "version": "1.2.10",
  "description": "Navigate sequences of images in a zoomable, extensible interface.",
  "devDependencies": {
    "async": "^0.9.0",
    "chalk": "^0.5.1",
    "cucumber": "^0.4.5",
    "glob": "^4.3.5",
    "glob-array": "^0.1.2",
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "~0.4.0",
    "grunt-contrib-compress": "~0.5.2",
    "grunt-contrib-connect": "~0.8.0",
    "grunt-contrib-copy": "~0.4.1",
    "grunt-exec": "~0.4.2",
    "grunt-protractor-runner": "^1.1.4",
    "grunt-sync": "^0.2.3",
    "grunt-text-replace": "~0.3.7",
    "grunt-ts": "^4.0.1",
    "hooker": "^0.2.3",
    "json-schema-generator": "krg7880/json-schema-generator",
    "less": "^2.4.0",
    "lodash": "^3.1.0",
    "ncp": "^2.0.0",
    "protractor": "1.3.1"
  }
}

I changed json-schema-generator to "2.0.0" as it gave me a list of available versions and this was the latest it could find!

**Comment by edsilv** [comment]
yep, that gives me the old version (pre-PR).

try this:

"json-schema-generator": "git://github.com/krg7880/json-schema-generator.git"
