### ISSUE TITLE
Override for language choice

### ISSUE THREAD

**Issue by fractos** [UniversalViewer/universalviewer#9]
Regardless of auto detection, the localisation setting can be overridden by the user. The sensible place for this is in the options dialogue (“hamburger menu”), which can list all the declared localisations from the behavioural config file (using the display labels). However, in the NLW case (and likely for other dual- rather than multi- language scenarios) we ALSO need a more prominent toggle between two specific options, because this language choice is a prime piece of UI. This needs to go in the top navigation bar. We need to determine how/if the theme can control this. The core build needs to provide some underlying support even if the theme styles / shows it.

**Comment by tomcrane** [comment]
Implement toggle between two main languages (theme maybe)

**Comment by edsilv** [comment]
fixed by https://github.com/UniversalViewer/universalviewer/commit/1c290c7258989202f024f9f587d4aaff083596fb
