### ISSUE TITLE
"Next result" button is missing from Welsh translation

### ISSUE THREAD

**Issue by LlGC-gel** [UniversalViewer/universalviewer#903]
**UV version:**

```
 universalviewer@v4.0.17
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/V4-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

"Next result" button is missing from the Welsh side of the Universal Viewer (see screenshots below)

### English Version

<img width="621" alt="GithubIssueEnglish" src="https://user-images.githubusercontent.com/120577552/212717508-3cffd369-ab72-4cd4-a310-5c03ed3e8098.png">

### Welsh Version

<img width="623" alt="GithubIssueWelsh" src="https://user-images.githubusercontent.com/120577552/212717600-647a9c6a-8d46-442f-b123-0ea7fb15f1d3.png">

**Expected behavior:**

"Next result" button should be higher up and visible like the English version (see first screenshot above)

**Steps to reproduce:**

**Related code:**

```
// insert any relevant code here
```

**Other information:**

This fix isn't specific for the Welsh translation as it should affect other strings over a certain length.

**Comment by edsilv** [comment]
fixed by #904
