### ISSUE TITLE
JSON.parse error when loading HLS media

### ISSUE THREAD

**Issue by masaball** [UniversalViewer/universalviewer#907]
**UV version:**

```
 universalviewer@4.0.0
 universalviewer@3.1.4
```

**I'm submitting a:**

- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior:**

When attempting to load a manifest from Avalon Media System, the UV player loads the metadata from the manifest but does not load the media. This was tested on the UV3 and UV4 demo sites in both Firefox and Chrome.
![Screenshot_20230202_103301](https://user-images.githubusercontent.com/68433277/216369383-ee88ae22-fea7-484d-9121-f5887ff2f705.png)

The network tab shows the `m3u8` file as being successfully retrieved but there is a javascript error:

![Screenshot_20230202_103718](https://user-images.githubusercontent.com/68433277/216370412-8413db00-bf24-4508-9d47-8d9d0d1e889e.png)
![Screenshot_20230202_104153](https://user-images.githubusercontent.com/68433277/216371737-6b8d0d50-6ffb-4912-90c9-74fe62a5bca2.png)

**Expected behavior:**

UV player accurately handles `m3u8` files and successfully plays HLS media.

**Steps to reproduce:**

Load the demo manifest into UV.

Demo manifest: https://demo.avalonmediasystem.org/media_objects/pk02cb02n/manifest.json

**Comment by stephenwf** [comment]
This appears to be caused by the following Service definition:
```json
{
  "@id": "https://demo.avalonmediasystem.org/master_files/9k41zd77z/low.m3u8",
  "@type": "AuthProbeService1",
  "profile": "http://iiif.io/api/auth/1/probe"
}
```

Which at the moment is expected to return a JSON with a `"location"` property that points to the resource that the user currently has access to. It will know if it's degraded if this location property does not match the resource that is being requested, and will show the auth login.
