### ISSUE TITLE
PDF download links missing in v4 viewer

### ISSUE THREAD

**Issue by LlGC-mag** [UniversalViewer/universalviewer#908]
**UV version:**

```
 universalviewer@4.0.17
```

**I'm submitting a:**

- [x] bug report => use current main branch
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

In the latest release, download links to PDF files are omitted in certain manifests. Download links for PDFs are ***NOT*** shown when `rendering` is nested in `structures`. Download links to the PDF ***ARE*** shown when `rendering` is nested in `sequences`.
In the v2 viewer download links are shown in either case.

**Expected behavior:**

A download link to the PDF should be shown when `rendering` is nested in either `structures` or `sequences`, as in v2

**Steps to reproduce:**

Using the current universalviewer main branch, view the following manifests:

**A) `rendering` nested in `sequences`**
https://damsssl.llgc.org.uk/iiif/2.0/2272262/2309009/manifest.json

**B) `rendering` nested in `structures`**
https://damsssl.llgc.org.uk/iiif/2.0/1356250/1362721/manifest.json

Manifest A *will* display download links to the PDF, manifest B *will not*.

When viewing either of these manifests in the v2 viewer, download links will be shown:
[https://journals.library.wales/view/2272262/2309009](https://journals.library.wales/view/2272262/2309009)
[https://journals.library.wales/view/1356250/1362721](https://journals.library.wales/view/1356250/1362721)

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by edsilv** [comment]
Is it possible to use renderings on canvases instead? e.g. https://digital.library.villanova.edu/Item/vudl:24299/Manifest

**Comment by LlGC-mag** [comment]
We'll look into changing the manifest as a temp fix for the moment - thanks!

**Comment by edsilv** [comment]
>When viewing either of these manifests in the v2 viewer, download links will be shown:
https://journals.library.wales/view/2272262/2309009
https://journals.library.wales/view/1356250/1362721

this is UV v4.0.10, do you have an example of it working in v2 I could look at?

**Comment by edsilv** [comment]
It also doesn't appear to work in v3? https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fdamsssl.llgc.org.uk%2Fiiif%2F2.0%2F1362721%2Fmanifest.json&xywh=-1626%2C-521%2C6101%2C4583

**Comment by edsilv** [comment]
https://github.com/UniversalViewer/user-stories/issues/2

test manifest: https://edsilv.github.io/test-manifests/range-renderings.json

**Comment by edsilv** [comment]
Getting a mixed content error for https://damsssl.llgc.org.uk/iiif/2.0/1356250/1362721/manifest.json

The info.json needs to be served over https.

![image](https://user-images.githubusercontent.com/1334393/228814063-da70e472-3354-46a2-89ba-80d1644a8aa8.png)

**Comment by LlGC-gel** [comment]
@edsilv Afternoon, I've included a list of manifests that do not display a "download pdf" button on the universal viewer v 4:

- https://damsssl.llgc.org.uk/iiif/2.0/1363072/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1365697/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1362721/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1157780/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1148522/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1162341/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1155335/manifest.json?
- https://damsssl.llgc.org.uk/iiif/2.0/1146159/manifest.json?

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by LlGC-szw** [comment]
Manifest structure to be investigate by NLW.
