### ISSUE TITLE
UV uses different modal for login user interaction?

### ISSUE THREAD

**Issue by nicolasfranck** [UniversalViewer/universalviewer#909]
**UV version:**

```
 universalviewer@v4.0.17
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/V4-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When I use a manifest whose images are protected by an access cookie,
the UV opens the header panel like this:

<img width="1308" alt="Screenshot 2023-02-24 at 14 04 04" src="https://user-images.githubusercontent.com/494636/221185662-b0e6259b-98ad-4786-ad07-685f3e98ff7f.png">

Isn't this message (and place) meant for images with degraded access control?
In version 3 of the universalviewer a big white modal opens with this kind of
information. Or has that changed (it is indeed strange that there are two modals
in the first place)?

Anyway, after some debugging I found that the function `Auth1.handleMovedTemporarily` was called.

Example manifest: https://adore.ugent.be/IIIF/manifests/archive.ugent.be:0000563A-0BCC-11E6-9A4C-1A41F264C48D

Don't get me wrong: this works too, but I am not sure if that is the intention (is that old dialogue somewhere unused?).

**Comment by nicolasfranck** [comment]
I see that the old modal `LoginDialogue` still exists, but only `Auth09` triggers the event `IIIFEvents.SHOW_LOGIN_DIALOGUE` that opens up this modal.

cf. https://github.com/UniversalViewer/universalviewer/blob/main/src/content-handlers/iiif/modules/uv-shared-module/Auth09.ts#L105
cf. https://github.com/UniversalViewer/universalviewer/blob/main/src/content-handlers/iiif/modules/uv-dialogues-module/LoginDialogue.ts#L30

**Comment by edsilv** [comment]
I think this is intentional... I ran into this when working on #860

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by nicolasfranck** [comment]
I see this no longer happening in `4.0.25`
