### ISSUE TITLE
api.cultural.jp manifest not loading

### ISSUE THREAD

**Issue by edsilv** [UniversalViewer/universalviewer#913]
**UV version:**

```
 universalviewer@4.0.17
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/V4-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
This manifest doesn't load: https://api.cultural.jp/iiif/britishm-776876/manifest

**Expected behavior:**
Manifest should load successfully.

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by 404mike** [comment]
When loading the manifest there is an error
`Assertion failed: [Viewport._setContentBounds] bounds.height must be greater than 0`


Which is a similar issue to [934](https://github.com/UniversalViewer/universalviewer/issues/934)

**Comment by agarzola** [comment]
We ran across this issue on a project that does not use an image service. We found that it impacts UV on versions as far back as 4.0.11. I have submitted #941 with what I believe to be a fix that correctly loads the manifest linked in this issue’s description as well as the manifests shared in the issue that the offending commit (3a01c62) originally intended to fix.

**Comment by edsilv** [comment]
Thanks @agarzola !
Have merged #941 which fixes this.
