### ISSUE TITLE
Display right-to-left languages correctly in left panel and title

### ISSUE THREAD

**Issue by hackartisan** [UniversalViewer/universalviewer#916]
Feature request:

We would like to display range labels and top-level labels in right-to-left direction as intended for their language.

Example resource: https://catalog.princeton.edu/catalog/9963572913506421
 * note that at the time of this writing the range label does not use an rdf literal, but we expect to deploy that soon on our side
 * top level label also does not use an rdf literal at the moment; we would likely implement this in our manifests if the feature were in place in UV.

https://github.com/UniversalViewer/universalviewer/issues/299 was closed when right-to-left language support was added for the metadata info pane. However, UV doesn't appear to support right-to-left title display or left panel contents values. The same config file approach would be fine.

If this is actually supported please point me in the right direction!

**Comment by edsilv** [comment]
manifest url: https://figgy.princeton.edu/concern/scanned_resources/cfec680e-1169-475d-b0f3-90b5f64e8115/manifest

**Comment by edsilv** [comment]
I added a `rtl` class to the root element to enable `direction:rtl` in the css: https://www.universalviewer.dev/#?xywh=-4021%2C-481%2C14609%2C9546&iiifManifestId=https%3A%2F%2Ffiggy.princeton.edu%2Fconcern%2Fscanned_resources%2Fcfec680e-1169-475d-b0f3-90b5f64e8115%2Fmanifest

**Comment by edsilv** [comment]
Tree now uses ranges. Main title is right aligned.

https://www.universalviewer.dev/?we#?xywh=-418%2C-1%2C13029%2C8483&iiifManifestId=https%3A%2F%2Ffiggy.princeton.edu%2Fconcern%2Fscanned_resources%2Fcfec680e-1169-475d-b0f3-90b5f64e8115%2Fmanifest&cv=4&rid=https%3A%2F%2Ffiggy.princeton.edu%2Fconcern%2Fscanned_resources%2Fcfec680e-1169-475d-b0f3-90b5f64e8115%2Fmanifest%2Frange%2Fr4e9c1d28-8603-4a5c-a92f-01a4cf9f1787
