### ISSUE TITLE
"Zoom To Results" functionality no longer working on Universal Viewer V4

### ISSUE THREAD

**Issue by LlGC-gel** [UniversalViewer/universalviewer#917]
**UV version:**

```
 universalviewer@v4.0.0
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

On load there's no default zoom, however when you use the pagination buttons "Next Result" and "Previous Result" the zoom works.

**Expected behavior:**

On load, the viewer should zoom into the first instance of a search result. 

**Steps to reproduce:**

I've included a link to a fork of the Universal Viewer on codesandbox. The only things I've changed is adding a different manifest into the manifest field and hardcoding the manifestIndex and canvasIndex.

https://codesandbox.io/s/epic-tu-bqf1vn?file=/index.html:0-1676

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by ebenenglish** [comment]
This is still an issue as of v4.0.22.

**Comment by demiankatz** [comment]
@jamesmisson noticed that the initial zoom to result was commented out in this commit: https://github.com/UniversalViewer/universalviewer/commit/f96a05447d09169f080a2c141fef6a2d66223174. That's probably the cause of the problem; maybe we need a config setting to control this behavior. It looks like next/prev buttons will cause a zoom, but initial zoom was intentionally disabled for some reason.

**Comment by demiankatz** [comment]
Here's the specific offending line of code: https://github.com/UniversalViewer/universalviewer/blob/2f1a29581ed4b5114f3795f03ee2ead4b50aefb6/src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/OpenSeadragonCenterPanel.ts#L78

**Comment by LlGC-jop** [comment]
I'll double check this, as we have at least one site where it does seem to work. Depending on that I'll have a look at making this a configurable option so it can be controlled per-instance.

**Comment by LlGC-jop** [comment]
Given that the commit was titled 'clear annotations' and added that function, I suspect the zoom function call was commented so the whole page could be seen to confirm that all annotation were removed.

I'm assuming the comment was meant to be undone, but missed.
