### ISSUE TITLE
Unable to use previous or next results buttons when searching through a single page item

### ISSUE THREAD

**Issue by thms-rmb** [UniversalViewer/universalviewer#923]
**UV version:**

```
 universalviewer@4.0.21
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**

When I am viewing a single page item, I can search for a term but I cannot click on the _Previous Result_ or _Next Result_ buttons.

**Expected behavior:**

I expect to be able to search for a term and then to click on the _Previous Result_ and _Next Result_ to navigate between the search results.

**Steps to reproduce:**

You can see the effect of searching on a single page item here: https://codesandbox.io/s/single-page-does-not-support-navigating-search-results-yqltjh?file=/index.html:652-865

1. Search for e.g. rabbit in the "Search within this item" field (you may need to make the preview frame wider to see the search input on codesandbox)
2. See search results in the page above
3. Unable to click previous result or next result buttons

It seems that the problem does not appear when there are multiple pages for an item. See here, where I've included two pages: https://codesandbox.io/s/multi-page-does-support-navigating-search-results-978dgh?file=/index.html:334-340

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by jamesmisson** [comment]
This has been fixed and a PR submitted: https://github.com/UniversalViewer/universalviewer/pull/1053
