### ISSUE TITLE
Add configuration to disable unwanted image download options.

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#926]
Currently, certain options ALWAYS appear in the download menu. We should add configuration settings to disable wholeImageHighRes, wholeImagesHighRes, and/or currentViewAsJpg for situations where they are not wanted. One use case could be to prevent the high resolution image from being easily available for download through the UV.

This issue is extracted from #878; see that earlier issue for some related discussions and examples.

**Comment by edsilv** [comment]
See new config options here: https://docs.universalviewer.io/types/_internal_.OSDDownloadDialogueOptions.html

- downloadCurrentViewEnabled
- downloadWholeImageHighResEnabled
- downloadWholeImageLowResEnabled
-
