### ISSUE TITLE
Configuration setting to add query parameter to download links

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#927]
It is possible that users may wish to control download behavior of links in the download menu -- some might prefer to have links open in a new tab, while others might prefer to have them download directly to the download folder of the browser. This behavior is controlled by server-side HTTP headers which cannot be changed from the client side. Thus, an implementation with full control might require the server-side code to react to query parameters in order to set appropriate headers. The UV cannot fully control this, but we could add a configuration setting to add optional query parameters to image links in the download menu, which the server-side code could be configured to act upon.

Prior to implementing this, we should identify more specific use cases so that we can design this as flexibly as possible.

This issue is extracted from #878; see that earlier issue for some related discussions and examples.

**Comment by demiankatz** [comment]
We discussed this in the October 16, 2024 Steering Group meeting and weren't sure if it was actually needed. Is this still of value to you, @kirkkwang?

**Comment by kirkkwang** [comment]
Thanks @demiankatz for getting back to me, I believe we did some sort of workaround so if this isn't deemed needed by  Steering Group then let's close the issue.  Much appreciated!

**Comment by demiankatz** [comment]
Thanks, @kirkkwang, glad to hear it. We can always reopen if a need arises, but this is such a specialized thing that it's hard to implement without a real-world use case to prove that we did it right. Closing for now!
