### ISSUE TITLE
The confinedImageSize setting should constrain both width and height

### ISSUE THREAD

**Issue by demiankatz** [UniversalViewer/universalviewer#928]
As of this writing, the confinedImageSize setting only appears to limit the width of images, not the height. It should constrain BOTH dimensions.

This issue is extracted from #878; see that earlier issue for some related discussions and examples.

**Comment by edsilv** [comment]
![confinedImageSize](https://github.com/UniversalViewer/universalviewer/assets/1334393/37a1e437-e328-4167-9e96-dc7a130674ed)

See before and after above. `confinedImageSize` is now treated as the longest side instead of the width
