### ISSUE TITLE
UV Version 4.x not supporting static images (non-IIIF images)

### ISSUE THREAD

**Issue by kirschbombe** [UniversalViewer/universalviewer#983]
**UV version:**

```
 universalviewer@v4.0.0
 universalviewer@v4.0.21
```

**I'm submitting a:**

- [x] bug report => please fork one of these [codesandbox examples](https://github.com/UniversalViewer/universalviewer/wiki/UV-Examples) with a repro of your issue and include a link to it below
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
When loading a manifest with a static (non-IIIF) image on a canvas, UV v4.x does not display the static image and the loading icon continues to spin. The browser console log gives the error: `Assertion failed: [Viewport._setContentBounds] bounds.height must be greater than 0 8863.c56e62097ef300b4ee08.js:2:183437`

**Expected behavior:**
I would expect the static image to load as it does in UV v3.1.4:
https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Ftest.iiif.library.ucla.edu%2Fark%253A%252F21198%252Fz1hf3f9k%2Fmanifest

**Steps to reproduce:**
Here is an example manifest, which works in v3.1.4 (above): An example manifest: https://test.iiif.library.ucla.edu/ark%3A%2F21198%2Fz1hf3f9k/manifest

However, it does not work as expected in v4.0.0 (the UV demo) or v4.0.21

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by demiankatz** [comment]
@kirschbombe, this seems to be working for me in universalviewer.dev (the latest dev branch): https://www.universalviewer.dev/#?xywh=-3260%2C-285%2C9357%2C4245&iiifManifestId=https%3A%2F%2Ftest.iiif.library.ucla.edu%2Fark%253A%252F21198%252Fz1hf3f9k%2Fmanifest

Am I missing something?

It does appear to be broken in universalviewer.io (the 4.0.0 release): https://uv-v4.netlify.app/#?manifest=https://www.universalviewer.dev/#?xywh=-3260%2C-285%2C9357%2C4245&iiifManifestId=https%3A%2F%2Ftest.iiif.library.ucla.edu%2Fark%253A%252F21198%252Fz1hf3f9k%2Fmanifest&c=&m=&cv=

Is it possible this was already fixed subsequent to release 4.0.21?

**Comment by kirschbombe** [comment]
Yes, it looks to be fixed in dev - I didn't test it there, only in the most recent versions I knew about (4.0.0 and 4.0.21 which is what the UCLA Library is currently using). Is there a release date for the dev branch?

**Comment by kirschbombe** [comment]
Thank you, @demiankatz! I wouldn't say "urgent" since I think that rarely applies in library context, but is time sensitive for us since we have some grant-funded collections that we need to publish soon. If the group has time to discuss in the next meeting, that would be great. But if @edsilv is able to get a new netlify instance up, that would be wonderful. Also because I'm going to suggest that the IIIF Cookbook start using the current UV instance for demoing (it's still using v3). So, two birds... :)

**Comment by LlGC-szw** [comment]
@edsilv @demiankatz Please make sure any work agreed on is added as a task to the community board :)

**Comment by kirschbombe** [comment]
Update: I had one of our graduate students spin up an instance of the most recent release (4.0.25) to test the static image manifests and the issue appears to be fixed here: https://uclalibrary.github.io/uv4025_demo/. Shall I go ahead and close this ticket?

**Comment by demiankatz** [comment]
Great news, @kirschbombe -- I'll go ahead and close this now.
